### ISSUE TITLE
Scaffolder creates repos as private even if the visibility is set to internal 

### ISSUE THREAD

**Issue by ebarriosjr** [backstage/backstage#5007] opened 2021-03-18 15:16 UTC
I build an app and everything works great except that my github repos are created as private repos even though i have:
scaffolder:
  github:
    visibility: internal # or 'public' or 'private'

## Expected Behavior
The created repos should be internal and not private

## Current Behavior

The repos are created as private inside the org.

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by kuangp** [comment] 2021-03-18 16:23
I'm running into the same issue using the scaffolder and the built-in `publish:github` action setting `repoVisibility` to `internal` for GHE

Looks like the issue is here: https://github.com/backstage/backstage/blob/e3718ad40670e2f73d2d4ba745758032527b6990/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts#L129

Possible fix could be to change this to `repoVisibility === 'private'` or according to the [octokit docs](https://octokit.github.io/rest.js/v18#repos) for `.repos.createInOrg()`, the `nebula-preview` preview header can be set to have the `visibility` param override the `private` param

**Comment by benjdlambert** [comment] 2021-03-19 10:20
Hmm yep, looks like that's a bug. Should be `repoVisibility === 'private'`. Who want's to contribute a fix? 🙏

**Comment by ebarriosjr** [comment] 2021-03-19 11:00
Sorry about the first one. I am still getting used to the DCO check :P

**Comment by jhaals** [comment] 2021-03-22 09:10
Closing now since the patch is in place, this should be out with the next release. Thanks for sorting this out @ebarriosjr! 👍 👍

**Closed by jhaals** 2021-03-22 09:10 UTC
Labels: bug
