### ISSUE TITLE
🚀 Feature: allow default openapi spec when placeholderresolver fails

### ISSUE THREAD

**Issue by hubofgitongithub** [backstage/backstage#25283] opened 2024-06-18 07:24 UTC
### 🔖 Feature description

Allow default openapi spec when placeholderresolver fails for the definition field. This way API's can be ingested while the dependency on other applications that may or may not be reachable/can be resolved is not a hard blocker for those api's to show up in the catalog.

What I cannot oversee: maybe it should be possible in general to supply a default value when the placeholderresolver fails.

### 🎤 Context

We currently submit api entities that have a placeholder for the api definition. This allows us to refer to the openapi json/yaml, so that it can be resolved by backstage easily and put into the entity. However, when this fails the api does not end up in the catalog. We now manually first check if the supplied URL is returning the right content type with a fetch call in backstage. However, this is inefficient as we now call the source twice (once by us manually and once by the placeholder resolver).

Of our 220+ apis, only 94 resolve successfully. This means that in the current implementation without our manual code, only 94 out of 220+ apis show up in the catalog.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment] 2024-06-20 10:05
Placeholders don't have a fallback feature and probably never will, in a centralized way.

You can supply your own resolvers implementation if you want, as an advanced use case. The general [modules docs](https://backstage.io/docs/backend-system/building-plugins-and-modules/index/#modules) happen to show a usage of the `catalogProcessingExtensionPoint`, which also has the method [`addPlaceholderResolver`](https://github.com/backstage/backstage/blob/08a6bd7bc456b29c12ecf2d0f0fd723d736562d8/plugins/catalog-node/src/extensions.ts#L44)

**Comment by freben** [comment] 2024-06-24 14:17
Yeah you'll copy paste it or make custom ones. The latter may actually be an even better way forward. So you can do `$definition: someInternal.Identifier.OrSomething` and then you have a resolver that's smart about calling exactly your service in the correct way and deal with the results of that. Then you are fully in control of things and aren't bound to the limitations of the builtin ones.

**Comment by camilaibs** [comment] 2024-07-09 07:44
> @freben fair enough. But would it be possible to for instance export [this function](https://github.com/backstage/backstage/blob/82126e289d84c55ef787f6255bba5fbc8bca26f6/plugins/catalog-backend/src/modules/core/PlaceholderProcessor.ts#L197) in that plugin? It would be awesome to have this callable as reusable code throughout backstage.
> 
> Again, we can copy paste this stuff as well. Exporting this would however massively simplify things for us and also still integrate with Backstage as much as possible. (If you ever decide to use a different framework under the hood to do this resolving, we automatically switch over to that as well then, which is exactly what we are looking for)

Hi @hubofgitongithub, as this function is simple to replicate, the effort to exporting it and starting worrying about future breaking changes doesn't seem worth it at the moment in terms of maintainability costs, so we keep it internal at the moment. Thank you for your understanding, it's best to copy it now 🙂 .

**Comment by Rugvip** [comment] 2024-07-11 12:36
Gonna close this as I don't think there are any remaining actions at this point

**Closed by Rugvip** 2024-07-11 12:36 UTC
Labels: enhancement, area:catalog

**Comment by tcardonne** [comment] 2024-07-25 15:03
Hi there,

I think there's something that could be improved on the subject of validating entities, especially when using the `/validate-entity` endpoint.

The validate API runs the same processing as any entity (validateEntityKind, pre/post processors, etc). If at any step there's a failure (an exception is thrown or an error is emitted), the validate API will say the entity is valid.

We want to leverage the API to validate files in the CI, but we're having an issue with placeholders that references files on external systems (AWS S3) **that are not published yet** (but will after the change is merged, so it'll pass).

Validating a file like this:
```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-api
spec:
  type: avro
  definition:
    $asyncapi: https://s3.eu-west-3.amazonaws.com/some-bucket/api-definitions/default/sample-api/specfile.yaml
```

results in `Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $asyncapi could not read location`

It's worth noting that since this error arrives early in the process, all subsequent errors (such as the missing `lifecycle`) won't be raised.

Currently it seems that the available solutions are:
- override the placeholder resolvers to allow a fallback value as recommended by @freben:

This should work but it also means that the normal processing will set dummy values on invalid placeholder.
There isn't a way to make the difference between a processing that happens during a "validate" vs a normal processing run. 

It should be possible to use the `baseUrl` passed to resolvers to determine if it should use dummy values. When using the validate API with a special `placeholder-dummy-value` location, the placeholders would silently replace/ignore any errors for placeholders. This feels like a hack to me and it would be great to have a way to have more info on the the context of the run. 

- make the dummy value replacement on the client side (eg, in the CI) as [done by roadiehq-backstage-entity-validator](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/utils/roadie-backstage-entity-validator/src/validator.js#L39)

This uses a replacement in the CI before calling the validate API, which is a bit cumbersome since resolvers can have different output formats. I feel like this should be handled by the validate API.


I think the first option would be the best, and maybe I'm not seeing something.
I can try to hack a PR to pass some context (eg, if it's a validation run or a normal one) in the ProcessingOrchestrator but I wanted to discuss this before digging into it.

What do you think?
