### ISSUE TITLE
Kubernetes plugin periodic refresh

### ISSUE THREAD

**Issue by Lucas-Desouza** [backstage/backstage#18730] opened 2023-07-19 15:47 UTC
### 📜 Description

When we are on the Kubernetes page with a deployment expanded it seems to automatically reload on intervals which causes open drawers to close.

### 👍 Expected behavior

Expect it to keep drawers open so that we can read the information.

### 👎 Actual Behavior with Screenshots

Just by being on the Kubernetes plugin I see these calls happening periodically and if we have the pod drawer open it closes on each of these calls.

![Screen Shot 2023-07-19 at 10 24 27 AM](https://github.com/backstage/backstage/assets/67918902/c5a824e1-786e-46ff-ad41-8937c63e209b)

### 👟 Reproduction steps

1. go to the Kubernetes plugin
2. expand a deployment 
3. open a pod info drawer

### 📃 Provide the context for the Bug.

Trying to troubleshoot is painful since the drawer closes in a few seconds 

### 🖥️ Your Environment

OS:   Darwin 21.6.0 - darwin/arm64
node: v18.16.1
yarn: 1.22.19
cli:  0.22.8 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/plugin-kubernetes-backend                  0.11.1
  @backstage/plugin-kubernetes-common                  0.6.4
  @backstage/plugin-kubernetes                                   0.9.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jamieklassen** [comment] 2023-07-19 15:52
Is this maybe a duplicate of #18471?

**Comment by mclarke47** [comment] 2023-07-21 15:02
Looks like a duplicate

**Closed by mclarke47** 2023-07-21 15:02 UTC
Labels: bug, area:kubernetes
