### ISSUE TITLE
🐛 Bug Report: GCP IAP Provider has wrong provider name in documentation

### ISSUE THREAD

**Issue by AdamHansrod** [backstage/backstage#25087] opened 2024-06-06 09:39 UTC
### 📜 Description

The docs refer to 'gcp-iap' as the provider string to use in config and on the proxied sign-in page. However, using that will result in a 404 result from the auth-backend. Using 'gcpIap' will succesfully work.

### 👍 Expected behavior

It should refer to 'gcpIap' as the provider id

### 👎 Actual Behavior with Screenshots

<img width="1785" alt="Screenshot 2024-06-06 at 10 36 53" src="https://github.com/backstage/backstage/assets/5097992/0913d782-7c39-4704-97d3-597d8a6d4715">
<img width="1812" alt="Screenshot 2024-06-06 at 10 37 00" src="https://github.com/backstage/backstage/assets/5097992/714b693a-5d2d-45b6-b148-3baa2cbc81fb">

### 👟 Reproduction steps

Include this in your backend index.ts
`backend.add(import('@backstage/plugin-auth-backend-module-gcp-iap-provider'));`
Spin up backend locally
Visit `http://localhost:8080/api/auth/gcp-iap/refresh` locally, it will return a 404. 
Visit `http://localhost:8080/api/auth/gcpIap/refresh` locally, it will return a 401 as it finds the auth plugin

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by nagyv** [comment] 2024-07-14 11:44
The issue seems bigger than a simple docs fix.

Following the [plugin config schema](https://github.com/backstage/backstage/blob/master/plugins/auth-backend-module-gcp-iap-provider/config.d.ts) I tried this config

```yaml
auth:
  environment: production
  providers:
    gcpIap:
      production:
        audience: ${GCP_IAP_AUDIENCE_CODE}
        signIn:
          resolvers:
            # typically you would pick one of these
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailMatchingUserEntityAnnotation
```

Backstage fails to start with "ForwardedError: Plugin 'auth' startup failed; caused by Error: Failed to initialize gcpIap auth provider, No sign-in resolver configured for proxy auth provider 'gcpIap'".

The following seems to work, despite not being ok with the schema

```yaml
auth:
  environment: production
  providers:
    gcpIap:
      production:
        audience: ${GCP_IAP_AUDIENCE_CODE}
        signIn:
          resolvers:
            # typically you would pick one of these
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailMatchingUserEntityAnnotation
      audience: ${GCP_IAP_AUDIENCE_CODE}
      signIn:
        resolvers:
          # typically you would pick one of these
          - resolver: emailMatchingUserEntityProfileEmail
          - resolver: emailMatchingUserEntityAnnotation
```

This gives a 401 error, ""Google IAP token verification failed, Error: Wrong recipient, payload audience != requiredAudience"" - I guess this will be an error on my end.

I tried to figure out where the issue might be, and tested

```yaml
auth:
  environment: production
  providers:
    gcpIap:
      audience: ${GCP_IAP_AUDIENCE_CODE}
      signIn:
        resolvers:
          # typically you would pick one of these
          - resolver: emailMatchingUserEntityProfileEmail
          - resolver: emailMatchingUserEntityAnnotation
```

This failed as well with 404 error. (If I remember correctly)

I checked out the codebase, and it seems to be too complex for me to come up with a fix.

**Comment by Rugvip** [comment] 2024-07-16 17:37
Ah yep the config schema is wrong, there's no `authEnv` for proxy providers. It should be flattened to accept the values at the provider root as you are passing them. Would you like to contribute a fix @nagyv? 🙏

**Comment by bsaltz** [comment] 2024-08-20 16:05
This is fixed now. I bumped to 1.30.1 and removed the workaround, and it worked.

**Closed** 2024-08-21 15:46 UTC
Labels: bug, help wanted, auth

**Comment by brettcurtis** [comment] 2025-01-05 18:48
Howdy. I'm learning Backstage out loud in this [PR](https://github.com/osinfra-io/backstage/pull/15). I was able to get GCP IAP authentication working fine in this [PR](https://github.com/osinfra-io/backstage/pull/15), but I'm trying to ingest GitHub organization data, so I need to build out a custom resolver.

I'm close, but hung up on a 404, that I can't figure out. It seems it could be related to this issue, grasping here so I'd really appreciate any help I can get! 

When I connect directly to the backend and hit: http://localhost:7007/api/auth/gcpiap/refresh I get a 401 as expected:

```json
{"error":{"name":"AuthenticationError","message":"Missing Google IAP header"},"request":{"method":"GET","url":"/api/auth/gcpiap/refresh"},"response":{"statusCode":401}}
```

When I go through the frontend I get the 404, I do see my `myVerifiedUserTransformer` doing what it should be doing I believe but you'll see the 404 directly after:

```json
{"contentLength":2,"date":"2025-01-05T18:17:44.625Z","httpVersion":"1.1","level":"info","message":"[2025-01-05T18:17:44.625Z] \"GET /api/c ││ atalog/entities?filter=kind%3DUser%2Cspec.profile.email%3Dbrett%40osinfra.io HTTP/1.1\" 200 2 \"-\" \"node-fetch/1.0 (+https://github.com/bitinn/node-fetch) \"","method":"GET","service":"rootHttpRouter","status":200,"type":"incomingRequest","url":"/api/catalog/entities?filter=kind%3DUser%2Cspec.profile.email%3Dbrett%40osinfra.io","userAgent":"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"}                                                               

{"contentLength":151,"date":"2025-01-05T18:17:44.629Z","httpVersion":"1.1","level":"info","message":"[2025-01-05T18:17:44.629Z] \"GET /api ││ /auth/gcpiap/refresh HTTP/1.1\" 404 151 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537 .36\"","method":"GET","service":"rootHttpRouter","status":404,"type":"incomingRequest","url":"/api/auth/gcpiap/refresh","userAgent":"Mozilla/5.0 (Windows NT  10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"}
```

Any ideas?
