### ISSUE TITLE
CatalogKindHeader dropdown takes time to open

### ISSUE THREAD

**Issue by dayadev** [backstage/backstage#12792] opened 2022-07-22 15:06 UTC
## Expected Behavior

When clicked on `Kinds` dropdown, the dropdown should open without any delays

## Actual Behavior

I am having issues with CatalogKindHeader which is basically a dropdown of all kinds. the dropdown takes a few seconds to load when I started adding more entities like I have injected around 20k entities of kind user. I don't see any logs in the browser console but looks like its fetching the data even to load the dropdown. not sure though. 

## Steps to Reproduce

1. Have a kind with over 15k entities, I have loaded 20k entities of kind `user` and 20k entities of kind `group`.
2. As soon as all the entities are emitted, the `CatalogKindHeader` which is a kinds dropdown on the Catalog page takes a few seconds to load. 

This behavior is anywhere the filters are involved.
Even the data takes time to display as it looks like pagination is happening in-memory and not on the server side but at least would like he `CatalogKindHeader` dropdown and filter should show up without much delay.

**Comment by benjdlambert** [comment] 2022-07-25 08:46
Hey :wave: We've got a focus on making the catalog a little more user friendly when you have large amounts of data. It's going to be taken care of all under this ticket I believe #12247

**Comment by freben** [comment] 2022-09-26 12:35
#13655 as well

**Comment by Rugvip** [comment] 2022-11-11 12:11
Closing this as a duplicate of #13655

**Closed by Rugvip** 2022-11-11 12:11 UTC
Labels: bug, catalog
