### ISSUE TITLE
"Next page link" broken

### ISSUE THREAD

**Issue by madelson** [backstage/backstage#6593] opened 2021-07-23 14:04 UTC
When I click the right arrow to advance the table to the next page, it does not work.

![image](https://user-images.githubusercontent.com/1269046/126793070-6a455897-96eb-4732-97ac-a7f959d6bbb6.png)

## Expected Behavior

Advances to the next page of the table.

## Current Behavior

Fails with a JavaScript error:

```
Uncaught TypeError: _this.props.onChangePage is not a function
    at eval (webpack-internal:///../../node_modules/material-table/dist/components/m-table-pagination.js:67)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:238)
    at invokeGuardedCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:293)
    at invokeGuardedCallbackAndCatchFirstError (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:307)
    at executeDispatch (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:390)
    at executeDispatchesInOrder (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:415)
    at executeDispatchesAndRelease (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:3279)
    at executeDispatchesAndReleaseTopLevel (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:3288)
    at forEachAccumulated (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:3260)
```

## Steps to Reproduce

We created the instance a few weeks ago, and updated to latest yesterday (7/22). Once we ingested enough components to trigger pagination this bug became apparent.

## Your Environment

- NodeJS Version (v12): 14.17.2
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 18.0.4
- Browser Information: Chrome latest

**Comment by timbonicus** [comment] 2021-07-23 19:32
Thanks for the report! This is a duplicate of #6452 and #6553, which are linked to the pull request #6581 that should fix this once merged. You can try this [potential workaround](https://github.com/backstage/backstage/issues/6452#issuecomment-880176906) in the meantime, and please report on that ticket if it worked for you.

**Closed by timbonicus** 2021-07-23 19:32 UTC
Labels: bug
