### ISSUE TITLE
Invalid X-Requested-With header using the Okta Provider

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4065] opened 2021-01-14 04:12 UTC
Using the Okta provider within the auth-backend plugin and getting the following error: Invalid X-Requested-With header

Okta is setup as follows:

Login redirect: https://myapp.com/api/auth/okta/handler/frame
Logout: https://myapp.com/api/auth/okta/logout
Initiate Login: https://myapp.com/api/auth/okta/start

App logs:
GET https://myapp.com/api/auth/okta/refresh?optional&env=development
GET https://myapp.com/api/auth/okta/start?scope=openid%20email%20profile%20offline_access&env=development

App Setup:
clientId/clientSecret/audience is set to https://my-domain.oktapreview.com

## Expected Behavior

Obtain access token and authenticate the user.

## Current Behavior

Front end error to user who has access is: Authentication failed, Failed to obtain access token

Front end error to user who does not have access is as expected: Authentication rejected, User is not assigned to the client application

## Steps to Reproduce

Create new Scaffolder app with app-backend plugin enabled running under port 7000. 

ingress with HTTPS enabled mapped to port 7000

## Your Environment

- NodeJS Version (v12):
- Docker image using Node-12-buster on Kubernetes.
- Chrome

**Comment by Rugvip** [comment] 2021-01-18 22:54
What are you using client-side to initiate the login? All of the included auth clients in `@backstage/core` should be setting the `x-requested-with` header, and this error is an indication of it not being set

**Comment by benjdlambert** [comment] 2021-01-21 14:39
@regicsolutions can we close this ticket as this is expected behaviour with the header/

**Comment by adamdmharvey** [comment] 2021-02-22 04:59
Bump @regicsolutions - thoughts?

**Comment by regicsolutions** [comment] 2021-02-22 12:58
Yep, good to close

**Closed** 2021-02-22 12:58 UTC
Labels: bug

**Comment by cal5barton** [comment] 2021-08-02 18:10
@regicsolutions what was the fix for this?

**Comment by kaiquerass** [comment] 2023-02-24 19:56
@regicsolutions how to solve this? we are unable to use authentication because of this error. Cant find any solution.

**Comment by kaiquerass** [comment] 2023-02-24 20:22
I was able to solve login setting the config: `prompt: auto` under the auth provider config.
but now I have this error trying to logout 😢

**Comment by carlossmartini** [comment] 2023-03-04 21:36
@kaiquerass  I have the same issue. Can you provide a bit more info in terms of where the prompt setting is? I can’t seem to find anything in the docs about it. Thanks so much!

**Comment by kaiquerass** [comment] 2023-03-08 20:01
```
auth:
  environment: development
  session:
    secret: 
  providers:
    keycloak:
      development:
        metadataUrl: 
        clientId: 
        clientSecret: 
        prompt: auto
```
