### ISSUE TITLE
🚀 Feature: Possible to use variable (prefill) in default value each property in template.yaml

### ISSUE THREAD

**Issue by 63070054** [backstage/backstage#24831] opened 2024-05-20 03:54 UTC
### 🔖 Feature description

🚀 Feature: Possible to use variable (prefill) in default value each property in template.yaml

### 🎤 Context

For example, I have repoUrlPicker and i want to set the default value to the field name "name" in the previous step and set to the field repositoryName automatically. For now I tried to use something like default: bitbucket.org?repo=${{parameters.name }}&workspace=&project=

But, Unfortunately It treat my variable ${{parameters.name }} as a string not variable

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment] 2024-05-20 08:38
Hey @63070054 :wave:

Thanks for raising this issue, I think that this is actually a duplicate of #23893 and #16275. Going to close this and keep the conversation there if that's OK? Reach out if you think i've made a mistake! :pray:

**Closed by benjdlambert** 2024-05-20 08:38 UTC
Labels: enhancement, area:scaffolder
