### ISSUE TITLE
🐛 Bug Report: Backend fails to come up with Entity Feedback Backend Plugin Integration

### ISSUE THREAD

**Issue by sharadpattanshetti** [backstage/backstage#16410] opened 2023-02-17 06:11 UTC
### 📜 Description

Followed the steps to configure the frontend and backend plugin as given here - https://github.com/backstage/backstage/tree/master/plugins/entity-feedback

However, after adding below line the backstage backend fails to come up and running, (sort of hanged)
  const entityFeedbackEnv = useHotMemoize(module, () => createEnv('entityFeedback'));

If this line is commented out then backstage backend works fine. 

Any suggestions on what could be wrong? 

CC : @kuangp 

### 👍 Expected behavior

The plugin should work properly. 

### 👎 Actual Behavior with Screenshots

Backend is hanging. No logs printed after `Build succeeded` line

$ yarn start-backend
yarn run v1.22.18
$ yarn workspace backend start
$ backstage-cli package start
Build succeeded
Restarting app...
Build succeeded

### 👟 Reproduction steps

Follow all the steps provided here - https://github.com/backstage/backstage/tree/master/plugins/entity-feedback

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by kuangp** [comment] 2023-02-17 15:16
hmm we'll probably need more info here to diagnose the issue. Can you share what the rest of your backend `index.ts` looks like? 

This plugin is also hooked up in this repos example app and looks to be working fine so maybe you can reference it's setup to compare with your own?
https://github.com/backstage/backstage/blob/da033811816d0fc1711da5f73ce2913615e43e75/packages/backend/src/index.ts#L152-L154

**Comment by FilipSwiatczak** [comment] 2023-02-17 17:56
@sharadpattanshetti I saw this with my backend unit tests failing right after installing the feedback backend with:
yarn add --cwd packages/backend @backstage/plugin-entity-feedback-backend

When I re-run yarn install at the root it fixed it though.

**Comment by sharadpattanshetti** [comment] 2023-02-19 16:34
Thanks @kuangp  and @FilipSwiatczak for your replies. We do have the same code in index.ts as in above example. I tried commenting other plugins and keep only entityFeedback but backend still fails to come up. 

@FilipSwiatczak  I did try reinstalling plugin-entity-feedback-backend at the root again but same issue.

**Comment by benjdlambert** [comment] 2023-02-20 12:42
Hmm, would it be possible for you to create a reproduction repository so that we can dig in a little more @sharadpattanshetti?

**Comment by sharadpattanshetti** [comment] 2023-02-22 15:55
Sorry for the delayed reply. I could get past the above issue by cleaning up the node modules and yarn.lock. 
However, getting 400 Bad Request on below api when clicked on Like or Dislike button : 

http://localhost:7000/api/entity-feedback/ratings/component%3Adefault%2Fmycomponent

**Comment by kuangp** [comment] 2023-02-22 16:08
You may be getting a 400 if you're not signed into Backstage with a [valid user identity](https://backstage.io/docs/auth/identity-resolver): 
https://github.com/backstage/backstage/blob/f16d9f31cd07b04048460bac4b406566ec2a0a5f/plugins/entity-feedback-backend/src/service/router.ts#L133-L136

The backend will logs feedback with the username of the person that supplied it so it requires you to be signed in as a non-guest user for this plugin to work.

**Comment by kuangp** [comment] 2023-02-22 16:11
> I am using Backstage v1.9.1

also realized you're on 1.9, this plugin was released in v1.11 so make sure your deps are upgraded to the latest version to successfully install this plugin

**Comment by sharadpattanshetti** [comment] 2023-02-22 16:29
The 400 error is resolved when signed in. I shall try the complete plugin after upgrading to v1.11. 
Thank you so much @kuangp for your help.

**Comment by kuangp** [comment] 2023-02-22 17:30
no problem! @benjdlambert I think this can be closed now

**Closed** 2023-02-23 09:24 UTC
Labels: bug
