### ISSUE TITLE
🐛 Bug Report: Catalog unit tests are broken after upgrade to 1.21.1

### ISSUE THREAD

**Issue by raphaelbp12** [backstage/backstage#22280] opened 2024-01-17 13:13 UTC
### 📜 Description

Hello all, I am experiencing some erros in `EntityLayout.test.tsx` (copied from @backstage/plugin-catalog) after the upgrade to the latest version.
If I import the `EntityLayout` from `@backstage/plugin-catalog`, it fails with the following error:

```
console.error
    Error: Uncaught [Error: No path for routeRef{type=absolute,id=catalog}]
```

But, if I copy the following files from and their dependencies to my project, and change the import to this new `EntityLayout`, the **test passes**.
Files that I copied: https://github.com/backstage/backstage/tree/master/plugins/catalog/src/components/EntityLayout

Then, when I use the package installed by yarn, it **fails**. But, if I use the files directly, copying it to my project, it **works**.

### 👍 Expected behavior

The existing tests should pass.

### 👎 Actual Behavior with Screenshots

My `EntityLayout.test.tsx` is exactly the same presented here: [https://github.com/backstage/backstage/tree/master/plugins/catalog/src/components/EntityLayout](https://github.com/backstage/backstage/tree/master/plugins/catalog/src/components/EntityLayout)

If I remove the `import { EntityLayout } from './EntityLayout';`  and import from `@backstage/plugin-catalog`, it fails.

![image](https://github.com/backstage/backstage/assets/1952333/3cc1d058-23f4-4d24-bef3-9ee6c196cb18)

### 👟 Reproduction steps

Steps to reproduce:
* copy those files to a folder in your backstage project:
https://github.com/backstage/backstage/tree/master/plugins/catalog/src/components/EntityLayout

* copy the dependencies:
  - EntityContextMenu
  - routes.ts

* run the tests how it is:
`yarn test backstage/packages/app/src/components/catalog/EntityLayout.test.tsx`
it should pass

* remove the following import line from  `EntityLayout.test.tsx`:
`import { EntityLayout } from './EntityLayout';`

* import the `EntityLayout` from `@backstage/plugin-catalog`
`import { EntityLayout } from '@backstage/plugin-catalog';`

* run the tests again

### 📃 Provide the context for the Bug.

I am trying to make my existing unit tests pass, given that it breaks my CI/CD and I cannot deploy the upgraded backstage version.

### 🖥️ Your Environment

```
backstage % yarn backstage-cli info
yarn run v1.22.19
$ /Users/dkrabapa/code/bump-baseplate/baseplate/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.2.0 - darwin/arm64
node: v18.18.2
yarn: 1.22.19
cli:  0.25.1 (installed)
backstage:  1.21.1

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.4.5, 0.5.10
  @backstage/backend-common                                        0.15.2, 0.18.5, 0.19.9, 0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.5.4, 0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/catalog-client                                        1.4.5, 1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.0.8, 1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.11.2, 0.12.5, 0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/dev-utils                                             1.0.26
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.3.0, 0.4.0, 0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.3
  @backstage/plugin-catalog-backend-module-github                  0.4.7
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.6
  @backstage/plugin-catalog-backend                                1.16.1
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog-unprocessed-entities                   0.1.7
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-devtools-backend                               0.2.6
  @backstage/plugin-devtools-common                                0.1.8
  @backstage/plugin-devtools                                       0.1.8
  @backstage/plugin-events-backend-module-aws-sqs                  0.2.12
  @backstage/plugin-events-backend-module-github                   0.1.19
  @backstage/plugin-events-backend                                 0.2.18
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-explore-backend                                0.0.18
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.35
  @backstage/plugin-explore                                        0.4.15
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-home-react                                     0.1.7
  @backstage/plugin-home                                           0.4.32, 0.5.11
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-backend                             0.5.32
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-explore                  0.1.13
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-addons-test-utils                     1.0.26
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-user-settings                                  0.7.14
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.4.0, 0.2.19, 0.4.4, 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment] 2024-01-17 13:32
It's most likely that you've forgotten to mount the `catalog` `routeRef` as mentioned here: https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityLayout/EntityLayout.test.tsx#L73-L76

**Comment by raphaelbp12** [comment] 2024-01-17 14:29
I copied this file and ran this exact test suit, and it failed in the scenario I described. I ran it today, with the most recent code in master.

**Comment by freben** [comment] 2024-01-17 14:39
You are copying the routeRefs as well, if I understand you correctly. You end up with two different route refs; you're mounting the cloned ref, but the code was looking for the original ref.

Why do you copy these in the first place?

**Comment by raphaelbp12** [comment] 2024-01-17 15:04
@freben I copied this as an attempt to test my own environment, given that my unit tests started to fail. Then, I thought "can I find a test suit that uses the same stuff that I need? Such as: renderInTestApp, TestApiProvider, EntityProvider and EntityLayout?

Just as an attempt to find working tests... then I went to my cloned backstage (full repo) and ran this test file, it worked... Then I thought: ok, backstage is not broken (as I supposed, given that you wouldn't merge a code that fails the unit tests...)

Next step? I could try to run this same test suit in my project, and check if it passes, and it does... But it was using a "customized" EntityLayout file... I needed to run this test with the `EntityLayout` from the package...

Then it failed.

Thanks in advance for the help, guys. ;D

**Comment by freben** [comment] 2024-01-18 09:55
Alright, if it's OK with you I'll close this as an unintended use case. Hope you get it sorted! See @benjdlambert 's comment at the top for how to mount routes

**Closed by freben** 2024-01-18 09:55 UTC
Labels: bug, area:catalog

**Comment by benjdlambert** [comment] 2024-01-18 09:56
Just a small thing here too, I'd advise against duplicating routeRefs wherever possible and re-use the ones from the `catalogPlugin.routes.root` wherever possible. It should circumvent this issue in the first place with duplicate `routeRefs` being the cause.

**Comment by raphaelbp12** [comment] 2024-01-18 10:05
guys, thank you so much for all this info! They were super valuable! I fixed this issue in the following way:

![image](https://github.com/backstage/backstage/assets/1952333/36d902d4-9fbc-4916-9bce-6de1eb42617d)
