### ISSUE TITLE
Error when serving simple documentation with TechDocs CLI 1.2.1

### ISSUE THREAD

**Issue by wunderdogneo** [backstage/backstage#13813] opened 2022-09-22 13:40 UTC
## Expected Behavior

I can serve TechDocs with

`npx @techdocs/cli@1.2.1 serve` 

## Actual Behavior

I get the following error message in the browser (not browser-specific, happens in Firefox, Safari, Chrome):

```
Error

Message
No implementation available for apiRef{plugin.search.queryservice}

Stack Trace
Error: No implementation available for apiRef{plugin.search.queryservice}
```

## Steps to Reproduce

Create the following file tree:

```
.
├── docs
│   └── index.md
└── mkdocs.yml
```

`index.md` can contain any Markdown. `mkdocs.yml` should contain:

```
site_name: 'example-docs'

nav:
  - Home: index.md

plugins:
  - techdocs-core
```

Running `npx @techdocs/cli@1.2.1 serve` inside that root directory should then result in the aforementioned error.

## Context

I tried to use TechDocs CLI based on the [Backstage documentation page](https://backstage.io/docs/features/techdocs/cli) on the matter, but was presented with the error above. After some back and forth I noticed that, with the exact same directory setup and environment, the following works fine:

`npx @techdocs/cli@1.2.0 serve -v`

As a result, I'm guessing that there was a bug introduced in the latest patch version of TechDocs CLI.

**Comment by soapraj** [comment] 2022-10-21 11:32
Hi! @wunderdogneo https://github.com/backstage/backstage/issues/14134 seems be the same issue on v1.2.1

I have added some context in this [comment](https://github.com/backstage/backstage/issues/14134#issuecomment-1286806563) on #14134. Can you try running on v1.2.2 with npx @techdocs/cli@1.2.2 serve?

**Comment by ivanaguilario** [comment] 2022-10-23 13:36
@soapraj Same for me using 1.2.2. Not working.

Can confirm 1.2.0 works without problems.

**Comment by ottosichert** [comment] 2022-10-26 08:38
Closing this issue as duplicate of https://github.com/backstage/backstage/issues/14134 as the discussion, PR and workaround are captured there

**Closed by ottosichert** 2022-10-26 08:38 UTC
Labels: bug, techdocs
