### ISSUE TITLE
FeatureFlagged component not working as expected when used in Sidebar

### ISSUE THREAD

**Issue by mhaley37** [backstage/backstage#10698] opened 2022-04-07 14:37 UTC
## Expected Behavior
The `FeatureFlagged` component (added in #5480) is a great feature for making components conditional based on app-level flags.  We've been able to use this to conditionally show components in the content area of pages, as well as use it to hide routes.  

We would expect to be able to also use this to conditionally show `SidebarItem` components within the `Sidebar` using the following code:

From `Root.tsx`
```
export const Root = ({ children }: PropsWithChildren<{}>) => (
  <SidebarPage>
    <Sidebar>
      <SidebarLogo />
      <SidebarGroup label="Search" icon={<SearchIcon />} to="/search">
        <SidebarSearchModal />
      </SidebarGroup>
      ...
        <SidebarDivider />
        <SidebarScrollWrapper>
        <FeatureFlagged with='fake-flag' >
          <SidebarItem icon={AccessAlarm} to="flagged-route" text="flaggedText" />
        </FeatureFlagged>
     ...
```

## Actual Behavior

The above code actually _does_ hide the the child `<SidebarItem />` component IF `some-feature-flag` is _not_ enabled, however the sidebar the component does not dynamically show/hide when the user changes this flag in user settings.  If the user toggles the flag controlling the `<FeatureFlagged />` component, the sidebar _will not_ update, however a refresh of the page will.

## Steps to Reproduce

Pre-steps: Setup a new backstage app via `npx @backstage/create-app`

1. Add a new route to `<FlatRoutes />` that is wrapped in a `<FlaggedFeature /`>
From `App.tsx`: (Note, `TechDocsIndexPage` used for the restricted page as well for simplicity)
```
    <FeatureFlagged with='fake-flag' >
      <Route path="/flagged-route" element = {<TechDocsIndexPage />} />
    </FeatureFlagged>
    <Route path="/docs" element={<TechDocsIndexPage />} />
```
2. Update `Root.tsx` as shown above in Expected Behavior
3. Start app locally (`yarn dev`) note that the `Feature Flagged` sidebar item is correctly not showing (since flag is disabled)
<img width="799" alt="image" src="https://user-images.githubusercontent.com/2686352/162219437-95ea66c8-72f6-46ba-9d99-de8986a11248.png">
   1. Also, the flagged route `/flagged-route` is also, correctly not accessible   
4. Enable the feature flag, Note that the sidebar _does not_ add the new sidebar item: 

<img width="777" alt="image" src="https://user-images.githubusercontent.com/2686352/162220301-b4e2cea2-f681-4b7b-aa57-726527d01679.png">

   4. Even after navigating to new pages, the sidebar does not update:
   
<img width="869" alt="image" src="https://user-images.githubusercontent.com/2686352/162220473-8803bbf0-ef42-4482-b1b8-b8b2d6863429.png">

   5. However, the `FeatureFlagged` route _is_ correctly accessible if typed into the address bar.
   6. A hard refresh also will render the sidebar with the new item correctly there:
   
<img width="845" alt="image" src="https://user-images.githubusercontent.com/2686352/162224207-3a811253-b017-4dec-a533-2366869a60e4.png">

   
   
   

## Context

We want to be able to use the sidebar to give quick access to one or more plugins.  However, not all of these plugins need be shown to all users -- for example, we have some plugins that are still in an early development phase.  We'd like to integrate these into backstage so that _some_ users can use them.  However, we'd like this to be opt-in, so using a feature flag to hide access to this would be a really simple way to accomplish this.  

We'd like to have some wide flags like "allow-expirimental-plugins" or "use-beta-features" to possibly drive what routes and sidebar items are shown to control things like this.

## Your Environment

This was reproduced on a freshly scaffold backstage app using: `npx @backstage/create-app` ( backstage version `1.0.0`).  I have verified this is still reproducible after updating to `1.1.0-next.2.`  

- Browser Information: 
* Google Chrome 100.0.4896.60
* Mozilla Firefox 98.0.2 

- Output of `yarn backstage-cli info`: 

```
yarn run v1.22.17
$ /Users/michaelhaley/projects/temp/temp-backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 21.4.0 - darwin/x64
node: v16.14.0
yarn: 1.22.17
cli:  0.17.0-next.2 (installed)

Dependencies:
  @backstage/app-defaults               1.0.1-next.1
  @backstage/backend-common             0.13.2-next.1
  @backstage/backend-tasks              0.3.0-next.2
  @backstage/catalog-client             1.0.0, 1.0.1-next.0
  @backstage/catalog-model              1.0.0, 1.0.1-next.1
  @backstage/cli-common                 0.1.8
  @backstage/cli                        0.17.0-next.2
  @backstage/config-loader              1.0.1-next.0
  @backstage/config                     1.0.0
  @backstage/core-app-api               1.0.1-next.0
  @backstage/core-components            0.9.2, 0.9.3-next.1
  @backstage/core-plugin-api            1.0.0
  @backstage/errors                     1.0.0
  @backstage/integration-react          1.0.0, 1.0.1-next.1
  @backstage/integration                1.0.0, 1.1.0-next.1
  @backstage/plugin-api-docs            0.8.4-next.2
  @backstage/plugin-app-backend         0.3.31-next.0
  @backstage/plugin-auth-backend        0.13.0-next.1
  @backstage/plugin-auth-node           0.2.0-next.0
  @backstage/plugin-catalog-backend     1.1.0-next.2
  @backstage/plugin-catalog-common      1.0.0, 1.0.1-next.1
  @backstage/plugin-catalog-graph       0.2.16-next.2
  @backstage/plugin-catalog-import      0.8.7-next.1
  @backstage/plugin-catalog-react       1.0.0, 1.0.1-next.2
  @backstage/plugin-catalog             1.1.0-next.2
  @backstage/plugin-github-actions      0.5.4-next.1
  @backstage/plugin-org                 0.5.4-next.2
  @backstage/plugin-permission-common   0.5.3, 0.6.0-next.0
  @backstage/plugin-permission-node     0.6.0-next.1
  @backstage/plugin-permission-react    0.3.4, 0.4.0-next.0
  @backstage/plugin-proxy-backend       0.2.25-next.0
  @backstage/plugin-scaffolder-backend  1.1.0-next.2
  @backstage/plugin-scaffolder-common   1.0.0, 1.0.1-next.0
  @backstage/plugin-scaffolder          1.0.1
  @backstage/plugin-search-backend-node 0.5.3-next.0
  @backstage/plugin-search-backend      0.5.0-next.1
  @backstage/plugin-search-common       0.3.2, 0.3.3-next.1
  @backstage/plugin-search              0.7.4, 0.7.5-next.0
  @backstage/plugin-tech-radar          0.5.11-next.1
  @backstage/plugin-techdocs-backend    1.0.1-next.1
  @backstage/plugin-techdocs-node       1.0.1-next.1
  @backstage/plugin-techdocs            1.0.1
  @backstage/plugin-user-settings       0.4.3-next.0
  @backstage/release-manifests          0.0.2
  @backstage/search-common              0.3.2, 0.3.3-next.1
  @backstage/test-utils                 1.0.1-next.1
  @backstage/theme                      0.2.15
  @backstage/types                      1.0.0
  @backstage/version-bridge             1.0.0
```

**Comment by freben** [comment] 2022-04-11 11:47
Hi Yeah unfortunately the feature flags aren't always respected "live". Internally the interface actually encourages a reload after toggling any feature flag.

**Comment by Rugvip** [comment] 2022-04-13 11:03
Will close this as it is the intended behavior and we don't have any plants to change it currently. The main reason we require a reload is so that feature flags can be used to determine how the app is wired together, in ways that you can't change while the app is running. There are cases were we could let the feature flags live update, but we're worried that would leave users very confused as there's no obvious way to tell what feature flags support that and which ones don't.

Let us know if we missed something, or if you think feature flags should support live updates in some situations then you could a separate issue for that instead :grin:

**Closed by Rugvip** 2022-04-13 11:03 UTC
Labels: bug

**Comment by mhaley37** [comment] 2022-04-14 02:21
Thank you @freben & @Rugvip -- that background gives some good context as to why this works like this.  This isn't a big deal for us, and the feature flags we are using need not be toggled often.  However, I'm wondering -- is there any easy for us to force a refresh _in response_ to a user toggling a feature flag?  If that is possible it would be a fine workaround for us.  If not, I may open up a new issue to request something similar.
