### ISSUE TITLE
🐛 Bug Report: 500 error fetching pod logs from LKE cluster

### ISSUE THREAD

**Issue by hritikch24** [backstage/backstage#18036] opened 2023-05-31 10:48 UTC
### 📜 Description

Pod logs component not working and still throwing error 500. Below is the screenshot attached. If some proxy changes are needed in app-config.yml then what are those?
<img width="1324" alt="image" src="https://github.com/backstage/backstage/assets/69822624/0b3b5095-3486-4428-a646-dedb69092d4d">

### 👍 Expected behavior

It should show pod logs.

### 👎 Actual Behavior with Screenshots

It should show pod logs.

### 👟 Reproduction steps

1). Go to backstage application.
2). Add application to backstage.
3). Goto kubernetes for existing ref in  backstage .
4). Click on pod.
5).Click on logs and see the result.

### 🖥️ Your Environment

I tried to pull these logs on latest code with yarn run command.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by ivangonzalezacuna** [comment] 2023-05-31 12:40
Maybe it helps to find a solution/fix for this.

We are also trying to upgrade to the latest version, but in our case the logs where making backstage to crash because "localhost" was being used instead of the correct Hostname (which is being used in the backend), so I was getting a `ERR_TLS_CERT_ALTNAME_INVALID`. To fix it, we added the `skipTLSVerify: true` to the kubernetes config. This makes the proxy to set the field `secure: false`, and then the logs are displayed as expected.

**Comment by jamieklassen** [comment] 2023-05-31 13:07
This may be tough to reproduce without more details -- @hritikch24 can you provide the actual app config you're using (redacting any explicit secrets)? It seems relevant to understand what cluster locator you are using, how/where your cluster is deployed (did you use a cloud provider? bare metal? etc), what authentication strategy is in play, and any other network configuration that might be relevant.

**Comment by jamieklassen** [comment] 2023-05-31 15:03
For posterity, when I extract the `kubernetes` stanza from that attachment, I see:
```yaml
kubernetes:
  logging:
    enabled: true
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://7b5b06da-1bb2-43f1-b3e8-2c8ae98f10d2.ap-west-1.linodelke.net:443
          name: lke80509
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: false
          caData: ERGdnRxxcdcs
          serviceAccountToken: xxxxxxxxxxxx
```

**Comment by rmartine-ias** [comment] 2023-05-31 15:54
Figured it out: we need to add a `changeOrigin: true` here: https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesProxy.ts#L137

**Comment by jamieklassen** [comment] 2023-05-31 16:01
That URI suggests that this thing is deployed on [Linode Kubernetes Engine (LKE)](https://www.linode.com/products/kubernetes/) which I've never used before! To properly reproduce I wonder if a Linode account is required...

**Comment by jamieklassen** [comment] 2023-05-31 16:03
@ivangonzalezacuna @rmartine-ias I'm a little anxious that your reports (which include mention of TLS errors and `localhost` as an invalid subject alternative name) are actually a different bug than the one reported here, since @hritikch24's app-config definitely has `skipTLSVerify: true`.

**Comment by rmartine-ias** [comment] 2023-05-31 16:08
@jamieklassen I think you are correct, good catch.

**Comment by jamieklassen** [comment] 2023-05-31 16:19
@hritikch24 I suspect the IP address 3.128.254.45 from your screenshot is either no longer valid or behind a firewall so I can't run this test myself, but can you try running
```bash
curl -vH 'Backstage-Kubernetes-Cluster: lke80509' 'http://3.128.254.45:7007/api/kubernetes/proxy/api/v1/namespaces/automation-gitlab-dev/pods/automation-gitlab-api-python-dp-65fb64dcc-ggjkk/log?container=automation-gitlab-api-python'
```
and see if you get a 500 again? I'd also be curious to see if there are any logs from the backstage backend when these failing requests are made.

**Comment by hritikch24** [comment] 2023-05-31 17:09
@jamieklassen i am getting below error while run above curl command 
<img width="1303" alt="image" src="https://github.com/backstage/backstage/assets/69822624/600eeaea-1a6b-4d24-85d3-521b71766026">

**Comment by jamieklassen** [comment] 2023-05-31 17:27
munging the data a bit here we see

`error.cause.stack`:
```
Error: Client network socket disconnected before secure TLS connection was established
 at connResetException (node:internal/errors:705:14)
 at TLSSocket.onConnectEnd (node:_tls_wrap:1594:19)
 at TLSSocket.emit (node:events:525:35)
 at endReadableNT (node:internal/streams/readable:1358:12)
 at processTicksAnd Rejections (node:internal/process/task_queues:83:21)
```

and `error.stack`:
```
Error: Cluster '1lke80509' request error; caused by Error: Client network socket disconnected before secure TLS connection was established
 at ProxyServer.onError (webpack-internal:///../../plugins/kubernetes—backend/src/service/KubernetesProxy.ts:118:42)
 at ProxyServer.emit (/home/ubuntu/backstage-91/new-backstage/backstage/node_modules/eventemitter3/index.js:210:27)
 at ClientRequest.proxyError (/home/ubuntu/backstage-01/new-backstage/backstage/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:165:18)
 at ClientRequest.emit (node:events:525:35)
 at TLSSocket.socketErrorListener (node:_http_client:494:9)
 at TLS Socket.emit (node:events:513:28)
 at emitErrorNT (node:internal/streams/destroy:157:8)
 at emitErrorCloseNT (node:internal/streams/destroy:122:3)
 at processTicksAndRejections (node: internal/process/task_queues:83:21)
```

**Comment by hritikch24** [comment] 2023-05-31 17:32
> Figured it out for our use case: we need to add a `changeOrigin: true` here: https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesProxy.ts#L137
> 
> Confirmed by editing `node_modules/@backstage/plugin-kubernetes-backend/dist/index.cjs.js` and checking that it works.
> 
> ```diff
> diff --git a/node_modules/@backstage/plugin-kubernetes-backend/dist/index.cjs.js b/node_modules/@backstage/plugin-kubernetes-backend/dist/index.cjs.js
> index 06673d6..7a61763 100644
> --- a/node_modules/@backstage/plugin-kubernetes-backend/dist/index.cjs.js
> +++ b/node_modules/@backstage/plugin-kubernetes-backend/dist/index.cjs.js
> @@ -1067,6 +1067,7 @@ class KubernetesProxy {
>      if (!middleware) {
>        const logger = this.logger.child({ cluster: originalCluster.name });
>        middleware = httpProxyMiddleware.createProxyMiddleware({
> +        changeOrigin: true,
>          logProvider: () => logger,
>          secure: !originalCluster.skipTLSVerify,
>          router: async (req) => {
> ```
> 
> For posterity, here's the error we're getting:
> 
> ```
> Host: localhost. is not in the cert's altnames: DNS:<somestuff>.gr7.us-east-1.eks.amazonaws.com, DNS:ip-172-16-<numbers>.ec2.internal, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:172.<numbers>, IP Address:10.<numbers>, IP Address:172.<numbers>"
> ```
> 
> The only difference is in dev, the Host is `green-backstage.k8s.dev.company.net` instead of `localhost`.



> Figured it out for our use case: we need to add a `changeOrigin: true` here: https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesProxy.ts#L137
> 
> Confirmed by editing `node_modules/@backstage/plugin-kubernetes-backend/dist/index.cjs.js` and checking that it works.
> 
> ```diff
> diff --git a/node_modules/@backstage/plugin-kubernetes-backend/dist/index.cjs.js b/node_modules/@backstage/plugin-kubernetes-backend/dist/index.cjs.js
> index 06673d6..7a61763 100644
> --- a/node_modules/@backstage/plugin-kubernetes-backend/dist/index.cjs.js
> +++ b/node_modules/@backstage/plugin-kubernetes-backend/dist/index.cjs.js
> @@ -1067,6 +1067,7 @@ class KubernetesProxy {
>      if (!middleware) {
>        const logger = this.logger.child({ cluster: originalCluster.name });
>        middleware = httpProxyMiddleware.createProxyMiddleware({
> +        changeOrigin: true,
>          logProvider: () => logger,
>          secure: !originalCluster.skipTLSVerify,
>          router: async (req) => {
> ```
> 
> For posterity, here's the error we're getting:
> 
> ```
> Host: localhost. is not in the cert's altnames: DNS:<somestuff>.gr7.us-east-1.eks.amazonaws.com, DNS:ip-172-16-<numbers>.ec2.internal, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:172.<numbers>, IP Address:10.<numbers>, IP Address:172.<numbers>"
> ```
> 
> The only difference is in dev, the Host is `green-backstage.k8s.dev.company.net` instead of `localhost`.

@rmartine-ias @jamieklassen @ivangonzalezacuna  Thanks guys this changeOrigin:true works.

**Comment by jamieklassen** [comment] 2023-05-31 17:32
Turned out to be the same bug after all...

**Comment by rmartine-ias** [comment] 2023-05-31 19:05
Oh sweet! I'll open up a PR.

**Comment by jamieklassen** [comment] 2023-05-31 23:31
I haven't tested this hypothesis as I don't have an  account handy, but it seems like LKE may have some heavily-reused load balancer IPs which do name-based routing (possibly using [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication)) to clusters. In these cases, it is pretty important that the request have the right host information, otherwise the server could very well interrupt the connection.

**Comment by ivangonzalezacuna** [comment] 2023-06-01 07:29
> @ivangonzalezacuna @rmartine-ias I'm a little anxious that your reports (which include mention of TLS errors and `localhost` as an invalid subject alternative name) are actually a different bug than the one reported here, since @hritikch24's app-config definitely has `skipTLSVerify: true`.

I have just tested to add the `changeOrigin` in the middleware. And I can confirm it's also working in our scenario, without needing to set the `skipTLSVerify` anymore. So looks like the issue has been found! So until the issue is release we will just keep the field temporarily. Thanks to all!

**Closed** 2023-06-01 18:56 UTC
Labels: bug, area:kubernetes
