### ISSUE TITLE
🐛 Bug Report: GraphiQL plugin wrapper test error

### ISSUE THREAD

**Issue by acwilan** [backstage/backstage#20366] opened 2023-10-04 19:12 UTC
### 📜 Description

When wrapping graphiql plugin inside a react component, it renders well, but a test done on such component just to verify rendering fails.

### 👍 Expected behavior

Test runs without issue

### 👎 Actual Behavior with Screenshots

When `npm run test` executes fails, with error

```
    /[redacted_base_path]/node_modules/@backstage/core-app-api/dist/index.esm.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import React, { useContext, createContext, useEffect, useState, Children, isValidElement, useMemo, useRef } from 'react';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { ApiFactoryRegistry, ApiProvider, ApiResolver } from '@backstage/core-app-api';
        | ^
      3 | import { createApiFactory } from '@backstage/core-plugin-api';
      4 | import { GraphQLEndpoints, graphQlBrowseApiRef, Router as GraphiQlRouter } from '@backstage/plugin-graphiql';
```

That part of the code pointed is at `GraphiQlWrapper.tsx`.

### 👟 Reproduction steps

I'm writing a react component that wraps the graphiql plugin, basically to allow dynamically adding/editing endpoints. Basically receives the list of endpoints in a property

```typescript
export const GraphiQlWrapper: React.FC<GraphiQlWrapperProps> = (props: GraphiQlWrapperProps) => {
    const { endpoints } = props;

    const getFetcher = (body: any, endpoint: MyGraphQlEndpoint) => {
        return fetch(endpoint.baseUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(body)
        });
    };

    const graphQlBrowseApiFactory = createApiFactory({
        api: graphQlBrowseApiRef,
        deps: {},
        factory: () => GraphQLEndpoints.from(endpoints.map(endpoint => 
            ({
                id: endpoint.title,
                title: endpoint.title,
                fetcher: async (params: any) => getFetcher(params, endpoint)
            })
        ))
    });
    
    const apiFactoryRegistry = new ApiFactoryRegistry();
    apiFactoryRegistry.register('app', graphQlBrowseApiFactory);
    apiFactoryRegistry.register('static', configApiFactory);
    const apiHolder: ApiResolver = new ApiResolver(apiFactoryRegistry);

    return (
        <ApiProvider apis={apiHolder}>
          <MyCustomThemeProvider>
            <Router />
          </MyCustomThemeProvider>
        </ApiProvider>
    );
};
```

And then the main react component

```typescript
const MyReactComponent: React.FC = () => {

    const [ isOpenPanel, openPanel ] = useState(false);
    const [ title, setTitle ] = useState('');
    const [ baseUrl, setBaseUrl ] = useState('');
    const [ endpointIndex, setEndpointIndex ] = useState(0);
    const [ key, setKey ] = useState(0);

    const endpoints: MyGraphQlEndpoint[] = [
      {
        title: title,
        baseUrl: baseUrl
      },
    ];

    function saveEndpoint() {
      const endpoint = endpoints[endpointIndex];
      endpoint.title = title;
      endpoint.baseUrl = baseUrl;
      setKey(key + 1);
      openPanel(false);
    }

    function cancelEdit() {
      const endpoint = endpoints[endpointIndex];
      setTitle(endpoint.title);
      setBaseUrl(endpoint.baseUrl);
      openPanel(false);
    }

    return (
      <>
          <HorizontalStack>
            <ActionButton
              iconProps={{ iconName: 'Settings' }}
              text='Configure'
              ariaLabel={'Configure'}
              onClick={() => openPanel(true)}
              />
            <Panel 
              headerText='Configure API Endpoints'
              isOpen={isOpenPanel}
              onDismiss={() => cancelEdit()}
              onRenderFooterContent={() => (
                <div>
                  <ActionButton
                    primary
                    onClick={saveEndpoint}
                    disabled={!title || !baseUrl}
                  >Save</ActionButton>
                  <ActionButton onClick={() => cancelEdit()}>Cancel</ActionButton>
                </div>
              )}
              >
                <VerticalStack>
                  <TextField
                    label='API name'
                    defaultValue={title}
                    required
                    onChange={(event, value) => setTitle(value)}
                    />
                  <TextField
                    label='API url'
                    defaultValue={baseUrl}
                    required
                    onChange={(event, value) => setBaseUrl(value)}
                    />
                </VerticalStack>
            </Panel>
          </HorizontalStack>
      <GraphiQlWrapper key={key} endpoints={endpoints} />
      </>);
}

export default MyReactComponent;
```

This is the simple test I wrote to verify.

```typescript
import React from 'react';
import ReactDOM from 'react-dom';
import MyReactComponent from './MyReactComponent';

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<MyReactComponent/>, div);
  ReactDOM.unmountComponentAtNode(div);
});
```

### 🖥️ Your Environment

MacOS with node 16.20.0, npm 8.19.4, using these dependencies

```
    "@backstage/app-defaults": "^1.4.2",
    "@backstage/config": "^1.0.8",
    "@backstage/core-app-api": "^1.9.1",
    "@backstage/core-components": "^0.13.4",
    "@backstage/core-plugin-api": "^1.5.3",
    "@backstage/plugin-graphiql": "^0.2.53",
    "@backstage/theme": "^0.4.1",
    "@backstage/version-bridge": "^1.0.4",
    "@material-ui/core": "^4.12.4",
    "@material-ui/icons": "^4.11.3",
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment] 2023-10-05 12:21
Hey @acwilan, could we get a reproduction repository or something here to help us dig in a little bit? It looks like there could be a bad `role` configured in one of the `package.json`s or something which is causing this error in bundling.

**Comment by acwilan** [comment] 2023-10-05 15:37
@benjdlambert let me put up a public repo to reproduce the issue, will get back to you

**Comment by acwilan** [comment] 2023-10-05 20:03
@benjdlambert I've set up this repository https://github.com/acwilan/graphiql-wrapper

**Comment by benjdlambert** [comment] 2023-10-09 11:27
Ah @acwilan it looks like you've setup the backstage repository without using `npx @backstage/create-app`, which does a lot of this setup for you.

For these tests in particular, I think it's most likely caused by `npm run test` executing `react-scripts` instead of `backstage-cli test`.

We don't really support installing and running backstage like this, and would recommend using `@backstage/create-app` to create a new installation of backstage locally.

**Comment by camilaibs** [comment] 2023-10-12 09:46
Thanks everyone for the great support here, closing the issue based on @benjdlambert's last comment.

**Closed by camilaibs** 2023-10-12 09:46 UTC
Labels: bug
