### ISSUE TITLE
Login via Auth0 does not persist

### ISSUE THREAD

**Issue by sonali-mishra-94** [backstage/backstage#8933] opened 2022-01-14 11:42 UTC
After login into Backstage application via Auth0 auth-provider, the login session does not persist.

## Expected Behavior

Post login via Auth0 or any Oauth2.0 based authentication provider, the local storage should have saved session details. Subsequent refreshes or new tabs should not request user login again.

## Current Behavior

After login to Backstage via Auth0, the session details do not get saved in the local storage. This leads to repeated user login requests upon refresh/new tab. 
All the information required for the session schema is available. The error is in the session local storage.

![image](https://user-images.githubusercontent.com/90190248/149461534-a4c2ab6c-62d6-4942-8586-663f93be5401.png)

## Possible Solution

https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/lib/AuthSessionManager/RefreshingAuthSessionManager.ts does not have a saveSession implementation. 

Taking Github as an example because this error is not present in login via Github.
Github is using a mux for session storage comprised of AuthSessionStore https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/lib/AuthSessionManager/AuthSessionStore.ts#L132 that has a saveSession.

A possible fix could be to have a similar saveSession available for OAuth2.

## Steps to Reproduce

1. Setup Auth0 configuration by providing clientId, clientSecret and domain in app-config.yaml file.
2. Follow https://backstage.io/docs/api/deprecations#generic-auth-api-refs to setup auth0

Add the following code to apis.ts file:
```
export const acmeAuthApiRef: ApiRef<
  OAuthApi &
  ProfileInfoApi &
  BackstageIdentityApi &
  SessionApi
  > = createApiRef({
  id: 'internal.auth.acme',
});
```

```
  createApiFactory({
    api: acmeAuthApiRef,
    deps: {
      discoveryApi: discoveryApiRef,
      oauthRequestApi: oauthRequestApiRef,
      configApi: configApiRef,
    },
    factory: ({ discoveryApi, oauthRequestApi, configApi }) =>
      OAuth2.create({
        discoveryApi,
        oauthRequestApi,
        provider: {
          id: 'auth0',
          title: 'Auth0',
          icon: () => null,
        },
        defaultScopes: ['openid', 'email', 'profile'],
        environment: configApi.getOptionalString('auth.environment'),
      }),
  })
```
Add the following to identityProvider.ts file

```
  {
    id: 'auth0-auth-provider',
    title: 'Auth0',
    message: 'Sign In using Auth0',
    apiRef: acmeAuthApiRef,
  },
```

Add the following to App.tsx

```
    <Route
      path="/settings"
      element={
        <UserSettingsPage
          providerSettings={
            <ProviderSettingsItem
              title="AUTH0"
              description="Provides sign-in via Auth0"
              apiRef={acmeAuthApiRef}
              icon={Star}
            />
          }
        />
      }
    />
```
3. yarn start both the backend and frontend
4. Login via Auth0
5. Inspect the local session storage. It will not have any session stored.
6. Press refresh/open another Backstage app tab. The login does not persist.

## Context

Inability to configure login via Auth0 or OAuth2 based auth-providers.

## Your Environment

- NodeJS Version (v14): v14.18.3
Output of `yarn backstage-cli info` command on my Backstage App

```
OS:   Darwin 20.6.0 - darwin/x64
node: v14.18.3
yarn: 1.22.1
cli:  0.10.2 (local)

Dependencies:
  @backstage/catalog-client       0.3.19
  @backstage/core-app-api         0.1.24
  @backstage/core-components      0.3.3, 0.4.2, 0.5.0, 0.6.1, 0.7.6
  @backstage/core-plugin-api      0.1.13, 0.2.2
  @backstage/plugin-catalog-react 0.4.6, 0.5.2
✨  Done in 1.25s.
```

**Comment by Rugvip** [comment] 2022-01-18 16:54
Thank you for reporting!

The `OAuth2 `-based providers don't and shouldn't store sessions in local storage. They're stored in a cookie scoped to the auth provider on the backend instead. This is quite different that the GitHub auth implementation, which doesn't work the same way.

Still wondering what's going on here though. Do you see any cookies if you navigate to `<backend.baseUrl>/api/auth/auth0-auth-provider/handler/frame`?
Are there any errors shown in the logs or anything else that's indicating that something's up?

**Comment by sonali-mishra-94** [comment] 2022-01-19 08:32
Oh okay, thanks for your response @Rugvip :) 
 
Do you see any cookies if you navigate to <backend.baseUrl>/api/auth/auth0/handler/frame?
- Yes I can see a cookie being set here `auth0-nonce`
However, there is no cookie on the frontend. Shouldnt it require a cookie to create front-end session, so that it comes with the next request to the backend/application? Why is the cookie being set on backend domain?

Are there any errors shown in the logs or anything else that's indicating that something's up?
- No, couldnt find any error in the logs

**Comment by sonali-mishra-94** [comment] 2022-01-19 09:01
Also, after successful login when I press refresh the following call is made:
<backend.baseUrl>/api/auth/auth0/refresh?optional&env=development

with the following error response:
"Refresh token is not supported for provider auth0"

**Comment by Rugvip** [comment] 2022-01-19 09:10
Oh that would explain it 😁 

Looks like it's [explicitly disabled](https://github.com/backstage/backstage/blob/f92294b0047eac83d1346649b937d09d4dc217e3/plugins/auth-backend/src/providers/auth0/provider.ts#L258), and has been since it was added. I'm not really seeing anything in the original PR that makes it look like that was intentional, so I'm assuming it's just a bug.

Do you have a setup where you can try disabling it easily? I think it's enough that we just verify that refresh works as expected and we can prolly then get rid of the flag

**Comment by sonali-mishra-94** [comment] 2022-01-19 09:20
Okay, I tried to enable refresh explicitly to see if refresh is working but then received the following error response:
"Refresh failed; caused by InputError: Missing session cookie"

**Comment by Rugvip** [comment] 2022-01-20 11:57
Alright, might simply be the case that auth0 doesn't support refresh in the default setup?

**Comment by sonali-mishra-94** [comment] 2022-01-20 12:01
I checked my application settings on Auth0 to see if I missed out this configuration. But I have set it up:
![image](https://user-images.githubusercontent.com/90190248/150335018-44628988-3280-4004-8dff-ece921acadd3.png)

**Comment by Rugvip** [comment] 2022-01-20 16:36
Hmm, if you log the refresh token that's being passed through [here](https://github.com/backstage/backstage/blob/bed2da46afe484667bb2c8e25f89941bd78610c2/plugins/auth-backend/src/providers/auth0/provider.ts#L86), do you see it, or is it empty? Wanna figure out if this is an issue on the passport/auth0 side or if it's something going wrong after that.

**Comment by sonali-mishra-94** [comment] 2022-01-21 08:35
I checked, its being passed as `undefined`

**Comment by Rugvip** [comment] 2022-01-21 09:24
Hmm, alright, so at least we know that it's not being lost somewhere then. It may be that Auth0 requires a particular scope to be passed for refresh to be allowed. You could try adding `'offline_access'` [here](https://github.com/backstage/backstage/blob/7fdeeead480075abe1d0b966f6c0b9f67480b894/packages/core-app-api/src/apis/implementations/auth/auth0/Auth0Auth.ts#L56), like for example the [OneLogin](https://github.com/backstage/backstage/blob/7fdeeead480075abe1d0b966f6c0b9f67480b894/packages/core-app-api/src/apis/implementations/auth/onelogin/OneLoginAuth.ts#L49) provider does.

**Comment by sonali-mishra-94** [comment] 2022-01-24 06:48
@Rugvip Thanks alot for your help! This seems to have worked. Not just by adding 'offline_access' [here](https://github.com/backstage/backstage/blob/7fdeeead480075abe1d0b966f6c0b9f67480b894/packages/core-app-api/src/apis/implementations/auth/auth0/Auth0Auth.ts#L56) owing to deprecation but also by the following change at apis.ts file.

```
  createApiFactory({
    api: acmeAuthApiRef,
    deps: {
      discoveryApi: discoveryApiRef,
      oauthRequestApi: oauthRequestApiRef,
      configApi: configApiRef,
    },
    factory: ({ discoveryApi, oauthRequestApi, configApi }) =>
      OAuth2.create({
        discoveryApi,
        oauthRequestApi,
        provider: {
          id: 'auth0',
          title: 'Auth0',
          icon: () => null,
        },
        defaultScopes: ['openid', 'email', 'profile', '**offline_access**'],
        environment: configApi.getOptionalString('auth.environment'),
      }),
  })
```

**Comment by sonali-mishra-94** [comment] 2022-01-24 06:50
We still need to consider removing the explicit disableRefresh setting. 
Maybe we can allow it via config like https://github.com/backstage/backstage/blob/f92294b0047eac83d1346649b937d09d4dc217e3/plugins/auth-backend/src/providers/oauth2/provider.ts#L247 ?

**Comment by Rugvip** [comment] 2022-01-24 17:55
Nice! :grin:

I think it's alright to have refresh always enabled. Do you want to create a PR that applies these fixes? 🙏

Good find on the change to `apis.ts` as well, forgot we did that 😅

**Comment by sonali-mishra-94** [comment] 2022-01-26 03:15
Thanks alot! Sure, I ll create a PR

**Comment by R-cen** [comment] 2022-02-11 10:11
Hi @Rugvip, I am facing similar issues to this but with the Okta Auth provider. I can confirm that the okta-refresh-token cookie is set on the backend API domain (which is different to our frontend domain) after logging in. This doesn't seem to be sent when the browser is refreshed which is resulting in the user being redirected to the signin page and popup. Upon sign in popup, the login then proceeds automatically. Do you have any thoughts on what might be happening here?

**Comment by Rugvip** [comment] 2022-02-16 00:52
@R-cen alright, let's dig into the refresh request in that case, since that seems to be the trouble. Does the refresh request fail and in that case in what way?

The request looks something like this, although ofc `okta` instead of `github`:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/4984472/154174928-454a5327-003d-4861-9417-8f2607074c78.png">

You should be able to see a `okta-refresh-token` cookie as part of the request headers of that request. If it's not there then it would seem the cookie isn't being set correctly and there might be a misconfigured `baseUrl` or `callbackUrl` somewhere. If you see the cookie in the client-side request headers, then I'm wondering whether it arrives in the server-side request? You could also try to execute a refresh request from outside the browser via curl or similar to debug from there.

**Comment by R-cen** [comment] 2022-02-16 00:57
thanks @Rugvip, for now we have updated both the backend and frontend to be served on the same domain instead which resolves the issue we were seeing

**Comment by benjdlambert** [comment] 2022-02-17 15:28
Going to close this, but if anyone else runs into this please let us know and we can keep debugging!

**Closed by benjdlambert** 2022-02-17 15:28 UTC
Labels: bug

**Comment by carlossmartini** [comment] 2023-03-04 20:41
@Rugvip  I know it's been a while since this closed, but I'm currently running into this issue with OKTA.  I can login fine, and if I hit /api/auth/okta/handler/frame?env=myenv I can see the okta-nonce cookie.  But the session persistence is not there.  Once it tries to call /api/auth/okta/refresh?optional&env=myenv the okta-refresh-token cookie is not there and I get the error message of "name":"AuthenticationError","message":"Invalid X-Requested-With header" with a status code of 401. offline_access is setup.  Any other ideas?  You started to mention baseUrl or callbackUrl, but looks like previous person figured it out before you got too far there.

**Comment by carlossmartini** [comment] 2023-03-07 01:15
I figured out the issue.  offline_access scope is probably the answer if you're having issues with session duration.  The OKTA provider out of the box has offline_access as a default scope so that's probably not the issue if you're using OKTA.  However, if you're using OKTA you have to make sure it is setup at the auth server and app server level.  That was my issue.  I had it setup at the app server level, but didn't at the auth server and never really saw any error or warning so the app server wasn't really doing anything as that is supposed to be a subset(or all) of the scopes the auth server has.  Hope this helps someone.

**Comment by Diego-Previdi** [comment] 2023-05-05 15:41
Hi @carlossmartini I have the same issue you had with the "Invalid X-Requested-With header" and status code of 401 on refresh.
I added already the `prompt: auto` as from [here ](https://github.com/backstage/backstage/issues/4065) and the Okta team confirmed that they assigned the following scopes to the refresh: `groups, openid, profile, email, offline_access`.
Can you provide some more details In order for me to understand what I am missing?
