### ISSUE TITLE
🐛 Bug Report: Main documentation search is broken

### ISSUE THREAD

**Issue by joshjung** [backstage/backstage#25048] opened 2024-06-03 20:09 UTC
### 📜 Description

Using the search on backstage.io frequently breaks and gives a 404 page on the links that are indexed.

For example, go to backstage.io and search for "debug", and click any of the links and it will say "Page Not Found".

### 👍 Expected behavior

Links in the search should work.

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-06-03 at 15 08 01](https://github.com/backstage/backstage/assets/913181/b912dad9-fee8-4629-a492-20f667643d49)
![Screenshot 2024-06-03 at 15 08 15](https://github.com/backstage/backstage/assets/913181/085ec4a8-cc81-4197-ae0c-a7c801110964)

### 👟 Reproduction steps

1. Backstage.io
2. Search for "debug" (or lots of other things)
3. Click on any of the links
4. Observe 404s while sipping on your favorite ale

Other examples:

Search for "user" and click first link takes you to `https://backstage.io/docs/reference/plugin-splunk-on-call.user/` (404)

Search for "entity" and click first link takes you to `https://backstage.io/docs/reference/plugin-cost-insights.entity/` (404)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment] 2024-06-03 20:23
Just want to add on that part of the problem is that the plugins that were moved to the Community Plugins repo still seem to be part of the search index.

This exact example with "debug" isn't showing those results though 🤔

**Comment by awanlin** [comment] 2024-06-03 20:24
It's the same underlying issue - bad search index. We moved these doc on debugging to the tooling folder: https://backstage.io/docs/tooling/local-dev/debugging

**Comment by benjdlambert** [comment] 2024-06-10 12:02
@awanlin I think that we've rebuilt the index now and it seems to work

**Comment by awanlin** [comment] 2024-06-10 12:21
Nice! Yes, it does look much better thanks @benjdlambert 🚀 

@joshjung, can you confirm that your search results are better now, please? If they are can you close this issue as well?

**Closed** 2024-06-10 17:17 UTC
Labels: bug, documentation
