### ISSUE TITLE
TechDocs: Cloud Storage bucket nested directories

### ISSUE THREAD

**Issue by ayshiff** [backstage/backstage#3948] opened 2021-01-06 23:03 UTC
## Feature Suggestion

Enable publishers support using nested directories in a bucket.

## Possible Implementation

Publishers should be able to handle the documentation sites in a nested directory, let's say `/root-path/docs` as the root.

We can define a `rootPath` variable  inside `techdocs.publisher.awsS3` and `techdocs.publisher.googleGcs`and access it inside our publishers.

For example:

```ts
const rootPath = config.getOptionalString('techdocs.publisher.awsS3.rootPath');
```

We can then use this variable to tell the publisher that our sites documentation are located in `rootPath/*` as the root.

## Context

- awsS3 publisher: `packages/techdocs-common/src/stages/publish/awsS3.ts` [Link](https://github.com/backstage/backstage/blob/master/packages/techdocs-common/src/stages/publish/awsS3.ts)
- googleGcs publisher: `packages/techdocs-common/src/stages/publish/googleStorage.ts` [Link](https://github.com/backstage/backstage/blob/master/packages/techdocs-common/src/stages/publish/googleStorage.ts)

**Comment by OrkoHunter** [comment] 2021-02-06 12:59
Closing as duplicate of https://github.com/backstage/backstage/issues/4070

**Closed by OrkoHunter** 2021-02-06 12:59 UTC
Labels: docs-like-code, enhancement, help wanted
