### ISSUE TITLE
Yarn 3 compatibility

### ISSUE THREAD

**Issue by taras** [backstage/backstage#8054] opened 2021-11-15 15:51 UTC
## Context

One of the takeaways from the Nov 4th, Backstage Openmic event was slow build times increasing becoming an issue for developers using Backstage. I want to start looking at how we can improve this in our project because we find hot module reloading to be fragile and the [existing build system doesn't support extension points that we need](https://github.com/backstage/backstage/issues/7102).

We're going to look at a few different options including [NX Workspaces](http://nx.dev). In the mean time, I wanted to learn about the status of Yarn 3 compatibility.  

## Feature Suggestion

It would be desirable to get bug fixes and performance improvements that come with Yarn 3. Some bug fixes are not getting backported to Yarn 1. Is backstage compatible with yarn 3?

## Possible Implementation

- Unknown

**Comment by Rugvip** [comment] 2021-11-16 08:35
Just to set the scope of this, are you thinking Yarn 3 with the node_modules linker or PnP?

I tried Yarn 3 the other day with the modules linker and it resulted in an much larger install and seemed slower as well, although it was a quite unscientific test. Compatibility-wise it seemed alright except that our tooling that works with the Lockfile would need updating. 

A more general question is what the breakdown of time spent is like and where slowness hurts the most. Is it local dev, CI, or production? And type checking, building, testing, yarn install, or something else?

**Comment by msamad** [comment] 2022-01-20 20:28
@Rugvip I played around a bit with Yarn 3 with Pnp in our backstage app that was created using `@backstage/create-app`. Looks like quite a difference, I went with [zero-install strategy](https://yarnpkg.com/features/zero-installs) . 

Cloning the repo has a bit of overhead now that the dependencies are committed as well for zero-install but didn't feel significant. Not needing to run `yarn install` feels so good. Didn't capture the the exact times, as just wanted to check but it sure feels great to work with.

I did get stuck at the lockfile though, as you mentioned above that it needs to be updated. Just ended up with this when I tried `yarn start`
```
SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile
```

Looking at what I've got, it would certainly improve developer experience when doing local dev. Switching branches would be so simple and of coarse, reliability of reproduceable and faster builds in CI would be great too if that lockfile issue is solved.

**Comment by Rugvip** [comment] 2022-01-26 09:32
Yep we've got some utilities based on parsing `yarn.lock` that would make sense to make optional. Both to make it easier to do these kind of explorations, but also just in general in case people want to run `npm` instead or whatnot. Sweetest thing would really be a generic lockfile parser that supports all package managers.

Bit more concretely, the check over [here](https://github.com/backstage/backstage/blob/0386a5975542420ba28796dbbf664e9a04d82a3a/packages/cli/src/commands/app/serve.ts#L28) could check if `yarn.lock` exists before it runs, and also just fail with a warning if it fails to parse. Happy if anyone wants to contribute that, or we might be able to look at it at some point.

**Comment by msamad** [comment] 2022-01-26 23:13
@Rugvip will this work? https://github.com/backstage/backstage/pull/9193

**Comment by Rugvip** [comment] 2022-01-27 15:33
@msamad Yep, thank you! How far do you get with that in place? :grin:

**Comment by msamad** [comment] 2022-01-27 16:16
> @msamad Yep, thank you! How far do you get with that in place? 😁

Looks like I've missed the release today 😢 Think I have all of it setup and #9193 should allow me to start the app now.

**Comment by djamaile** [comment] 2022-02-05 13:46
@msamad did you try out? was wondering for it's performace

**Comment by msamad** [comment] 2022-02-07 00:47
@djamaile performance in which area? 

I haven't really tried it yet, ran into `yarn.lock` incompatibility again when I tried to bump the dependencies. Did a quick V2 of version bump code in local backstage cli, it sort of worked but is not complete and needs more attention.

**Comment by msamad** [comment] 2022-02-09 20:39
I've tried a quick hack of version bump for yarn 3 lock file and that worked but then hit issues with bundler when using pnp. That pnp is what I was most interested in as it would have improved developer experience with zero-installs and improved the reliability of builds. Looks like there is a need to look deep into the bundler and possibly other parts as well to get it all going with yarn 3 pnp, not as simple as I thought 😭 . This is where I stop for now, don't think I have intimate details of the backstage cli or enough time to dig deep into it at this point unfortunately.

It may work by keeping nodeLinker to node-modules instead of pnp but I don't think that is worth the effort at this point, not much to gain.

**Comment by Rugvip** [comment] 2022-02-11 12:56
I actually think it would be quite interesting and beneficial to move to Yarn 3 even if we have to use the `node_modules` linker. There's plenty of other potential benefits like bugfixes, `workspace:` dependencies, etc.

Happy to go down the pnp support rabbit hole too though :grin: wouldn't mind adding Yarn FS support anywhere we don't have it for example.

**Comment by msamad** [comment] 2022-02-14 00:43
> There's plenty of other potential benefits like bugfixes, workspace: dependencies, etc.

didn't look into other yarn 3 features to be honest so I'll just trust you on this. 😄 

> Happy to go down the pnp support rabbit hole too though 😁 wouldn't mind adding Yarn FS support anywhere we don't have it for example.

hmmm, this is quite tempting, I do like going down the rabbit holes sometimes to have some fun. But, don't think I've got that much time at this point. May be, if we split it into two parts. 
- 1st to just upgrade to yarn 3 with `node_modules` linker
- 2nd to use `pnp` linker

**Comment by dschwank** [comment] 2022-02-16 07:25
Thanks for bringing this up! ❤️

> A more general question is what the breakdown of time spent is like and where slowness hurts the most. Is it local dev, CI, or production? And type checking, building, testing, yarn install, or something else?

@Rugvip For us it is the `yarn install` procedure which is pretty slow. For sure, one doesn't have to install it quite often, but from time to time we have to and that always takes quite a while.

I gave it a try this morning in our main repo and it looked quite promising - I used the `node-modules` linker to make first the small step and it was pretty amazing. In detail I used the following configuration options:

```yaml
nodeLinker: node-modules
compressionLevel: 0
enableGlobalCache: true
```

(To prevent you from the trap I walked into - it is `node-modules`, NOT `node_modules` ... argh)

Here are some timing results from my local machine - it is pretty impressive:

| Version | Timing |
| ---- | --- |
| yarn 1.22.10 (without cache) | `yarn install 192,96s user 226,60s system 66% cpu 10:29,61 total` |
| yarn 3.1.1 (without cache) | `yarn install  77,96s user 105,34s system 131% cpu 2:19,67 total` |
| yarn 3.1.1 (with global cache) | `yarn install  43,23s user 114,34s system 151% cpu 1:43,85 total` |

So we are - in this non-scientific test - **down from ~10:30min to ~2:20min** 🚀 . That's pretty impressive, especially because the change is pretty small. @msamad are you about to open a PR for that?

**Comment by msamad** [comment] 2022-02-16 07:36
@dschwank that's great! I haven't done anything about that yet so all yours if you want to do a PR.

**Comment by dschwank** [comment] 2022-02-17 14:38
I created #9619, it is still work in progress - I tested the main functionality, but not sure if _everything_ is working and if we might have to do further adjustments.

https://github.com/backstage/backstage/pull/9619

**Comment by narwold** [comment] 2022-04-25 19:43
Yarn 1 is now 2 versions behind, and I'm not comfortable continuing to have a product in use in my organization that uses it. We long ago determined that `pnpm` was much faster for us... or we fall back on `npm` if we have to. Yarn 2/3 have a much more complicated architecture, but even that as an isolated use case would be better for us than Yarn 1 since in my opinion it's increasingly legacy and Yarn 2/3 are much more performant. I'd love to see some progress on alternatives here.

**Comment by narwold** [comment] 2022-04-25 19:45
Additional note: oftentimes a project can be easily converted, but it appears Backstage will have some challenges due to Yarn being deeply embedded in the CLI (parsing the lockfile, etc.)

**Comment by webark** [comment] 2022-05-07 23:10
so using `@yarnpkg/parsers` vs `@yarnpkg/lockfile` allows for the proper parsing of the lockfile across all versions. (and all version check tests pass with this switch). However, its `stringifySyml` seems to only output the latest lockfile format, so I'm not sure of all the use cases where we parse the file, but then want to output it in a valid format.

**Comment by webark** [comment] 2022-05-07 23:11
There is also the `yarn-lock-check` command which relies on `@yarnpkg/lockfile` but this might be able to be switched out with a package that supports all 3 versions.

**Closed** 2022-05-19 08:44 UTC
Labels: enhancement

**Comment by dimisjim** [comment] 2023-11-02 16:19
Is yarn v3 fully supported?

There is still this weird message in the packages/backend/Dockerfile: backstage/backstage/blob/master/packages/backend/Dockerfile#L50 "we don't recommend Yarn 3 yet"

**Comment by webark** [comment] 2023-11-02 18:31
we have been using yarn 3 for a year now with no issues, and are going to try yarn 4 next week.
