### ISSUE TITLE
 yarn lint-staged Parsing error: The keyword 'const' is reserved

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#18100] opened 2023-06-02 20:06 UTC
### 📜 Description

yarn lint-staged throw error on scripts folder.

### 👍 Expected behavior

It should not through error. either it should be ignored or pass the lint.

### 👎 Actual Behavior with Screenshots

it should not throw error

### 👟 Reproduction steps

run following command

yarn lint-staged 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment] 2023-06-02 20:32
@lalit774, any chance you could include the full error? Also details about the files? I'm assuming you are running this against the Backstage repo itself, is that correct?

Currently if I run `yarn lint-staged` I just get "No staged files found." as output

**Comment by lalit774** [comment] 2023-06-02 20:39
@awanlin yes, I am running against backstage repo. I noticed this issue for stage file for scripts folder on backstage root and i had following files. for time being, I have added script folder in .eslintignore and it works. 
check-docs-quality.js
prepare-release.js
techdocs-cli.js

**Comment by awanlin** [comment] 2023-06-05 11:57
Thanks, the tricky thing with this is that you need changes to be able to really trigger it. I did a fresh clone of `master` as well as my own fork updated to latest and all I get is when I run `yarn lint-staged` is the "No staged files found." as output like before. 

Would you be able to provide more details on what you are working on and what the changes are? That could help figure out what's going on but like I said, without the changes it's going to be pretty hard

**Comment by jhaals** [comment] 2023-06-07 08:07
Agree with Awanlin here, there's currently not enough information to confirm that this is actually a bug and something that needs fixing in the main repository. I can edit said script, stage it and run the commands without problems. Please submit enough information for us to understand and reproduce the problem you're seeing.

**Comment by awanlin** [comment] 2023-06-07 12:50
OK, this helps, so the command you ran was `yarn test` and then? Sorry, just can't tell this part from the image

As for documentation on linting there is some here, I found this by doing a search for lint: https://backstage.io/docs/local-dev/cli-build-system/#linting

**Comment by Rugvip** [comment] 2023-06-08 12:05
Wanna highlight that it's this that makes the scripts lint in the main repo: https://github.com/backstage/backstage/blob/master/scripts/.eslintrc.js. In general you'll need either an ESLint config or ignore for any code in the repo. We don't ship the scripts folder in new apps, but feel free to copy ours 😁

**Comment by Rugvip** [comment] 2023-06-13 11:39
Gonna close this since adding `.eslinrc*` is the solution to this issue.

**Closed by Rugvip** 2023-06-13 11:39 UTC
Labels: bug
