### ISSUE TITLE
🐛 Bug Report: Missing morgan module

### ISSUE THREAD

**Issue by bcaurel** [backstage/backstage#25318] opened 2024-06-19 12:28 UTC
### 📜 Description

Using the latest version of techdocs-cli I have the following error : 
`Cannot find module 'morgan'
2024-06-19T12:08:28.1594249Z Require stack:
2024-06-19T12:08:28.1596103Z - 
...@techdocs/cli/node_modules/@backstage/backend-common/dist/index.cjs.js`

I saw a commit with a potential fix but seems to be not deployed : https://github.com/backstage/backstage/commit/c964a3d03cce15461c843dc38b0eeb46df268b76

### 👍 Expected behavior

No dependency error 

### 👎 Actual Behavior with Screenshots

`Cannot find module 'morgan'
2024-06-19T12:08:28.1594249Z Require stack:
2024-06-19T12:08:28.1596103Z - 
...@techdocs/cli/node_modules/@backstage/backend-common/dist/index.cjs.js`

### 👟 Reproduction steps

1. exec` techdocs-cli generate`
2. exec techdocs-cli publish

### 📃 Provide the context for the Bug.

Trying to push some docs to S3 in a GHA workflow

### 🖥️ Your Environment

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment] 2024-06-19 13:34
Closing as a duplicate of https://github.com/backstage/backstage/issues/25303

**Closed by awanlin** 2024-06-19 13:34 UTC
Labels: bug
