### ISSUE TITLE
custom relationship types not choosable in relationship pop up list

### ISSUE THREAD

**Issue by djamaile** [backstage/backstage#8896] opened 2022-01-12 22:42 UTC
If you pop up to see all the relations I would like to see the custom relations I have added to the `catalog-graph` page. 

## Current Behavior

They are not being loaded in the pop up view but are there with the chips. 

<img width="303" alt="Screenshot 2022-01-12 at 23 14 22" src="https://user-images.githubusercontent.com/15789670/149231926-8c82e0c5-dbc9-46fc-ae36-4248b1bc1c90.png">

You can see `isTrusted` and `isTrustedBy` is being loaded in with the chips but not in the pop view. 

## Possible Solution

Maybe change this line here: https://github.com/backstage/backstage/blob/master/plugins/catalog-graph/src/components/CatalogGraphPage/SelectedRelationsFilter.tsx#L71

to:
```tsx
 options={value ? [...new Set([...value, ...relations])] : relations}
```

Let me know what you think.

## Steps to Reproduce

1. Add a new relationship here: https://github.com/backstage/backstage/blob/master/packages/app/src/App.tsx#L155
2. Run application
3. navigate to http://localhost:3000/catalog-graph

## Context

If I click away a custom relationship you not enable it again because it is not choosable in the popview. 

## Your Environment

```sh
yarn run v1.22.17
OS:   Darwin 20.6.0 - darwin/x64
node: v16.13.1
yarn: 1.22.17
cli:  0.10.5 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.3
  @backstage/backend-common                                0.10.2
  @backstage/backend-tasks                                 0.1.2
  @backstage/catalog-client                                0.5.3
  @backstage/catalog-model                                 0.9.8
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.10.5
  @backstage/config-loader                                 0.9.1
  @backstage/config                                        0.1.11
  @backstage/core-app-api                                  0.3.1
  @backstage/core-components                               0.8.3
  @backstage/core-plugin-api                               0.4.1
  @backstage/dev-utils                                     0.2.16
  @backstage/errors                                        0.1.5
  @backstage/integration-react                             0.1.17
  @backstage/integration                                   0.7.0
  @backstage/plugin-api-docs                               0.6.21
  @backstage/plugin-app-backend                            0.3.21
  @backstage/plugin-auth-backend                           0.6.1
  @backstage/plugin-catalog-backend-module-ldap            0.3.8
  @backstage/plugin-catalog-backend                        0.19.4
  @backstage/plugin-catalog-graph                          0.2.5
  @backstage/plugin-catalog-import                         0.7.8
  @backstage/plugin-catalog-react                          0.6.10
  @backstage/plugin-catalog                                0.7.7
  @backstage/plugin-github-actions                         0.4.30
  @backstage/plugin-kubernetes-backend                     0.4.2
  @backstage/plugin-kubernetes-common                      0.2.1
  @backstage/plugin-kubernetes                             0.5.3
  @backstage/plugin-org                                    0.3.33
  @backstage/plugin-permission-common                      0.3.0
  @backstage/plugin-permission-react                       0.2.1
  @backstage/plugin-proxy-backend                          0.2.15
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.7
  @backstage/plugin-scaffolder-backend                     0.15.19
  @backstage/plugin-scaffolder-common                      0.1.2
  @backstage/plugin-scaffolder                             0.11.17
  @backstage/plugin-search-backend-module-pg               0.2.3
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.3.0
  @backstage/plugin-search                                 0.5.4
  @backstage/plugin-shortcuts                              0.1.18
  @backstage/plugin-techdocs-backend                       0.12.2
  @backstage/plugin-techdocs                               0.12.13
  @backstage/plugin-todo-backend                           0.1.17
  @backstage/plugin-todo                                   0.1.17
  @backstage/plugin-user-settings                          0.3.15
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.2
  @backstage/test-utils                                    0.2.1
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1
Done in 0.52s.
```

**Comment by freben** [comment] 2022-01-14 14:58
Yeah, the pairs come in as an [optional prop to CatalogGraphPage](https://github.com/backstage/backstage/blob/71b09c83be5db8b645b61b6f03d61ee2095ef0fc/plugins/catalog-graph/src/components/CatalogGraphPage/CatalogGraphPage.tsx#L100), and their default value when not given, is [hard coded here](https://github.com/backstage/backstage/blob/71b09c83be5db8b645b61b6f03d61ee2095ef0fc/plugins/catalog-graph/src/components/EntityRelationsGraph/relations.ts#L52).

The quick fix you could do on your side is to supply a different list of pairs as a prop to that page.

The more thorough thing would be if the catalog could efficiently provide facets out of its stored data - e.g. all existing kinds, all existing types per kind, all existing labels ... etc. Then this type of selector could more easily be filled in dynamically.

**Comment by freben** [comment] 2022-01-14 15:00
If you are able to successfully pass in a list of pairs that fit your system, feel free to close this issue for now (as "works as intended, even though it's not optimal" so to speak).

If you want a more thorough and smart fix that scours the catalog dynamically, I think that we won't be able to find time for that in the near term - contributions are definitely welcome though.

**Closed** 2022-01-17 17:10 UTC
Labels: bug

**Comment by rolandothedev** [comment] 2025-02-20 22:26
Hi @freben,
Is the quick fix above still the only way to visualize custom relationships?
