### ISSUE TITLE
🚀 Feature: Audit Trails for backstage

### ISSUE THREAD

**Issue by vikyathharekal** [backstage/backstage#21605] opened 2023-11-28 12:54 UTC
### 🔖 Feature description

An audit trail is a chronological record of activities, providing a documented history of actions within a system or organization. It ensures accountability, traceability, and security by logging user activities, system events, and data changes.

### 🎤 Context

Audit trail monitoring should encompass the following activities:
1. Registration of components
2. Execution of templates
3. System updates (such as the YAML updated on GitHub is ingested via a periodic sync/refresh)

### ✌️ Possible Implementation

To capture actions such as component registration and template execution, our approach involves integrating a middleware to intercept API calls. Upon interception, pertinent details like the registered component and the initiating user will be extracted. Subsequently, this information will be sent to our backend systems for storage.

Additionally, we aim to monitor changes to YAML during a refresh, specifically focusing on differences in updated content. Exploring potential solutions, we are considering the development of a custom processor. This processor would be triggered upon any entity modification, allowing us to obtain the new YAML. 
Is there any available mechanism or support to retrieve the old YAML during the custom processor's invocation, enabling us to compute the differences during entity modifications?

We're open to see if this can be contributed!

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment] 2023-11-30 12:32
Indeed, some more intentional audit trail support has been on our mind and would be a worthwhile thing to explore.

Part of it would probably be to implement more parts of https://github.com/backstage/backstage/issues/15999, including more distinct handling and propagation of identities in the services.

Then when the identities are universally available, we'd need a transport. It could be that this actually leveraged the existing loggers, marked in some way so as to be able to distinguish (and perhaps separately persist) audit related payloads. Or an entirely separate audit logging api which happens to by default send to the regular logger, but can be replaced to stream it elsewhere.

**Comment by efenner-cambia** [comment] 2024-02-06 19:52
I would like to see this reopened even if it isn't at the top of the roadmap

**Comment by gioppoluca** [comment] 2024-05-09 14:38
any update on this? is there anything already usable for audit?

**Comment by Rugvip** [comment] 2024-05-10 09:26
Gonna close this as a duplicate of #23950, let's focus the discussion there

**Closed by Rugvip** 2024-05-10 09:26 UTC
Labels: enhancement
