### ISSUE TITLE
techdocs-cli generate fails with manifest for spotify/techdocs:v1.1.0 not found

### ISSUE THREAD

**Issue by ghelyar** [backstage/backstage#13186] opened 2022-08-17 08:18 UTC
## Expected Behavior

docs generated

## Actual Behavior

```
$ techdocs-cli generate
info: Using source dir ...
info: Will output generated files in ...
info: Generating documentation...
Failed to generate docs from ... into ...; caused by Error: (HTTP code 404) unexpected - manifest for spotify/techdocs:v1.1.0 not found: manifest unknown: manifest unknown
```

## Steps to Reproduce

```
npm install -g @techdocs/cli
techdocs-cli generate
```

## Context

This seems to happen on any version of the `@techdocs/cli` package, including 1.1.3 and 1.2.0

It seems to be trying to download the `v1.1.0` tag of the docker image, but [that doesn't exist](https://hub.docker.com/r/spotify/techdocs/tags) - at the time of writing, the latest is `spotify/techdocs:v1.0.4`.

This was working yesterday and started failing today.

Seems to be related to https://github.com/backstage/backstage/issues/11553

**Comment by ghelyar** [comment] 2022-08-17 08:56
From what I can tell by digging through the code, this seems to be caused by `defaultDockerImage` being set to `spotify/techdocs:v1.1.0`, which does not exist, rather than `v1.0.4`, which does exist.
https://github.com/backstage/backstage/commit/23abde02b63e9dda7197c6f1c70f9ac4e1e09939
https://github.com/backstage/backstage/commit/e7d8ef03d37419ec7036fc5588fe6d2267519d59

but I would have thought this would only affect CLI version 1.2.0. I don't know why this is also affecting older versions of the CLI that were previously working.

**Comment by iamEAP** [comment] 2022-08-17 08:59
It looks like there was a problem in the build step associated with the `v1.1.0` release tag that caused it to [publish an old manifest instead](https://github.com/backstage/techdocs-container/runs/7609912296?check_suite_focus=true#step:6:634).

I'm trying to get `v1.1.0` published now.

As for why it would affect older and newer versions of the CLI: I think it's the nature of npm dependencies.  On a fresh install, it will load in the most recent version of `@backstage/plugin-techdocs-node` that still fits the constraint (which would be the most recent version, which contains the version bump).

**Comment by iamEAP** [comment] 2022-08-17 09:32
Alright.  `v1.1.0` is now published (and is a duplicate of `v1.0.4`).  Does the `generate` command work for you now, @ghelyar?

**Comment by ghelyar** [comment] 2022-08-17 09:36
Yes, this seems to be working now, thank you.

For what it's worth, the v1.1.0 release seems to be appearing under [the v1.0.4 branch filter](https://github.com/backstage/techdocs-container/actions?query=branch%3Av1.0.4) even though it's supposedly built from the v1.1.0 release tag. I can't tell where it's getting this v1.0.4 from though, as I can't see any ref of any kind called v1.0.4.

**Comment by iamEAP** [comment] 2022-08-17 09:57
🤔 Yeah, it's all odd to me.  In any event, I created a follow-up (link above) to see if we can make the tag release workflow a little more deterministic (or at least a little more clear).

Thanks for the report!  Will close this out for now.

**Closed by iamEAP** 2022-08-17 09:57 UTC
Labels: bug, docs-like-code
