### ISSUE TITLE
AsyncApi $ref with external URL not possible

### ISSUE THREAD

**Issue by dweber019** [backstage/backstage#9040] opened 2022-01-19 18:32 UTC
## Expected Behavior
I can $ref external urls in AsyncApi definitions.

## Current Behavior
The current behavior is described here https://discord.com/channels/687207715902193673/687235481154617364/933248339116429312 but basically I get the error:
```
Error: Error downloading https://gist.githubusercontent.com/dweber019/9f20724849df6c02e35ecfb152a3d6f4/raw/b634fe410fccd099b8cbfca8b908996eacc97afa/Bong.avsc protocol.get is not a function
```
I think the underling issue is https://github.com/APIDevTools/json-schema-ref-parser/blob/main/lib/resolvers/http.js#L4 which uses core node modules and webpack doesn't provide the polifill anymore?

## Possible Solution
Add polifill => https://github.com/backstage/backstage/blob/8d07a8b038269cba0485cf03dbf2887e7af1f63a/packages/cli/src/lib/bundler/config.ts#L191

## Steps to Reproduce
Here an example definition I have the issue with
```
asyncapi: '2.2.0'
info:
  title: Stockexhange Broker
  version: '1.0.0'

defaultContentType: application/avro

channels:
  sometopic:
    subscribe:
      message:
        $ref: '#/components/messages/Option'

components:

  messages:
    Option:
      title: Option
      schemaFormat: 'application/vnd.apache.avro+json;version=1.9.0'
      payload:
        $ref: 'https://gist.githubusercontent.com/dweber019/9f20724849df6c02e35ecfb152a3d6f4/raw/b634fe410fccd099b8cbfca8b908996eacc97afa/Bong.avsc'
```
You can copy this to https://studio.asyncapi.com/ to see that is works there.

**Comment by Rugvip** [comment] 2022-01-20 17:15
Will close this as a duplicate of #7571, and reopened that one instead. It has quite a lot of discussion that we don't wanna lose

**Closed by Rugvip** 2022-01-20 17:15 UTC
Labels: bug
