### ISSUE TITLE
🐛 Bug Report: UI issue when expanding the my groups entity when sidebar is pinned. 

### ISSUE THREAD

**Issue by nia-potato** [backstage/backstage#25888] opened 2024-08-02 09:00 UTC
### 📜 Description

when sidebar is pinned, and hovering over the my groups tab, the groups tab covers up the sidebar. 

### 👍 Expected behavior

when the sidebar is pinned, and hovering over the My groups tab, it should dynamically expand. 

### 👎 Actual Behavior with Screenshots

<img width="97" alt="Screenshot 2024-08-02 at 01 54 43" src="https://github.com/user-attachments/assets/e9ffe54b-ca5f-4dd0-bf6c-84e0d0c47cb1">

### 👟 Reproduction steps

1. sidebar is pinned 
2. hover over my groups tab

### 🖥️ Your Environment

Backstage version: 1.29.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment] 2024-08-05 13:35
Ah, that does sound like a visual bug. Would you like to take a stab at fixing that? 🙏

**Comment by fostemi** [comment] 2024-08-05 17:11
Hi @nia-potato - I am attempting to reproduce your bug. I have...
1. Pinned Side bar
2. Hovered over Home and successfully expanded that tab
I may be missing something, could you expand on the reproduction steps a bit more?

**Comment by nia-potato** [comment] 2024-08-06 20:27
https://github.com/user-attachments/assets/5bf60645-81a9-4dee-8f59-036de7802fa6

@fostemi

**Comment by darylgraham** [comment] 2024-08-06 23:12
I have had this issue in my instances too, just not got around to looking deeper into it.

To replicate:
1. **Unpin** the sidebar (ie: allow it to collapse).
2. While the sidebar is in a collapsed state, move the mouse over a menu item with a submenu.

The sidebar begins to expand, but then the submenu expansion is triggered, which stops the sidebar expansion from continuing. The issue is only triggered if the sidebar expansion and submenu expansion are both initiated at around the same time. Allowing the sidebar to fully expand before hovering over a submenu works as expected.

https://github.com/user-attachments/assets/7f9a44de-44e3-4408-90c6-e1d5e92d57fa

**Comment by ja9-look** [comment] 2024-09-20 17:26
Hi @nia-potato - I would love to work on this issue. Please kindly assign me - thank you :)

**Comment by camilaibs** [comment] 2024-09-23 07:30
Hi @ja9-look, we appreciate you offering help. There is already a pull request open; could you check that the changes align with what you wanted?
https://github.com/backstage/backstage/pull/26053

**Comment by ja9-look** [comment] 2024-09-23 07:56
Oh yes @camilaibs - thank you for letting me know! The PR LGTM. Do you know why it's taking so long to get reviewed/merged?

**Closed** 2024-09-25 12:46 UTC
Labels: bug, good first issue, help wanted
