### ISSUE TITLE
Techdocs plugin fails with "unexpected end of file"

### ISSUE THREAD

**Issue by nadworny** [backstage/backstage#11512] opened 2022-05-13 15:41 UTC
## Expected Behavior
Techdocs are generated.

## Actual Behavior
Techdocs generation fails
```
[1] 2022-05-13T15:34:01.125Z backstage info ::1 - - [13/May/2022:15:34:01 +0000] "GET /api/techdocs/static/docs/default/component/space/index.html HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
[1] 2022-05-13T15:34:01.133Z backstage info ::ffff:127.0.0.1 - - [13/May/2022:15:34:01 +0000] "GET /api/catalog/entities/by-name/component/default/space HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2022-05-13T15:34:01.134Z backstage info ::ffff:127.0.0.1 - - [13/May/2022:15:34:01 +0000] "GET /api/catalog/entities/by-name/component/default/space HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2022-05-13T15:34:01.135Z backstage info ::ffff:127.0.0.1 - - [13/May/2022:15:34:01 +0000] "GET /api/catalog/entities/by-name/component/default/space HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2022-05-13T15:34:01.136Z backstage info ::1 - - [13/May/2022:15:34:01 +0000] "GET /api/techdocs/metadata/entity/default/component/space HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
[1] 2022-05-13T15:34:01.140Z backstage info ::1 - - [13/May/2022:15:34:01 +0000] "GET /api/techdocs/metadata/techdocs/default/component/space HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
[1] 2022-05-13T15:34:01.161Z backstage info ::1 - - [13/May/2022:15:34:01 +0000] "GET /api/techdocs/static/docs/default/component/space/assets/stylesheets/main.50e68009.min.css HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
[1] 2022-05-13T15:34:01.161Z backstage info ::1 - - [13/May/2022:15:34:01 +0000] "GET /api/techdocs/static/docs/default/component/space/assets/stylesheets/palette.e6a45f82.min.css HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
[1] 2022-05-13T15:34:01.182Z search info Search request received: term="", filters={"kind":"component","name":"space","namespace":"default"}, types=techdocs, pageCursor= type=plugin
[1] 2022-05-13T15:34:01.190Z backstage info ::1 - - [13/May/2022:15:34:01 +0000] "GET /api/search/query?term=&filters%5Bkind%5D=component&filters%5Bname%5D=space&filters%5Bnamespace%5D=default&pageCursor=&types%5B0%5D=techdocs HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
[1] 2022-05-13T15:34:01.191Z search info Search request received: term="", filters={"kind":"component","name":"space","namespace":"default"}, types=techdocs, pageCursor= type=plugin
[1] 2022-05-13T15:34:01.195Z backstage info ::1 - - [13/May/2022:15:34:01 +0000] "GET /api/search/query?term=&filters%5Bkind%5D=component&filters%5Bname%5D=space&filters%5Bnamespace%5D=default&pageCursor=&types%5B0%5D=techdocs HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" type=incomingRequest
[1] 2022-05-13T15:34:02.643Z techdocs error Failed to build the docs page: unexpected end of file unexpected end of file type=plugin errno=-5 code=Z_BUF_ERROR stack=Error: unexpected end of file
[1]     at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
```

## Steps to Reproduce

1. Run `npx @backstage/create-app` 
2. Add an azure repo with techdocs to the app-config.yaml
3. Start backstage with `yarn dev`

## Context
We have upgrade backstage to the latest version and this problem seems to be happening only with this new version. Strange is, I have one component in azure with mkdocs that works without problem but the other gives always this error. 

I'm getting the same error when deployed to kubernetes with the newest mkdocs-techdocs-core==1.0.2.

The mkdocs generation works when I point to the local directory. Also with `npx @techdocs/cli serve:mkdocs` and `mkdocs serve` it works fine.

I'm not sure how I can debug it further... Any help would be awesome! 

## Your Environment

- Browser Information: Microsoft Edge Version 101.0.1210.39 (Official build) (arm64)

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.4.0 - darwin/arm64
node: v16.15.0
yarn: 1.22.17
cli:  0.17.0 (installed)

Dependencies:
  @backstage/app-defaults               1.0.1
  @backstage/backend-common             0.13.2
  @backstage/backend-tasks              0.3.0
  @backstage/catalog-client             1.0.1
  @backstage/catalog-model              1.0.1
  @backstage/cli-common                 0.1.8
  @backstage/cli                        0.17.0
  @backstage/config-loader              1.1.0
  @backstage/config                     1.0.0
  @backstage/core-app-api               1.0.1
  @backstage/core-components            0.9.3
  @backstage/core-plugin-api            1.0.1
  @backstage/errors                     1.0.0
  @backstage/integration-react          1.0.1
  @backstage/integration                1.1.0
  @backstage/plugin-api-docs            0.8.4
  @backstage/plugin-app-backend         0.3.31
  @backstage/plugin-auth-backend        0.13.0
  @backstage/plugin-auth-node           0.2.0
  @backstage/plugin-catalog-backend     1.1.1
  @backstage/plugin-catalog-common      1.0.1
  @backstage/plugin-catalog-graph       0.2.16
  @backstage/plugin-catalog-import      0.8.7
  @backstage/plugin-catalog-react       1.0.1
  @backstage/plugin-catalog             1.1.0
  @backstage/plugin-github-actions      0.5.4
  @backstage/plugin-org                 0.5.4
  @backstage/plugin-permission-common   0.6.0
  @backstage/plugin-permission-node     0.6.0
  @backstage/plugin-permission-react    0.4.0
  @backstage/plugin-proxy-backend       0.2.25
  @backstage/plugin-scaffolder-backend  1.1.0
  @backstage/plugin-scaffolder-common   1.0.1
  @backstage/plugin-scaffolder          1.1.0
  @backstage/plugin-search-backend-node 0.6.0
  @backstage/plugin-search-backend      0.5.1
  @backstage/plugin-search-common       0.3.3
  @backstage/plugin-search-react        0.1.0
  @backstage/plugin-search              0.8.0
  @backstage/plugin-tech-radar          0.5.11
  @backstage/plugin-techdocs-backend    1.1.0
  @backstage/plugin-techdocs-node       1.1.0
  @backstage/plugin-techdocs-react      0.1.0
  @backstage/plugin-techdocs            1.1.0
  @backstage/plugin-user-settings       0.4.3
  @backstage/release-manifests          0.0.2
  @backstage/search-common              0.3.3
  @backstage/test-utils                 1.0.1
  @backstage/theme                      0.2.15
  @backstage/types                      1.0.0
  @backstage/version-bridge             1.0.1

```

**Comment by garyniemen** [comment] 2022-05-16 11:53
@nadworny We in [@backstage/techdocs-core](https://github.com/orgs/backstage/teams/techdocs-core) do not use Azure internally - but we will discuss and get back here.

**Comment by nadworny** [comment] 2022-05-16 11:56
@garyniemen I noticed it last year when I committed a bugfix for Azure 😄 

Nevertheless, some guidance on how to debug it would be great...

**Comment by ottosichert** [comment] 2022-06-07 12:58
Hey @nadworny, we've looked into the issue and we're able to reproduce it locally.

The issue is that the `AzureUrlReader` works by zipping and unzipping the response, which breaks in the case of a nested zip situation. Starting below:

https://github.com/backstage/backstage/blob/d76cabf329e33fa463a00f96c44d02e203f7c4c8/packages/backend-common/src/reading/AzureUrlReader.ts#L133

Fix coming up soon!

**Comment by awanlin** [comment] 2022-06-07 13:57
@ottosichert whatever you do with this can you let me know? As @nadworny can confirm, Azure DevOps Services (Cloud) and Azure DevOps Server (Self hosted on premise) seem to behave a little differently around this functionality. I'm happy to test any fix on our Azure DevOps Server instance

**Comment by ottosichert** [comment] 2022-06-16 13:25
We've had a deeper look into this issue and it turns out there are multiple problems involved in this.

1. Some ZIP archives provided by Azure DevOps Services (Cloud or self hosted) seem to be incompatible with NodeJS `zlib` inflater. This behaviour occurs once there is a nested ZIP file present
2. When trying to unzip this archive, TechDocs throws (which is to be expected)
3. Other corrupt archives hang the read stream indefinitely

**About 1)**
It seems to be a known issue (https://github.com/ZJONSSON/node-unzipper/issues/213) that certain ZIP files seem to throw when using `node-unzipper` (which in turn uses NodeJS' `zlib` implementation).

What is unclear however is what the difference in archives provided by Azure DevOps Services is. Maybe @nadworny would it be possible to provide a ZIP file without sensitive content that shows the same behaviour?

**About 2)**
Since the actual error was propagated all the way up to the logs, and indeed the backend is unable to unzip this archive, this behaviour shouldn't really be changed from our point of view. Let us know if you have a suggestion what could be done different here.

**About 3)**
We've pushed a change fixing this issue here: https://github.com/backstage/backstage/pull/12090

**Comment by nadworny** [comment] 2022-06-16 14:11
@ottosichert you can try with this https://github.com/nadworny/backstage-zip-test. Or do you actually need a zip that you'd get from Azure for such a repo?

**Comment by ottosichert** [comment] 2022-06-22 09:28
@nadworny thanks for setting up this test case in a repository!

We've worked in a similar way in this PR https://github.com/backstage/backstage/pull/12090 so that we already create an archive that contains a corrupted ZIP file itself (`mock-corrupted.zip`).

(Some additional info: turns out that Node 14 and 16 behave differently, as the file from https://github.com/ZJONSSON/node-unzipper/issues/213 hangs on 16 but unzips perfectly fine on 14)

I think to further continue this investigation an actual file from Azure would be needed to fully recreate this scenario.

I've added the label `help-wanted` as we're primarily focusing on fixing the core functionality, which is addressed in the PR above. We're happy to review any contribution around this!

**Comment by nadworny** [comment] 2022-06-22 18:31
@ottosichert what do you mean by that?
`I think to further continue this investigation an actual file from Azure would be needed to fully recreate this scenario.`

Shall I create the same repo in Azure and provide a zip which I download from there?

**Comment by ottosichert** [comment] 2022-07-25 14:58
Closing this issue as @benjaminr has changed the underlying library in https://github.com/backstage/backstage/pull/12090 which eliminates this problem! 🎉

@nadworny if you still encounter this issue, please feel free to re-open this issue so we can troubleshoot 🙏

**Closed by ottosichert** 2022-07-25 14:58 UTC
Labels: bug, help wanted, docs-like-code
