### ISSUE TITLE
🐛 Bug Report: Searching for 'EntityPage' in docs yields nothing

### ISSUE THREAD

**Issue by joshjung** [backstage/backstage#27143] opened 2024-10-15 13:57 UTC
### 📜 Description

When looking for information on how to use the provided `EntityPage` the documentation search shows no useful results:

![Screenshot 2024-10-15 at 08 55 44](https://github.com/user-attachments/assets/7eb6511a-98c3-436a-b488-2a0f9e98e280)

### 👍 Expected behavior

A core feature like `EntityPage` should at least have something describing how it is intended to be used in the documentation.

### 👎 Actual Behavior with Screenshots

See above

### 👟 Reproduction steps

See the screenshot above

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment] 2024-10-17 08:45
Gonna close this one as a duplicate of #26985, let's focus the discussion there

**Closed by Rugvip** 2024-10-17 08:45 UTC
Labels: bug, microsite
