### ISSUE TITLE
🐛 Bug Report:  useLocation() may be used only in the context of a <Router> component when adding plugin using yarn add

### ISSUE THREAD

**Issue by ch-enfuse** [backstage/backstage#15315] opened 2022-12-20 00:59 UTC
### 📜 Description

Hi,

We built a [plugin](https://github.com/enfuse/asae-backstage-plugin) for Azure Spring Apps that is publicly available to use for anyone. We have seen an issue come up where adding the plugin using **yarn add --cwd packages/app @enfuse/plugin-azure-spring-apps** and consequently using the plugin breaks the application. 
When we manually add the dependency to the package.json and run 'yarn install" this does not come up.

We were wondering if you can shed some light to why this might be happening. Error picture is left below. thank you 

### 👍 Expected behavior

After installation and setup, the plugin components should be able to display in catalog page

### 👎 Actual Behavior with Screenshots

Application breaks with the following error
<img width="1435" alt="Screen Shot 2022-12-19 at 4 51 51 PM" src="https://user-images.githubusercontent.com/107439111/208556611-6c405693-fa6d-4a8f-83a1-ba27b4881f29.png">

### 👟 Reproduction steps

run **yarn add --cwd packages/app @enfuse/plugin-azure-spring-apps** breaks the application. 
Follow steps in [README](https://github.com/enfuse/asae-backstage-plugin) to create a system component and display component in catalog.

### 🖥️ Your Environment

OS:   Darwin 20.6.0 - darwin/arm64
node: v16.18.1
yarn: 1.22.19
cli:  0.19.0 (installed)
backstage:  1.6.0

Dependencies:
  @backstage/app-defaults                          1.0.6
  @backstage/backend-common                        0.15.2, 0.15.1
  @backstage/backend-plugin-api                    0.1.2
  @backstage/backend-tasks                         0.3.5
  @backstage/catalog-client                        1.1.0, 1.1.1
  @backstage/catalog-model                         1.1.1, 1.1.2
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.19.0
  @backstage/config-loader                         1.1.4, 1.1.5
  @backstage/config                                1.0.3, 1.0.2
  @backstage/core-app-api                          1.1.0
  @backstage/core-components                       0.11.1, 0.11.2
  @backstage/core-plugin-api                       1.0.6, 1.0.7
  @backstage/errors                                1.1.1, 1.1.2
  @backstage/integration-react                     1.1.4
  @backstage/integration                           1.3.1, 1.3.2
  @backstage/plugin-api-docs                       0.8.9
  @backstage/plugin-app-backend                    0.3.36
  @backstage/plugin-auth-backend                   0.16.0
  @backstage/plugin-auth-node                      0.2.5
  @backstage/plugin-azure-devops-backend           0.3.15
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.0
  @backstage/plugin-catalog-backend                1.4.0
  @backstage/plugin-catalog-common                 1.0.6, 1.0.7
  @backstage/plugin-catalog-graph                  0.2.21
  @backstage/plugin-catalog-import                 0.8.12
  @backstage/plugin-catalog-node                   1.1.0
  @backstage/plugin-catalog-react                  1.1.4, 1.2.0
  @backstage/plugin-catalog                        1.5.1
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-org                            0.5.9
  @backstage/plugin-permission-common              0.6.4, 0.7.0
  @backstage/plugin-permission-node                0.6.5
  @backstage/plugin-permission-react               0.4.5, 0.4.6
  @backstage/plugin-proxy-backend                  0.2.30
  @backstage/plugin-scaffolder-backend             1.6.0
  @backstage/plugin-scaffolder-common              1.2.0
  @backstage/plugin-scaffolder                     1.6.0
  @backstage/plugin-search-backend-module-pg       0.4.0
  @backstage/plugin-search-backend-node            1.0.2
  @backstage/plugin-search-backend                 1.0.2
  @backstage/plugin-search-common                  1.0.1, 1.1.0
  @backstage/plugin-search-react                   1.1.0
  @backstage/plugin-search                         1.0.2
  @backstage/plugin-tech-radar                     0.5.16
  @backstage/plugin-techdocs-backend               1.3.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.4
  @backstage/plugin-techdocs-node                  1.4.0
  @backstage/plugin-techdocs-react                 1.0.4
  @backstage/plugin-techdocs                       1.3.2
  @backstage/plugin-user-settings                  0.4.8
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.0
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment] 2022-12-22 09:19
This is likely due to the direct `react-router-dom` dependency in the plugin, I've reported it over at https://github.com/enfuse/asae-backstage-plugin/issues/9

**Comment by drodil** [comment] 2022-12-23 06:15
Found out this too with backstage v1.7.1. Updating to 1.9.0 seems to fix the issue but @Rugvip has good point that should be taken care of by the plugin developers.

**Comment by Rugvip** [comment] 2022-12-29 11:39
Closing this since the issue is likely not in this repo.

**Closed by Rugvip** 2022-12-29 11:39 UTC
Labels: bug
