### ISSUE TITLE
🐛 Bug Report: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists

### ISSUE THREAD

**Issue by soaand01** [backstage/backstage#15299] opened 2022-12-19 12:19 UTC
### 📜 Description

I am trying to deploy backstage in Kubernetes by follow the steps here: https://backstage.io/docs/deployment/k8s but I get the following issue:

```
{"level":"info","message":"Loaded config from app-config.yaml, app-config.production.yaml","service":"backstage"}
{"level":"info","message":"1 secret found in the config which will be redacted","service":"backstage"}
{"level":"info","message":"Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=true},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{}","service":"backstage"}
Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN.
    at /app/node_modules/@backstage/backend-common/dist/index.cjs.js:1017:17
    at async CatalogBuilder.build (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:4084:22)
    at async createPlugin$4 (/app/packages/backend/dist/index.cjs.js:62:40)
    at async main (/app/packages/backend/dist/index.cjs.js:206:29)
```

the psql database are up and running.
I have 2 secrets created:

backstage secret with 1 secret called github_token
potgress secret with 2 secrets called postgres_password and postgres_user.

### 👍 Expected behavior

Be able to deploy backstage.

### 👎 Actual Behavior with Screenshots

N/A

### 👟 Reproduction steps

```
# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: registry.digitalocean.com/soaand01/backstagedev:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
# Uncomment if health checks are enabled in your app:
# https://backstage.io/docs/plugins/observability#health-checks
#          readinessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
#          livenessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
```

kubectl apply -f kubernetes/backstage.yaml

### 🖥️ Your Environment

```
yarn backstage-cli info
yarn run v1.22.19
$ /Users/anderson/labs/test/backstage-new/node_modules/.bin/backstage-cli info
OS:   Darwin 21.6.0 - darwin/x64
node: v18.12.1
yarn: 1.22.19
cli:  0.21.1 (installed)
backstage:  1.8.0

Dependencies:
  @backstage/app-defaults                          1.0.8
  @backstage/backend-common                        0.16.0
  @backstage/backend-plugin-api                    0.1.4
  @backstage/backend-tasks                         0.3.7
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.21.1
  @backstage/config-loader                         1.1.6
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.2.0
  @backstage/core-components                       0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/errors                                1.1.3
  @backstage/integration-react                     1.1.6
  @backstage/integration                           1.4.0
  @backstage/plugin-api-docs                       0.8.11
  @backstage/plugin-app-backend                    0.3.38
  @backstage/plugin-auth-backend                   0.17.1
  @backstage/plugin-auth-node                      0.2.7
  @backstage/plugin-catalog-backend                1.5.1
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.23
  @backstage/plugin-catalog-import                 0.9.1
  @backstage/plugin-catalog-node                   1.2.1
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.6.1
  @backstage/plugin-github-actions                 0.5.11
  @backstage/plugin-org                            0.6.1
  @backstage/plugin-permission-common              0.7.1
  @backstage/plugin-permission-node                0.7.1
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.32
  @backstage/plugin-scaffolder-backend             1.8.0
  @backstage/plugin-scaffolder-common              1.2.2
  @backstage/plugin-scaffolder                     1.8.0
  @backstage/plugin-search-backend-module-pg       0.4.2
  @backstage/plugin-search-backend-node            1.0.4
  @backstage/plugin-search-backend                 1.1.1
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.2.1
  @backstage/plugin-search                         1.0.4
  @backstage/plugin-tech-radar                     0.5.18
  @backstage/plugin-techdocs-backend               1.4.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.6
  @backstage/plugin-techdocs-node                  1.4.2
  @backstage/plugin-techdocs-react                 1.0.6
  @backstage/plugin-techdocs                       1.4.0
  @backstage/plugin-user-settings                  0.5.1
  @backstage/release-manifests                     0.0.7
  @backstage/test-utils                            1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2
✨  Done in 3.77s.

```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by soaand01** [comment] 2022-12-19 12:21
I updated my issue with my correct container registry name

**Comment by freben** [comment] 2022-12-20 10:42
This sounds like your `backend.database` config section may be out of sorts, or containing references to env variables that aren't set for the deployment.

**Comment by soaand01** [comment] 2022-12-22 16:47
It's weird because still doesnt work even updating the backend.database properties.

**Comment by buggtb** [comment] 2023-01-20 02:18
This took me a while to work out, the Postgres variables defined in the production file, don't match the kubnetes injected variables, so double check you've got POSTGRES_SERVICE_HOST and POSTGRES_SERVICE_PORT set, not the defaults.

**Comment by jschirad** [comment] 2023-02-14 18:05
That it, the problem came to the app.config.production yaml. I replace the app.config.production.yaml with the app.config.yaml- just to run localy

**Comment by benjdlambert** [comment] 2023-02-16 09:51
same as previous one. this is close the other?

**Comment by benjdlambert** [comment] 2023-02-16 09:52
Closing this as it looks like a duplicate issue, want to keep the conversation in one place.

**Comment by benjdlambert** [comment] 2023-02-16 09:54
Hey @soaand01, what does you app-config.yaml look like?

**Comment by sharadpattanshetti** [comment] 2023-02-23 07:46
We recently bumped our backstage instance to 1.10 version and also implemented permission policy(added backend_secret to Helm charts) and since then we facing below error in our environments: 

stderr F Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, Error: Connection terminated unexpectedly

**Comment by benjdlambert** [comment] 2023-02-27 10:52
@sharadpattanshetti what does the rendered app-config.yaml look like in the running pods?

**Comment by Kaliszby** [comment] 2023-02-28 05:05
You can close this issue.

.env :
```
POSTGRES_HOST=localhost #or export POSTGRES_HOST=localhost
```

readmore : https://github.com/sequelize/sequelize/issues/11014#issuecomment-1273603909

**Comment by freben** [comment] 2023-02-28 06:52
Ok!

**Closed by freben** 2023-02-28 06:52 UTC
Labels: bug, catalog

**Comment by soaand01** [comment] 2023-02-28 07:56
@benjdlambert I will retry and  share with you.

**Comment by Alok650** [comment] 2023-06-28 13:05
developer-portal-backstage-1  | Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, error: password authentication failed for user "postgres"

getting this error when running the backstage image through docker-compose. the steps followed are of https://github.com/Rugvip/backstage-prod-diff/blob/master/DIFF.md

the error is coming from backstage container. How do we resolve this?

**Comment by benjdlambert** [comment] 2023-06-29 09:59
Hmm. I'd recommend not following that repo as that could be pretty outdated by now. It looks like the password of the postgres user is not the same in the `docker-compose.yaml` as what it is in the `app-config.yaml` Try a hardcoded value instead. `error: password authentication failed for user "postgres"`

**Comment by Umoren** [comment] 2023-07-01 20:41
@Alok650 have you found a fix? i'm stuck with this problem.

**Comment by milind12** [comment] 2023-09-20 06:51
I was facing `error: password authentication failed for user "` in local Kubernetes, if we follow the steps from https://backstage.io/docs/deployment/k8s, then this scenario could be reproduced by doing deployments more than one time and changing the POSTGRES_USER and POSTGRES_PASSWORD in the subsequent deployment without clearing /mnt/data manually from the node. 

In the subsequent deployment if the POSTGRES_USER and POSTGRES_PASSWORD change, then we are able to connect to the Postgres pod using the new  POSTGRES_USER and POSTGRES_PASSWORD, however, the backstage pod throws an error: password authentication failed for user ". I was able to overcome this by clearing  /mnt/data manually from the node and so backstage ran init and migration scripts and backstage pod was able to use new credentials as well. As I was just playing around for learning purposes, it was fine to clear /mnt/data manually from the node
@benjdlambert any suggestion on what is the right way to change db credentials and provide the right privileges to a new user? Or do we have to do this manually to grant the new user the required permissions?
