### ISSUE TITLE
Backstage icons are not replaced by the ones provided in options when creating the app

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#8244] opened 2021-11-25 13:50 UTC
According to this comment here https://github.com/backstage/backstage/issues/7443#issuecomment-938115930 we should be able to override the app icons. This is not happening.

## Expected Behavior

The icons should be overridden

## Current Behavior

The icons are not overridden

## Steps to Reproduce

Include `icons` object in the `createApp` options like this, for example:

```js
import BusinessIcon from '@material-ui/icons/Business';
import VoicemailIcon from '@material-ui/icons/Voicemail';

createApp({
  ...
  icons: {
    business: BusinessIcon,
    email: VoicemailIcon // this one here is not working
  }
  ...
})
```

The business icon works fine because it is a non-existing one, a new one from the backstage perspective. However, the email icon already exists and the backstage is not picking up the newly assigned icon.

I've tried to override a couple of the available keys from here https://github.com/backstage/backstage/blob/f00e7ababefa8abd4095a7c712583898dcbd864c/packages/core-app-api/src/app/icons.tsx#L57 but no luck

## Context
I'm trying to customize the app icons, therefore, overriding some of the existing ones should be possible

## Your Environment
- NodeJS Version (v14): v14.17.5
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10
- Browser Information: Chrome

**Comment by Rugvip** [comment] 2021-11-26 13:54
I'm not able to reproduce this, or rather I'm able to override icons. For example, given this config in `createApp`

![image](https://user-images.githubusercontent.com/4984472/143590529-fb1e41ed-05c3-4527-a2c4-394be0c4e0b4.png)

It ends up properly overriding the GitHub icon in the support dropdown

![image](https://user-images.githubusercontent.com/4984472/143590693-b4c28750-c6a2-432c-a537-422aab0877fc.png)

I think the issue here might be that some of the icons you are trying to override might be hardcoded in the plugins? The icon overrides only work for icons that are fetched using `useApp().getSystemIcon(...)`

**Comment by ProticM** [comment] 2021-11-26 20:56
Yes, it seems you are right. When I try to override `github` icon, like in your example, then it works. I've tried to override `email` and `kind:api` and those did not work.

Well, overriding some of the icons would cause design mismatch which is not that good. We have our own set of icons and it would be a good thing for us to be able to replace all of the existing ones.

Is there a plan to change this approach with hardcoded icons?

**Comment by Rugvip** [comment] 2021-11-29 22:41
In many cases I don't think the hardcoded icons are intentional and could rather be considered bugs. We'd really want to move over to more usage of the built-in icon components from https://github.com/backstage/backstage/blob/4d61dc97c6507529867ca14afabc697ba10b8c92/packages/core-components/src/icons/icons.tsx#L31-L73 and would always be happy to accept contributions that replace existing hardcoded icons with usage of equivalent app icons. Adding new icons is a bit more tricky but we're open to suggestions there too.

**Comment by ProticM** [comment] 2021-12-01 17:03
Ok, so it seems that we cannot do much until the inner icons are switched/used from that location

**Comment by jhaals** [comment] 2021-12-03 07:31
I'm going to close this issue specifically as we've figured out that those are currently hardcoded. Feel free to raise a specific issue about replacing the hardcoded icons or we are happy to accept PRs that addresses this.

Thanks!

**Closed by jhaals** 2021-12-03 07:31 UTC
Labels: bug
