### ISSUE TITLE
Publishing private plugins to an internal artifactory

### ISSUE THREAD

**Issue by GiladFeder** [backstage/backstage#13969] opened 2022-10-03 12:15 UTC
## Summary

Hello,
We are interested in creating internal plugins which we do not wish to share with the outside world, hence needing to privately hosting it. We use JFrog Artifactory.
Is there any way nowadays to privately publishing plugins?

Thank you
Gilad

**Comment by OrkoHunter** [comment] 2022-10-28 05:57
@GiladFeder I'm closing the issue. Feel free to re-open if the problem is not solved for you.

**Closed by OrkoHunter** 2022-10-28 05:57 UTC
Labels: question, plugin
