### ISSUE TITLE
TechDocs API Discovery Returns Incorrect Base URL

### ISSUE THREAD

**Issue by egnwd** [backstage/backstage#4665] opened 2021-02-23 17:55 UTC
## Expected Behavior

When I have my site hosted somewhere such as `https://backstage.example.com` (and have `app`/`backend` `baseUrl` config set as such) the TechDocs API discovery should use `https://backstage.example.com` as the base URL not `https://localhost:7000`. 

## Current Behavior

When I load some TechDocs in my production environment I get a 404 mic drop page. (see screenshot).
In the network tab in Chrome I also see (expand for _some_ useful stack trace):

<details>
  <summary><code>GET https://localhost:7000/api/techdocs/static/docs/default/Component/name/index.html net::ERR_SSL_PROTOCOL_ERROR</code></summary>
  
```
getEntityDocs @ index.esm.js:63
async function (async) 
getEntityDocs @ index.esm.js:61
// ... more (anonymous minified javascript)
```
</details>

So it appears to be the call from [`getEntityDocs`](https://github.com/backstage/backstage/blob/59b1b04f0bd10a77671123679245414d3ae16a0c/plugins/techdocs/src/api.ts#L150)

![Skärmavbild 2021-02-23 kl  17 21 33](https://user-images.githubusercontent.com/2790386/108884257-497cf100-75fe-11eb-9605-9a9cf3d212fd.png)

## Possible Solution

Not sure...

## Steps to Reproduce

1. Set `app.baseUrl` to `https://backstage.example.com`
2. Set `backend.baseUrl` to `https://backstage.example.com`
3. Deploy app to that domain
4. Load docs page
5. 💥 

(Locally my docs seem to work fine, but they are hosted at `localhost:7000`)

## Context

- In the production setup I'm use `awsS3` as a backend, but hitting `https://backstage.example.com/api/techdocs/static/docs/default/Component/name/index.html` returns the correct page. Therefore it doesn't seem to be related to the publisher.
- **Workaround**: [Adding the legacy](https://backstage.io/docs/features/techdocs/configuration) `techdocs.requestUrl` and `techdocs.storageUrl` to app-config.yaml fixes the issue (thanks @OrkoHunter)
- [Link to the start of the Discord #support thread](https://discord.com/channels/687207715902193673/687235481154617364/813813113555648512)

Techdocs versions I'm using:
```
├─ @backstage/plugin-techdocs-backend@0.6.2
│  ├─ @backstage/techdocs-common@^0.4.2
├─ @backstage/plugin-techdocs@0.5.8
│  ├─ @backstage/techdocs-common@^0.4.2
├─ @backstage/techdocs-common@0.4.2
│  ├─ @backstage/techdocs-common@^0.3.4
│  ├─ @backstage/techdocs-common@0.3.7
│  ├─ @backstage/plugin-techdocs@^0.5.5
│  ├─ @backstage/techdocs-common@^0.4.1
│  ├─ @backstage/plugin-techdocs-backend@^0.6.0
```
## Your Environment

- Docker Image Running backend: `node:14-buster-slim`
- Browser Information: Chrome and Safari on macOS BigSur

**Comment by OrkoHunter** [comment] 2021-02-24 07:02
This can be investigated by removing `techdocs.requestUrl` and `techdocs.storageUrl` from [backstage/demo](https://github.com/backstage/demo/blob/bb77f3bb830cde67eb3c15c0589f5e5a0d43ec6c/app-config.heroku.yaml#L13-L15) deployment.

Another case of this bug - https://discord.com/channels/687207715902193673/714754240933003266/811601986238545925

**Comment by iamEAP** [comment] 2021-07-08 09:16
Hey @egnwd!  @camilaibs @soapraj and I were looking into this today and don't appear to be able to reproduce using the latest TechDocs plugin.  Is this still an issue for you without the `techdocs.requestUrl` / `techdocs.storageUrl` configs?

**Comment by egnwd** [comment] 2021-07-09 23:59
Hi @iamEAP, sorry just seen this, I'll test on Monday when I can get a deploy out to our remote env.

**Comment by petejespersqbe** [comment] 2021-07-23 14:42
Hi. I've been setting up TechDocs recently and encountered something similar.

I was running on `release-2021-06-03` and adding the legacy `techdocs.requestUrl` and `techdocs.storageUrl` to app-config.yaml didn't fix it (after finding the cause I now understand why). I upgraded to `release-2021-07-16` and still had the same issue.

For me the issue began with the entity metadata lookup:
`https://mydomain.com:7000/api/techdocs/metadata/entity/default/Component/documented-component-github`

```
{
  "error": {
    "name": "NotFoundError",
    "message": "Unable to get metadata for 'component:default/documented-component-github'; caused by FetchError: request to https://localhost:7000/api/catalog/entities/by-name/Component/default/documented-component-github failed, reason: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:mydomain.com",
    "cause": {
      "message": "request to https://localhost:7000/api/catalog/entities/by-name/Component/default/documented-component-github failed, reason: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:mydomain.com",
      "type": "system",
      "errno": "ERR_TLS_CERT_ALTNAME_INVALID",
      "code": "ERR_TLS_CERT_ALTNAME_INVALID",
      "name": "FetchError",
      "stack": "FetchError: request to https://localhost:7000/api/catalog/entities/by-name/Component/default/documented-component-github failed, reason: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:mydomain.com\n    at ClientRequest.<anonymous> (E:\\Deployment\\Sites\\Techdocs-v3-01\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:315:20)\n    at ClientRequest.EventEmitter.emit (domain.js:467:12)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket.EventEmitter.emit (domain.js:467:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
    }
  },
  "request": {
    "method": "GET",
    "url": "/api/techdocs/metadata/entity/default/Component/documented-component-github"
  },
  "response": { "statusCode": 404 }
}
```

The `techdocs-backend` router uses `discovery.getBaseUrl('catalog')` to then call the `/api/catalog/entities/by-name/` endpoint.

It took me longer than it should have to figure out that there's a distinction between internal and external urls in `SingleHostDiscovery`, with `getBaseUrl` returning a localhost address.

```
> SingleHostDiscovery.ts

async getBaseUrl(pluginId: string): Promise<string> {
  return `${this.internalBaseUrl}/${pluginId}`;
}

async getExternalBaseUrl(pluginId: string): Promise<string> {
  return `${this.externalBaseUrl}/${pluginId}`;
}
```

We're hosting the site on a Windows server using [PM2](https://pm2.keymetrics.io/). It works well in general but means that the localhost call on the server with a TLS certificate throws the above error.

In order to "fix" this for us I've used [patch-package](https://www.npmjs.com/package/patch-package) to have `getBaseUrl` return the external url which uses the `backend.baseUrl` config.

```
> node_modules/@backstage/backend-common/dist/index.cjs.js

async getBaseUrl(pluginId) {
	/*
	* Patch Start
	*
	* Fixes issue with trying to access localhost on server using https certificate
	*/
	// return `${this.internalBaseUrl}/${pluginId}`;
	return this.getExternalBaseUrl(pluginId);
	/*
	* Patch End
	*/
}
async getExternalBaseUrl(pluginId) {
	return `${this.externalBaseUrl}/${pluginId}`;
}
```

This is working well and hasn't caused any issues with the (limited) set of features/plugins that we're using so far.

Hope this helps someone.

And can I just take a moment to say thank you to the maintainers and everyone else involved in creating this great product. I'm loving working with it!

**Comment by egnwd** [comment] 2021-07-28 11:10
@iamEAP Hi, sorry again for the delay, I've tested this without this config and it seems to still work for me. Would you like me to close the issue or leave it open given the comment above from @petejespersqbe?

**Comment by iamEAP** [comment] 2021-08-09 16:54
Thanks for the detailed run-down, @petejespersqbe.  This sounds like perhaps an edge-case of how the discovery API works with respect to different SSL termination strategies.  It might deserve an issue of its own, given it would affect any in-process backend-to-backend communication within Backstage.  Would you mind opening a separate issue?

For this issue, thanks for getting back @egnwd!  I'll go ahead and close it out.

**Closed by iamEAP** 2021-08-09 16:54 UTC
Labels: bug, help wanted, docs-like-code
