### ISSUE TITLE
🐛 Bug Report: Config value: 'plugins'. Error: The "techdocs-core" plugin is not installed

### ISSUE THREAD

**Issue by Umoren** [backstage/backstage#18595] opened 2023-07-05 17:36 UTC
### 📜 Description

I am trying to run techdocs using the basic setup. This is my `app-config.yaml` techdocs config
```yaml
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
```
My `mkdocs.yml` looks like this
```yml
site_name: 'nodejsapp'
site_description: 'This is a sample Nodejs service that exposes a User Api'
repo_url: https://github.com/officialsamtech/nodejs-app

nav:
  - Home: index.md
  - API Reference: api.md
  - User Guide: usage.md
```

When i run `mkdocs build`, the `/site` directory is generated:

```sh
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /Users/mac/Desktop/sammy23/dummy-apps/Nodejs-App/site 
```
However, in my backstage app, when i run `yarn dev` to start the app and navigate to docs, this is the error i get:
```sh
DEBUG   -  Loading configuration file: /private/var/folders/hq/dq6yvv_n1zbggb8jt_609_d00000gn/T/backstage-qSWXnr/mkdocs.yml[5](http://localhost:3000/catalog/default/component/NodejsApp/docs#line-
ERROR   -  Config value: 'plugins'. Error: The "techdocs-core" plugin is not installed
```
I have `mkdocs-techdocs-core` installed:
```sh
➜  ~ pip3 show mkdocs-techdocs-core
Name: mkdocs-techdocs-core
Version: 1.2.1
Summary: The core MkDocs plugin used by Backstage's TechDocs as a wrapper around multiple MkDocs plugins and Python Markdown extensions
Home-page: https://github.com/backstage/mkdocs-techdocs-core
Author: TechDocs Core
Author-email: pulp-fiction@spotify.com
License: Apache-2.0
Location: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
Requires: Markdown, markdown-inline-graphviz-extension, mdx-truly-sane-lists, mkdocs, mkdocs-material, mkdocs-monorepo-plugin, plantuml-markdown, pygments, pymdown-extensions
Required-by:
```

### 👍 Expected behavior

It should generate the docs. Something like this:

![image](https://github.com/backstage/backstage/assets/22575481/617dc7db-0839-473f-8a85-142f3ef97ae6)

### 👎 Actual Behavior with Screenshots

<img width="1440" alt="Screenshot 2023-07-05 at 18 35 23" src="https://github.com/backstage/backstage/assets/22575481/a3a3996d-e411-41ec-aca5-812f4d1f5f66">

### 👟 Reproduction steps

1. `npx @backstage/create-app`
2. Running backstage on PC (mac)
   `pip3 install mkdocs-techdocs-core `
3. `app-config.yaml `has:
  ```yaml
  techdocs:
    builder: 'local' 
    generator:
      runIn: 'local' 
    publisher:
      type: 'local'
   ```
4. Register a component with a `docs/index.md` and `mkdocs.yml` 

### 📃 Provide the context for the Bug.

I am trying to demo the techdocs feature and I'm stuck with this problem.

### 🖥️ Your Environment

```sh
Dependencies:
  @backstage/app-defaults                          1.4.0
  @backstage/backend-app-api                       0.4.4
  @backstage/backend-common                        0.19.0
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.3
  @backstage/backend-tasks                         0.5.3
  @backstage/catalog-client                        1.4.2
  @backstage/catalog-model                         1.4.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.1
  @backstage/cli                                   0.22.8
  @backstage/config-loader                         1.3.1
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.8.1
  @backstage/core-components                       0.13.2
  @backstage/core-plugin-api                       1.5.2
  @backstage/errors                                1.2.0
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.4
  @backstage/integration-react                     1.1.14
  @backstage/integration                           1.5.0
  @backstage/plugin-api-docs                       0.9.5
  @backstage/plugin-app-backend                    0.3.46
  @backstage/plugin-auth-backend                   0.18.4
  @backstage/plugin-auth-node                      0.2.15
  @backstage/plugin-catalog-backend                1.10.0
  @backstage/plugin-catalog-common                 1.0.14
  @backstage/plugin-catalog-graph                  0.2.31
  @backstage/plugin-catalog-import                 0.9.9
  @backstage/plugin-catalog-node                   1.3.7
  @backstage/plugin-catalog-react                  1.7.0
  @backstage/plugin-catalog                        1.11.2
  @backstage/plugin-events-node                    0.2.7
  @backstage/plugin-github-actions                 0.6.0
  @backstage/plugin-org                            0.6.9
  @backstage/plugin-permission-common              0.7.6
  @backstage/plugin-permission-node                0.7.9
  @backstage/plugin-permission-react               0.4.13
  @backstage/plugin-proxy-backend                  0.2.40
  @backstage/plugin-scaffolder-backend             1.15.0
  @backstage/plugin-scaffolder-common              1.3.1
  @backstage/plugin-scaffolder-node                0.1.4
  @backstage/plugin-scaffolder-react               1.5.0
  @backstage/plugin-scaffolder                     1.14.0
  @backstage/plugin-search-backend-module-catalog  0.1.2
  @backstage/plugin-search-backend-module-pg       0.5.7
  @backstage/plugin-search-backend-module-techdocs 0.1.2
  @backstage/plugin-search-backend-node            1.2.2
  @backstage/plugin-search-backend                 1.3.2
  @backstage/plugin-search-common                  1.2.4
  @backstage/plugin-search-react                   1.6.2
  @backstage/plugin-search                         1.3.2
  @backstage/plugin-tech-radar                     0.6.5
  @backstage/plugin-techdocs-backend               1.6.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.14
  @backstage/plugin-techdocs-node                  1.7.2
  @backstage/plugin-techdocs-react                 1.1.7
  @backstage/plugin-techdocs                       1.6.4
  @backstage/plugin-user-settings                  0.7.4
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.0
  @backstage/theme                                 0.4.0
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
  
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by grvpandey11** [comment] 2023-07-05 20:56
@Umoren Can you try to add below plugin to your mkdocs.yaml
```
plugins:
  - techdocs-core
```

So, your mkdocs.yaml will be 
```
site_name: 'nodejsapp'
site_description: 'This is a sample Nodejs service that exposes a User Api'
repo_url: https://github.com/officialsamtech/nodejs-app

nav:
  - Home: index.md
  - API Reference: api.md
  - User Guide: usage.md

plugins:
  - techdocs-core
```

**Comment by Umoren** [comment] 2023-07-06 09:43
Yeah, i had that config earlier but it didn't work either.

Also when i run `mkdocs serve` with the config, i get same error:
```sh
INFO    -  Building documentation... 
ERROR   -  Config value: 'plugins'. Error: The "techdocs-core" plugin is not installed 
```
I'm probably missing something here and i have no idea what

**Comment by johnphilip283** [comment] 2023-08-22 20:58
> Thanks @grvpandey11 Yeah, I had that config earlier, but it didn't work either.
> 
> Also when i run `mkdocs serve` with the config, i get same error:
> 
> ```shell
> INFO    -  Building documentation... 
> ERROR   -  Config value: 'plugins'. Error: The "techdocs-core" plugin is not installed 
> ```
> 
> I'm probably missing something here and i have no idea what

Hey there @Umoren! Even after following the reproduction steps, I'm still not able to reproduce the issue. Can you confirm that running `npx @backstage/create-app --version` prints out `1.17.0`?

**Comment by agentbellnorm** [comment] 2023-08-25 09:32
@Umoren This looks like an issue with the python environment (can you beleive it?! 😆), and not backstage. Especially since it's not working when running mkdocs directly.

Can you try to install it with `pip` instead of `pip3` and see if it makes a difference?

you can check what versions `pip` and `pip3` use:
```sh
pip --version
pip3 --version
```
if they are different that could be a part of the answer.

If that still doesn't work, I'd recommend to generate in docker:
```yaml
techdocs:
  builder: 'local' 
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'
```

I'll close this issue, but feel free to reopen if you think this is something we can fix in backstage

**Closed by agentbellnorm** 2023-08-25 09:32 UTC
Labels: bug, area:techdocs

**Comment by Umoren** [comment] 2023-08-25 11:06
> npx @backstage/create-app --version
Yes @johnphilip283 , version `1.17.0`.

But as @agentbellnorm has pointed, it is definitely my Python environment setup.
I'm really sorry I didn't close or update this issue earlier.
I instead used the recommended techdocs setup. I set my environment with AWS S3 and GitHub Actions. 
Thank you very much for taking the time to check this issue out.

If i were to make any suggestions for the docs, i'll say:
- A detailed tutorial on setting up techdocs whether with docker, local env or an external builder (i can even work on that if i figure out how to fix my python env)
- The recommended setup should come first in the docs and then the basic setup as a last resort (even for dev or prod environments).

Both of these suggestions work together. If there's a detailed tutorial, then there's no need for restructuring. 
Anyways i really enjoyed working through the docs because it's inclusive to developers of any level. More tutorials will improve the experience and reduce unnecessary issues like this.
