### ISSUE TITLE
🐛 Bug Report: @techdocs/cli version 1.8.12 fails to publish

### ISSUE THREAD

**Issue by smafre** [backstage/backstage#25317] opened 2024-06-19 10:45 UTC
### 📜 Description

When we do `techdocs-cli publish` with the latest version of @techdocs/cli (1.8.12) we get this error in our Azure DevOps pipeline:

> Cannot find module 'morgan'
> Require stack:
> - /opt/hostedtoolcache/node/18.20.3/x64/lib/node_modules/@techdocs/cli/node_modules/@backstage/backend-common/dist/index.cjs.js
> - /opt/hostedtoolcache/node/18.20.3/x64/lib/node_modules/@techdocs/cli/dist/cjs/publish-CnXRqKHz.cjs.js
> - /opt/hostedtoolcache/node/18.20.3/x64/lib/node_modules/@techdocs/cli/dist/index.cjs.js
> - /opt/hostedtoolcache/node/18.20.3/x64/lib/node_modules/@techdocs/cli/bin/techdocs-cli
> 
> ##[error]Bash exited with code '1'.

This started happening after version 1.8.12 was released. If we install the previous version with this command `npm install -g @techdocs/cli@1.8.11` it works like a charm to publish.

### 👍 Expected behavior

I think version 1.8.12 of @techdocs/cli should work like before. I can't see any changes in functionality in the changelog.

### 👎 Actual Behavior with Screenshots

The publish command failed with this error:
> Cannot find module 'morgan'
> Require stack:
> - /opt/hostedtoolcache/node/18.20.3/x64/lib/node_modules/@techdocs/cli/node_modules/@backstage/backend-common/dist/index.cjs.js
> - /opt/hostedtoolcache/node/18.20.3/x64/lib/node_modules/@techdocs/cli/dist/cjs/publish-CnXRqKHz.cjs.js
> - /opt/hostedtoolcache/node/18.20.3/x64/lib/node_modules/@techdocs/cli/dist/index.cjs.js
> - /opt/hostedtoolcache/node/18.20.3/x64/lib/node_modules/@techdocs/cli/bin/techdocs-cli
> 
> ##[error]Bash exited with code '1'.

### 👟 Reproduction steps

Try running this command with version 1.8.12 of @techdocs/cli (account information hidden):

> techdocs-cli publish  --entity $(entity) \
> --publisher-type azureBlobStorage \
> --azureAccountName $(AZURE_ACCOUNT_NAME) \
> --azureAccountKey $(AZURE_BLOB_STORAGEKEY) \
> --storage-name $(AZURE_BLOB_STORAGENAME)

If it fails, try running it again using version 1.8.11 and see if that works. If it does, this should mean a bug in 1.8.12?

### 📃 Provide the context for the Bug.

We build and publish docs in our Azure DevOps pipelines. This stopped working yesterday (18th of June 2024) after version 1.8.12 was released which we automatically started using since we install @techdocs/cli with this command, giving us the latest version: `npm install -g @techdocs/cli`

### 🖥️ Your Environment

Running in Azure DevOps pipeline using `vmImage: 'ubuntu-latest'`.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment] 2024-06-19 11:00
Closing as duplicate of https://github.com/backstage/backstage/issues/2530, patch should be out later today

**Closed** 2024-06-19 11:00 UTC
Labels: bug, area:techdocs

**Comment by davidg-idealo** [comment] 2024-06-20 07:54
I guess you linked the wrong issue. @freben
