### ISSUE TITLE
Code source links should be decoupled from the Location of the Component

### ISSUE THREAD

**Issue by backjo** [backstage/backstage#3559] opened 2020-12-04 01:49 UTC
When using a custom location, entities emitted from the custom location have the "View Source" link pointing to the target of the location, which is not the actual source code. 
## Expected Behavior
The Location of the entity and the link to the source code should not be coupled. I'd expect that some well-known annotation would be able to provide this information, and that the relevant processors (GitHub, GitLab etc) would then seed that annotation with the relevant information. 

## Current Behavior
The Location of the entity and the link to the source code are coupled. 

## Possible Solution
Add a new well-known annotation (or maybe a new field in spec, since this is agnostic of which source control system is being used?) that points to the source code location for a given Component. This data would then be seeded by the various processors 

## Steps to Reproduce
Write a simple custom processor that loads data from a custom target, and then try to view source code for the entities emitted. 
```ts
export class CustomProcessor implements CatalogProcessor {

    private logger: Logger
    constructor(logger: Logger) {
        this.logger = logger;
    }

    async readLocation(location: LocationSpec, _optional: boolean, emit: CatalogProcessorEmit): Promise<boolean> {
        if(location.type !== "my-processor") {
            return false
        }

        const response: any = await r2(location.target).response
        const services: any = await response.json()

        Object.keys(services).forEach((serviceId) => {
            const {github} = services[serviceId];
            const entity: ComponentEntityV1alpha1 = {
                apiVersion: "backstage.io/v1alpha1",
                kind: "Component",
                metadata: {
                    annotations: {
                        "github.com/project-slug": `${github.org}/${github.repo}`,
                    },
                    name: serviceId,
                    namespace: "default"
                },
                spec: {
                    type: "service",
                    lifecycle: "experimental",
                    owner: "user:unknown"
                }
            }
            emit({
                type: "entity",
                entity,
                location
            });
        })

        return true;
    }

}
```

**Comment by freben** [comment] 2020-12-04 14:56
Yep, this makes a lot of sense. Now that custom locations and processors are becoming more of a thing, this has reared its head.

It would probably be a new well-known annotation as you mention, next to the existing one.

```yaml
# Rough draft suggestion
metadata:
  annotations:
    backstage.io/managed-by-location: custom-dumps-source:latest
    backstage.io/source-location: url:https://ghe.mycompany.net/org/org-dumps/2020-12-04/org.yaml
```

and then these two would be the same, if it was sourced off of the latter one in the first place.

I may need to think about this some more, what the implications are. What if the source data is on S3? How do we think of what's a "browser friendly view or edit link" that corresponds to that `source-location`?

**Comment by backjo** [comment] 2020-12-04 18:10
It might also be worth considering the use case of  >1 source locations as well - for folks using GitOps, they often have second (or third) repositories to manage the deployment source.

**Comment by freben** [comment] 2020-12-04 18:36
Hm. There is likely to be a primary resource to point to though, I hope. For a backend service we wouldn't want to point to individual source files either :)

Joking aside, what I mean is that we'll have to think about what the purpose is of this annotation. The primary driver so far sounded like being able to render links/buttons in the frontend. I wonder how much related info we would want to encode like this. Maybe there should be a generic `metadata.links` concept that kind of works like in html where you can have `rel` classified links to elsewhere?

**Comment by backjo** [comment] 2020-12-04 18:40
Hehe

Yeah, that makes sense. Probably worthy of it's own issue for discussion, separate from this one :)

**Comment by andrewthauer** [comment] 2020-12-06 14:40
This could also apply even if the location is unique per entity as well. For instance, if you stored the catalog files somewhere from the source code or had an existing registry endpoint that was a unique per entity (rather then a bulk import).

I also ran into a similar case where defining the Component & API entities in a single catalog file means they are now coupled.  Unregistering one or the other causes both to be removed since they share the same location. At first I was slightly confused, but it does make sense after thinking about it. But this also means that they are coupled based on the location which may or may not be ideal in some cases.

**Comment by freben** [comment] 2020-12-08 09:29
@andrewthauer Right, so the right action would have been to remove the line from the Location entity in that case, instead of unregistering. Maybe that's something we could clarify in messaging in the frontend because it is obviously not entirely clear for those that are starting out with Backstage.

**Comment by andrewthauer** [comment] 2020-12-08 18:09
@freben - Yep, the behaviour makes sense, it's just not intuitive unless you understand the catalog model under the covers and how locations and entities are tied together.

**Comment by timbonicus** [comment] 2021-03-17 17:41
I believe this is resolved now by the well-known [source-location](https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageiosource-location) annotation. The `View Source` button has been updated to respect that.

**Comment by andrewthauer** [comment] 2021-03-17 18:16
I can confirm the view source does work when there are multiple entities in a single file or the `Location` type is used. I'm not sure if this is by design or not, but unregistering one does not unregister the batch even though the dialog prompt suggests it should. I'm not entirely sure what the behaviour should be when you have a tree of entities and locations. But this is probably a separate issue and/or clarification.

**Comment by freben** [comment] 2021-03-17 19:05
Thanks for confirming. Yeah thanks @timbonicuso let's close this

**Closed by freben** 2021-03-17 19:05 UTC
Labels: bug, catalog, enhancement
