### ISSUE TITLE
🔌 Plugin: Notification center

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#15765] opened 2023-01-16 10:47 UTC
### 🔖 Summary

Notification center could show notifications to users and redirect them to locations of interest within Backstage. Other plugins and the backstage app could utilize the notification API to send notifications to users. The notification system should automatically figure out the user entities based on relations (for example ownedBy and group hasMember) so that when sending a notification to any catalog component, it would be resolved to the user entities.

### ✌️ Context

This would be useful when there are changes to catalog items that require action from user or when for example scaffolder action is run.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment] 2023-01-16 13:06
Worth mentioning the Notifications RFC: https://github.com/backstage/backstage/issues/10652 as it would potentially impact how this gets built

**Comment by Rugvip** [comment] 2023-01-16 14:01
Yep will actually close this as a duplicate of #10652. I think it's definitely possible that #10652 gets built as a plugin, but there's a lot more discussion going on there already and would like to make sure to keep it focused.

**Closed by Rugvip** 2023-01-16 14:01 UTC
Labels: plugin
