### ISSUE TITLE
npx  @backstage/create-app - [Errno 2] No such file or directory: 'install'

### ISSUE THREAD

**Issue by Kris-B** [backstage/backstage#10837] opened 2022-04-14 10:01 UTC
## Expected Behavior

Install backstage

## Actual Behavior

```npx  @backstage/create-app``` breaks after selection of the database.

```
? Enter a name for the app [required] backstage-app
? Select database for the backend [required] SQLite

Creating the app...

 Checking if the directory is available:
  checking      backstage-app ✔

 Creating a temporary app directory:
  creating      temporary directory ✔

 Preparing files:
  copying       .dockerignore ✔
  copying       .eslintrc.js ✔
  templating    .gitignore.hbs ✔
  copying       .prettierignore ✔
  copying       README.md ✔
  copying       app-config.production.yaml ✔
  templating    app-config.yaml.hbs ✔
  templating    backstage.json.hbs ✔
  templating    catalog-info.yaml.hbs ✔
  copying       lerna.json ✔
  templating    package.json.hbs ✔
  copying       tsconfig.json ✔
  copying       .eslintrc.js ✔
  copying       Dockerfile ✔
  copying       README.md ✔
  templating    package.json.hbs ✔
  copying       index.test.ts ✔
  copying       index.ts ✔
  copying       types.ts ✔
  copying       app.ts ✔
  copying       auth.ts ✔
  copying       catalog.ts ✔
  copying       proxy.ts ✔
  copying       scaffolder.ts ✔
  templating    search.ts.hbs ✔
  copying       techdocs.ts ✔
  copying       .eslintrc.js ✔
  copying       cypress.json ✔
  templating    package.json.hbs ✔
  copying       android-chrome-192x192.png ✔
  copying       apple-touch-icon.png ✔
  copying       favicon-16x16.png ✔
  copying       favicon-32x32.png ✔
  copying       favicon.ico ✔
  copying       index.html ✔
  copying       manifest.json ✔
  copying       robots.txt ✔
  copying       safari-pinned-tab.svg ✔
  copying       .eslintrc.json ✔
  copying       app.js ✔
  copying       App.tsx ✔
  copying       apis.ts ✔
  copying       index.tsx ✔
  copying       setupTests.ts ✔
  copying       App.test.tsx ✔
  copying       LogoFull.tsx ✔
  copying       LogoIcon.tsx ✔
  copying       Root.tsx ✔
  copying       index.ts ✔
  copying       EntityPage.tsx ✔
  copying       SearchPage.tsx ✔

 Moving to final location:
  moving        backstage-app ✔

 Building the app:
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
  executing     yarn install ✖

Error: Could not execute command yarn install

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!

```

## Steps to Reproduce

execute ```npx @backstage/create-app```

## Context

trying to install Backstage

## Your Environment

Ubuntu on WSL2 Windows 11

**Comment by Kris-B** [comment] 2022-04-14 12:38
Finally, I could install after changing app's name from ```backstage-app``` to ```my-backstage-app```

**Comment by Rugvip** [comment] 2022-04-19 16:23
Dafuq, was it reliably failing with the apps name set to `backstage-app`, or does it seem like it was just flaky? I'd expect this to be some bug in the shell escaping when calling subprocesses under WSL or something like that 🤔

**Comment by lalit774** [comment] 2022-04-22 17:59
I tested new app using name backstage-app. I did not see any issue. Please see the followings screenshots.

![image](https://user-images.githubusercontent.com/225961/164769265-ddd18d24-109d-43fc-9426-957b63121560.png)

![image](https://user-images.githubusercontent.com/225961/164769304-d4738bde-8310-41eb-a999-affed84764c2.png)

**Comment by jhaals** [comment] 2022-04-25 08:23
Thanks for checking! Closing as we're not able to reproduce, please reopen if the issue persists.

**Closed by jhaals** 2022-04-25 08:23 UTC
Labels: bug

**Comment by sp0tt13** [comment] 2022-04-25 10:26
I have this issue still - tried both backstage-app and my-backstage-app names
Using wsl2 under win10: 
Linux xxx 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu", VERSION="20.04.4 LTS (Focal Fossa)"
Node: v16.14.2

$ npx @backstage/create-app
? Enter a name for the app [required] backstage-app
? Select database for the backend [required] SQLite

Creating the app...

 Checking if the directory is available:
  checking      backstage-app ✔

 Creating a temporary app directory:
  creating      temporary directory ✔

 Preparing files:
  copying       .dockerignore ✔
  templating    .eslintrc.js.hbs ✔
  templating    .gitignore.hbs ✔
  copying       .prettierignore ✔
  copying       README.md ✔
  copying       app-config.production.yaml ✔
  templating    app-config.yaml.hbs ✔
  templating    backstage.json.hbs ✔
  templating    catalog-info.yaml.hbs ✔
  copying       lerna.json ✔
  templating    package.json.hbs ✔
  copying       tsconfig.json ✔
  copying       README.md ✔
  copying       README.md ✔
  templating    .eslintrc.js.hbs ✔
  copying       Dockerfile ✔
  copying       README.md ✔
  templating    package.json.hbs ✔
  copying       index.test.ts ✔
  copying       index.ts ✔
  copying       types.ts ✔
  copying       app.ts ✔
  copying       auth.ts ✔
  copying       catalog.ts ✔
  copying       proxy.ts ✔
  copying       scaffolder.ts ✔
  templating    search.ts.hbs ✔
  copying       techdocs.ts ✔
  templating    .eslintrc.js.hbs ✔
  copying       cypress.json ✔
  templating    package.json.hbs ✔
  copying       android-chrome-192x192.png ✔
  copying       apple-touch-icon.png ✔
  copying       favicon-16x16.png ✔
  copying       favicon-32x32.png ✔
  copying       favicon.ico ✔
  copying       index.html ✔
  copying       manifest.json ✔
  copying       robots.txt ✔
  copying       safari-pinned-tab.svg ✔
  copying       .eslintrc.json ✔
  copying       app.js ✔
  copying       App.test.tsx ✔
  copying       App.tsx ✔
  copying       apis.ts ✔
  copying       index.tsx ✔
  copying       setupTests.ts ✔
  copying       LogoFull.tsx ✔
  copying       LogoIcon.tsx ✔
  copying       Root.tsx ✔
  copying       index.ts ✔
  copying       EntityPage.tsx ✔
  copying       SearchPage.tsx ✔

 Moving to final location:
  moving        backstage-app ✔

 Building the app:
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
  executing     yarn install ✖

Error: Could not execute command yarn install

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!

**Comment by Rugvip** [comment] 2022-04-25 11:58
Hmm, I'm unable to reproduce this under Win 10 / WSL 2. Running Ubuntu 18.04 though, but Node.js v16.14.2

**Comment by sp0tt13** [comment] 2022-04-25 21:40
It seems yarn is the problem somehow.  I had followed the instructions on the backstage.io website, which sent me to https://classic.yarnpkg.com/en/docs/install.  After installing yarn, it gave me what seemed to be the latest version;
$ npm info yarn version
1.22.18
$ yarn --version
0.32+git
The error in my previous message seemed to be a yarn error, so I looked for an alternative and found
https://dev.to/bonstine/installing-yarn-on-wsl-38p2
which suggested I install yarn with 
curl -o- -L https://yarnpkg.com/install.sh | bash
After installing that way, I now get yarn --version giving 1.22.18 instead of 0.32+git, but more importantly, it is building the my-backstage-app without error.

**Comment by blabaschin** [comment] 2022-05-06 23:54
I had the same issues. It was a headache. I had to uninstall all of my yarn as above but in addition I had to brew install python, cmake, and gcc. I suggest someone looks into adding these to the instructions.

**Comment by phil123456** [comment] 2024-12-10 12:42
same issue, just installed
ubuntu 24.04
node js 23.3.0

npx @backstage/create-app@latest

![image](https://github.com/user-attachments/assets/4a65441e-4911-4459-bfc4-25a8009cc016)

**Comment by phil123456** [comment] 2024-12-10 12:43
> I had the same issues. It was a headache. I had to uninstall all of my yarn as above but in addition I had to brew install python, cmake, and gcc. I suggest someone looks into adding these to the instructions.

can you give some details ? brew install ???

**Comment by phil123456** [comment] 2024-12-10 12:58
ok found the solutions, get rid of /usr/bin/yarn then

curl -o- -L https://yarnpkg.com/install.sh | bash
.bachrc

**Comment by phil123456** [comment] 2024-12-10 13:12
this process really does not work at all

![image](https://github.com/user-attachments/assets/7e8165fe-c607-45f6-89e1-c1f4080b8f52)

![image](https://github.com/user-attachments/assets/526a6c6f-49f1-4cd5-99c9-99f47544246e)

**Comment by nouknouk** [comment] 2024-12-23 12:00
Hi,

linux mint user here, I faced the same issue.
Default Yarn version is well the root cause.

```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.2
DISTRIB_CODENAME=victoria
DISTRIB_DESCRIPTION="Linux Mint 21.2 Victoria"
```

before:
```
$ node --version
v20.5.1
$ npm --version
10.9.0
$ yarn --version
0.32+git
```

I installed a more recent version using the bash installer **and exported the right path** (I suppose a `source ~/.bashrc` would have done the same)
```
curl -o- -L https://yarnpkg.com/install.sh | bash
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
```

The default yarn version becomes:
```
$ yarn --version
1.22.22
```

and then, the backstage command works well.
