### ISSUE TITLE
🐛 Bug Report: `yarn backstage-cli versions:bump --release X.Y.Z` installs latest instead for many plugins

### ISSUE THREAD

**Issue by adrianke77** [backstage/backstage#18881] opened 2023-08-01 05:48 UTC
### 📜 Description

if we try to use backstage-cli to target an intermediate non-latest release version, e.g. 
yarn backstage-cli versions:bump --release 1.7.2, 
the versions added/installed to package.json use ^ which for A.B.C version format would increase B to latest available, but for most/all Backstage plugins that is the effectively major version, i.e. can have breaking changes when increased. 

### 👍 Expected behavior

It seems like it would make more sense to hard pin the version (no ^, ~ etc)

### 👎 Actual Behavior with Screenshots

yarn backstage-cli versions:bump --release 1.7.2 produces installed plugins with many much more recent versions, eg we had to implement fixes only mentioned in release notes for 1.15.1.

### 👟 Reproduction steps

On an older installation of Backstage, eg 1.5.1, run:

yarn backstage-cli versions:bump --release 1.7.2 

and compare installed version in yarn.lock against package.json. Many plugins will have a version that is the latest Backstage release instead of the targeted version in the command

### 📃 Provide the context for the Bug.

As we were behind on versions recently we wanted to target an intermediate version to avoid too many breaking changes in one upgrade task, but hit on the above problem, causing other complications, as we get versions different from upgrade-helper, we see items to fix covered in release notes of versions far beyond our target version, etc.

Also different developers working on their plugins running the same command ended up with different plugin versions in yarn.lock, depending on when they ran it and what was the latest released for the plugin, instead of a pinned target version.

### 🖥️ Your Environment

Should occur on any environment, as this is due to the ^ included in package.json versions. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by aakankshabhende** [comment] 2023-08-01 17:29
@Rugvip I would like to work on this. Could you please assign me this?

**Comment by freben** [comment] 2023-08-03 13:20
Assigned!

I'm not sure what the exact best behavior is here - semver to "equal or best compatible higher" _should_ ideally be safe. Maybe it could be an option to use exact versions or not? @Rugvip FYI.

**Comment by freben** [comment] 2023-08-07 08:47
Note also that `^` for 0.x versions only is meant to bump the patch version, because for zero-major packages. This is what npm and yarn do. Did you see a different behavior than that?

**Comment by aakankshabhende** [comment] 2023-08-07 17:34
@freben I saw that mostly ^ has been used which is automatically updating to major versions.

**Comment by freben** [comment] 2023-08-07 18:06
Are you sure? Do you have an example of a package name, and the version range that it started with, and the version you got resolved to in the end?

**Comment by freben** [comment] 2023-08-07 18:10
Note the separate treatment of 0.x versions [in the NPM docs](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004)

**Comment by aakankshabhende** [comment] 2023-08-31 10:36
@freben 

https://github.com/backstage/backstage/blob/5623a818b957b0ef3d44434cd4b8afbf9ae43f7d/packages/integration-react/package.json

Can we replace ^ with either ~ or just version and then having a script to bump in the latest version of packages like backstage/core-components?

**Comment by Rugvip** [comment] 2023-09-04 09:49
@aakankshabhende we prefer using `^` because it minimizes package duplication and in general results in the fewest headaches for users. This generally shouldn't be a problem for projects on old versions either because Yarn will install dependencies in a way which satisfies all ranges.

An important think to note here is that the Backstage version does not adhere to semver, meaning that a bump from for example `1.5.0` to `1.7.0` will most likely contain breaking changes. That has nothing to do with Yarn or dependency ranges in our packages, it's simply how we version things. The k8s version policy is what inspired us to go for that particular system.

Now we could discuss whether it's worth locking down out package dependency ranges to either `~` or exact version. We do have the tooling that still makes it convenient to stay on top of the latest releases anyway. Though I don't like it for two reasons, one is that it will make patching harder, it's more straightforward to have automated dependency bumps when you only need to unlock `yarn.lock` entries for patches. The other is that the `@backstage/` packages would become "special" in the backstage ecosystem, because a fixed version would not make sense for any other packages since you want that range to be there to avoid duplication and receive patches faster. I think it's better if we just have a single preferred way to handle dependencies in the ecosystem.

As a final note I'd also say that we optimize for the best experience for users that keep their projects up to date. If we can improve the experience for users on older versions that's fine, but it can not come at the cost of a worse experience for the aforementioned users.

I'm going to close this issue as the original bug reported is intended behavior that we do not intend to change. At least not without a broader discussion that would require an RFC.

**Closed by Rugvip** 2023-09-04 09:49 UTC
Labels: bug
