### ISSUE TITLE
NotAllowedError when trying to fetch OpenApi definition from external URL

### ISSUE THREAD

**Issue by autoamator** [backstage/backstage#11149] opened 2022-04-28 10:36 UTC
## Expected Behavior

I'm trying to import the OpenApi json file to backstage. Here's my definition:
```
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: another-api
  description: API added by url
spec:
  type: openapi
  lifecycle: production
  owner: platform
  definition:
    $text: http://backend.company.com:8080/service/v2/api-docs
---
```
 I expect the above description of API appears in backstage same as it does for petstore example:

```
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
  description: petstore test API
spec:
  type: openapi
  lifecycle: production
  owner: platform
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
---
```

## Actual Behavior

Instead I get the following error:

```backstage_1  | 2022-04-28T09:57:47.286Z catalog warn Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location http://backend.company.com:8080/service/v2/api-docs, NotAllowedError: Reading from 'http://backend.company.com:8080/service/v2/api-docs' is not allowed type=plugin entity=api:default/another-api```

## Context

My suspicion is that the address http://backend.company.com:8080 needs to be whitelisted somewhere, but I don't see where or how exactly. What I tried was editing app-config.yaml:

```backend:
  baseUrl: ${BASE_URL}
(...)
  cache:
    store: memory
  reading:
    allow:
      #- host: petstore.swagger.io
      - host: bitbucket.company.com
      - host: backend.company.com:8080
      - host: backend.company.com
 ```
No success.
 I even commented out the petstore line and the petstore example is still working.

Also I tried with Catalog settings in app-config.yaml:
```
catalog:
  rules:
    - allow: [ Component, System, API, Group, User, Resource, Location ]
  locations:
    - type: url
      target: http://backend.company.com:8080/service/v2/api-docs
    - type: bitbucket-discovery
      target: https://bitbucket.company.com/projects/*/repos/*/catalog-info.yaml
```

Didn't work as well.

Both petstore and my api-docs are in the same version ("swagger":"2.0").

## Your Environment

Windows, backstage run via docker-compose.

- Browser Information: <Edge, Chrome>

- Output of `yarn backstage-cli info`: 

```
it's a dockerized version, not sure how to execute the above

```

**Comment by autoamator** [comment] 2022-04-28 12:00
Can it be related to [a different issue](https://github.com/backstage/backstage/issues/9668) ?
I found following section in the [docs](https://backstage.io/docs/plugins/url-reader):
![image](https://user-images.githubusercontent.com/9354531/165746491-c7d2c97f-5922-4d78-9121-426dabf7cd4a.png)
https://backstage.io/docs/plugins/url-reader
My link to api definition looks raw, but on the other hand the one for petstore example looks the same and it works...

**Comment by awanlin** [comment] 2022-04-28 12:16
I think you are missing the file. You have:

`$text: http://backend.company.com:8080/service/v2/api-docs`

Should it not be:

`$text: http://backend.company.com:8080/service/v2/api-docs/swagger.json`? Or `$text: http://backend.company.com:8080/service/v2/api-docs/swagger.yaml` (the file really can be called anything just needs to be a valid OpenAPI spec)


If you look at the petstore example you posted it is:

`$text: https://petstore.swagger.io/v2/swagger.json`

**Comment by awanlin** [comment] 2022-04-28 12:17
I could be wrong and your URL returns a file but maybe that's not something Backstage handles properly then 🤔

**Comment by autoamator** [comment] 2022-04-28 13:50
Thanks for a quick reply.

My URL actually opens a json file.
Also I'm getting the same error for kinds of URLs you're mentioning (http://backend.company.com:8080/service2/swagger/v1/swagger.json) so probably the problem is elsewhere.

**Comment by benjdlambert** [comment] 2022-05-02 11:38
Hmm, so what's the error you're getting locally now?

I see that if I use a URL in the definition like `$text: http://test:1234` then I need to have `- test:1234` including the port in the `backend.reading.allow` array. But it seems to work for me locally if I add the port and reads as expected.

**Comment by lalit774** [comment] 2022-05-02 18:17
It is working for me. I figured out following two issues.

1) Behind a corporate-proxy
   https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md

2) backend.reading.allow

Please close this, as it is not a bug.

**Comment by benjdlambert** [comment] 2022-05-03 09:31
Perfect! Glad it all worked out!

**Closed by benjdlambert** 2022-05-03 09:31 UTC
Labels: bug

**Comment by awanlin** [comment] 2022-05-03 10:26
Awesome, glad this is working for you

**Comment by autoamator** [comment] 2022-05-04 09:39
Thanks for suggestions!
I already had the proper entry in backend.reading.allow and it did not work. I still need to check the coorporate-proxy solution.

**Comment by autoamator** [comment] 2022-05-26 03:57
Final update- it turned out that my backstage version was simply too old. After upgrading to the newest it all works fine. Thank you all for your help.

**Comment by azhar-beg** [comment] 2023-04-06 10:39
@autoamator I want to reproduce the same bug, could you please help me with that?
