### ISSUE TITLE
kid is not validated while trying to generate backstage internal token while passing the details manually from an end point

### ISSUE THREAD

**Issue by ankitapandey1106** [backstage/backstage#13893] opened 2022-09-28 15:43 UTC
I am trying to call the issueToken() method of TokenFactory.ts to generate the backstage token from an end point, in order to enable some validations while calling backstage's backend apis from an external service, the token generation is successful and on ecoding jwt token, all the headers and claims are exactly as we have in the originally generated backstage token but the while trying to hit the backend api, it says unauthorized ( there's token mismatch) 
Not sure what am I missing here or it's just not possible to go via the approach I have taken?

**Comment by Rugvip** [comment] 2022-09-29 09:42
Going to close this as a duplicate of #11158. The `issueToken()` method is for user authentication, so you don't want to use that one for service-to-service auth.

**Closed by Rugvip** 2022-09-29 09:42 UTC
Labels: auth
