### ISSUE TITLE
SyntaxError: Unexpected token { in JSON at position 95

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4726] opened 2021-02-27 21:19 UTC
## Expected Behavior

All plugins should be auto-updated when running: yarn backstage-cli versions:bump

## Current Behavior

Failing @backstage/plugin-techdocs

```
Checking for updates of @backstage/dev-utils
Checking for updates of @backstage/plugin-techdocs-backend
Checking for updates of @backstage/plugin-kubernetes-backend
Checking for updates of @backstage/plugin-scaffolder-backend
Checking for updates of @backstage/plugin-graphql-backend
Checking for updates of @backstage/plugin-proxy-backend
Checking for updates of @backstage/plugin-catalog-backend
Checking for updates of @backstage/plugin-auth-backend
Checking for updates of @backstage/plugin-app-backend
Checking for updates of @backstage/config
Checking for updates of @backstage/catalog-client
Checking for updates of @backstage/backend-common
Checking for updates of @backstage/theme
Checking for updates of @backstage/test-utils
Checking for updates of @backstage/plugin-user-settings
Checking for updates of @backstage/plugin-techdocs

SyntaxError: Unexpected token { in JSON at position 95
```

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by Rugvip** [comment] 2021-02-27 22:03
Is this happening every time you run the command? I'm not able to reproduce it, and `yarn info --json @backstage/plugin-techdocs` looks alright for me too

**Comment by regicsolutions** [comment] 2021-02-28 18:16
Not sure if something

> Is this happening every time you run the command? I'm not able to reproduce it, and `yarn info --json @backstage/plugin-techdocs` looks alright for me too

Not sure if something was updated but i am no longer getting the error. I do keep getting an error for @backstage/core but i always got this in the past... any idea why?

![image](https://user-images.githubusercontent.com/6157895/109428897-2029df80-79c7-11eb-94f7-35b6dee8db1c.png)

**Comment by Rugvip** [comment] 2021-03-02 15:57
The CLI is using `execFile` to run the `yarn info` command and then just gets the full output of `stdout`, so having a hard time seeing this would be a piping or data chunking error. Cosmic rays perhaps? 😅

**Comment by benjdlambert** [comment] 2021-03-04 17:45
@regicsolutions can we close this?

**Closed** 2021-03-05 03:46 UTC
Labels: bug

**Comment by nikmel2803** [comment] 2022-02-17 18:18
I'm facing with the same issue now.
It resolved after I deleted all the `node_modules`, `yarn.lock` and then reinstall all dependencies.

But now I'm facing with another problems...

**Comment by regicsolutions** [comment] 2022-02-17 22:39
Good with closing this one
