### ISSUE TITLE
 TechDocs does not register `extra_javascript` from "mkdocs.yaml"

### ISSUE THREAD

**Issue by ericis** [backstage/backstage#13856] opened 2022-09-26 20:36 UTC
## Expected Behavior

The JavaScript file path(s) configured in "mkdocs.yaml" in the "extra_javascript" value should be registered on the page.

## Actual Behavior

The JavaScript configuration and files are ignored.

## Steps to Reproduce

1. Create a new TechDocs site with the `techdocs-cli` NPM package (`yarn` or `npm`)
2. Configure "mkdocs.yaml" with a custom JS file (e.g. "extra_javascript: [./assets/scripts/example.js]")
3. Start `techdocs-cli serve -v`

## Context

Related to issue #12302 with "extra_css" support.

## Your Environment

- Browser Information: Firefox 104.0.2 (64-bit)
- Output of `yarn techdocs-cli --version`: 1.2.1
- Output of `yarn backstage-cli info`: n/a

**Comment by realandersn** [comment] 2022-10-05 12:38
Hey! All features of `mkdocs` are not allowed in TechDocs. The `extra_javascript`, for instance, cannot be allowed for security reasons.

**Comment by ericis** [comment] 2022-10-05 22:35
@realandersn what about #12302 for `extra_css`? Authors can't style their own docs?

Also, TechDocs AddOns are great, but are also site-wide. I was hoping to empower teams with similar capabilities as they would get with GitHub Pages since many developers are familiar with pages and have similar expectations for TechDocs.

Is there any documentation on why it's a security concern if we're only loading trusted TechDocs sources and the authors of those sources work for the company?

**Comment by ottosichert** [comment] 2022-10-19 15:45
Hey there @ericis! Let me try to expand on the reply from @realandersn, as there is quite some context behind this in terms of intentional design decisions, gradual iterations and necessary restrictions that are worth sharing here. Also, this context can be applied to both `extra_css` and `extra_javascript`, as we share the same view on both.

In a nutshell, TechDocs exposes an official interface, which is TechDocs Addons, that allows you to customize your sites to your liking, you can even go as far and ship your custom CSS and custom JavaScript with it. You could also restrict it to certain pages only by inspecting the currently displayed entity docs. While everything is possible, it is **more difficult by design** to have a different reading experience on every documentation site. Outside of the supported interface, it is intended to be impossible, for the number of reasons outlined below:

**MkDocs is an implementation detail**. We have to agree though that historically the whole product has been initially built around that assumption, but we are moving towards a decoupled architecture that allows bringing your own Markdown generator, for example MDX or any engines of static site generators like Gatsby or Hugo. We currently only use parts MkDocs, and heavily modify those parts that we use. If you we're to implement CSS and JS based on the current HTML tree, you will start noticing that we sometimes change certain parts how they are rendered, as we don't require sticking to the MkDocs output, but we build the `<TechDocsReader* />` around the public API we provide. Therefore like any other private interface you were to use, you can expect it to break in minor or even patch changes, so it is definitely not recommended.

**TechDocs is an enhanced Markdown reader**. By providing a standardized way to quickly build doc sites along your code with Markdown files, the focus is on optimizing the "happy case" for the best reading experience. As an implication, TechDocs is not best suited for a CMS-like system or website, if you require more flexibility and Addons are not enough, we advise to create your own Backstage plugin where you have any possibilities exceeding Markdown reading.

**The main feature of Addons is its architecture**. The way TechDocs has grown, all improvements and features have simply been added to the core functionality. This approach does not scale, and has led us to a high number of bugs and reduced maintainability. Therefore, we started an initiative to break up each feature into its own package, and have those packages interact with each other with clean interfaces. The outcome is to keep a small core, and bundle all extras into self-contained modules (more context in the Addons RFC: https://github.com/backstage/backstage/issues/9636). So if there are features that can't be implemented in any other way, at least they are contained in one Addon, and don't leak loose abstractions into the rest of TechDocs. However, by allowing developers to simply inject custom CSS and JS, we would completely break this architecture.

**We move closer towards React's modular structure**. We have to admit, using a Python-based generator to create HTML pages, extracting parts of it, statically transforming those parts, throwing them into a shadow DOM and mutating DOM nodes afterwards goes against a majority of Backstage's design principles. Therefore we are heavily invested in taking every possible step to move closer to a proper component-based architecture, all in the same JS and React ecosystem as the rest of the page. By allowing custom CSS and JS, we introduce a whole new dimension of architectural problems: how are CSS and JS assets being transformed and built? How do we store and share those assets? How do we interact between the Backstage world and custom changes? How do we prevent it to break on every change to the structure?

**Custom CSS/JS has major risks**. As explained above, opening the door for any arbitrary change through custom CSS and JS break basically any architectural promise about your component. You never know it will break, until it does. If we were to publicly support custom CSS or JS, we have to choose to either support an exponential explosion in surface area, or to make breaking changes with most, if not all structural improvements. Then, security is only as strong as it weakest element. One example is the `<iframe>` tag, where one needs to explicitly whitelist a subset of hosts that are allowed (see `allowedIframeHosts` PR: https://github.com/backstage/backstage/pull/8237). By including external assets it is nearly impossible to monitor all doc sites in your organization and all their external references that not a single one of them has been breached, especially if subresource integrity is not enforced (see https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity). For both issues mentioned here, we carry the responsibility to design our public interfaces in a way that affects hundreds, if not thousand of organizations and all their developers and customers. As your Backstage instance is the central platform for your developers, security becomes even more important in that aspect.

That being said, I can see TechDocs working more closely with the Backstage theme and allow customizing through it 😄 

I hope this context helps, and happy to hear your thoughts about this! Maybe we can get a better understanding if you could share with us what changes you are intending to make using custom CSS and JS.

**Comment by ericis** [comment] 2022-10-19 21:24
This is FANTASTIC context and helps clarify why some MkDocs features are supported out-of-the-box and others are explicitly designed not to be supported. We can update Backstage TechDocs documentation to ensure this is communicated clearly too.

Interestingly, MkDocs supports plugins that extend Markdown and TechDocs seems to implicitly support that plug-in model as long as those MkDocs plugins are installed in the TechDocs build pipeline.

There aren't a lot of layout options in the current solution of TechDocs + MkDocs + Markdown e.g. "Cards", multi-column layouts, responsive layouts, etc. That will be wonderful to have in the future.

**Comment by ericis** [comment] 2022-10-19 21:25
Should we close this issue as well as #12302 as "intentionally not planned" ?

**Closed** 2022-10-20 11:51 UTC
Labels: bug, wontfix, techdocs
