### ISSUE TITLE
Catalog-backend- need for optimizing the ingestion loop 

### ISSUE THREAD

**Issue by SuganJoe** [backstage/backstage#3534] opened 2020-12-02 18:45 UTC
In service catalog backend, there is auto-refresh of locations happens every 1.6 min . Even using postgre DB for Production data(around 13K entities) from an organization, It takes around  ~16 min to complete refresh.

Background - Service catalog backend is integrated with our organization 's internal metadata API (Fetching around 13K entities)-following external-integrations approach (https://backstage.io/docs/features/software-catalog/external-integrations)

Issue - This latency will have a great effect in time taken to display an app in backstage catalog, once it is created by scaffolder. 

a) on every refresh there is a comparison of existing entities and new entities for all the entities and then entities are split into three groups {toAdd, toUpdate, toIgnore}. Though there will be lot of entities endup in 'toIgnore' - they are updated as well with setRelations()- meaning there is an DB update operation happens for all entities.
https://github.com/backstage/backstage/blob/f531d307c4b9c8fb98f0d4b1b3006dd6023a8961/plugins/catalog-backend/src/catalog/DatabaseEntitiesCatalog.ts#L190-L212

b) batch _size == 100 (having 12K entities) this may slow down things further
When I increase the batch size -5000 (may not be realistic and may lead to race condition) its takes around 10 min to finish - not a significant improvement.

![image](https://user-images.githubusercontent.com/25852441/100916377-8071b980-348a-11eb-9a3c-c3e9b15f2491.png)

## Context
To decrease the time to display an app in service catalog, once it is create by scaffolder.

**Comment by freben** [comment] 2020-12-02 20:50
Thank you!

I tried with a fairly large input dataset (Spotify LDAP) on latest master.

First with sqlite in memory:

```
2020-12-02T20:30:15.674Z catalog info Read 17857 entities from location bootstrap:bootstrap in 8.5s
2020-12-02T20:30:39.361Z catalog info Posting update success markers
2020-12-02T20:30:55.500Z catalog info Wrote 17857 entities from location bootstrap:bootstrap in 39.8s
2020-12-02T20:30:55.502Z catalog info Completed locations refresh in 48.4s
```

Not too shabby. Then with a local postgres 12.3 running in docker:

```
2020-12-02T20:34:38.006Z catalog info Read 17857 entities from location bootstrap:bootstrap in 9.9s
...
```

... I stopped waiting 15 minutes later while the Docker daemon was under very high CPU usage.

This is a regression; when I did the same test with the same source a few months ago the times were comparable between the two databases (although the inmemory one was a bit faster).

**Comment by freben** [comment] 2020-12-02 20:56
If you run the backend with `LOG_LEVEL=debug`, you will see it process individual batches as they are being written. You'll notice that the batches get very quickly slower and slower the more data that's stored.

```
2020-12-02T20:51:37.917Z catalog debug Found 100 entities to add, 0 entities to update in 12ms
2020-12-02T20:51:37.927Z catalog debug Found 100 entities to add, 0 entities to update in 22ms
2020-12-02T20:51:37.935Z catalog debug Found 100 entities to add, 0 entities to update in 30ms
2020-12-02T20:51:39.370Z catalog debug Added 100 entities in 1.5s
2020-12-02T20:51:39.371Z catalog debug Considering batch [redacted] (100 entries)
2020-12-02T20:51:40.388Z catalog debug Found 100 entities to add, 0 entities to update in 1.0s
2020-12-02T20:51:40.395Z catalog debug Added 100 entities in 2.5s
2020-12-02T20:51:40.395Z catalog debug Considering batch [redacted] (100 entries)
2020-12-02T20:51:41.467Z catalog debug Found 100 entities to add, 0 entities to update in 1.1s
2020-12-02T20:51:41.474Z catalog debug Added 100 entities in 3.5s
2020-12-02T20:51:41.474Z catalog debug Considering batch [redacted] (100 entries)
2020-12-02T20:51:42.506Z catalog debug Found 100 entities to add, 0 entities to update in 1.0s
2020-12-02T20:51:43.959Z catalog debug Added 100 entities in 3.6s
2020-12-02T20:51:43.959Z catalog debug Considering batch [redacted] (100 entries)
2020-12-02T20:51:46.352Z catalog debug Found 100 entities to add, 0 entities to update in 2.4s
2020-12-02T20:51:46.360Z catalog debug Added 100 entities in 4.9s
2020-12-02T20:51:46.360Z catalog debug Considering batch [redacted] (100 entries)
2020-12-02T20:51:48.747Z catalog debug Found 100 entities to add, 0 entities to update in 2.4s
2020-12-02T20:51:48.753Z catalog debug Added 100 entities in 6.2s
2020-12-02T20:51:48.753Z catalog debug Considering batch [redacted] (100 entries)
2020-12-02T20:51:51.210Z catalog debug Found 100 entities to add, 0 entities to update in 2.5s
2020-12-02T20:51:52.690Z catalog debug Added 100 entities in 6.3s
```

The logs are there in this form because I've seen this behaviour before and fixed it. I'll look into again why it has resurfaced.

**Comment by SuganJoe** [comment] 2020-12-02 21:20
@freben Thanks for checking on the issue.

Was it consistent for subsequent refreshes? 
Because the first time it just has to add all the entities, so it is faster for me as well refresh completed below 1 min. But, in the following refreshes it took around 15  min, as entities are compared with old version of entities and then updated.

**Comment by SuganJoe** [comment] 2020-12-02 21:28
About using sqlite in-memory for Production - In our organization there is an existing DB  for storing all entity information and an API to fetch entities from. So, Catalog backend DB merely acts as a cache layer in this case. 

Do you see any potential reason for not using sqlite for production in this case?

**Comment by freben** [comment] 2020-12-02 21:43
I didn't follow through since even the first run (starting from an empty database) just took too long. I expect the next run would have been almost equally slow!

Current theory is that it's actually reads that are slowing it down. Removing this step (replacing it with an empty array) makes it run to completion pretty quickly.

https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/catalog/DatabaseEntitiesCatalog.ts#L285

The core of the issue would then be the query bilder here.

https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/database/CommonDatabase.ts#L242

I rewrote it some time ago to use WHERE...IN instead of JOIN. This made sense from a code standpoint but maybe it hurt the pg query planner. Or maybe some other fix around that time removed an index. I'll have to look closer when I get some time to do so.

Using sqlite in prod - sorry that won't work well. Even if it's cache-like here, you will get other ill  effects and other plugins that want actual persistence - including the catalog itself which stores locations that users have registered - will lose their data on each deploy.

**Comment by SuganJoe** [comment] 2020-12-03 18:33
Created PR - https://github.com/backstage/backstage/pull/3540
Why?
During location refresh in catalog backend, there is a comparison between old entities and new entities in entityHasChanges() function. In that method, relations in the existing entity from DB (e1) is not removed causing lodash.IsEqual() to always returns false and entities always end up in toUpdate list instead of ideally going to toIgnore list. Due to this, there is a high latency especially if the entities count is large though those entities exist in DB already.

Note :

relations don't exist in incoming entity, but exist only in existing entity in DB
For 13K entities, it took around 60 seconds for first write to DB and successive updates took 1000 seconds.
What?
Removed relations in the existing entity from DB (e1) before performing lodash.IsEqual(), and this helps successive updates to complete within 100 seconds.

**Comment by timbonicus** [comment] 2021-03-17 17:57
I see a few related issues like #3592, #3666 - is this resolved, or still an issue?

**Comment by freben** [comment] 2021-03-17 19:08
Yes, we had some massive speedups through batching and other fixes. And especially given that large parts of the engine that drives refreshes is being rewritten as we speak, we should close this ticket and open a new more targeted one if performance issues happen again.

**Closed by freben** 2021-03-17 19:08 UTC
Labels: bug, catalog, enhancement
