### ISSUE TITLE
🐛 Bug Report: Fetching a file from github does not work if the target branch contains a / (slash)

### ISSUE THREAD

**Issue by adrien-saunier-decathlon** [backstage/backstage#19668] opened 2023-08-30 09:57 UTC
### 📜 Description

Some of our teams set their default branch as `release/v3`. 

While scanning the repository, the catalog-info.yaml is not found because the used repository branch (default) is transformed as `release` instead of `release/v3`.

The issue seems related to `getGithubFileFetchUrl`, how rely on one methode that does not extract correctly the `ref`.

### 👍 Expected behavior

When registering an existing component (on /catalog-import page) using a direct file URL (example: https://github.com/my-org/my-repo/blob/release/v3.37/catalog-info.yaml, the catalog file should be found and integrated.

### 👎 Actual Behavior with Screenshots

It actually attempt to call the github API using the wrong url, which result in a 404 error.

```json
{"error":{"name":"InputError","message":"NotFoundError: Unable to read url, NotFoundError: https://github.com/my-org/my-repo/blob/release/v3.37/catalog-info.yaml could not be read as https://api.github.com/repos/my-org/my-repo/contents/v3.37/catalog-info?ref=release, 404 Not Found"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}
```

### 👟 Reproduction steps

1. Create repository for testing
2. Create a branch called `release/v3` (or any other name that contains a slash) that contains a `catalog-info.yaml`
3. Set that branch as default
4. Try to import the repository into a backstage instance

The bug is appearing in those cases : 
- When giving the repository URL (example: https://github.com/my-org/my-repo)
- When giving the direct file access (example: https://github.com/my-org/my-repo/blob/release/v3.37/catalog-info.yaml)

### 📃 Provide the context for the Bug.

- Backstage v1.17
- Github provider

### 🖥️ Your Environment

OS:   Darwin 22.5.0 - darwin/arm64
node: v18.17.1
yarn: 1.22.19
cli:  0.22.12 (installed)
backstage:  1.17.5

Dependencies:
  @backstage/app-defaults                          1.4.2
  @backstage/backend-app-api                       0.5.2
  @backstage/backend-common                        0.19.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-openapi-utils                 0.0.3
  @backstage/backend-plugin-api                    0.6.2
  @backstage/backend-tasks                         0.5.7
  @backstage/catalog-client                        1.4.3
  @backstage/catalog-model                         1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.3
  @backstage/cli                                   0.22.12
  @backstage/config-loader                         1.4.0
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.9.1
  @backstage/core-components                       0.13.4
  @backstage/core-plugin-api                       1.5.3
  @backstage/dev-utils                             1.0.20
  @backstage/errors                                1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.18
  @backstage/integration                           1.6.2
  @backstage/plugin-adr-backend                    0.3.8
  @backstage/plugin-adr-common                     0.2.14
  @backstage/plugin-adr                            0.6.6
  @backstage/plugin-api-docs                       0.9.10
  @backstage/plugin-app-backend                    0.3.50
  @backstage/plugin-app-node                       0.1.2
  @backstage/plugin-auth-backend                   0.18.8
  @backstage/plugin-auth-node                      0.2.19
  @backstage/plugin-catalog-backend-module-github  0.3.7
  @backstage/plugin-catalog-backend                1.12.4
  @backstage/plugin-catalog-common                 1.0.15
  @backstage/plugin-catalog-graph                  0.2.35
  @backstage/plugin-catalog-import                 0.9.13
  @backstage/plugin-catalog-node                   1.4.3
  @backstage/plugin-catalog-react                  1.8.3
  @backstage/plugin-catalog                        1.12.4
  @backstage/plugin-events-backend-module-github   0.1.12
  @backstage/plugin-events-backend                 0.2.11
  @backstage/plugin-events-node                    0.2.11
  @backstage/plugin-github-actions                 0.6.4
  @backstage/plugin-github-pull-requests-board     0.1.17
  @backstage/plugin-org                            0.6.13
  @backstage/plugin-permission-common              0.7.7
  @backstage/plugin-permission-node                0.7.13
  @backstage/plugin-permission-react               0.4.14
  @backstage/plugin-proxy-backend                  0.3.2
  @backstage/plugin-scaffolder-backend             1.16.5
  @backstage/plugin-scaffolder-common              1.4.0
  @backstage/plugin-scaffolder-node                0.2.2
  @backstage/plugin-scaffolder-react               1.5.4
  @backstage/plugin-scaffolder                     1.14.4
  @backstage/plugin-search-backend-module-catalog  0.1.6
  @backstage/plugin-search-backend-module-pg       0.5.11
  @backstage/plugin-search-backend-module-techdocs 0.1.6
  @backstage/plugin-search-backend-node            1.2.6
  @backstage/plugin-search-backend                 1.4.2
  @backstage/plugin-search-common                  1.2.5
  @backstage/plugin-search-react                   1.6.4
  @backstage/plugin-search                         1.3.6
  @backstage/plugin-sonarqube-backend              0.2.4
  @backstage/plugin-sonarqube-react                0.1.7
  @backstage/plugin-sonarqube                      0.7.4
  @backstage/plugin-tech-radar                     0.6.7
  @backstage/plugin-techdocs-backend               1.6.7
  @backstage/plugin-techdocs-module-addons-contrib 1.0.18
  @backstage/plugin-techdocs-node                  1.7.6
  @backstage/plugin-techdocs-react                 1.1.9
  @backstage/plugin-techdocs                       1.6.8
  @backstage/plugin-user-settings                  0.7.8
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.2
  @backstage/theme                                 0.4.1
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
✨  Done in 1.07s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment] 2023-08-31 11:13
Closing this as a duplicate of #2815, let's focus the discussion there

**Closed by Rugvip** 2023-08-31 11:13 UTC
Labels: bug

**Comment by adrien-saunier-decathlon** [comment] 2023-08-31 12:15
Oh sorry, i missed this issue.
Thanks !
