### ISSUE TITLE
Incorrect response when validating Entities fails in the LocationReaders

### ISSUE THREAD

**Issue by GoWind** [backstage/backstage#4267] opened 2021-01-26 23:07 UTC
## Expected Behavior
When a Processor attempts to validate a corresponding `Entity` and returns false, it should be known that the Entity
was not processed completely because of a validation failure

## Current Behavior
After all processors attempt to validate an `Entity` and one of them actually does and the result is `false`, the reported
Error is that of `No processor recognized the entity ${kind}:${namespace}/${name} at ${item.location.type} ${item.location.target}`
An [Error](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/LocationReaders.ts#L240) is set, when no processor can validate an Entity. 
But this maskes the fact that  `BuiltinKindsEntityProcessor` relying on core validators such as [Group](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/kinds/GroupEntityV1alpha1.ts) validators, returns a `false` when an Entity fails a validation. 
In this case, it is not sure if the failure is because no processor can validate an entity or if the validation fails. The Error when a processor  throws an Exception, when validating an entity is cleanly handled [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/LocationReaders.ts#L230).

## Possible Solution
**Simple solution**
 [BuiltinKindsEntityProcessor](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/BuiltinKindsEntityProcessor.ts#L67) much dispatch the Entity to the right  validator based on the `kind` and if the validation fails, throws an Exception. If the argument to `validateEntity` is not a builtin/core `kind` , then it simply returns a `false`

This will provide quick feedback that processing a `BuiltinKindsEntity` fails, when a consumer uses it in the Catalog.

** Ideal Solution **
A `true/false` doesn't really say anything about validation as this could also be the `Processor` refusing to process that particular Enity caused by The current design of running an `Entity` through each processor linearly. 
To truly differentiate between a failure to validate and failure to find a processor to validate,
1. Have a mapping between `kind` -> processor, for validating an entry. 
2. Return `No Processor found` iff no entry exists for processing a certain entry `kind`.
3. Return `Validation Failure` if a mapping exists and returns false. 

This could be done without upsetting the API of a `Processor` (returns false/throws Exceptions when validation fails).

**
## Steps to Reproduce
Build a `CatalogBuilder` instance calling `.replaceProcessors([...customProcessors, BuiltinKindsEntityProcessor])`.
One of the processors reads a location emitting a `Group` entity with `spec: {name: "Team Rocket"}` and no `children` or `type`  fields (from [spec](https://backstage.io/docs/features/software-catalog/descriptor-format#spectype-required-2))

The `Group` entry is not added but the response is one of `No processor recognized the entity ${kind}:${namespace}/${name} at ${item.location.type} ${item.location.target}`

## Context

While adding Group entries and adding a `BuiltinKindsEntityProcessor` to the list of `Processor` , I noticed that the I had made mistakes in emitting a `Group` Entry  but couldn't understand what went wrong because of the impreciseness of the `Error` Message.

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by GoWind** [comment] 2021-01-26 23:07
Would be interested in offering a solution to this as a PR.

**Comment by freben** [comment] 2021-02-01 08:19
Do you have an exact entity where this happens? I think you might see this only if the `apiVersion` + `kind` combination is entirely unknown. And in that case, the error message seems to be the appropriate one.

If I try to register a location with a component that does not conform to schema, this is what I get:

```
HTTP/1.1 400 Bad Request

InputError: Processor BuiltinKindsEntityProcessor threw an error while validating the entity Component:default/example-apis at file /Users/freben/dev/github/backstage/broken.yaml, TypeError: Malformed Component, /spec should have required property 'type'
    at Module.inputError (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/results.ts:51:12)
    at LocationReaders.handleEntity (webpack-internal:///../../plugins/catalog-backend/src/ingestion/LocationReaders.ts:231:78)%
```

**Comment by freben** [comment] 2021-02-01 08:23
To provide some more detail, the act of returning `false` is "I did not understand what this thing even is, so let somebody else go at it". If you DO know what it is, you are not supposed to return false for validation errors; you should throw an exception.

https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/types.ts#L69

**Comment by GoWind** [comment] 2021-02-01 09:53
@freben  : Yes, I believe this was the case` I think you might see this only if the apiVersion + kind `. 

I had accidentally made a typo in the `apiVersion` and was assumed that the builtin kinds processor would catch as it depends on  (GroupEntityV1alpha) [https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/kinds/GroupEntityV1alpha1.ts]. 

Since backstage has a default/standard `apiVersion` for the core entities, can we make it throw  an Exception if  the `apiVersion`   values mismatch ? 

```
To provide some more detail, the act of returning false is "I did not understand what this thing even is, so let somebody else go at it". If you DO know what it is, you are not supposed to return false for validation errors; you should throw an exception.
```
On this, perhaps this is not the right place, but to me this API looks like a consequence of the choice of algorithm  for  processing each entity through a series of processors such as [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/BuiltinKindsEntityProcessor.ts#L68) linearly, rather  than the opposite (API driving design). 
In order to be predictable and reliable, I think there should be only one deterministic processor responsible for processing an Entity's schema (preProcess, postProcess, validateEntity, etc).

Can I propose a change ( would be also interesting doing an initial prototype / PR)  to provide an associative lookup (Map<apiVersion+Kind,  Processor>  for validating and processing entities ? This would also have the advantage of not having to do a linear scan (O(n)) for each entity.

**Comment by freben** [comment] 2021-02-01 10:13
I'm not at all worried about the performance aspect of it, it'll be vastly overshadowed by just it being js or doing I/O :)

For now I think we won't be able to change the processor interface short term. One may argue that it's overly flexible and that that choice has drawbacks, but it has also proven pretty flexible and powerful. We'll have one final look at the interface as we productionise the catalog this quarter, maybe some level of restructuring can be had at that point.

**Comment by freben** [comment] 2021-02-01 10:14
I think one effective way to give some direction to the design there, could be to make a concrete RFC issue for The Next Iteration Of The Processor Interface or something :) Then we can discuss in there.

**Comment by GoWind** [comment] 2021-02-01 10:43
@freben : Sounds good :)  I will then create an RFC issue then. We are starting to massively use the catalog and ramping up to support our internal infra and I have other improvements/suggestions as well that might , if not now, then in the near future, might be bottlenecks as we increase our adoption. Will layout the proposals that we'd like to help with under the  RFC !

**Comment by freben** [comment] 2021-02-01 14:51
Cool! Given that the current error reporting seems to work as intended, I am closing this issue. If this is a mistake or we need to take further action, feel free to reopen it!

**Closed by freben** 2021-02-01 14:51 UTC
Labels: bug
