### ISSUE TITLE
Huge icon and missing styles from ReportIssue in techdocs shadow dom

### ISSUE THREAD

**Issue by iriswang233** [backstage/backstage#13995] opened 2022-10-05 02:39 UTC
## Expected Behavior

The style from ReportIssue should be added in shadow dom.
```
  root: {
    transform: 'translate(-100%, -100%)',
    position: 'absolute',
    padding: theme.spacing(1),
    zIndex: theme.zIndex.tooltip,
    background: theme.palette.common.white,
  },
```
Like this
![image](https://user-images.githubusercontent.com/49713904/193966354-1833cce1-0cb5-4854-81cd-4a018d4049a3.png)

Report issue works fine when running code from backstage repo at v1.4.0

<img width="385" alt="image" src="https://user-images.githubusercontent.com/49713904/193967535-d0f6c824-1c87-44f6-a520-5f0ecc041ff1.png">

## Actual Behavior

When running from our codebase with backstage v1.4.0,
this style is added outside shadow dom, so all the content in shadow dom is missing styling.
<img width="792" alt="Screenshot 2022-10-05 at 10 20 52 AM" src="https://user-images.githubusercontent.com/49713904/193966633-c9738c0e-5e86-4184-a7bb-11a974bb9417.png">
<img width="927" alt="Screenshot 2022-10-05 at 10 22 20 AM" src="https://user-images.githubusercontent.com/49713904/193966644-74512a92-eceb-44b0-b8d7-6712063a7f82.png">

The report issue then generated a huge icon like this.
<img width="847" alt="Screenshot 2022-10-05 at 10 32 02 AM" src="https://user-images.githubusercontent.com/49713904/193967304-5272e37d-e1c9-417b-9d8c-6d9725447f6c.png">

## Steps to Reproduce

1. Original code in plugins/techdocs-react/src/component.tsx
```
 <StylesProvider jss={jss} sheetsManager={new Map()}>
        <div ref={ref} data-testid="techdocs-native-shadowroot" />
        {children}
      </StylesProvider>
```
Change to be
```
 <StylesProvider jss={jss}>
        <div ref={ref} data-testid="techdocs-native-shadowroot" />
        {children}
      </StylesProvider>
```
2. run backstage
## Context

 It looks like a compiling issue but I don;t know what's the cause. And it's weird that the @backstage/plugin-techdocs-react                 1.0.3 does have the ```sheetsManager={new Map()}``` in StylesProvider.

## Your Environment

- Browser Information: 
Google Chrome 106.0.5249.91
Firefox 105.0.1

- Output of `yarn backstage-cli info`: 

```text
yarn backstage-cli info
yarn run v1.22.18

OS:   Darwin 21.6.0 - darwin/x64
node: v16.14.2
yarn: 1.22.18
cli:  0.18.1 (installed)
backstage:  1.4.0

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.15.0
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.2
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.11.0, 0.9.5
  @backstage/core-plugin-api                       1.0.5, 1.0.6
  @backstage/errors                                1.1.0, 1.1.1
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0, 1.3.1
  @backstage/plugin-analytics-module-ga            0.1.19
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-app-backend                    0.3.35
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4
  @backstage/plugin-catalog-backend-module-gitlab  0.1.6
  @backstage/plugin-catalog-backend-module-ldap    0.5.2
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.6
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.1, 1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-explore-react                  0.0.20
  @backstage/plugin-explore                        0.3.39
  @backstage/plugin-home                           0.4.24
  @backstage/plugin-kubernetes-backend             0.7.1
  @backstage/plugin-kubernetes-common              0.4.1
  @backstage/plugin-kubernetes                     0.7.1
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-pagerduty                      0.5.1
  @backstage/plugin-permission-backend             0.5.10
  @backstage/plugin-permission-common              0.6.4
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.5, 0.4.4
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.1
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.1
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-shortcuts                      0.3.0
  @backstage/plugin-stack-overflow                 0.1.4
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
✨  Done in 1.70s.
```

**Comment by ottosichert** [comment] 2022-10-26 09:24
Hey @iriswang233! Thanks for your issue report.

Looking at the file `plugins/techdocs-react/src/component.tsx` you referred to, it is hinted explicitly that passing a new `sheetsManager` is required:

https://github.com/backstage/backstage/blob/58c3581f8d6b74dc4527e13b5bbc05e5cefd55df/plugins/techdocs-react/src/component.tsx#L251-L255

Thus when removing it, it is expected to break. It is required as we are effectively running two JSS instances (Backstage + Shadow DOM) on one React instance. There is some additional context here: https://github.com/mui/material-ui/issues/19785

Before we close this issue, could you explain in what scenario you would need to remove the `sheetsManager`?

**Comment by iriswang233** [comment] 2022-10-31 01:24
Hi @ottosichert ,

Sorry for confusion here. I don't mean to remove the sheetsManager. The problem is the two JSS instances (Backstage + Shadow DOM) don't run well on one React instance.

All the JSS belong to Shadow DOM was compiled under Backstage rather than in the Shadow DOM, like what is described in Actual Behavior. 

I am wondering why this could happen. Could you help on this?

**Comment by ottosichert** [comment] 2022-11-09 13:24
Hey @iriswang233,

let my try to clarify:

> I am wondering how to make sure the shadow DOM's jss is rendered inside shadow DOM. Could you help on this?

The only possible way right now is to use two JSS instances with the second one having a separate sheets manager. This is due to the current architecture of TechDocs having effectively two HTML documents, one for Backstage, one for the shadow DOM. This is by design, meaning that there is no overlap between styles and behaviour between those boundaries. Almost like an `<iframe>` but less strict, i.e. still giving us the option to run one React instance instead of two, but coming with other limitations like the need for two JSS instances. You can read more about shadow DOM in general here: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

We agree that the setup is not ideal, and you might run into several suboptimal situations due to that boundary in TechDocs design.

If you don't mind I will go ahead and close this issue for now. Feel free though to outline the exact problem you are facing with the two JSS instances, we can at the moment not resolve that by itself but we might be able to help you out in other ways!

**Closed by ottosichert** 2022-11-09 13:24 UTC
Labels: bug, techdocs

**Comment by goququ** [comment] 2024-11-13 11:58
Hi everyone!

@ottosichert I just faced with the same issue, but I haven't changed `sheetsManager` at all. So my setup is the same as in the documentation, but somehow this functionality is just not working. Please provide me some details. What can I do to find the problem in my code? Thank you!
