### ISSUE TITLE
Scaffolder Validator not called on `type: object` custom field

### ISSUE THREAD

**Issue by goenning** [backstage/backstage#8542] opened 2021-12-17 17:29 UTC
I have a scaffolder custom field that emits an object like `{ name: 'bar', domain: 'foo' }` using the onChange function. 

This custom field has a validation function which is being passed on to `createScaffolderFieldExtension`

During runtime, this function is never called.

## Expected Behavior

I expected the validation function to be called for custom field of type 'object'

## Current Behavior

Validation function for custom field that emits an object are not being called.

## Possible Solution

I was looking at the `validate` function on the `TemplatePage.tsx` and this is where it's skipping the function call:

https://github.com/backstage/backstage/blob/6ae3e64b14b48d19511c5d34d0166fc9e208830a/plugins/scaffolder/src/components/TemplatePage/TemplatePage.tsx#L78-L102

If the value is an object, it recursivelly validations each individual property. But in my case, I don't have a form of different individual props, I just have a single `type: object` field:

```yaml
parameters:
  - title: Fill in some details
    required:
      - serviceName
    properties:
      serviceName:
        title: Service Name
        type: object
        description: Unique name of this service
        ui:field: MySuperExtension
```

## Context

I actually don't know if this is a bug or an unimplemented feature. I'm happy to send a PR to fix/include this, just want to confirm it's it should work like that or not.

The logic i'm thinking is just invert the if condition, so it'll first check if the field has a validation function, if it doesn't, then check if it's an object and recursively validate it.

**Comment by ProticM** [comment] 2021-12-17 18:35
Linking similar problem as described here https://github.com/backstage/backstage/issues/7577

**Comment by goenning** [comment] 2021-12-20 15:53
Yeah, it's similar, but a bit different. Today is does:

To me the solution is something like:

```
validate(form):
  for each key/value in form:
    if: does it have a custom validation? call customValidate(value) 
    else: is it an array? loop through each value and call validate again
    else: is it an object? loop through each key/value and call validate again
```

I think this would solve both the object validation issue (this) and the array validation issue (yours)

**Comment by freben** [comment] 2021-12-21 15:46
Would you like to make a pull request that works for your use case?

**Comment by karlhaworth** [comment] 2022-02-19 16:06
Still a valid issue I believe

**Comment by freben** [comment] 2022-02-21 20:22
For what it's worth, the suggested fix sounds like it makes sense!

**Comment by benjdlambert** [comment] 2022-03-21 19:49
Closing as duplicate of #8420

**Closed by benjdlambert** 2022-03-21 19:49 UTC
Labels: bug
