### ISSUE TITLE
🐛 Bug Report: SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by SuSaiGit** [backstage/backstage#22610] opened 2024-01-30 18:15 UTC
### 📜 Description

techdocs-cli --version returns error

/usr/local/lib/node_modules/@techdocs/cli/node_modules/@azure/msal-node/dist/cache/serializer/Serializer.cjs:36
                tenantProfiles: accountEntity.tenantProfiles?.map((tenantProfile) => {
                                                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@techdocs/cli/node_modules/@azure/msal-node/dist/internals.cjs:5:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

### 👍 Expected behavior

It should return version of the techdocs cli

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/26898730/70f034ce-e623-4901-9d7e-5dfc60403426)

### 👟 Reproduction steps

1. Install techdocs-cli with `sudo npm install -g @techdocs/cli`
2. `pip3 install mkdocs-techdocs-core`
3. Run `techdocs-cli --version` or `techdocs-cli --help`

### 🖥️ Your Environment

Ubuntu 22.04 WSL on Windows 11

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment] 2024-01-31 00:19
Please make sure you are running Node.js v18 or v20, as I think this may be caused by running an older node version, which we [do not support](https://backstage.io/docs/overview/versioning-policy#nodejs-releases)

**Comment by SuSaiGit** [comment] 2024-01-31 16:19
> Please make sure you are running Node.js v18 or v20, as I think this may be caused by running an older node version, which we [do not support](https://backstage.io/docs/overview/versioning-policy#nodejs-releases)

Thank you @Rugvip. It fixed my issue with upgrading NodeJS to 18

**Comment by benjdlambert** [comment] 2024-01-31 16:20
@SuSaiGit nice that it works! Going to close this issue :pray:

**Closed by benjdlambert** 2024-01-31 16:20 UTC
Labels: bug
