### ISSUE TITLE
🚀 Feature: Allow Postgresql under pluginDivisionMode='schema' to change the plugin schema name

### ISSUE THREAD

**Issue by Carho0523** [backstage/backstage#17838] opened 2023-05-17 08:55 UTC
### 🔖 Feature description

Allow Postgresql under pluginDivisionMode='schema' to change the plugin schema 

  database:
    client: pg
    prefix: 'test_prefix'
    pluginDivisionMode: schema
    connection:
      host: localhost
      port: 5432
      user: xxx
      password: xxx
    plugin:
      auth: 
        connection: 'postgresql://carho:prudential@localhost:5432/test1'
      catalog:
        connection: 'postgresql://carho:prudential@localhost:5432/test1'
      scaffolder:
        connection: 'postgresql://carho:prudential@localhost:5432/test1'
      search:
        connection: 'postgresql://carho:prudential@localhost:5432/test1'

### 🎤 Context

Our requirement is to run the backstage database within a database, but we want to be able to use the pluginId not as the name of the schema, and can customize the name of the schema

### ✌️ Possible Implementation

Maybe add an config properties to allow us to set up plugin schema name in pg database

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment] 2023-05-22 15:36
Gonna close this as a duplicate of #15914 and reopen that issue instead

**Closed by Rugvip** 2023-05-22 15:36 UTC
Labels: enhancement
