### ISSUE TITLE
Entity Registration cannot process branches with forward slash

### ISSUE THREAD

**Issue by unredundant** [backstage/backstage#4817] opened 2021-03-04 18:58 UTC
## Expected Behavior

When testing out registering a service in backstage, say on a feature branch `feature/my-awesome-feature`, the user should be able to register by passing `https://github.com/MyOrg/my-service/blob/feature/my-awesome-feature/catalog-info.yaml` to the entity registration form

## Current Behavior

Instead, the user will get the following error 

```
Unable to read url, NotFoundError: https://github.com/MyOrg/my-service/blob/feature/my-awesome-feature/catalog-info.yaml could not be read as https://api.github.com/repos/MyOrg/my-service/contents/backstage/catalog-info.yaml?ref=feature, 404 Not Found
```

`my-awesome-feature` looks as though it is being truncated from `?ref=...`

## Possible Solution

Haven't looked into it, but presumably a simple fix of just not truncating, and perhaps URL encoding the `/`?

## Steps to Reproduce

1. Create a branch with a `/` in the name
2. Attempt to register an entity on that branch in Backstage

## Context

Honestly, not a blocker, since 99/100 you are either going to have the entity registered on a scaffolding event or are going to track the head branch, _but_ for testing this can be a bit of a rough start for people trying to be onboarded to backstage. 

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): Mac (though deployed app is running ubuntu.... 18?) 
- Browser Information: Chrome

**Comment by adamdmharvey** [comment] 2021-03-04 19:00
Related, though potentially not exactly the same:
https://github.com/backstage/backstage/issues/2815

**Comment by benjdlambert** [comment] 2021-03-09 08:25
@rgbrizzlehizzle yep we're aware of this, and it's a little tricky to solve as without making a call out to the required git provider we don't know what is a branch name and what is a file path. More info can be found in the ticket @adamdmharvey mentioned and more in this one too https://github.com/IonicaBizau/git-url-parse/pull/114#issuecomment-706091677

It's not impossible, just needs some more thought on how we do this I think.

**Comment by kuangp** [comment] 2021-04-19 16:23
Wanted to add that we're also hitting this limitation to keep this issue relevant since #2815 was closed as stale.

**Comment by kiranpatel11** [comment] 2021-06-21 04:54
We are also getting this for Bitbucket Server (on-prem) while registering resource from non-default branch.

URL:  https://mybitbucket-server.company.com/projects/BS/repos/backstage/browse/catalog-info.yaml?at=docs/readme

```
This URL was not recognized as a valid GitHub URL because there was no configured integration that matched the given host name. You could try to paste the full URL to a catalog-info.yaml file instead.
```

**Comment by benjdlambert** [comment] 2021-06-21 07:00
@kiranpatel11 I don't think that yours is the same issue. I think it's down to the support in the `catalog-import` route for anything that is not Github, or Github Enterprise. 

It doesn't seem to really support much other than that at the moment - but contributions are welcome :pray:

**Comment by kuangp** [comment] 2021-08-20 13:20
unfortunately, still relevant :(

**Comment by freben** [comment] 2021-12-18 15:08
Keeping alive again. Still interested in alternative url formats - and this should probably be backed by a `parseUrl` method in [`ScmIntegrationRegistry`](https://github.com/backstage/backstage/blob/master/packages/integration/src/registry.ts#L29) and the respective integrations under it. It would have special case support for one or more custom formats, plus falling back to the `git-url-parse` that we know and hesitantly love.

**Comment by freben** [comment] 2022-01-13 21:28
Thanks. I started [experimenting briefly](https://github.com/backstage/backstage/compare/freben/url-parse?expand=1) on what a centralized parsing facility might look like, which would add support for alternative formats and might be a place to put per-provider special knowledge. But didn't get all that far.

**Comment by ShayNehmad-RecoLabs** [comment] 2022-10-14 00:07
OMG, just found this issue, it killed my last... 3 hours? 

Worth fixing 😢

**Comment by zcstellar** [comment] 2022-12-06 17:56
Would love at least a note in the docs about this. I also just lost a couple hours wondering what was going on :(

**Comment by Rugvip** [comment] 2022-12-08 11:59
Gonna close this as a duplicate of #2815, let's focus the discussion there.

**Closed by Rugvip** 2022-12-08 11:59 UTC
Labels: bug, help wanted, will-fix
