### ISSUE TITLE
🐛 Bug Report: Scaffolder Actions failing with JWTClaimValidationFailed

### ISSUE THREAD

**Issue by adityasinghal26** [backstage/backstage#25096] opened 2024-06-07 11:05 UTC
### 📜 Description

We have a backend plugin that we're using to connect with Oracle Cloud. As part of that, we have few APIs to interact with Container Registry. We're trying to run these APIs using Scaffolder Template, which are failing in the New Backend system. 

```
    - id: oci-container-repo-create
      name: Create Container Repo
      action: http:backstage:request
      input:
        name: 'backend'
        method: 'POST'
        useProxy: true
        path: /oracle-cloud/artifacts/container/repository?repositoryName=${{ parameters.name }}&compartmentName=JBApps&profile=DEFAULT
```

### 👍 Expected behavior

The template uses `http:backstage:request` (a custom action by Roadie) to trigger HTTP requests. This action uses `ctx.secrets.backstageToken` to get the logged-in user token details and pass that as `Authorization` header (refer the below snippet). This token is a base64-encoded token that decodes to the below payload data.

```
{
  "sub": "scaffolder",
  "aud": "catalog",
  "iat": 1717741358,
  "exp": 1717744739,
  "obo": "eyJ0eXAiOiJ2bmQuYmFja3N0YWdlLmxpbWl0ZWQtdXNlciIsImFsZyI6IkVTMjU2Iiwia2lkIjoiODU5YTVkMmItZTFhMC00MmRiLWE3MWEtNTFkNWFjMGI2NjNlIn0.eyJzdWIiOiJ1c2VyOmRldmVsb3BtZW50L2d1ZXN0IiwiZW50IjpbInVzZXI6ZGV2ZWxvcG1lbnQvZ3Vlc3QiXSwiaWF0IjoxNzE3NzQxMTM5LCJleHAiOjE3MTc3NDQ3Mzl9.u_zXUICc2DfTc1QvfQnYobRW08lY1kcR6dvKA4wy6EZ4csqYOJSa2tnrerD1vyZu15hHZi3gveDoTD3PwWDchA"
}
```

It's expected that `backstageToken` will be sufficient to authorize instance APIs. This is working fine for Catalog APIs (tested with `/catalog/entities/`.

### 👎 Actual Behavior with Screenshots

The requests for our Oracle Cloud plugin fails with the below error when using the `backstageToken`.

```
"error": {
        "name": "AuthenticationError",
        "message": "Invalid plugin token; caused by JWTClaimValidationFailed: unexpected \"aud\" claim value",
        "cause": {
            "code": "ERR_JWT_CLAIM_VALIDATION_FAILED",
            "name": "JWTClaimValidationFailed",
            "claim": "aud",
            "reason": "check_failed",
            "message": "unexpected \"aud\" claim value",
```

However, when I test API using Base64 token in `obo` value using Postman, my API is successful with the expected response (in this case, 500 response code).

Request:
```
curl --location 'http://localhost:7007/api/oracle-cloud/identity/tenancy?profile=DEFAULT' \
--header 'Authorization: Bearer eyJ0eXAiOiJ2bmQuYmFja3N0YWdlLmxpbWl0ZWQtdXNlciIsImFsZyI6IkVTMjU2Iiwia2lkIjoiODU5YTVkMmItZTFhMC00MmRiLWE3MWEtNTFkNWFjMGI2NjNlIn0.eyJzdWIiOiJ1c2VyOmRldmVsb3BtZW50L2d1ZXN0IiwiZW50IjpbInVzZXI6ZGV2ZWxvcG1lbnQvZ3Vlc3QiXSwiaWF0IjoxNzE3NzQxMTM5LCJleHAiOjE3MTc3NDQ3Mzl9.u_zXUICc2DfTc1QvfQnYobRW08lY1kcR6dvKA4wy6EZ4csqYOJSa2tnrerD1vyZu15hHZi3gveDoTD3PwWDchA'
```

Response:
```
{
    "error": {
        "name": "Error",
        "message": "File does not exists at ./.oci/jb-config. For more info about config file and how to get required information, see https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm for more info on OCI configuration files.",
        "stack": "Error: File does not exists at ./.oci/jb-config. For more info about config file and how to get required information, see https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm for more info on OCI configuration files.\n    at Function.parseFileFromPath (/Users/adityasinghal/Documents/github-backup/hangar7/backstage-app/lib/config-file-reader.ts:97:11)\n    at IdentityApi.getProfileConfig (/Users/adityasinghal/Documents/github-backup/hangar7/backstage-app/backstage101/node_modules/@adityasinghal26/plugin-oracle-cloud-backend/src/api/OracleCloudApi.ts:207:55)\n    at IdentityApi.getProfileConfigFromTenancy (/Users/adityasinghal/Documents/github-backup/hangar7/backstage-app/backstage101/node_modules/@adityasinghal26/plugin-oracle-cloud-backend/src/api/OracleCloudApi.ts:227:50)\n    at IdentityApi.getTenancy (/Users/adityasinghal/Documents/github-backup/hangar7/backstage-app/backstage101/node_modules/@adityasinghal26/plugin-oracle-cloud-backend/src/api/IdentityApi.ts:85:39)\n    at <anonymous> (/Users/adityasinghal/Documents/github-backup/hangar7/backstage-app/backstage101/node_modules/@adityasinghal26/plugin-oracle-cloud-backend/src/service/router.ts:35:7)"
    },
    "request": {
        "method": "GET",
        "url": "/identity/tenancy?profile=DEFAULT"
    },
    "response": {
        "statusCode": 500
    }
}
```

### 👟 Reproduction steps

1. Integrate package [@adityasinghal26/plugin-oracle-cloud-backend](https://www.npmjs.com/package/@adityasinghal26/plugin-oracle-cloud-backend) in your backend. All the steps are documented.
2. Trigger the API request to get basic details. You will need to add Authorization Header to the request which you can get from `ctx.secrets.backstageToken`.

### 📃 Provide the context for the Bug.

My intention here is to trigger my backend plugin API using Scaffolder template action. I am authenticating the REST API request with `ctx.secrets.backstageToken` which is not working. In fact, the `obo` value inside `backstageToken` is what's working with my backend plugin REST APIs. I am trying to identify if I have missed something in my backend plugin. Will be glad to receive any inputs.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment] 2024-06-10 08:34
The `http:backstage:request` action uses the old `ctx.secrets.backstageToken`, it needs to be updated to use the new `ctx.getInitiatorCredentials()` instead over here: https://github.com/RoadieHQ/roadie-backstage-plugins/blob/c62ec52707b3be39c40d240d299dba00995a3243/plugins/scaffolder-actions/scaffolder-backend-module-http-request/src/actions/run/backstageRequest.ts#L120

Since the issue isn't in this repo I'll close this, please report to the target repo instead.

**Closed by Rugvip** 2024-06-10 08:34 UTC
Labels: bug, area:scaffolder
