### ISSUE TITLE
bump `@types/node` to `16.x`

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#9724] opened 2022-02-22 10:43 UTC
We support LTS versions 14 and 16 right now, but we currently use `@types/node@14`. Let's bump the project and all references to `@types/node` to `^16.11.7`.

There might be some small changes that we have to make in the project too, with regards to extra type safety. `child.pid` can be undefined in `16` so we probably want to add some additional checking around it.

Some packages that we depend on might also need bumping to later versions if `16.x` types are not compatible.

**Comment by ismailelbadawy** [comment] 2022-02-22 11:19
I can work on this

**Comment by benjdlambert** [comment] 2022-02-22 11:25
Thanks! 🙏

**Comment by Rugvip** [comment] 2022-02-22 11:38
I think it's best if we stick to v14 of @types/node as long as long as we support Node.js v14 tbh. That way we make sure we're not using any APIs that are only supported in v16

**Comment by benjdlambert** [comment] 2022-02-22 11:43
I guess there's also the flip side that we could be using stuff in 14 that doesn't exist in 16 either, and also with 16 being the active version shouldn't we be looking more to using that?

 This is needed to fix the `openid-client` type issues as they're not compatible - but happy to explore other options in getting that library in if this is not what we should be doing.

**Comment by freben** [comment] 2022-02-22 12:44
Yeah @Rugvip see the linked openid-client PR above - the maker of that library has very intentionally taken the opposite stance of ours, if you look at their issues. They use the upper bound types of the engines they support rather than the lower bound. Performing the openid update turns out to be hairy because types travel poorly from our end over to their end. Maybe we'll get the opposite problem elsewhere if we bump ours, of course

**Comment by Rugvip** [comment] 2022-02-22 14:26
Alright, didn't realize it was to unbreak openid, let's go ahead then. It seems like a bit of a weird stance to use the highest version, but w/e, we're running tests towards 14 at least. Tbh it's not too long until we should drop support for 14 either

**Comment by freben** [comment] 2022-02-22 14:47
I actually don't really have a strong opinion, I was merely curiously wondering which solution was the least risky / bad :) But yeah it sounds reasonable to bump I think

**Comment by ismailelbadawy** [comment] 2022-02-24 17:08
There is a type issue in ``@grpc/grpc-js`` this issue was resolved in version ``1.4.5``

When i tried upgrading the ``@types/node`` package to ``16.11.7`` an issue occurred in ``@grpc/grpc-js`` which is depended on in ``backstage/plugin-kubernetes-backend`` because this depends on ``@google-cloud/container`` which depends on ``google-gax``



The issue is that the latest version of ``@google-cloud/container@2.6.0`` depends on ``google-gax@2.24.1``.

``google-gax@2.24.1`` depends on ``@grpc/grpc-js@1.3.0``

Any idea how can i go about continuing work on this issue without having to wait for a release from ``@google-cloud/container``

**Comment by benjdlambert** [comment] 2022-04-08 13:47
@ismailelbadawy personal request, can you either delete your fork of backstage and refork or pull latest changes from upstream? We had a little bit of a bug that the workflows run in the fork, so I get emails every 5 minutes of a failed workflow when it hits the rate limit :joy:

**Comment by benjdlambert** [comment] 2022-04-08 13:48
Also - closing this as it was fixed in #10558

**Closed** 2022-04-08 13:47 UTC
Labels: help wanted, version-bump
