### ISSUE TITLE
🐛 Bug Report: Error InputError - Committing the changes to feature/branchname failed. Please check that none of the files created by the template already exists

### ISSUE THREAD

**Issue by vinaykv23** [backstage/backstage#25968] opened 2024-08-09 16:13 UTC
### 📜 Description

backstage "version": "1.28.0"
Using software template creating merge requests to existing repository in gitlab
if we create merge request with new files its creating merge requests
if we create merge request with files already exists in repository its resulting in error, tried with create and update options

below is our template
https://github.com/vinaykv23/catalog-info/blob/main/catalog-info.yaml
properties:
        action:
          title: Merge action
          type: string
          default: "create"
          enum:
            - "create"
            - "update"
            - "delete"

Error
InputError

Message
Committing the changes to feature/branchname failed. Please check that none of the files created by the template already exists. HTTPError: Response code 400 (Bad Request)

### 👍 Expected behavior

it should be able to complete the gitlab merge request creation process

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/b66a4765-ff8a-4ac0-95fc-def2a961e257)

### 👟 Reproduction steps

backstage "version": "1.28.0"
Using software template creating merge requests to existing repository in gitlab
if we create merge request with new files its creating merge requests
if we create merge request with files already exists in repository its resulting in error, tried with create and update options

below is our template
https://github.com/vinaykv23/catalog-info/blob/main/catalog-info.yaml
properties:
        action:
          title: Merge action
          type: string
          default: "create"
          enum:
            - "create"
            - "update"
            - "delete"

Error
InputError

Message
Committing the changes to feature/branchname failed. Please check that none of the files created by the template already exists. HTTPError: Response code 400 (Bad Request)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment] 2024-08-12 09:45
Gonna close this as a duplicate of #16662

This is now also fixed by #25548, which will be released on Aug 20th.

**Closed by Rugvip** 2024-08-12 09:45 UTC
Labels: bug, area:scaffolder

**Comment by ddeath** [comment] 2025-01-22 10:38
@Rugvip looks like this is an issue again in newest version of backstage (1.35.0)

It was working on `1.31.2`
