### ISSUE TITLE
Provide the ability to know if any database upgrades are needed for an upgrade. 

### ISSUE THREAD

**Issue by iqbal722** [backstage/backstage#23445] opened 2024-03-07 16:09 UTC
### 🔖 Feature description

Provide the ability to know if any database upgrades are needed for an upgrade.

### 🎤 Context

1) To know if a specific upgrade will be not backwards compatible/break my integration env
2) To possibly have rollback scripts. (that can be an enhancement) 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by vinzscam** [comment] 2024-03-11 12:13
Cross linking with #6366 as the issue is very much related.

**Comment by Rugvip** [comment] 2024-03-14 09:44
Gonna close this as a duplicate of #6366

**Closed by Rugvip** 2024-03-14 09:44 UTC
Labels: enhancement
