### ISSUE TITLE
🐛 Bug Report: Impossible to list users from gitlab.com for public groups (not linked to a paid organization)

### ISSUE THREAD

**Issue by yodamad** [backstage/backstage#26438] opened 2024-09-03 15:52 UTC
### 📜 Description

Trying to use gitlab.com as authentication provider for my backstage instance, it doesn't list users because they are not `using a seat`, which is a behavior link to license on GitLab.

Here i want to use public groups to authenticate users, but they keep beeing filtered.

This is due to this filter : https://github.com/backstage/backstage/blob/3c587ef7898bf7b584dc218419d2468b472e4e12/plugins/catalog-backend-module-gitlab/src/lib/client.ts#L143

This `show_seat_info` filter should optional in my opinion

### 👍 Expected behavior

Users in the groups are correctly listed and created into db

### 👎 Actual Behavior with Screenshots

Users are not processed at all

```bash
{"class":"GitlabOrgDiscoveryEntityProvider","level":"info","message":"Scanned 0 users and processed 0 users","plugin":"catalog","service":"backstage","target":"GitlabOrgDiscoveryEntityProvider:yourProviderId","taskId":"GitlabOrgDiscoveryEntityProvider:yourProviderId:refresh","taskInstanceId":"5c0ae6c3-6ea8-4f52-bfd1-8a2eb51d3725"}
```

### 👟 Reproduction steps

Configure gitlab as provider in your app (here is the relevant info only)

```yaml
integrations:
  gitlab:
    - host: gitlab.com
      token: <TOKEN>

auth:
  environment: local
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    gitlab:
      local:
        clientId: <ID>
        clientSecret: <SECRET>
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: usernameMatchingUserEntityName

catalog:
  providers:
    gitlab:
      yourProviderId:
        host: gitlab.com
        orgEnabled: true
        group: <GROUP_PATH>
        allowInherited: true
        groupPattern: '[\s\S]*'
        schedule: # Same options as in SchedulerServiceTaskScheduleDefinition. Optional for the Legacy Backend System.
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 3 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
```

### 🖥️ Your Environment

MacOS 14
Running backstage on Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by hghtwr** [comment] 2024-09-05 20:44
@jhaals I remember this filter being implemented for SaaS users before I did my PR, so I'm not sure about the reasons for it. Guess we need to be careful🤓. 

But we got a licensed Gitlab to test both ways and I can spend some time checking it.

@yodamad Is there a public group with unlicensed users I can use to reproduce this? Or can you describe your setup in more detail?

**Comment by yodamad** [comment] 2024-09-05 21:07
@hghtwr you can try on gitlab.com/fun_with 
Let me know if you need some access on this one

**Comment by hghtwr** [comment] 2024-09-10 15:58
After first investigation it seems like this filter was introduced on purpose to avoid fetching bots from the members api: https://github.com/backstage/backstage/blob/f094dfd54a293bfe03cd00cb6dbd7f562cc26a8b/docs/releases/v1.19.0-changelog.md?plain=1#L1506

GitLab offers an actual filter for the /users endpoint to remove bots but unfortunately not for groups/members. 

Because of the side effect of making this filter optional, I would propose to investigate a bit more if there are other options before doing that.

**Comment by hghtwr** [comment] 2024-09-10 20:19
Referencing [this post](https://about.gitlab.com/pricing/licensing-faq/#who-gets-counted-in-the-subscription) I learn about another implication of this filter: 
Guest users on Gitlab SaaS Ultimate. I know companies are using Guest users for non-developers in Gitlab Ultimate as they are free of charge. These users will be filtered out on SaaS as well, right now.

**Comment by hghtwr** [comment] 2024-09-12 08:08
@jhaals @yodamad 

So, if we make this filter optional, disabling it will come with having bots & service account in the user catalog.
Project Access Tokens & Group Access Tokens can be filtered out but there are few more bot users that will remain, e.g. service accounts.

Personally, I guess it would be worth it to have a few bots in the user base instead of not processing Gitlab Free users but I don't know what other's think.

**Comment by yodamad** [comment] 2024-09-12 08:38
Thank you for investigation 

I agree as service account should not be used that much as Project / Group access token are the recommended way to authenticate, and these will be filtered as they are bots 

Even more for public projets, i don't know if service accounts are used.
And for private ones we can enable the flag to filter them

**Comment by Rugvip** [comment] 2024-09-12 10:39
👍 to adding a configuration option for toggling the behavior here unless we can find a clean way to filter, but I think it's best to keep the default behavior as is. Gonna leave this open for contributions and appreciate any help towards getting this resolved 🙏

**Comment by hghtwr** [comment] 2024-09-12 10:41
@Rugvip I can take care if it the next few days.

**Comment by jhaals** [comment] 2024-09-17 11:40
Closing this as this feature will be in the release today 👏

**Closed by jhaals** 2024-09-17 11:40 UTC
Labels: bug, help wanted, area:catalog
