### ISSUE TITLE
🐛 Bug Report: Location entity is not deleted when Component entity creation throws error with CatalogProcessor implementation

### ISSUE THREAD

**Issue by tgnanakumar** [backstage/backstage#21037] opened 2023-11-07 14:27 UTC
### 📜 Description

We've implemented a _CatalogProcessor_ which does custom validation for component name and system name, in addition to the [default rules](https://backstage.io/docs/features/software-catalog/descriptor-format/#name-required) defined by Backstage for _metadata.name_. For example, no uppercase letters, underscores and dots are allowed in our case. The validation clearly throws an error when a component is tried to register from the UI and neither a Component entity nor a Location entity is created. However, when the component is created using the [API](http://localhost:7007/api/catalog/locations) way via POST method, the component that fails on the name validation is not created but a Location entity associated/linked to this component is being created internally and not deleted automatically (rollback mechanism).

### 👍 Expected behavior

When a component or system name is created via API way and if the name validation fails after passing through the _CatalogProcessor_ implementation, then the associated/linked _Location_ entity shouldn't exist in the catalog.

### 👎 Actual Behavior with Screenshots

When a component or system name is created via API way and if the name validation fails after passing through the _CatalogProcessor_ implementation, then the associated/linked _Location_ entity is created and just lying around in the catalog.

### 👟 Reproduction steps

1. Create a custom CatalogProcessor implementation.
2. In the CatalogProcessor, override the "preProcessEntity" method to add custom validation for component and system name, and throw an error if the validation fails.
3. Create a component or system using [API](http://localhost:7007/api/catalog/locations) POST method such that the name fails in the validation.
4. Component or system entity is not created but the associated/linked Location entity is created.

### 📃 Provide the context for the Bug.

N/A

### 🖥️ Your Environment

yarn run v1.22.19
OS:   Windows_NT 10.0.22621 - win32/x64
node: v18.14.0
yarn: 1.22.19
cli:  0.23.1 (installed)
backstage:  1.18.4

Dependencies:
  @backstage/app-defaults                                          1.4.3
  @backstage/backend-app-api                                       0.5.5
  @backstage/backend-common                                        0.19.7
  @backstage/backend-dev-utils                                     0.1.1
  @backstage/backend-openapi-utils                                 0.0.4
  @backstage/backend-plugin-api                                    0.6.5
  @backstage/backend-tasks                                         0.5.10
  @backstage/catalog-client                                        1.4.4
  @backstage/catalog-model                                         1.4.2
  @backstage/cli-common                                            0.1.12
  @backstage/cli-node                                              0.1.4
  @backstage/cli                                                   0.22.13
  @backstage/config-loader                                         1.5.0
  @backstage/config                                                1.1.0
  @backstage/core-app-api                                          1.10.0
  @backstage/core-components                                       0.12.5, 0.13.5
  @backstage/core-plugin-api                                       1.6.0
  @backstage/dev-utils                                             1.0.21
  @backstage/errors                                                1.2.2
  @backstage/eslint-plugin                                         0.1.3
  @backstage/integration-aws-node                                  0.1.6
  @backstage/integration-react                                     1.1.19
  @backstage/integration                                           1.7.0       
  @backstage/plugin-api-docs                                       0.9.11      
  @backstage/plugin-app-backend                                    0.3.53      
  @backstage/plugin-app-node                                       0.1.5       
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.1.2       
  @backstage/plugin-auth-backend-module-github-provider            0.1.2       
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.2       
  @backstage/plugin-auth-backend-module-google-provider            0.1.2       
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.2       
  @backstage/plugin-auth-backend                                   0.19.2      
  @backstage/plugin-auth-node                                      0.3.2       
  @backstage/plugin-catalog-backend-module-github                  0.4.3       
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.2       
  @backstage/plugin-catalog-backend                                1.13.3      
  @backstage/plugin-catalog-common                                 1.0.16      
  @backstage/plugin-catalog-graph                                  0.2.36      
  @backstage/plugin-catalog-import                                 0.10.0      
  @backstage/plugin-catalog-node                                   1.4.6       
  @backstage/plugin-catalog-react                                  1.8.4       
  @backstage/plugin-catalog                                        1.13.0      
  @backstage/plugin-events-node                                    0.2.14      
  @backstage/plugin-github-actions                                 0.6.5       
  @backstage/plugin-github-pull-requests-board                     0.1.18      
  @backstage/plugin-home-react                                     0.1.3       
  @backstage/plugin-home                                           0.4.32, 0.5.8
  @backstage/plugin-kubernetes-backend                             0.12.2      
  @backstage/plugin-kubernetes-common                              0.6.6       
  @backstage/plugin-kubernetes                                     0.10.3      
  @backstage/plugin-org                                            0.6.14      
  @backstage/plugin-permission-common                              0.7.8       
  @backstage/plugin-permission-node                                0.7.16      
  @backstage/plugin-permission-react                               0.4.15      
  @backstage/plugin-proxy-backend                                  0.4.2       
  @backstage/plugin-scaffolder-backend                             1.17.3      
  @backstage/plugin-scaffolder-react                               1.5.5
  @backstage/plugin-scaffolder                                     1.15.0
  @backstage/plugin-search-backend-module-catalog                  0.1.9
  @backstage/plugin-search-backend-module-pg                       0.5.14
  @backstage/plugin-search-backend-module-techdocs                 0.1.9
  @backstage/plugin-search-backend-node                            1.2.9
  @backstage/plugin-search-backend                                 1.4.5
  @backstage/plugin-search-common                                  1.2.6
  @backstage/plugin-search-react                                   1.7.0
  @backstage/plugin-search                                         1.4.0
  @backstage/plugin-sentry                                         0.5.9
  @backstage/plugin-stack-overflow-backend                         0.2.9
  @backstage/plugin-stack-overflow                                 0.1.20
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.37
  @backstage/plugin-tech-insights-backend                          0.5.19
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.4.11
  @backstage/plugin-tech-insights                                  0.3.16
  @backstage/plugin-tech-radar                                     0.6.8
  @backstage/plugin-techdocs-backend                               1.7.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.0
  @backstage/plugin-techdocs-node                                  1.8.2
  @backstage/plugin-techdocs-react                                 1.1.11
  @backstage/plugin-techdocs                                       1.7.0
  @backstage/plugin-user-settings                                  0.7.10
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.3
  @backstage/theme                                                 0.2.18, 0.3.0, 0.4.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.5

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment] 2023-11-07 15:09
This works as intended. If you POST a location, there's no initial validation step. The frontend does a dry-run first to ensure that the pointed-to data is correct, and that's a separate operation. If you want to mimic that, you'll need to copy what it does.

As a separate note, you shouldn't write a dedicated processor to alter the name rules. You should pass in a custom validator to your catalog builder in the backend instead:

```ts
  builder.setFieldFormatValidators(makeValidator({
    isValidEntityName: v => ...
  }))
```

[here is the default implementation](https://github.com/backstage/backstage/blob/1f9525bd7ac72bf63fac2b9bb6a801ba7a278730/packages/catalog-model/src/validation/KubernetesValidatorFunctions.ts#L47).

**Comment by freben** [comment] 2023-11-07 15:09
closing this as working as intended

**Closed by freben** 2023-11-07 15:09 UTC
Labels: bug, area:catalog

**Comment by tgnanakumar** [comment] 2023-11-07 17:50
> As a separate note, you shouldn't write a dedicated processor to alter the name rules. You should pass in a custom validator to your catalog builder in the backend instead

@freben Well! We're not creating a dedicated processor but created our own _custom validator_ that implements _CatalogProcessor_ as shown in below code snippet. Are we following and passing the custom validator to catalog builder as it is supposed to be, or are we doing something differently here? Please advise or comment.

_backend > src > plugins > catalog.ts_
```
export default async function createPlugin(env: PluginEnvironment): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(new MyCustomNameValidator());
  . . . . .
  . . . . .
  . . . . .
```

_backend > src > processors > myCustomNameValidator.ts_
```
export class MyCustomNameValidator implements CatalogProcessor {
  . . . . .
  . . . . .
  . . . . .
  async preProcessEntity(entity: Entity): Promise<Entity> {
    if (entity.kind.toLowerCase() === 'component') {
        if (!whitelistPattern.test(entityName) {
          // my name validator logic
          . . . . .
          . . . . .
          . . . . .
          throw new Error(`Invalid component name!`);
        }
    }
    return entity;
  }
}
```

**Comment by freben** [comment] 2023-11-07 19:01
No I meant that to change the validation rules for the existing central fields (the name in this case), you _don't_ make a `CatalogProcessor` at all - you call `setFieldFormatValidators` as I showed above and give the adjusted validator callback.

The validation step is also _after_ the preProcess step; when your current checker runs, it may be too soon; other processors may sneak in and still modify the name to something illegal after you've done your check.

**Comment by tgnanakumar** [comment] 2023-11-07 19:22
> you call `setFieldFormatValidators` as I showed above and give the adjusted validator callback

@freben Yes, in fact tried something similar as given below. As we understand `isValidEntityName` validates for all entities, but in our case we want the custom name validation to happen only for 'component' and 'system' kind. Are we missing something?

```
builder.setFieldFormatValidators(
  makeValidator({
    isValidEntityName: value => {
      return (
        typeof value === 'string' &&
        value.length >= 1 &&
        value.length <= 63 &&
        /^([a-z0-9][-a-z0-9]*)?[a-z0-9]$/.test(value)
      );
    },
  }),
);
```

**Comment by freben** [comment] 2023-11-07 19:28
Hm ok. It's unfortunate then that the contextual entity isn't present in the callback.

OK then, do the check in postProcess instead then. But you'll only be able to restrict to a subset of the builtin checks - you won't be able to make these more forgiving than the builtins.

**Comment by tgnanakumar** [comment] 2023-11-07 20:00
> OK then, do the check in postProcess instead then.

Thank you for confirming! 👍🏻

> The validation step is also after the preProcess step; when your current checker runs, it may be too soon; other processors may sneak in and still modify the name to something illegal after you've done your check.

By the way, if I interpret this correctly, this indicates the same as your previous comment, that is to do my name check in _preProcessEntity()_ method. Am I correct in my understanding over here?

**Comment by tgnanakumar** [comment] 2023-11-09 15:19
> Your processor will only be "in addition to" the builtin one.

Got it! 👍🏻

> If you POST a location, there's no initial validation step. The frontend does a dry-run first to ensure that the pointed-to data is correct, and that's a separate operation. If you want to mimic that, you'll need to copy what it does.

@freben On this point, we have users/systems that will create components and systems into Backstage catalog using [API](http://localhost:7007/api/catalog/locations) way via POST method. To prevent the creation of an associated _Location_ entity for components that fail in the name validation which we will implement inside _postProcessEntity()_, we could think of 2 approaches to handle this. One, as you mentioned, is to mimic the frontend behaviour by running a dry-run and checking the success status before invoking an actual POST by all the clients (users/systems) that create components via API. The other is to handle manually by deleting the associated Location entity as part of the name validation implementation we write inside _postProcessEntity()_. Please share your comments or thoughts.

Or better, is there any other Backstage API endpoint that we can make use of in registering components and systems, than using [Locations](http://localhost:7007/api/catalog/locations) endpoint?
