### ISSUE TITLE
💬 RFC: Add handling for relative paths as placeholders in PlaceholderProcessor

### ISSUE THREAD

**Issue by rewixe** [backstage/backstage#25067] opened 2024-06-05 10:42 UTC
### 🔖 Need

We have a backstage template where we want to make reference to another YAML file. We are currently making reference to this file by using the URL as a placeholder. We are trying to use a relative path instead but this is not working as PlaceholderProcessor does not seem to support relative paths.

### 🎉 Proposal

I want to update PlaceholderProcessor, and any other files involved in processing placeholders, such that we can pass in relative paths as placeholders in the template the same way we would pass in URLs.

### 〽️ Alternatives

We could continue to exclusively use URLs instead of relative paths as we are not aware of any way of handling relative paths currently.

### ❌ Risks

There is a risk that allowing relative paths will have a knock on effect on other parts of the code, so we will need to perform testing to ensure that the impact of any change is restricted to allowing relative paths to be used as placeholders

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment] 2024-06-10 08:57
Thank you for reporting!

I'm gonna close this as a duplicate of #14372 so that we continue the discussion there to keep it all in one place. I'll reopen the issue so that you can chime in with a proposed solution. We do need to make sure it's done in a secure way though, all constraints should be in the other issue.

**Closed by Rugvip** 2024-06-10 08:57 UTC
Labels: rfc
