### ISSUE TITLE
npx @backstage/create-app and then empty screen and javascript error

### ISSUE THREAD

**Issue by jotka** [backstage/backstage#12784] opened 2022-07-22 07:19 UTC
## Expected Behavior

I would like to have an empty instance to play with.

## Actual Behavior

an empty screen and javascript error

![image](https://user-images.githubusercontent.com/2701356/180385127-0cc68935-52eb-43e8-8616-f3ee16c8c9d9.png)

## Steps to Reproduce

1. npx @backstage/create-app
2. cd myapp && yarn dev
3. open [localhost:3000](http://localhost:3000)

## Your Environment

- Browser Information: Safari 15.5 on MacOS 12.4 -->

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.5.0 - darwin/arm64
node: v16.16.0
yarn: 1.22.19
cli:  0.18.0 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.4
  @backstage/backend-common                        0.14.1
  @backstage/backend-plugin-api                    0.1.0
  @backstage/backend-tasks                         0.3.3
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.0
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.4
  @backstage/core-components                       0.10.0
  @backstage/core-plugin-api                       1.0.4
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.2
  @backstage/integration                           1.2.2
  @backstage/plugin-api-docs                       0.8.7
  @backstage/plugin-app-backend                    0.3.34
  @backstage/plugin-auth-backend                   0.15.0
  @backstage/plugin-auth-node                      0.2.3
  @backstage/plugin-catalog-backend                1.3.0
  @backstage/plugin-catalog-common                 1.0.4
  @backstage/plugin-catalog-graph                  0.2.19
  @backstage/plugin-catalog-import                 0.8.10
  @backstage/plugin-catalog-node                   1.0.0
  @backstage/plugin-catalog-react                  1.1.2
  @backstage/plugin-catalog                        1.4.0
  @backstage/plugin-github-actions                 0.5.7
  @backstage/plugin-org                            0.5.7
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.3
  @backstage/plugin-permission-react               0.4.3
  @backstage/plugin-proxy-backend                  0.2.28
  @backstage/plugin-scaffolder-backend             1.4.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.4.0
  @backstage/plugin-search-backend-module-pg       0.3.5
  @backstage/plugin-search-backend-node            1.0.0
  @backstage/plugin-search-backend                 1.0.0
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.0
  @backstage/plugin-search                         1.0.0
  @backstage/plugin-tech-radar                     0.5.14
  @backstage/plugin-techdocs-backend               1.2.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.2
  @backstage/plugin-techdocs-node                  1.2.0
  @backstage/plugin-techdocs-react                 1.0.2
  @backstage/plugin-techdocs                       1.3.0
  @backstage/plugin-user-settings                  0.4.6
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
✨  Done in 1.06s.

```

**Comment by benjdlambert** [comment] 2022-07-22 12:49
Closing this as duplicate of #6039

**Closed by benjdlambert** 2022-07-22 12:49 UTC
Labels: bug
