### ISSUE TITLE
🐛 Bug Report: Basic search feature is not working consistently

### ISSUE THREAD

**Issue by mist3r3** [backstage/backstage#14402] opened 2022-11-02 08:12 UTC
### 📜 Description

Hi, so I'm succesfully running on production from a docker-compose (one with backstage docker, the one given in the website, and one for postgres).
But I have this issue only with the search plugin. when researching I'm receiving 304 status code (instead of 200 locally with an answer).

Any idea what could cause this issue?
(I'm using multiple plugins like github-pr, teamcity and no issues there).

PS1: So I didn't really investigate, but sometimes the search is working correctly... But most of the time it doesn't... It seems like a bug to me.

What I did is run yarn dev locally. It was working. I restarted it and now it doesn't work anymore I have this kind of messages in the backlog:

`"GET /api/search/query?term=test HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" type=incomingRequest`

### 👍 Expected behavior

Search bar to work all of the time without delays or without any inconsistencies

### 👎 Actual Behavior with Screenshots

When I search for some items it doesn't show anything:
![image](https://user-images.githubusercontent.com/16564723/199432976-11d83a2b-1ed3-4637-8562-27415a69326b.png)

I also have this error (not showing everytime):
`
{"level":"error","message":"Missing index for software-catalog. This could be because the index hasn't been created yet or there was a problem during index creation.","name":"MissingIndexError","service":"backstage","stack":"MissingIndexError: Missing index for software-catalog. This could be because the index hasn't been created yet or there was a problem during index creation.\n    at LunrSearchEngine.query (/app/node_modules/@backstage/plugin-search-backend-node/dist/index.cjs.js:426:13)\n    at /app/node_modules/@backstage/plugin-search-backend/dist/index.cjs.js:246:67\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /app/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /app/node_modules/express-promise-router/lib/express-promise-router.js:64:7\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)","type":"errorHandler"}
`

Or this:
`
{"body":{"error":{"message":"Request failed with status 404 Not Found","name":"Error"},"response":{"statusCode":404}},"cause":{},"level":"error","message":"Request failed with 404 Error","name":"ResponseError","plugin":"search","response":{"size":0,"timeout":0},"service":"backstage","stack":"ResponseError: Request failed with 404 Error\n    at Function.fromResponse (/app/node_modules/@backstage/errors/dist/index.cjs.js:151:12)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CatalogClient.requestRequired (/app/node_modules/@backstage/catalog-client/dist/index.cjs.js:243:13)\n    at async CatalogClient.getEntities (/app/node_modules/@backstage/catalog-client/dist/index.cjs.js:72:22)\n    at async DefaultCatalogCollatorFactory.execute (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1009:25)\n    at async next (node:internal/streams/from:85:11)","task":"search_index_software_catalog","type":"taskManager"}
`

I restarted it, waiting for around 10min, played with the search field and it came back.

### 👟 Reproduction steps

1. Start the backstage app
2. Try to search directly from the search bar.
3. Restart and do it again.

### 📃 Provide the context for the Bug.

I'm just trying to have a simple search bar working.

### 🖥️ Your Environment

I'm using postgres running on docker.

`OS:   Darwin 21.6.0 - darwin/arm64
node: v16.16.0
yarn: 1.22.10
cli:  0.20.0 (installed)
backstage:  1.7.0

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-common                        0.15.2
  @backstage/backend-plugin-api                    0.1.3
  @backstage/backend-tasks                         0.3.6
  @backstage/catalog-client                        1.1.1
  @backstage/catalog-model                         1.1.2
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0
  @backstage/config-loader                         1.1.5
  @backstage/config                                1.0.3
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.11.2
  @backstage/core-plugin-api                       1.0.7
  @backstage/dev-utils                             1.0.7
  @backstage/errors                                1.1.2
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.3.2
  @backstage/plugin-api-docs                       0.8.10
  @backstage/plugin-app-backend                    0.3.37
  @backstage/plugin-auth-backend                   0.17.0
  @backstage/plugin-auth-node                      0.2.6
  @backstage/plugin-catalog-backend-module-openapi 0.1.3
  @backstage/plugin-catalog-backend                1.5.0
  @backstage/plugin-catalog-common                 1.0.7
  @backstage/plugin-catalog-graph                  0.2.22
  @backstage/plugin-catalog-import                 0.9.0
  @backstage/plugin-catalog-node                   1.2.0
  @backstage/plugin-catalog-react                  1.2.0
  @backstage/plugin-catalog                        1.6.0
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-permission-common              0.7.0
  @backstage/plugin-permission-node                0.7.0
  @backstage/plugin-permission-react               0.4.6
  @backstage/plugin-proxy-backend                  0.2.31
  @backstage/plugin-scaffolder-backend             1.7.0
  @backstage/plugin-scaffolder-common              1.2.1
  @backstage/plugin-scaffolder                     1.7.0
  @backstage/plugin-search-backend-module-pg       0.4.1
  @backstage/plugin-search-backend-node            1.0.3
  @backstage/plugin-search-backend                 1.1.0
  @backstage/plugin-search-common                  1.1.0
  @backstage/plugin-search-react                   1.2.0
  @backstage/plugin-search                         1.0.3
  @backstage/plugin-sonarqube-backend              0.1.2
  @backstage/plugin-sonarqube                      0.4.2
  @backstage/plugin-tech-radar                     0.5.17
  @backstage/plugin-techdocs-backend               1.4.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.4.1
  @backstage/plugin-techdocs-react                 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-user-settings                  0.5.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by emmaindal** [comment] 2022-11-14 08:19
Hello @mist3r3 thanks for opening this issue. 

> I restarted it, waiting for around 10min, played with the search field and it came back.

As the search require the indexing processes to finish before it has any index to search for I wonder if that is the issue you run into.

This is a natural behaviour but maybe we can improve the user experience of it? Do you have any suggestions?

**Comment by mist3r3** [comment] 2022-11-16 10:00
Hi, yes so locally it seems it takes some time to get the info, I feel there is a bug though when I'm deploying it. I'm using a different path like mydomain/backstage.

In that case the indexing is not happening.
`
{"body":{"error":{"message":"Request failed with status 404 Not Found","name":"Error"},"response":{"statusCode":404}},"cause":{},"level":"error","message":"Request failed with 404 Error","name":"ResponseError","plugin":"search","response":{"size":0,"timeout":0},"service":"backstage","stack":"ResponseError: Request failed with 404 Error\n    at Function.fromResponse (/app/node_modules/@backstage/errors/dist/index.cjs.js:151:12)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async CatalogClient.requestRequired (/app/node_modules/@backstage/catalog-client/dist/index.cjs.js:243:13)\n    at async CatalogClient.getEntities (/app/node_modules/@backstage/catalog-client/dist/index.cjs.js:72:22)\n    at async DefaultCatalogCollatorFactory.execute (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1009:25)\n    at async next (node:internal/streams/from:85:11)","task":"search_index_software_catalog","type":"taskManager"}
{"level":"debug","message":"task: search_index_software_catalog will next occur around 2022-11-16T09:34:55.863+00:00","plugin":"search","service":"backstage","task":"search_index_software_catalog","type":"taskManager"}
{"level":"info","message":"127.0.0.1 - - [16/Nov/2022:09:24:55 +0000] \"GET /api/catalog/entities?filter=metadata.annotations.backstage.io%2Ftechdocs-ref&fields=kind,namespace,metadata.annotations,metadata.name,metadata.title,metadata.namespace,spec.type,spec.lifecycle,relations&offset=0&limit=500 HTTP/1.1\" 404 - \"-\" \"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)\"","service":"backstage","type":"incomingRequest"}
{"documentType":"techdocs","level":"error","message":"Collating documents for techdocs failed: ResponseError: Request failed with 404 Error","plugin":"search","service":"backstage","type":"plugin"}
`

you see that it tries to GET from /api/catalog/entities instead of /backstage/api/entities...

Thanks

**Comment by emmaindal** [comment] 2022-11-22 10:49
Thanks for providing that extra context @mist3r3, I've seen a similar issue reported on Discord the last week. Can you verify this issue is only happening when updating the `app.baseUrl` and the `backend.baseUrl` in your app-config.yaml?

**Comment by stephanschielke** [comment] 2022-11-22 14:31
Just sharing the solution to a similar symptom:
We too saw the `Missing index for software-catalog. This could be because the index hasn't been created yet or there was a problem during index creation.` message. 

We adjusted our search index scheduler settings:
```
  const schedule = env.scheduler.createScheduledTaskRunner({
    frequency: { minutes: 15 },
    timeout: { minutes: 15 },
    // A 3 second delay gives the backend server a chance to initialize before
    // any collators are executed, which may attempt requests against the API.
    initialDelay: { seconds: 3 },
  });
```
and confirmed the successful run by querying `backstage_backend_tasks__tasks`,
but without success.

We noticed the problem occurred after upgrading to 1.8.0 and switching to node 18.
While debugging certain context objects we noticed the `internalBaseUrl` didn't contain a host.
```
export declare class SingleHostDiscovery implements PluginEndpointDiscovery {
    private readonly internalBaseUrl;
    private readonly externalBaseUrl;
```
After changing our app-config to:
```
backend:
  listen:
    port: 7007
    host: 0.0.0.0
```
the indexer was able to create an index.

I feel the `Missing index for software-catalog` message is accurate, though couldn't find a single log line indicating the search index failed with an Invalid URL exception.

Hope this helps someone.

**Comment by jerroydmoore** [comment] 2022-12-13 01:43
I'm upgrading to v1.8.3 and was getting similar errors. It looks like 8646067e071462bfe2a70cb967edbc3770b154f0 fixes should fix the issue once the next release is cut.

**Comment by iamEAP** [comment] 2023-01-02 14:45
Thanks for the report and the linked [PR](https://github.com/backstage/backstage/pull/14873), y'all!  My recommendation if you are still encountering this is to upgrade to Backstage v1.9.0.

If you still see this issue after upgrading, feel free to re-open this issue.  Closing for now, though!

**Closed by iamEAP** 2023-01-02 14:45 UTC
Labels: bug, search

**Comment by markandersontrocme** [comment] 2023-01-04 20:19
@iamEAP I upgraded to `1.9.1` and everytime we deploy Backstage to Kubernetes (pods are recreated) the entire catalog gets re-indexed, and it takes about 10-15min for the search to be fully working...

![image](https://user-images.githubusercontent.com/16004416/210642512-71cf1662-12c6-4d28-a13e-9c1b22edf762.png)

**Comment by iamEAP** [comment] 2023-01-04 20:55
That's familiar! It sounds like you are using the Lunr search engine in combination with Kubernetes, which is not recommended. Lunr's index only exists in-memory, so any auto-scaling or deployment behavior will adversely affect the index state.

The solution is to move to a production-ready search engine (like Elasticsearch, or Postgres search is supported as well), which will move that index state out of the backend app process.

**Comment by markandersontrocme** [comment] 2023-01-04 21:15
Ah I missed that when setting up my Backstage instance... Thanks so much will implement that ASAP :)
