### ISSUE TITLE
Disable menu UnregisterEntity

### ISSUE THREAD

**Issue by prasaria** [backstage/backstage#6316] opened 2021-07-02 09:27 UTC
Hello, I want to make `Unregister Entity` menu can be disabled by adding optional props to the Menu Item component
<img width="1677" alt="Screen Shot 2021-07-02 at 16 10 56" src="https://user-images.githubusercontent.com/7909323/124251570-449df000-db50-11eb-9bea-3858f82efb6b.png">

Currently my solution is to add optional props into `EntityContextMenu` component and this props will be passed down from EntityPage --> EntityLayout --> EntityContextMenu.

I want to get feedback before I raise my code into a PR. So what do you guys think about my approach here?

This is example of the code : 
**`EntityContextMenu.ts`**

```typescript
type Props = {
  UNSTABLE_extraContextMenuItems?: ExtraContextMenuItem[];
  onUnregisterEntity: () => void;
  disableUnregisterEntity?: boolean;
};

export const EntityContextMenu = ({
  UNSTABLE_extraContextMenuItems,
  onUnregisterEntity,
  disableUnregisterEntity,
}: Props) => {
  const [anchorEl, setAnchorEl] = useState<HTMLButtonElement>();
  const classes = useStyles();

  const onOpen = (event: React.SyntheticEvent<HTMLButtonElement>) => {
    setAnchorEl(event.currentTarget);
  };

  const onClose = () => {
    setAnchorEl(undefined);
  };

  const extraItems = UNSTABLE_extraContextMenuItems && [
    ...UNSTABLE_extraContextMenuItems.map(item => (
      <MenuItem
        key={item.title}
        onClick={() => {
          onClose();
          item.onClick();
        }}
      >
        <ListItemIcon>
          <item.Icon fontSize="small" />
        </ListItemIcon>
        <ListItemText primary={item.title} />
      </MenuItem>
    )),
    <Divider key="the divider is here!" />,
  ];

  const disableUnregister = disableUnregisterEntity ?? false;
  return (
    <>
      <IconButton
        aria-label="more"
        aria-controls="long-menu"
        aria-haspopup="true"
        onClick={onOpen}
        data-testid="menu-button"
        className={classes.button}
      >
        <MoreVert />
      </IconButton>
      <Popover
        open={Boolean(anchorEl)}
        onClose={onClose}
        anchorEl={anchorEl}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
        transformOrigin={{ vertical: 'top', horizontal: 'right' }}
      >
        <MenuList>
          {extraItems}
          <MenuItem
            onClick={() => {
              onClose();
              onUnregisterEntity();
            }}
            disabled={disableUnregister}
          >
            <ListItemIcon>
              <Cancel fontSize="small" />
            </ListItemIcon>
            <ListItemText primary="Unregister entity" />
          </MenuItem>
        </MenuList>
      </Popover>
    </>
  );
};
```

**Comment by freben** [comment] 2021-07-02 11:56
Hi!

There are two candidate mechanisms we could latch on to for this, so it could be implemented without needing any custom props.

- There's the [readonly config param](https://github.com/backstage/backstage/blob/375f5c3f01c2ced5e91e80141dd88c61f5699eb5/plugins/catalog-backend/config.d.ts#L57), which governs whether the catalog backend accepts modifying user actions or not. Currently it's only available in the backend (it has no `@visibility frontend`), but that could be reconsidered I guess.
- There's the [`create-component` route ref](https://github.com/backstage/backstage/blob/375f5c3f01c2ced5e91e80141dd88c61f5699eb5/plugins/catalog/src/components/CreateComponentButton/CreateComponentButton.tsx#L24) which, when not supplied to the catalog plugin, makes sure that the create component button isn't rendered.

I'm thinking that the second one could be used here with the same logic. If users aren't allowed to register things, then maybe they shouldn't be allowed to unregister them either. So that would be a two-line copy-paste essentially (not quite, but not much more, just making sure the menu item isn't rendered). Would you like to contribute that?

**Comment by Crevil** [comment] 2021-07-03 08:10
I agree woth @freben on using the same mechanism. The readonly config param was scoped for the backend as the frontend could be configured in a more granular way.

Does the new catalog processor handle deletes when eg. bootstrap locations are removed?

**Comment by freben** [comment] 2021-07-03 08:44
@Crevil Yeah the intent is that when unregistering, the entity itself and its descendants (other entities that spawned as a side effect of it, eg when registering a Location enyity) are eagerly deleted from the catalog.

**Comment by Crevil** [comment] 2021-07-03 09:51
What I was wondering is: If we disable this menu item, will unmanaged entities still be removed?

I seem to remember that the old catalog engine would not "garbage collect" entities, so we had to use this menu item to clean up if entites were removed in an upstream bootstrap location. I just wanted to make sure that this is no longer relevant and thus removing the item is safe.

**Comment by freben** [comment] 2021-07-03 12:10
Right. The proposed solution fits really static use cases.

Regard the set of entities as a graph where the roots are registered or config-declared things, while inner nodes are locations and entities that spawn from that.

`registered location A -> location entity yaml B -> component entity yaml C`

If you make changes to the yaml file B such that C is no longer referenced, C will NOT be removed eagerly but instead marked as orphaned using [the `backstage.io/orphan` annotation](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/next/stitching/Stitcher.ts#L155). This is by design.

So your point is good - maybe the menu entry should remain, but the dialog made aware of refusing to delete or unregister things that corresponds to actual registered locations, when the route ref in question is not set

**Comment by Crevil** [comment] 2021-07-03 12:34
Makes sense, I do however see the value of having the option available and letting it be up to the operator to decide whether they want users to be able to remove such orphaned entities. 🧐

**Comment by andrewthauer** [comment] 2021-07-04 11:38
I'm not sure I agree about disabling the button when the `create-component` route is not registered. This route hosts the scaffolder home page which isn't the only way to register components. You can also go directly to the `catalog-import` route. For instance, we've currently removed links to the create page since we haven't focused on the scaffolder yet. Instead we have an `Import` sidebar button.

**Comment by prasaria** [comment] 2021-07-05 01:20
Hello,sorry for late reply here.

I see there are some discussion about what is the correct way to disable.

For a little bit of context here, my company want to restrict user for doing deletion, and just want to limit this to specific teams only. In the future we want to apply some kind of role based authorization but I guess for now it is nice if we can have an option whether we want to disable the unregister menu or not.

Yes ,  I want to contribute for this issue, but do we agree to use the approach that @freben proposed here ?

**Comment by andrewthauer** [comment] 2021-07-05 21:49
I personally don't feel it's appropriate to assume that entities shouldn't be unregistered based on this existence of the route ref alone. However, I'm not completely opposed to it either. 

If this approach was used we would end up adding the route ref back and probably building a custom catalog index page to hide the create button from there (which is now possible). However, I'd rather not have to go down this route.

As for other solutions I'm not entirely sure. A specific configuration setting could also work, but that might become obsolete if and when something f like RBAC on operations is supported.

**Comment by freben** [comment] 2021-07-06 07:43
Yeah totally agree that this is all a bit awkward.

The RIGHT solution is probably composability, where you can replace and redesign this part of the page at will using JSX. But assuming, then, that this is the layer where we want customisability to be, would it make sense to instead have an options prop that drills through the layers, while waiting for something better? Maybe it's both more visible and less "polluting" than the other ideas?

There is one more place where this menu has bitten us. When the first plugin appeared that wanted to add itself to that same menu, we admitted defeat and added [an unstable prop](https://github.com/backstage/backstage/blob/9b743a33b89e7a1b60877a9f1a05de75f700fe13/packages/app/src/components/catalog/EntityPage.tsx#L127) while waiting for the right solution to appear. Maybe we should do the same here.

```
<EntityLayout UNSTABLE_contextMenuOptions={{ disableUnregister: true }}>
  ...  
```

or something like that? It could also hold an `additionalItems` key that covers the previous prop's use case.

**Comment by benjdlambert** [comment] 2021-07-08 14:48
Does anyone want to pick this up? 🙏

**Comment by prasaria** [comment] 2021-07-12 03:53
Hello, sorry I've been away last week, yes I want to pick this issue. Thank you

**Comment by prasaria** [comment] 2021-07-12 09:50
I already made a PR : https://github.com/backstage/backstage/pull/6438.. Thank You

**Comment by freben** [comment] 2021-07-19 18:06
Closing since the linked PR is merged. Feel free to reopen if this is a mistake.

**Closed by freben** 2021-07-19 18:06 UTC
