### ISSUE TITLE
Scaffolder does not work when Backstage API requires auth

### ISSUE THREAD

**Issue by erikxiv** [backstage/backstage#5041] opened 2021-03-21 14:42 UTC
## Expected Behavior

* One can create new entities using the scaffolder, via the `/create` page, with a backend that requires token authorization of api requests

## Current Behavior

* The scaffolder plugin will not work in its current state if the backstage API is protected behind token auth, breaking with a 401 when trying to register the new entity using the catalog API
* (Running the latest code in master, which seems to use the v2 api of the scaffolder)

```
2021-03-21T14:02:50.845Z Beginning step Register
2021-03-21T14:02:50.852Z info: Registering https://github.example.com/ab/template-test/blob/master/catalog-info.yaml in the catalog {"timestamp":"2021-03-21T14:02:50.849Z"}
2021-03-21T14:02:50.856Z Error: Unauthorized
    at CatalogClient.addLocation (/usr/src/app/node_modules/@backstage/catalog-client/dist/index.cjs.js:53:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.handler (/usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:945:22)
    at async TaskWorker.runOneTask (/usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2181:11)
    at async /usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2122:9
```

## Possible Solution

* The catalog request at https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/catalog/register.ts#L98 needs to provide a auth token as the second parameter
  * Pass on the token from the user requesting the template creation. With the current scaffolder design (v2) that likely means storing the token alongside the task specification in the database to be able to retrieve it when the action is later executed
  * Have the scaffolder backend issue its own token (see https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/google/provider.ts#L164 for a possible example)

## Steps to Reproduce

1. Follow instructions in https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md on how to require authentication of the backstage api
2. Start backstage and use the UI to create a new entity using the scaffolder
3. The error above should appear when trying to register the new entity

## Context

Since we protect our Backstage API using the token auth method, the scaffolder does not work. This is sad as we would like to start using it.

See also https://github.com/backstage/backstage/issues/5039 which has the same problem, although not as critical

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): alpine
- Browser Information: Chrome

**Comment by codingdiaz** [comment] 2021-06-29 21:46
We are experiencing this same issue currently. Software templates are a core feature we are ready to implement but, this unfortunately is blocking us.

**Comment by erikxiv** [comment] 2021-06-29 21:58
Fixed by #5202

**Comment by codingdiaz** [comment] 2021-07-02 15:37
We are still having authentication issues in this scenario. For example, loading the `/create/actions` page gives us a 500 error. 

I think auth needs to be passed to that page as well?https://github.com/backstage/backstage/blob/47dac4081978cfa66ab6f5035b1191c67b6ebb9c/plugins/scaffolder/src/api.ts#L246-L256

We also get a 401 to an eventstream endpoint. 

![Screen Shot 2021-07-02 at 8 46 50 AM](https://user-images.githubusercontent.com/20445982/124298104-dc3c1800-db29-11eb-97cf-cf9d10360563.png)

https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/api.ts#L193

**Comment by benjdlambert** [comment] 2021-07-05 07:58
Hmmm, so for the two use cases I can see, it looks like they are not using the Authorization Header forwarding, which is going to be a little troublesome for the `EventSource` use case as there is no support for headers in the default `EventSource` implementation in the browser.

We could use another implementation which does support headers like: https://github.com/EventSource/eventsource or I wonder if we could make the `idToken` available in a cookie which gets forwarded with `withCredentials`

I haven't really played around with this authorization middleware so much, but I'll have a little play around today to see what I can find out.

**Comment by benjdlambert** [comment] 2021-07-05 08:07
Looking at this: https://github.com/whatwg/html/issues/2177 looks like support for Headers in EventSource might not be coming any time soon, there is the option to use ReadableStreams and `fetch` to apply the headers which seems like a pretty insane solution and something we don't really want to maintain just because of the header https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams

**Comment by codingdiaz** [comment] 2021-07-05 14:13
@benjdlambert thanks for taking a look! I have a colleague who forked the scaffolder frontend to get this working for us to propose a change. We are on holiday today but, I wanted to see if something like this would be acceptable? We were unsure how the backstage team would feel about polyfill. Currently we have a working fork of the scaffolder plugin doing something like...

``` 
import { EventSourcePolyfill } from 'event-source-polyfill';
const eventSource = new EventSourcePolyfill(url, {
              withCredentials: true,
              headers: token ? { Authorization: `Bearer ${token}` } : {},
            });
```

There is also a small change for `/create/actions` (https://github.com/backstage/backstage/blob/47dac4081978cfa66ab6f5035b1191c67b6ebb9c/plugins/scaffolder/src/api.ts#L246-L256)

```
 async listActions() {
    const token = await this.identityApi.getIdToken(); // grab the id token
    const baseUrl = await this.discoveryApi.getBaseUrl("scaffolder");
    const response = await fetch(`${baseUrl}/v2/actions`, {
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    }); // pass the token with the Authorization header
    if (!response.ok) {
      throw ResponseError.fromResponse(response);
    }
    return await response.json();
  }
```

**Comment by benjdlambert** [comment] 2021-07-05 16:21
@codingdiaz yep - so I was looking through the code a little bit, and it looks like the Cookie middleware should decorate the request to the backend plugin with the header from the Cookie and that seems broken right now. I think it's to do with the path from my testing.

You're right that the `listActions` will definitely need to include the credentials as it currently doesn't, we can do this both with the header explicitly and with `credentials: 'include'`.

@erikxiv from my testing it looks like the cookie is not passed to all backend requests, if I change this https://github.com/backstage/backstage/blame/master/contrib/docs/tutorials/authenticate-api-requests.md#L35 to `*` instead, it seems to work, is this something that should be there or am I hacking around? I'm afraid I don't have so much knowledge when it comes to cookies and especially if this is secure or not.

**Comment by erikxiv** [comment] 2021-07-05 17:22
Sorry for my slow response - I've been meaning to find some time to reproduce the issue with latest from master but have not gotten there yet. My quick gut response is:

* The proposed change to `listActons` looks right to me, adding the token to the `Authorization` header. I am a bit confused by the 500 status though - if the initial request is blocked due to authorization, it should receive a 401. Might be that a secondary request after that fails in the backend somewhere?
* I got eventstream to work before by using the cookie workaround. I went down the same path as you did, looking for other auth mechanisms, but considered the alternatives to be too messy for now. By simply setting a token cookie on login/refresh, that should be forwarded on eventstream requests as well. Not sure if something has changed to make this not work? Note that setting and accepting the cookie as auth is done by the custom code [specified in the contrib section](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md), but you seem to be aware of this.
* Setting the cookie path to `/` ought to send the cookie on all requests as far as I understand. This is an optional field though, feel free to remove it and see if it makes any difference.

I will try to find some time to help out soonish, but no promises during vacation ;)

**Comment by erikxiv** [comment] 2021-07-05 21:36
PR on the list actions auth: https://github.com/backstage/backstage/pull/6346 (The UI displays `ERROR 500: Failed to load installed actions` although the network request responds with a `401`)

When trying locally with latest from master and cookie added as per https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md eventstream works for me. E.g. I use a template, can view task logs being streamed back and can see a 200 OK as response status on the eventstream request. Could you try logging out/in again and then verify if the cookie is set and sent on all non-xhr requests?

**Comment by benjdlambert** [comment] 2021-07-06 08:05
@erikxiv thanks for addition on the `listActions` stuff, that will definately be needed, I will also confirm that the cookie is sent to the eventstream without any changes to the contrib stuff, admittedly I was trying to get the `listActions` to work by just using `credentials: 'include'` rather than the explicit auth header yesterday.

**Comment by benjdlambert** [comment] 2021-07-06 08:35
So - just confirmed. The `/eventstream` does get the cookie when using https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md.

Think that PR for the `listActions` should be enough for now.

**Comment by erikxiv** [comment] 2021-07-06 09:40
@codingdiaz Could you confirm that it works for you too? Do you have a different use-case with different needs?

**Comment by codingdiaz** [comment] 2021-07-06 12:47
Thanks for looking into this! @erikxiv we don't have cookie based auth on currently. I would imagine once we tweak our auth middleware this should start to work.

**Comment by codingdiaz** [comment] 2021-07-06 13:22
@erikxiv I just confirmed it works once I follow [this](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md more closely. Sorry about the confusion there!

**Comment by benjdlambert** [comment] 2021-07-06 16:13
Perfect! Glad it's working as expected, will go ahead and close this then given the `listActions` changes that are merged and will be shipped this week.

**Closed by benjdlambert** 2021-07-06 16:13 UTC
Labels: bug

**Comment by hill-giant** [comment] 2022-04-06 11:59
Hi there. Is there any chance that the backstage team might consider switching to the polyfill in scaffolder in the future? My team and I have managed to implement token authorization without having to set cookies as [mentioned in the contrib section](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md). In our deployment, the eventstream seems to be the only thing that does not work without that cookie.

**Comment by hill-giant** [comment] 2022-04-06 13:23
@benjdlambert awesome! Will do. Yeah, we are using long polling, but it was mentioned in review that it is worth creating an issue or contributing a fix for it upstream.
