### ISSUE TITLE
Can't create a repository in Azure DevOps

### ISSUE THREAD

**Issue by KariemSoudy** [backstage/backstage#10962] opened 2022-04-20 16:45 UTC
I can't create a new repository for a tech-docs template, 

here are the steps and the error:
![1](https://user-images.githubusercontent.com/15885984/164281377-10f83eba-72ae-42e1-9add-4f5356415576.PNG)
![2](https://user-images.githubusercontent.com/15885984/164281382-ab72a3d4-7480-4260-984e-22d031a4577e.PNG)
![3](https://user-images.githubusercontent.com/15885984/164281384-0d437d06-2ae2-4f20-af7d-ff2df05f8ad6.PNG)
![4](https://user-images.githubusercontent.com/15885984/164281386-259b632a-f664-42fa-baf0-a0f092834c45.PNG)

here are the configurations:
![5](https://user-images.githubusercontent.com/15885984/164281421-7bc8f6b9-a97e-41da-a2c4-aac4679202cb.PNG)

please tell me if i have something wrong in the configurations or what should be wrong

**Comment by awanlin** [comment] 2022-04-20 19:04
Hi @KariemSoudy, your config looks good. The part that is a bit odd is the reference to `getOctokitOptions`, Octokit is GitHub stuff. Could you post the template YAML you are using? Is it this one? https://github.com/backstage/software-templates/blob/main/scaffolder-templates/docs-template/template.yaml If it is this is geared to GitHub and won't work with Azure DevOps

**Comment by KariemSoudy** [comment] 2022-04-20 21:20
Hi @awanlin , yes this is the template I'm using, i just tweaked it a bit and added dev.azure.com to allowedHosts
If this is only for GitHub, can you guide me on how to configure it to azure ?

Thank you

**Comment by awanlin** [comment] 2022-04-21 11:38
OK, at least we know where the issue is. Sadly I don't have any experience with the Software Templates, we just haven't used them much yet where I work.

@benjdlambert could you help us out here, please? I feel like there must be a way to get this working with Azure DevOps I'm just not sure the places that need to be changed

**Comment by shailahir** [comment] 2022-04-21 14:39
If you are using publish:github action step in template.yml, try after changing it to publish:azure

**Comment by KariemSoudy** [comment] 2022-04-22 11:01
@shailahir , thank you, it worked,
this is my publish step in template.yaml
![image](https://user-images.githubusercontent.com/15885984/164702051-e0f90bcc-8b19-4ed9-9667-967cf3007c93.png)

so can i allow two integrations in the same time?
i have github and azure integrations in config,
and in template.yaml i could add github.com here:
![image](https://user-images.githubusercontent.com/15885984/164702294-acc9aa20-ac66-4d46-852b-ea0217273c6d.png)

but only one of them will work depending on the publish step, if it is publish:github or publish:azure

**Comment by benjdlambert** [comment] 2022-04-22 11:14
Yep as noted, you need to use `publish:azure` instead of `publish:github`. You can optionally do steps by using the `if:` option on the `step` itself.

Something like:

```yaml
steps:
  - id: publish azure
  action: publish:azure
  if: ${{ (parameters.repoUrl | parseRepoUrl).host === 'dev.azure.com' }}
  - id: publish github
  action: publish:github
  if: ${{ (parameters.repoUrl | parseRepoUrl).host === 'github.com' }}
```

**Comment by benjdlambert** [comment] 2022-04-22 11:14
Going to close this as the original issue seems fixed, please let us know to re-open if there's something still not working 👍

**Closed by benjdlambert** 2022-04-22 11:14 UTC
Labels: bug

**Comment by awanlin** [comment] 2022-04-22 11:43
Thanks @benjdlambert for the help!

**Comment by KariemSoudy** [comment] 2022-04-22 12:08
@benjdlambert  thank you so much
