### ISSUE TITLE
github auth diff between OAuth App vs Github App

### ISSUE THREAD

**Issue by kissmikijr** [backstage/backstage#9163] opened 2022-01-25 14:39 UTC
We got the following bug ticket for one of our plugins: https://github.com/RoadieHQ/roadie-backstage-plugins/issues/385
If you use a github OAuth App it will persist your session, however if you use a Github App it won't.

After researching it a bit I don't think this behaviour is plugin specific. I was able to reproduce it without adding any of our github plugins.
My question is: Is it intended that they are not working the same? actually can they work the same?

## Expected Behavior
OAuth App and Github App handles the session the same

## Current Behavior
If you use a Github App for authentication you'll need to relogin after every page refresh

## Steps to Reproduce

1. Configure a Github App as an auth provider
2. Log in
3. Refresh page
4. You'll need to log in again.

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by ryan-hanchett** [comment] 2022-01-26 01:24
We're also running into this issue. I spent some time digging in today comparing the behavior of using a GH Oauth App versus a GH App. 

From my basic debugging, it appears the major difference is the evaluation of whether or not the session can be refreshed. The Oauth App seems to return no `expiresAt` in the session info, whereas the GH App does ([context](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/apis/implementations/auth/github/GithubAuth.ts#L116)).

Because the GH App session evaluates as being able to refresh, it skips over the step to add the session via the `staticSessionManager` [here](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/lib/AuthSessionManager/OptionalRefreshSessionManagerMux.ts#L90), and doesn't get set in local storage as `githubSession`. Then, on refresh, it [fails to find the session in local storage and kicks off the login flow](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/lib/AuthSessionManager/OptionalRefreshSessionManagerMux.ts#L77-L80). 

When I made it so that `setSession` ran either way, I hit this error on refresh:
```
Failed to load session from local storage because it did not conform to the expected schema, [
  {
    "code": "invalid_type",
    "expected": "date",
    "received": "string",
    "path": [
      "providerInfo",
      "expiresAt"
    ],
    "message": "Expected date, received string"
  }
]
```

But, if I modify the local storage entry for the `githubSession` and remove the expiry date, I can refresh and am still auth'd, no prompt to re-login. 

I think long story short, with some slight modifications to the `OptionalRefreshSessionManagerMux` class, as well as some better serialization for the GH App expiration date to appease [the schema validator](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/lib/AuthSessionManager/AuthSessionStore.ts#L115), we should be able to make it persist across refreshes / sessions. 

I'm suspicious of the fact that the tokens w/o expiration dates are the ones stored in localStorage and not the other way around, so I might be missing something big here. Happy to take a closer look tomorrow to verify these assumptions further.

**Comment by Rugvip** [comment] 2022-01-27 13:55
[GitHub OAuth](https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app) apps and [GitHub Apps](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app) are completely different. The OAuth apps do not support refresh, so we therefore store the returned token permanently in local storage. The Apps on the other hand do support refresh, so for those we store the session in a http-only cookie and we retrieve new access tokens whenever needed from the `/refresh` endpoint.

If the refresh flow for Apps isn't working that's a bug that should be fixed, I'll have a look and see if I'm able to reproduce it. To be clear, when you're using a GH App, then the `StaticAuthSessionManager` should **not** be used to store the session, and the session should **not** be stored in local storage, that is intended.

**Comment by ryan-hanchett** [comment] 2022-01-28 01:18
Hah yep, I figured I was too deep in the weeds and missing something at a higher level. 

I am able to reproduce this in latest `master` with a GitHub App when trying to access http://localhost:3000/catalog/default/component/backstage. Modified `integrations.github` as well as `providers.github` to point to my GH App in the `app-config.yaml`. When I navigate to that entity, I am prompted with the login initially, and on every subsequent refresh. 

I see a successful call to refresh the session hitting http://localhost:7007/api/auth/github/refresh?optional&env=development, which returns the new session/ provider token. Seems that portion of the logic is working, but for some reason the login prompt is still firing. Not quite sure where the disconnect is in the plumbing.

**Comment by Rugvip** [comment] 2022-01-28 08:35
Ah alright, that's gonna be down to some issues with scope handling! GitHub Apps don't let users request scopes, and there might be something we overlooked there. Will have a look

**Comment by ryan-hanchett** [comment] 2022-01-28 17:29
@kissmikijr - I had tried isolating to see if it was due to specific plugins, but when using each of the following I was able to repro: 
- `@backstage/plugin-github-actions` 
- `@roadiehq/backstage-plugin-security-insights`
- `@roadiehq/backstage-plugin-github-pull-requests`
- `@roadiehq/backstage-plugin-github-insights`

I also see the same issue in the auth providers section. I see my oauth refresh call, but not GitHub, and the button shifts from Sign Out to Sign In on each refresh.

**Comment by Rugvip** [comment] 2022-02-01 21:37
Hopefully shipping a fix for this in #9163, would be awesome if someone could try out reproducing the issue there to check that it's fixed

**Comment by ryan-hanchett** [comment] 2022-02-01 21:48
Awesome! I'll try and take a look this afternoon to see if I can reproduce with the changes.

Thanks @Rugvip

**Comment by ryan-hanchett** [comment] 2022-02-01 23:32
Hey @Rugvip - I pulled in your latest changes but can still reproduce the behavior I described in [my above comment](https://github.com/backstage/backstage/issues/9163#issuecomment-1023795476) on the branch `rugvip/auth-refresh` even after clearing out my cache/cookies and trying again.

Is there anything specific you want me to try / behavior to look out for? I see the new `github-granted-scope` being added to the cookies, and I still see the successful token refresh calls.

**Comment by Rugvip** [comment] 2022-02-02 00:56
@ryan-hanchett ah yep, thanks! Found a fix, will push it up tomorrow

**Comment by kissmikijr** [comment] 2022-02-02 13:59
I can see the #9294 PR got merge, should I try to replicate this on master?

**Comment by Rugvip** [comment] 2022-02-02 14:03
@kissmikijr sure!

**Comment by ryan-hanchett** [comment] 2022-02-02 23:47
Just tested locally on latest master and the issue seems to be resolved 🎉

**Comment by benjdlambert** [comment] 2022-02-03 15:22
Going to close as it seems resolved, please open if there's anything else!

**Closed by benjdlambert** 2022-02-03 15:22 UTC
Labels: bug
