### ISSUE TITLE
@backstage/create-app fails on Node 18

### ISSUE THREAD

**Issue by divideby0** [backstage/backstage#14012] opened 2022-10-05 23:50 UTC
## Expected Behavior

Running `@backstage/create-app` should succeed in a Node 18 environment.

## Actual Behavior

The `yarn install` step throws an error:

```bash
executing     yarn install ◝ error root@1.0.0: The engine "node" is incompatible with this module. Expected version "14 || 16". Got "18.7.0"
error Found incompatible module.
yarn install v1.22.19
info No lockfile found.
[1/5] Validating package.json...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## Steps to Reproduce

[![asciicast](https://asciinema.org/a/5NehpsMBcn42KHhkPspCt0MQO.svg)](https://asciinema.org/a/5NehpsMBcn42KHhkPspCt0MQO)

```

1. Download and install latest Node.js 18.x.x version, (e.g. `brew install node`)
2. Execute bootstrap script (`@backstage/create-app`)

## Context

I use a MacBook M1 Max as my daily driver. While Node 16 technically supports Apple Silicon natively, Node 18 adds several efficiencies and performance improvements for this architecture. The Node 18 compatibility issue seems to be related to this code in the handlebars template:

https://github.com/backstage/backstage/blob/49bf199e7ea9057eb375d7520a3e6a81c9f9560e/packages/create-app/templates/default-app/package.json.hbs#L5-L7

The commit associated with this block was from Sept 2021, dropping support for 12 and adding support for 16. Node 18 wasn't released until April 2022. So I'm unsure if this restriction is vestigial (to block an issue with Node 15) or intentional (due to current known issues with Node 18).

## Your Environment

macOS Monterey 12.6
MacBook M1 Max
Node.js 18.7.0

```bash
npm version
{
  npm: '8.15.0',
  node: '18.7.0',
  v8: '10.2.154.13-node.9',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.7',
  openssl: '3.0.5+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

**Comment by divideby0** [comment] 2022-10-05 23:53
As a workaround, you can run `yarn install --ignore-engines` (https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines) and everything seems to run fine under Node 18.

**Comment by jhaals** [comment] 2022-10-06 08:07
We don't support node 18 yet, closing as this is a duplicate of #12558 :)

**Closed by jhaals** 2022-10-06 08:07 UTC
Labels: bug
