### ISSUE TITLE
importing duplicate templates causes backend to crash

### ISSUE THREAD

**Issue by esrefeska** [backstage/backstage#3899] opened 2021-01-02 08:23 UTC
if you add two templates with the same "name" 
sqllite crashes 
'template:default/docs-template' as `full_name`, 1 as `generation`, 'ae4dca91-4ec2-47a6-b971-eb33937d6851' as `id`, '20afeebe-f030-488e-ac5b-424f7c429861' as `location_id` - SQLITE_CONSTRAINT: UNIQUE constraint failed: entities.full_name
    at CommonDatabase.transaction (webpack-internal:///../../plugins/catalog-backend/src/database/CommonDatabase.ts:84:15) type=plugin component=catalog-all-locations-refresh

expected behavior is it shouldn't be allowing me to add this template or had to use db primary id

**Comment by freben** [comment] 2021-01-02 10:07
That's not a crash though! It's just the database informing you that it works as intended - the catalog uses database constraints to strongly enforce that you don't end up in a weird state with duplicate identity keys. Entities are identified by the kind + namespace + name triplet; you can never have two with the same (case insensitive) triplet.

How did you add them? The catalog tries to stop you from making duplicates upfront (such as when registering new entities), but since these are files that can be edited and modified asynchronously by humans at any time in the future, all it can do is to tell you that there's an error and that you need to make adjustments.

**Comment by EsrefDurna** [comment] 2021-01-02 21:19
I updated the api configuration yaml manually.
At least the frontend should have shown some kind of error message.

**Comment by Rugvip** [comment] 2021-01-07 18:46
Think we've arrived at this being a duplicate of #2876, so gonna close this and let's continue any discussion there.

**Closed by Rugvip** 2021-01-07 18:46 UTC
Labels: bug
