### ISSUE TITLE
Backstage returns HTTP error code 304 on iPad and iPhone

### ISSUE THREAD

**Issue by ibootstrapper** [backstage/backstage#8125] opened 2021-11-18 00:06 UTC
on iPhone and iPad backstage returns HTTP error code 304 and not loading

## Expected Behavior

website should load fine

## Current Behavior

website loads fine on PC/Mac but not on iPhone/iPad , did not test other devices. 

## Steps to Reproduce

no link to a live example.

1. Setup latest backstage on a server via docker
2. Access website via iPhone or IPad - website will not load
3. Access website via PC/Mac - website loads

## Context

trying to setup a staging backstage instance via docker compose with backstage and postgress

## Your Environment

on premise HP Server with 80 cpus , 512GB Ram and 2GB NVME
- Operating System and Version Ubuntu: 20
- Browser Information: chrome, safari (both on PC/Mac/iPhone and IPad)

I tried to clear cache on both safari and chrome on the iPad and iPhone though problem persists.

**Comment by isamuelson** [comment] 2021-11-18 00:13
PS. Also tried in incognito mode on chrome.

**Comment by jhaals** [comment] 2021-11-18 09:42
Hi, sorry to hear that you're having issues. I tried this on locally running `yarn start` and setting app.baseUrl to `http://0.0.0.0:3000` to get it to listen on all interfaces. I have no problems reaching the site on my iPhone.

**Comment by freben** [comment] 2021-11-18 09:45
I believe this may be related to https://github.com/backstage/backstage/issues/6039 . It will happen in all browsers on those devices since they are all forced to use the same underlying system web view component, if I recall correctly.

**Comment by jhaals** [comment] 2021-11-18 09:57
I managed to reproduce this on master and also purging yarn.lock. It's the same problem on Safari on Mac so freben is right that it's related to the issue linked.

**Comment by freben** [comment] 2021-11-18 10:02
Trying to put in place the (probably partial) fix proposed in the comment in that linked ticket: https://github.com/backstage/backstage/pull/8132

**Comment by freben** [comment] 2021-11-18 10:46
I'll close this as a duplicate, but thanks for reporting and it'll stay pointed to through the references in the "main" ticket.

**Closed by freben** 2021-11-18 10:46 UTC
Labels: bug
