### ISSUE TITLE
🐛 Bug Report: scaffolder uses globby for copyWithoutTemplating but prevents negative matches

### ISSUE THREAD

**Issue by electrofelix** [backstage/backstage#18926] opened 2023-08-03 10:03 UTC
### 📜 Description

Discovering that copyWithoutTemplating was using globby I expected to be able to use a negated glob so that when most files in a directory should be copied without templating it would be possible to ensure the one file that did need templating could be listed instead of needing to list all files that did not.

I appreciate this may not be a bug as it may currently be working as expected, it is however sufficiently surprising to not be able to handle this that makes me initially think it's not what was intended, particular as it appears that globby has supported accepting a list of patterns to process at the same time for at least 8 years (https://www.npmjs.com/package/globby/v/4.0.0), making the existing code using map to handle each match separately suggest a mistake?

https://github.com/backstage/backstage/blob/e8bebb6f5f7e20539511720778afc478510a5cc9/plugins/scaffolder-backend/src/scaffolder/actions/builtin/fetch/template.ts#L207-L221

This looks like it should be sufficient to replace the above with the following for this to work:
```
      const nonTemplatedEntries = new Set(
        await globby(copyOnlyPatterns || [], {
            cwd: templateDir,
            dot: true,
            onlyFiles: false,
            markDirectories: true,
            followSymbolicLinks: false,
          }),
        )
      );
```

### 👍 Expected behavior

When provided with the following input:
```
    - id: template
      name: Template
      action: fetch:template
      input:
        url: ./template
        copyWithoutRender:
          - .github/workflows/*
          - '!.github/workflows/deploy.yaml'
```

It should perform template substitution on `.github/workflows/deploy.yaml` while not on any other `.github/workflow/*` files

Dry run mode should show:
```
info: Writing file .github/workflows/deploy.yaml to template output path with mode 33188.
```
without any reference to `without processing.` for this file.

### 👎 Actual Behavior with Screenshots

Dry run mode log output contains:
```
info: Copying file/directory .github/workflows/deploy.yaml without processing.
info: Writing file .github/workflows/deploy.yaml to template output path with mode 33188.
```
![image](https://github.com/backstage/backstage/assets/912324/02e3f8db-35a0-4a78-8e7e-5a02f22852de)

Sorry, I'm having to limit the full screenshot as I can't share details on other files being copied.

### 👟 Reproduction steps

Not sure where to provide a live example as using a SaaS instance of backstage. It should be possible to reproduce this with any template definition where a directory contains multiple files where only one should be rendered and others copied without being templated.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment] 2023-08-07 11:58
Alright, thanks for the detailed breakdown. Yeah, go ahead and contribute this change if you like, it makes sense.

The only potential concern is that in doing so, we are making a "larger promise" on the semantics of that input array and have to stand by it over time. You may want to expand any doc comment for that field to cover the wider scope. Essentially what you are describing here is a feature request, not a bug - it probably never intended to support negation. But it makes sense to do so, because it's reasonably easy to find libraries that support it, so no real worries there.

I marked it as an enhancement ticket.

**Comment by electrofelix** [comment] 2023-08-25 10:51
Thanks, new baby arrived so might be a little while before I get back to this.

**Comment by electrofelix** [comment] 2023-10-24 11:03
Still relevant, just haven't been able to get back to this.

**Comment by benjdlambert** [comment] 2023-10-27 13:25
@electrofelix congrats on the :baby:

Do you think you will have time to look at this? Otherwise we can add some labels to get some more help from the community :tada:

**Comment by electrofelix** [comment] 2023-11-02 09:24
@benjdlambert Hoping that I might get to it in the next week or two

**Comment by benjdlambert** [comment] 2023-11-02 11:23
Nice! No stress! Thanks :pray:

**Closed** 2023-11-08 20:45 UTC
Labels: enhancement, area:scaffolder
