### ISSUE TITLE
Table view performance issue. It should be pull data as lazy load.

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#9829] opened 2022-02-25 21:38 UTC
I have 1800 records. Table view make super slow loading. because it pull all data at once. It should be pull data by lazy loading or batches.

## Expected Behavior
It should pull data by lazy loading. 

## Actual Behavior
Table view pull all data even in api catalog download all swagger files.

**Comment by Rugvip** [comment] 2022-03-01 13:55
Thank you for reporting! This is indeed something we want to fix. Gonna close this one as a duplicate of #5921 as I think the discussion over there is where we should move this forward.

**Closed by Rugvip** 2022-03-01 13:55 UTC
Labels: bug
