### ISSUE TITLE
route for /catalog?filters broken again particular for Postgres

### ISSUE THREAD

**Issue by kim5566** [backstage/backstage#10387] opened 2022-03-23 05:17 UTC
Previous issue: https://github.com/backstage/backstage/issues/8929

visit `/catalog/?filters%5Bkind%5D=component&filters%5Buser%5D=owned` directly from url broken

It's not working on with github intergretion enabled.

```
# backstage.json
{
  "version": "1.0.1"
}

```
## Expected Behavior

Click url http://localhost:3000/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned should direct me to my owned entities

## Current Behavior

Click url http://localhost:3000/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned

But redirect me to http://localhost:3000/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all somehow

It works for demo site https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned,

So i suspect it caused by recent changes.

## Possible Solution

I haven't identified the cause yet.

## Steps to Reproduce

1. backstage version is up to date
2. have GitHub App integration setup.
3. import a catalog-info.yaml that you will own
4.  click `localhost:3000/catalog` --> seems default to show all entities
5. try to change this in App.tx
```
        <Route path="/catalog" element={<CatalogIndexPage initiallySelectedFilter='owned'/>}/>
```
6. click `localhost:3000/catalog`, the above DOES NOT work, still show me ALL entities.
7. view my owned entities directly from url `http://localhost:3000/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned`
8. The above DOES NOT WORK, still redirect me to `http://localhost:3000/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all`
9. The ONLY way to see my owned entitles is click from UI

## Context

Should the OWNED entities shown by default like the demo.backstage.io or at least be possible to set it up? 

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by jhaals** [comment] 2022-03-25 14:13
Sorry to hear that there's problems. Looks like the previous fix for this was worked on in #9538. @vinzscam would you be bale to help out on this? 🤞

**Comment by vinzscam** [comment] 2022-03-25 14:14
> 



> Sorry to hear that there's problems. Looks like the previous fix for this was worked on in #9538. @vinzscam would you be bale to help out on this? 🤞

looking into it!

**Comment by vinzscam** [comment] 2022-03-25 15:07
Hi @kim5566,
I've looked into it but I couldn't reproduce the issue.
A couple of things that could help you investigating the issue.

- Passing `initiallySelectedFilter="owned"` to `CatalogIndexPage` shouldn't change the result. `owned` is the default.
- If your user has zero owned entities, we switch automatically to `all`.  Before doing this operation, we wait until all the entities have been download AND your backstage identity has been resolved (waiting for your `ownershipEntityRefs` from your claims). So, ideally the UI should never automatically switch to `all` if the number shown next to `Owned` (in the left menu) is > 0.

Perhaps a recording of your screen could help us investigating more.

**Comment by kim5566** [comment] 2022-03-26 10:29
hi @vinzscam ! thanks for looking into this!

apologies, I have updated my issue description.

It is not working with GitHub Integration enabled.

As following screenshot, in my sample organisation i have a team called red-team.

with
```
catalog:
  rules:
    - allow: [Component, System, API, Group, User, Template, Location, Resource]
  locations:
    - type: github-org
      target: https://github.com/example-org
```

It auto discovered my team and user(me). ok

![Image from iOS (1)](https://user-images.githubusercontent.com/28945404/160234989-8ba06643-de39-4994-ab66-03d86a39569a.jpg)


Then i have defined a catalog-info.yaml with ownership == red-team.

Login with my GitHub account. Expected to see 1 owned service in catalog but it's empty.


![Image from iOS](https://user-images.githubusercontent.com/28945404/160234980-84b6272c-70df-4053-8ae5-9f0205435dd1.jpg)

Hopefully that's clear and make sense to you.

A side notice, everything works perfect before we bumped (from v0.69.0)  to Backstage v1.0. I could only suspect the issue was caused by recent changes.

**Comment by vinzscam** [comment] 2022-03-28 10:42
thank you for the explanation, everything looks more clear!
This looks more a claims issue. Basically, in order to understand that your authenticated user belongs to a certain team, you need to add this information in your JWT token. [Here](https://backstage.io/docs/auth/identity-resolver#resolving-membership-through-the-catalog) is an example on how to do it 😄

**Comment by mattmarchany** [comment] 2022-03-28 13:57
Hey there, I have the same problem as @kim5566 - we're also using the GitHub Discovery functionality. For us, we noticed that this stopped working with the upgrade to [v0.71.0](https://github.com/backstage/backstage/releases/tag/v0.71.0) where `@backstage/plugin-catalog-backend@0.24.0` split out GitHub, GitLab, etc. discovery and reader functionality into their own packages. We're currently on [v1.0.0](https://github.com/backstage/backstage/releases/tag/v1.0.0).

We have no issue with the `@backstage/plugin-catalog-backend-module-github` automatically handling the relationship between users, groups, and their entities (as @kim5566 also stated above), but the ownership filtering on the Home page no longer works. I've combed through the upgrade instructions multiple times to make sure we didn't miss anything in the transition to the new package but everything looks good. I'd expect other users would have the same issue?

Admittedly I haven't had a chance to comb through the code to figure out what might be going on.

**Comment by kim5566** [comment] 2022-03-28 23:04
thanks @vinzscam !

hey @mattmarchany , i ended up to resolve issues with adding a custom github identity resolver.

as linked provided by @vinzscam , and following is the key part to add group memberships.


```
            // Resolve group membership from the Backstage catalog
            const fullEnt = await ctx.catalogIdentityClient.resolveCatalogMembership({
              entityRefs: [id].concat(ent),
              logger: ctx.logger,
            });
```

**Closed** 2022-03-28 23:04 UTC
Labels: bug, catalog
