### ISSUE TITLE
styling is not being reflected in techdocs - extra.css is not being found/registered

### ISSUE THREAD

**Issue by alper98** [backstage/backstage#13636] opened 2022-09-12 07:13 UTC
## Expected Behavior

the CSS path registered under "extra_css" in mkdocs.yml should be registered on the page.

## Actual Behavior

Styling is not being reflected. 

## Steps to Reproduce

1. Create a new TechDocs site with the techdocs-cli NPM package (yarn or npm)
2. Configure "mkdocs.yml" with a custom CSS file (e.g. "extra_css: [./assets/styles/example.css]"
3. Start techdocs-cli serve -v

## Context

I am trying to make stylin changes all troughout our techdocs.

## Your Environment

- Browser Information: 
Microsoft Edge
Version 105.0.1343.33 (Official build) (64-bit)

- Output of `yarn backstage-cli info`: 

```text
OS:   Windows_NT 10.0.19044 - win32/x64
node: v16.16.0
yarn: 1.22.4
cli:  0.18.1 (installed)
backstage:  1.5.0

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.15.0
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.11.0
  @backstage/core-plugin-api                       1.0.5
  @backstage/dev-utils                             1.0.5
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4
  @backstage/plugin-catalog-backend-module-github  0.1.6
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.5
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-explore-react                  0.0.20
  @backstage/plugin-explore                        0.3.39
  @backstage/plugin-github-actions                 0.5.8
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-permission-backend             0.5.10
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.4
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
```

**Comment by benjdlambert** [comment] 2022-09-19 13:10
Going to close this as a duplicate of #12302

**Closed by benjdlambert** 2022-09-19 13:10 UTC
Labels: bug, docs-like-code
