### ISSUE TITLE
🐛 Bug Report: Cloudbuild doesn't work

### ISSUE THREAD

**Issue by Chomb3** [backstage/backstage#19514] opened 2023-08-22 15:26 UTC
### 📜 Description

Hi team, I've been trying to configure the Cloudbuild plugin, but it seems to be quite outdated, as the full integration is not working as it should.
In the component-info.yaml, it doesn't seem to recognize the annotation google.com/cloudbuild-project-slug, and when I start Backstage, the message 'No CI/CD available for this entity' appears.

Following the Roadie documentation (https://roadie.io/backstage/plugins/google-cloud-build/), the error seems to be in the configuration of EntityPage.tsx.

### 👍 Expected behavior

Cloudbuild should work properly

### 👎 Actual Behavior with Screenshots

Doesn't recognize de google.com/cloudbuild-project-slug.
![image](https://github.com/backstage/backstage/assets/63661465/c8101a85-76b6-478c-91d9-cc53705141c5)

### 👟 Reproduction steps

Just follow the Roadie documentation https://roadie.io/backstage/plugins/google-cloud-build/

### 📃 Provide the context for the Bug.

I need to show a PoC of Backstage working with Cloudbuild 

### 🖥️ Your Environment

OS:   Darwin 22.6.0 - darwin/x64
node: v18.0.0
yarn: 1.22.19
cli:  0.22.11 (installed)
backstage:  1.17.2

Dependencies:
  @backstage/app-defaults                          1.4.2
  @backstage/backend-app-api                       0.5.1
  @backstage/backend-common                        0.15.2, 0.19.3
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-openapi-utils                 0.0.3
  @backstage/backend-plugin-api                    0.6.1
  @backstage/backend-tasks                         0.5.6
  @backstage/catalog-client                        1.4.3
  @backstage/catalog-model                         1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.3
  @backstage/cli                                   0.22.11
  @backstage/config-loader                         1.4.0
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.9.1
  @backstage/core-components                       0.11.2, 0.13.4
  @backstage/core-plugin-api                       1.5.3
  @backstage/errors                                1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.17
  @backstage/integration                           1.6.1
  @backstage/plugin-api-docs                       0.9.9
  @backstage/plugin-app-backend                    0.3.49
  @backstage/plugin-app-node                       0.1.1
  @backstage/plugin-auth-backend                   0.18.7
  @backstage/plugin-auth-node                      0.2.18
  @backstage/plugin-catalog-backend                1.12.1
  @backstage/plugin-catalog-common                 1.0.15
  @backstage/plugin-catalog-graph                  0.2.34
  @backstage/plugin-catalog-import                 0.9.12
  @backstage/plugin-catalog-node                   1.4.2
  @backstage/plugin-catalog-react                  1.8.2
  @backstage/plugin-catalog                        1.12.3
  @backstage/plugin-cloudbuild                     0.3.22
  @backstage/plugin-events-node                    0.2.10
  @backstage/plugin-gcp-projects                   0.3.40
  @backstage/plugin-github-actions                 0.6.3
  @backstage/plugin-org                            0.6.12
  @backstage/plugin-permission-common              0.7.7
  @backstage/plugin-permission-node                0.7.12
  @backstage/plugin-permission-react               0.4.14
  @backstage/plugin-proxy-backend                  0.3.1
  @backstage/plugin-scaffolder-backend             1.16.2
  @backstage/plugin-scaffolder-common              1.4.0
  @backstage/plugin-scaffolder-node                0.2.1
  @backstage/plugin-scaffolder-react               1.5.3
  @backstage/plugin-scaffolder                     1.14.3
  @backstage/plugin-search-backend-module-catalog  0.1.5
  @backstage/plugin-search-backend-module-pg       0.5.10
  @backstage/plugin-search-backend-module-techdocs 0.1.5
  @backstage/plugin-search-backend-node            1.2.5
  @backstage/plugin-search-backend                 1.4.1
  @backstage/plugin-search-common                  1.2.5
  @backstage/plugin-search-react                   1.6.4
  @backstage/plugin-search                         1.3.5
  @backstage/plugin-tech-radar                     0.6.7
  @backstage/plugin-techdocs-backend               1.6.6
  @backstage/plugin-techdocs-module-addons-contrib 1.0.17
  @backstage/plugin-techdocs-node                  1.7.5
  @backstage/plugin-techdocs-react                 1.1.9
  @backstage/plugin-techdocs                       1.6.7
  @backstage/plugin-user-settings                  0.7.7
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.2
  @backstage/theme                                 0.2.19, 0.4.1
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by vinzscam** [comment] 2023-08-24 11:01
yeah it looks like the docs are a bit outdated. You should change your `EntityPage.tsx` as following:

```diff
+ import {
+   EntityCloudbuildContent,
+   isCloudbuildAvailable,
+ } from '@backstage/plugin-cloudbuild';

  export const cicdContent = (
    <EntitySwitch>
      <EntitySwitch.Case if={isJenkinsAvailable}>
        <EntityJenkinsContent />
      </EntitySwitch.Case>

+.    <EntitySwitch.Case if={isCloudbuildAvailable}>
+       <EntityCloudbuildContent />
+     </EntitySwitch.Case>
```

We should update the instructions [here](https://github.com/RoadieHQ/marketing-site/blob/main/content/backstage/plugins/google-cloud-build.md?plain=1)

**Comment by adamdmharvey** [comment] 2023-08-29 17:01
It's an intering nuance too, that this plugin is in the Backstage monorepo and so it's install documentation really should be here?

https://github.com/backstage/backstage/tree/master/plugins/cloudbuild

Indeed Roadie does sometime have their own documentation, and I wonder if that switch example (which is cool btw :) ) is the way their default Roadie service handles multiple CI/CD vs. how the Backstage sample code in open source does?

Anyway, if you visit backstage.io, then click plugins, you see the Google Cloud Build plugin, and if you explore it, it takes you here to install it:

https://github.com/backstage/backstage/tree/master/plugins/cloudbuild

Which is essentially blank.  So I'd recommend from an open source perspective that page likely needs an update, too!

**Comment by cl-christschantz** [comment] 2023-08-31 00:38
Add the following to EntityPage.tsx:
/packages/app/src/components/catalog/EntityPage.tsx
```import { EntityCloudbuildContent, isCloudbuildAvailable } from '@backstage/plugin-cloudbuild';```

Then in your cicdContent const, add the following switch case:

```
    <EntitySwitch.Case if={isCloudbuildAvailable}>
      <EntityCloudbuildContent />
    </EntitySwitch.Case>
```

E.G.
```
const cicdContent = (
  // This is an example of how you can implement your company's logic in entity page.
  // You can for example enforce that all components of type 'service' should use GitHubActions
  <EntitySwitch>
    <EntitySwitch.Case if={isCloudbuildAvailable}>
      <EntityCloudbuildContent />
    </EntitySwitch.Case>
    
    <EntitySwitch.Case if={isGithubActionsAvailable}>
      <EntityGithubActionsContent />
    </EntitySwitch.Case>
```

**Comment by tfhartmann** [comment] 2023-10-21 16:03
Thank you this bug/comment thread helped me.

**Comment by camilaibs** [comment] 2023-10-23 12:44
Hi @cl-christschantz would you like to help us update the documentation? This will be greatly appreciated 🙂

**Comment by cl-christschantz** [comment] 2023-10-23 19:16
> Hi @cl-christschantz would you like to help us update the documentation? This will be greatly appreciated 🙂

Sure, Ill get a PR submitted.

**Comment by camilaibs** [comment] 2023-10-24 08:49
> > Hi @cl-christschantz would you like to help us update the documentation? This will be greatly appreciated 🙂
> 
> Sure, Ill get a PR submitted.

Thank you so much in advance, issue assigned to you 🙌🏻

**Comment by cl-christschantz** [comment] 2023-10-25 22:25
@camilaibs PR is up. #20812

**Comment by tfhartmann** [comment] 2023-11-02 03:54
Sadly, while the docs in this issue helped me get the plugin installed, I don't see any cloud build data :(   Looking at this https://github.com/backstage/backstage/blob/master/plugins/cloudbuild/src/api/CloudbuildClient.ts#L33 makes me think that this plugin supports the v1 API only, and I'm wondering if since my cloud build repo was set up using 2nd Gen if this plugin is unable to see my builds..

**Comment by cl-christschantz** [comment] 2023-11-02 04:30
> Sadly, while the docs in this issue helped me get the plugin installed, I don't see any cloud build data :( Looking at this https://github.com/backstage/backstage/blob/master/plugins/cloudbuild/src/api/CloudbuildClient.ts#L33 makes me think that this plugin supports the v1 API only, and I'm wondering if since my cloud build repo was set up using 2nd Gen if this plugin is unable to see my builds..

Not sure if that is the case or not. I wouldn't think it would matter since the build runs are independent from the repo. Also, there is no "projects.builds.list" Method that I can find on the v2 api.

You could try the list method manually using this page:

https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds/list

If you get results, then what you stated likely is not the case.

I assume you are properly specifying the correct project slug in your component-info.yaml file?

`google.com/cloudbuild-project-slug: your-project-name`

**Comment by tfhartmann** [comment] 2023-11-03 15:23
I can run it, and get a 200, and the return is an empty map `{}`   and  `google.com/cloudbuild-project-slug: your-project-name`.  Is set to set to  my GCP project name/ID (which are the same) when I view the GCP project overview.  It's the same string I used for the `projectId` key when I set up my k8s integration, which is working correctly. (And Cloudbuild  is currently in that same project) 

Thanks for the  replies, they are really helpful! I appreciate it!

**Comment by PurseChicken** [comment] 2023-11-08 22:08
> I can run it, and get a 200, and the return is an empty map `{}` and `google.com/cloudbuild-project-slug: your-project-name`. Is set to set to my GCP project name/ID (which are the same) when I view the GCP project overview. It's the same string I used for the `projectId` key when I set up my k8s integration, which is working correctly. (And Cloudbuild is currently in that same project)
> 
> Thanks for the replies, they are really helpful! I appreciate it!

Sounds like you may not be able to use 2nd gen repo's in cloud build and use this plugin.

Ill try to do some testing after I setup a 2nd gen repo and run a build from that repo.

**Closed as completed** 2023-11-13 11:57 UTC
Labels: type:bug, priority:contrib-needed

**Comment by vedantthapa** [comment] 2023-11-21 22:51
I'm facing the same issue as @tfhartmann even though I'm using a 1st gen repo. Could it be possible that it only works for global scope? Is there a way to specify region?

I tried the calling the list method manually with:
```console
> gcloud builds list
Listed 0 items.
```
However, when I specify the region, it works as expected:
```console
> gcloud builds list --region us-central1
ID   CREATE_TIME                DURATION  SOURCE  IMAGES  STATUS
id1  2023-11-21T20:01:24+00:00  6M25S     -       -       SUCCESS
id2  2023-11-21T17:26:10+00:00  5M50S     -       -       SUCCESS
```

**Comment by PurseChicken** [comment] 2023-11-22 00:15
> [tfhartmann](/tfhartmann)

Yes, currently its only going to return builds in the global scope.

@tfhartmann are your builds also in a specific region vs global?

**Comment by PurseChicken** [comment] 2023-11-22 00:58
@vedantthapa 

Can you try the following projects.locations.builds.list method:

https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.builds/list?

In the `parent` parameter, use the following: `projects/your-project/locations/us-central1`. Replace `your-project` with your actual project name (the one you would use in your project-slug annotation.

![Screenshot 2023-11-21 at 4 54 16 PM](https://github.com/backstage/backstage/assets/29956166/a1487cdb-9b95-4c0d-bfc0-7633aabdb008)

**Comment by vedantthapa** [comment] 2023-11-22 01:39
@PurseChicken Yes, that works and returns the relevant results!

**Comment by PurseChicken** [comment] 2023-11-22 01:47
> @PurseChicken Yes, that works and returns the relevant results!

Awesome thanks! Could you please open a new issue and tag me? I have an open PR for some changes already to the plugin and I'll submit another based on your issue.

Thanks again!

**Comment by tfhartmann** [comment] 2023-12-09 15:09
> region

Sorry for the late reply, but yes I can confirm my builds are in a specific region, and not in a global scope!

**Comment by PurseChicken** [comment] 2023-12-10 21:38
> > region
> 
> Sorry for the late reply, but yes I can confirm my builds are in a specific region, and not in a global scope!

Perfect. I have a PR up which will allow you to specify a region in you component-info manifest which will pull the relevant results for your backstage entity. @vedantthapa has already tested this as well.

**Comment by tfhartmann** [comment] 2024-02-29 22:02
> > > region
> > 
> > 
> > Sorry for the late reply, but yes I can confirm my builds are in a specific region, and not in a global scope!
> 
> @tfhartmann. I have a PR up which will allow you to specify a region in you component-info manifest which will pull the relevant results for your backstage entity. @vedantthapa has already tested this as well.

As a follow up, I've never been able to get this working... no idea why. Works from the CLI, with `gcloud --project my-project builds list --region us-east4`

I totally get results from https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.builds/list using the parent...   but when I try to get this from  backstage 

```
    google.com/cloudbuild-project-slug: my-project
    google.com/cloudbuild-repo-name: repo-name (tried both org/reponame and just reponame) 
    google.com/cloudbuild-location: us-east4
```
 
no idea why.... I checked my oauth scopes, but don't see anything missing from them... 🤷  kind of at a loss...

**Comment by PurseChicken** [comment] 2024-03-01 18:10
@tfhartmann Are you sure that the plugin is the updated version in your backstage instance?

**Comment by tfhartmann** [comment] 2024-03-02 15:06
> @tfhartmann Are you sure that the plugin is the updated version in your backstage instance?

I show this when running, `yarn list --pattern plugin-cloudbuild` so I believe I'm at the most recent...   

```
yarn list v1.22.19
└─ @backstage/plugin-cloudbuild@0.4.0
✨  Done in 0.66s.
```

I do get the Google Login prompt, the CI/CD tab "things about it" then returns 
"No records to display" 


I do see a url in my logs  from `/api/auth/google/handler/frame`  which leads me to this url https://www.googleapis.com/auth/userinfo.email<truncated> 
That returns this message... 

```
You are receiving this error either because your input OAuth2 scope name is invalid or it refers to a newer scope that is outside the domain of this legacy API. which made me think is was a scope in my Oauth setup on GCP, but I couldn't find any scope that changed the behavior. 

This API was built at a time when the scope name format was not yet standardized. This is no longer the case and all valid scope names (both old and new) are catalogued at https://developers.google.com/identity/protocols/oauth2/scopes. Use that webpage to lookup (manually) the scope name associated with the API you are trying to call and use it to craft your OAuth2 request.
```

I think it's *something* I've misconfigured or missed...

**Comment by PurseChicken** [comment] 2024-03-02 23:23
You only need to specify repo-name if its different than the repo your component-info is in. Have you tried an annotation like the following:

` google.com/cloudbuild-project-slug: my-project
  google.com/cloudbuild-location: us-east4`

**Comment by tfhartmann** [comment] 2024-03-05 16:15
> You only need to specify repo-name if its different than the repo your component-info is in. Have you tried an annotation like the following:
> 
> If your builds happen to be associated with a different repo-name, make sure repo-name matches what you get in your results when using `gcloud --project my-project builds list --region us-east4`

Ok... wild... so when I run `builds list`  the SOURCE field is always returned as a dash `-`  So I'm not seeing a repo name in that output, although when I go the the gcp console, I clearly see the SOURCE with the repo.  I *do*  see the correct repos when running 

`gcloud --project my-project builds repositories list --connection github --region us-east4`

**Comment by PurseChicken** [comment] 2024-03-05 21:03
That is very strange. Have you tried using the trigger filter instead? I wonder if the plugin is not matching on repo name (since as you stated it shows blank when using builds list) so that would explain why there are no results with the plugin.

**Comment by tfhartmann** [comment] 2024-03-08 16:36
> That is very strange. Have you tried using the trigger filter instead? I wonder if the plugin is not matching on repo name (since as you stated it shows blank when using builds list) so that would explain why there are no results with the plugin.

Sadly using trigger filter returns no results in backstage either. 😢
