### ISSUE TITLE
🐛 Bug Report: Backstage packages (front-end) no longer seem to be minified

### ISSUE THREAD

**Issue by jslott2sigma** [backstage/backstage#25938] opened 2024-08-07 18:45 UTC
### 📜 Description

Looking at the Backstage packages that get installed in `node_modules`, the latest version does not seem to be minified by webpack.

### 👍 Expected behavior

Taking an example plugin `plugin-catalog-react` v1.11.3 (not the latest), the file layout in `node_modules` is:
```
$ ls
alpha.d.ts  alpha.esm.js  alpha.esm.js.map  esm  index.d.ts  index.esm.js  index.esm.js.map
```

### 👎 Actual Behavior with Screenshots

For the latest version of `plugin-catalog-react` v1.12.2 (the latest), the file layout in `node_modules` is:
```
$ ls
alpha.d.ts    alpha.esm.js.map	api.esm.js.map	components	filters.esm.js.map  index.d.ts	  index.esm.js.map  routes.esm.js.map  translation.esm.js      utils
alpha.esm.js  api.esm.js	apis		filters.esm.js	hooks	
```

### 👟 Reproduction steps

1. Do a `yarn add <package plugin>` anywhere
2. Examine the file layout in `node_modules`.

### 📃 Provide the context for the Bug.

We also noticed that our internal plugins (that we publish to an internal artifactory) have also been minified in the past, but no longer.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment] 2024-08-08 09:29
Ah, there was never any minification of the published packages. In a typical setup, minification happens when you create a production build of the app.

We did change the `dist` dir layout in #23417 though, which is the reason for this change.

I'll close this, since it's all working as intended.

**Closed by Rugvip** 2024-08-08 09:29 UTC
Labels: bug

**Comment by jslott2sigma** [comment] 2024-08-08 17:30
@Rugvip Many thanks for the explanation! Much appreciated.
