### ISSUE TITLE
Backstage Auth (Microsoft) Error: Failed to sign-in, unable to resolve user identity

### ISSUE THREAD

**Issue by guppyfish123** [backstage/backstage#24572] opened 2024-05-01 09:13 UTC
### 📜 Description

I'm trying to setup Azure AD Auth (Microsoft) for backstage, though after countless hours reading thru docs and experimenting, I'm still unable to get it to work. The error that I'm running into is:
`Failed to sign-in, unable to resolve user identity`
![msedge_Wp8Q9DwfH7](https://github.com/backstage/backstage/assets/27799164/c3624061-750c-4e05-9715-e8fb045f98ef)

### 👍 Expected behavior

From the debug logs the msgraghorg is finding the group. 
`Committed 0 msgraph users and 2 msgraph groups in 0.0 seconds.`
If might be that its not pulling the members from it.
I'm using a Security group called `Backstage Users` in Azure which the the user is apart of. And following the docs have ensure that app registration has correct permissions.
https://backstage.io/docs/auth/microsoft/provider/#configure-app-registration-on-azure
https://backstage.io/docs/integrations/azure/org/#app-registration

### 👎 Actual Behavior with Screenshots

![Code_ujF1srDsD1](https://github.com/backstage/backstage/assets/27799164/9fd8209c-4ce6-483c-9ee5-bfe3802ce810)

### 👟 Reproduction steps

```yaml
# app-config.local.yaml
auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: **REDACTED**
        clientSecret: **REDACTED**
        tenantId: **REDACTED**
        domainHint: **REDACTED**
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityAnnotation
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName

catalog:
  providers:
    microsoftGraphOrg:
      default:
          clientId: **REDACTED**
          clientSecret: **REDACTED**
          tenantId: **REDACTED**
          user:
            filter: accountEnabled eq true and userType eq 'member'
          group:
            filter: >
              displayName eq '**REDACTED**'
          schedule:
            frequency: PT1H
            timeout: PT50M
            retry: PT5M

```

```ts
# Backstage/sec/index.ts
// ...
backend.add(import('@backstage/plugin-app-backend/alpha'));
backend.add(import('@backstage/plugin-proxy-backend/alpha'));
backend.add(import('@backstage/plugin-scaffolder-backend/alpha'));
backend.add(import('@backstage/plugin-techdocs-backend/alpha'));

// auth plugin
backend.add(import('@backstage/plugin-auth-backend'));
// See https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin
backend.add(import('@backstage/plugin-auth-backend-module-guest-provider'));
backend.add(import('@backstage/plugin-auth-backend-module-microsoft-provider'));
// See https://backstage.io/docs/auth/guest/provider

// catalog plugin
backend.add(import('@backstage/plugin-catalog-backend-module-msgraph/alpha'));
backend.add(import('@backstage/plugin-catalog-backend/alpha'));
backend.add(
  import('@backstage/plugin-catalog-backend-module-scaffolder-entity-model'),
);

// permission plugin
backend.add(import('@backstage/plugin-permission-backend/alpha'));
backend.add(import('@backstage/plugin-permission-backend-module-allow-all-policy'));

// search plugin
backend.add(import('@backstage/plugin-search-backend/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-catalog/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-techdocs/alpha'));
// ...
```

All other configs are set and default and has not been changed.
Following - 
https://backstage.io/docs/backend-system/building-backends/migrating/
https://backstage.io/docs/integrations/azure/org

### 📃 Provide the context for the Bug.

Any Help would be great as the docs are still a bit confusing with the backend migration causing a bit of a mess. I understand that the team is still working on perfecting the docs and pouring and sweat and tears with the community on updating them.  Happy to assist with updating the docs to make a more clear path with authentication and azure integration. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GuptaNavdeep1983** [comment] 2024-05-01 12:51
I am sure that you are not interested in disabling the authentication but just to check that its just an authentication issue, you can disable the authentication like documented here, https://backstage.io/docs/tutorials/auth-service-migration#disabling-the-default-auth-policy

I think your issue is related to this one https://github.com/backstage/backstage/issues/24569

**Comment by benjdlambert** [comment] 2024-05-02 09:13
It looks like there's no users being ingested which would probably lead to this issue that you're seeing.

> Committed 0 msgraph users and 2 msgraph groups in 0.0 seconds.

**Comment by guppyfish123** [comment] 2024-05-02 10:00
@GuptaNavdeep1983  Yes that does work. I can also use guest access with no issues. 
```tsx
  components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        providers={[
          'guest',
          {
            id: 'microsoft-auth-provider',
            title: 'Microsoft',
            message: 'Sign in using Microsoft',
            apiRef: microsoftAuthApiRef,
          }
        ]}
      />
    ),
  },
 ```
 
 Yeah you might be right with it not pulling any users @benjdlambert. Though I'm following whats the docs are saying to use 
 https://backstage.io/docs/integrations/azure/org/#customizing-transformation
 and if even I query the users directly it doesn't work. 
 ```yaml
          user:
            filter: displayName eq 'Backstage'
```
 Confirmed that it works fine though on msgragh explorer
 https://developer.microsoft.com/en-us/graph/graph-explorer
 Any ideas if I'm doing the query wrong in the yaml configs?

**Comment by jagexjake** [comment] 2024-05-03 09:33
We are experiencing the same problem, and currently only getting this to work with a custom resolver also.
But, doing so without the `isUserInBackstageGroup` step aswell.
Would much rather use the builtin resolver and msgraph integration

**Comment by benjdlambert** [comment] 2024-05-06 11:24
So to clarify you should be able to use the built-in resolvers if the users are in the catalog, so it looks like there's something gone wrong here and the users aren't in the catalog. Have the users been in the catalog before and then on upgrading they're no longer being populated? I think we're going to need some help from the community here to understand what's going on with `msgraph` and why it's not ingesting users properly, if it's something that's been broken in the code we own, or if something else has changed.

**Comment by cliffAtOsaic** [comment] 2024-05-07 23:05
I am experiencing the same issue.

**Comment by benjdlambert** [comment] 2024-05-08 08:57
@pjungermann can you take a look at some of the config here and maybe help troubleshoot why we can't get any users in the catalog from the `msgraphProvider` :pray:

**Comment by pjungermann** [comment] 2024-05-08 09:23
We have it in place with built-in resolvers on the latest release version, and it works just fine. Ingestion of users as well as sign in.

I agree with @benjdlambert that the underlying issue is that no user gets ingested. At least for the author of this issue and based on the details and logs shared above.

The easiest way without debugging the code is to try calling the Graph API directly using the same credentials and query. Also, ensure that you use the same query mode, etc.

I see that you use query mode basic. E.g., our user.filter requires query mode advanced.

You could also check with the yaml reader like yq whether the value is as you intended.

I'm not sure whether the user.filter is the same in your actual setup.

It doesn't seem like you have a custom transformer that might cause user entities to get invalid, etc.

**Comment by guppyfish123** [comment] 2024-05-09 05:11
I DID IT!!!!

Soooo for everyone facing the issue, after a couple of hours of debugging here's what you need to do. @pjungermann was right with there technically not being anything wrong with the code. It's more of a config issue that isn't very well documented, which is understandable with the team trying to update all the docs for the new backend. 

Basically the defaultUserTransformer() Function needs three parameters from a users in msgragh to be enter in as a catalog user in backstage, which is: ID, DisplayName, & **Mail**. Mail is the key point that you need to add to your select config, that is missing from the docs.
```yaml
[...]
        queryMode: advanced
        user:
          filter: displayName eq '**User***'
          loadPhotos: true
          select: ['id', 'displayName', 'mail']
        schedule: 
          frequency: PT1H
          timeout: PT3M
[...]
```

You also need to make sure that in azure that your user has the Email Parameter set. Which if your creating a cloud user usually has to be done manually and isn't auto populated like the User principal name. The reason why backstage doesn't pull the User principal name instead of the email parameter is bc the User principal name isn't always going to a email in some rare cases. You can change this manually function to use the User principal name instead of the email. We could also make a PR to add to the function to pickup if the email if Null and the User principal name is a email to use User principal name instead.

**Comment by vinzscam** [comment] 2024-05-10 18:36
Amazing @guppyfish123! 👏
Closing the issue, feel free to re-open it in case more help is needed. 🙏

**Closed by vinzscam** 2024-05-10 18:36 UTC
Labels: bug

**Comment by twanbeeren** [comment] 2024-05-31 12:36
Just to clarify here:

It is only necessary to make changes in the app-config.yaml?

My app-config.yaml
```
    catalog:
      providers:
        microsoftGraphOrg:
          providerId:
              target: https://graph.microsoft.com/v1.0
              authority: https://login.microsoftonline.com
              clientId: ${AZURE_CLIENT_ID}
              clientSecret: ${AZURE_CLIENT_SECRET}
              tenantId: ${AZURE_TENANT_ID}
              queryMode: advanced
              user:
                filter: displayName eq '**Users**'
                loadPhotos: true
                select: ['id', 'displayName', 'mail']
              schedule:
                frequency: PT1H
                timeout: PT3M
```

Or are there also changes needed in the backend?

**Comment by ervison** [comment] 2024-06-04 22:21
Hello, 

I dont know it is the best way to solve, but in my case, the users in the Azure does not have the  mail field filed, so I  used transformer (https://backstage.io/docs/integrations/azure/org#using-custom-transformers) and i added the line below:

```
graphUser.mail = graphUser.mail || graphUser.userPrincipalName;
```

The final code block:
```
export async function myUserTransformer(
 
  graphUser: MicrosoftGraph.User,
  userPhoto?: string,
): Promise<UserEntity | undefined> {

  graphUser.mail = graphUser.mail || graphUser.userPrincipalName;


  const backstageUser = await defaultUserTransformer(graphUser, userPhoto);
  
  if (backstageUser) {
    backstageUser.metadata.description = 'Loaded from Microsoft Entra ID';
    
  }

  return backstageUser;
}
```

The solution was based in the @guppyfish123 post about defaultUserTransformer parameters. Thank you all

**Comment by manishalankala** [comment] 2025-04-03 17:25
Unable to Sign In Using Microsoft Authentication Provider in Backstage

**Description:** 
I am encountering an issue with the Microsoft Authentication provider in Backstage.
Error message indicates : Login failed; caused by Error: Failed to sign-in, unable to resolve user identity. Please verify that your catalog contains the expected User entities that would match your configured sign-in resolver.

**Versions :** 
Backstage Version : 1.3.7
Frontend: http://localhost:3000
Backend: http://localhost:7007
yarn version : 4.4.1
npm version: 10.8.2
"@types/react": "^18.3.20",
"@types/react-dom": "^18.3.7",
"@types/react-router-dom": "^5.3.3",
"react": "^18.3.1",
"react-dom": "^18.3.1",
"react-hook-form": "^7.33.0",
"react-router": "^7.4.0",
"react-router-dom": "^7.4.0"

**ScreenPrint :** 
![Image](https://github.com/user-attachments/assets/fc4fb87b-3f78-4522-95b0-63fe26936232)


Currently i have modified with few new changes, please find below, now encounntering issue with backend

**auth-config.local.yaml**
`
app:
  baseUrl: http://localhost:3000
  title: Backstage App

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  database:
    client: better-sqlite3
    connection: ':memory:'

auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
        scope: 'offline_access openid profile User.Read'
        tokenUrl: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
        signIn:
          resolvers:
          - resolver: emailMatchingUserEntityAnnotation 

    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        enterpriseInstanceUrl: https://github.com/
        signIn:
          resolvers:
            - type: usernameMatchingUserEntityName 

            logging:
            level: debug
          
catalog:
  locations:
    - type: file
      target: ./catalog-info.yaml
  rules:
    - allow: [Component, API, Resource]
    - allow: [Group, User]
    - allow: [Domain, DomainGroup]
    - allow: [System, SystemGroup]    
  integrations:
    microsoftGraphOrg:
      providerId: default
      target: https://graph.microsoft.com/v1.0
      authority: https://login.microsoftonline.com
      tenantId: ${AZURE_TENANT_ID}
      clientId: ${AZURE_CLIENT_ID}
      clientSecret: ${AZURE_CLIENT_SECRET}
      queryMode: advanced # Enables advanced queries for filtering and selecting fields
      queryMode: advanced # Enables advanced queries for filtering and selecting fields
      user:
       filter: accountEnabled eq true  # Filters out users without a display name
       select: [id, displayName, mail, userPrincipalName]
      group:
       select: [id, displayName, description]
      schedule:
        frequency: PT1H # Sync every hour
        timeout: PT3M # Timeout after 3 minutes
        initialDelay: PT15S # Initial delay of 15 seconds before the first sync

techdocs:
  builder: 'local' # Mandatory: Specifies how documentation sites are built ('local' or 'external')
  generator:
    runIn: 'local' # Mandatory: Specifies whether MkDocs runs locally or in Docker
  publisher:
    type: 'local' # Mandatory: Specifies where TechDocs sites are stored ('local', 'googleGcs', or 'awsS3')`



**packages/backend/src/index.ts**

`import { createBackend } from '@backstage/backend-defaults';
import createMicrosoftProvider from '@backstage/plugin-auth-backend-module-microsoft-provider';
import providers from '@backstage/plugin-auth-backend';

const backend = createBackend();

// Core backend plugins
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(import('@backstage/plugin-app-backend'));
backend.add(import('@backstage/plugin-catalog-backend'));
backend.add(import('@backstage/plugin-techdocs-backend'));
backend.add(import('@backstage/plugin-scaffolder-backend'));
backend.add(import('@backstage/plugin-search-backend'));
backend.add(import('@backstage/plugin-proxy-backend'));


backend.add(
  createMicrosoftProvider({
    signIn: {
      resolver: providers.resolvers.emailMatchingUserEntityAnnotation({
        annotation: 'microsoft.com/email' // Annotation key must match your catalog
      }),
    },
  }),
);

// Start the backend
backend.start();`


**packages/app/src/App.tsx** 
`import React from 'react';
import { createApp } from '@backstage/app-defaults';
import { SignInPage } from '@backstage/core-components';
import { AppRouter, FlatRoutes } from '@backstage/core-app-api';
import { Root } from './components/Root';
import { Route, Navigate } from 'react-router-dom';
import { entityPage } from './components/catalog/EntityPage';
import { searchPage } from './components/search/SearchPage';
import { authProviders } from './components/signin/identityProviders';
import { CatalogEntityPage,CatalogIndexPage,catalogPlugin } from '@backstage/plugin-catalog';
import { CatalogImportPage,catalogImportPlugin } from '@backstage/plugin-catalog-import';
import { catalogEntityCreatePermission } from '@backstage/plugin-catalog-common/alpha';
import { TechDocsIndexPage,techdocsPlugin,TechDocsReaderPage } from '@backstage/plugin-techdocs';
import { ScaffolderPage,scaffolderPlugin } from '@backstage/plugin-scaffolder';
import { ApiExplorerPage, apiDocsPlugin } from '@backstage/plugin-api-docs';
import { UserSettingsPage } from '@backstage/plugin-user-settings';
import { CatalogGraphPage } from '@backstage/plugin-catalog-graph';
import { RequirePermission } from '@backstage/plugin-permission-react';
import { AlertDisplay, OAuthRequestDialog } from '@backstage/core-components';

const app = createApp({
  components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        auto
        providers={ authProviders }
      />
    ),
  },
  bindRoutes({ bind }) {
    bind(catalogPlugin.externalRoutes, {
      createComponent: scaffolderPlugin.routes.root,
      viewTechDoc: techdocsPlugin.routes.docRoot,
      createFromTemplate: scaffolderPlugin.routes.selectedTemplate,
    });
    bind(apiDocsPlugin.externalRoutes, {
      registerApi: catalogImportPlugin.routes.importPage,
    });
    bind(scaffolderPlugin.externalRoutes, {
      registerComponent: catalogImportPlugin.routes.importPage,
      viewTechDoc: techdocsPlugin.routes.docRoot,
    });
  },
});


// Define application routes
const routes = (
  <FlatRoutes>
    {/* Default redirect */}
    <Route path="/" element={<Navigate to="catalog" />} />

    {/* Catalog routes */}
    <Route path="/catalog" element={<CatalogIndexPage />} />
    <Route 
      path="/catalog/:namespace/:kind/:name" 
      element={<CatalogEntityPage />}
    >
      {entityPage}
    </Route>

    {/* TechDocs routes */}
    <Route path="/docs" element={<TechDocsIndexPage />} />
    <Route path="/docs/:namespace/:kind/:name/*" element={<TechDocsReaderPage />} />

    {/* Scaffolder route */}
    <Route path="/create" element={<ScaffolderPage />} />

    {/* API Explorer route */}
    <Route path="/api-docs" element={<ApiExplorerPage />} />

    {/* Catalog Import route */}
    <Route
      path="/catalog-import"
      element={
        <RequirePermission permission={catalogEntityCreatePermission}>
          <CatalogImportPage />
        </RequirePermission>
      }
    />

    {/* Search page route */}
    <Route path="/search" element={searchPage} />

    {/* User Settings route */}
    <Route path="/settings" element={<UserSettingsPage />} />

    {/* Catalog Graph route */}
    <Route path="/catalog-graph" element={<CatalogGraphPage />} />
  </FlatRoutes>
);

export default app.createRoot(
  <>
    {/* Global components like alerts and OAuth dialogs */}
    <AlertDisplay transientTimeoutMs={5000} />
    <OAuthRequestDialog />
    
    {/* Application Router */}
    <AppRouter>
      <Root>{routes}</Root>
    </AppRouter>
  </>
);
`


**packages/app/src/signin/identityProviders.tsx**
`import { microsoftAuthApiRef, githubAuthApiRef } from '@backstage/core-plugin-api';
import { SignInProviderConfig } from '@backstage/core-components';
//import { guestAuthApiRef } from '@backstage/plugin-auth-backend-module-guest-provider';

export const authProviders: SignInProviderConfig[] = [
  {
    id: 'microsoft-auth-provider',
    title: 'Sign in using Microsoft',
    message: 'Microsoft login',
    apiRef: microsoftAuthApiRef,
    options: {
      env: 'development',
    },
  }as SignInProviderConfig,
  {
    id: 'github-auth-provider',
    title: 'Sign in using GitHub',
    message: 'GitHub login',
    apiRef: githubAuthApiRef,
  },
//   {
//     id: 'guest',
//     title: 'Sign in as Guest',
//     message: 'Continue as Guest',
//     apiRef: guestAuthApiRef, 
//   },
];`

Questions
1. Is a custom resolver required in this case, or should one of the built-in resolvers suffice?
2. Are there additional steps or configurations needed for resolving user identities when using Azure AD?

Reference: 
https://backstage.io/docs/auth/identity-resolver/#custom-resolver-example
https://backstage.io/docs/reference/plugin-auth-node.authresolvercontext/
https://backstage.io/docs/integrations/azure/org
https://backstage.io/docs/auth/microsoft/provider
