### ISSUE TITLE
[create-app] Module not found: Error: Can't resolve 'graphql-ws'

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#11515] opened 2022-05-14 14:49 UTC
## Expected Behavior

Backstage from `npx @backstage/create-app` should start up using `yarn dev` without any errors

## Actual Behavior

After starting a brand new instance of Backstage from `npx @backstage/create-app` we get this error in the UI:

![image](https://user-images.githubusercontent.com/67169551/168430588-efd7a925-bdda-4352-8fc3-bed676adff54.png)

The same error happens when you run `yarn build`

## Steps to Reproduce

1. Run `npx @backstage/create-app`
2. Navigate to the directory with the new Backstage instance
3. Run `yarn dev`

Notice: in your Browser that opens after a bit you will get the error: "Module not found: Error: Can't resolve 'graphql-ws'"

## Context

This is preventing potential Backstage users from creating a new instances. In this case I was trying to help someone on Discord regarding a different error: https://discordapp.com/channels/687207715902193673/974765069705564190

## Your Environment

```text
~/repos/forks/test-app> yarn backstage-cli info
yarn run v1.22.18
$ /Users/andre.wanlin/repos/forks/test-app/node_modules/.bin/backstage-cli info
OS:   Darwin 21.4.0 - darwin/x64
node: v14.18.1
yarn: 1.22.18
cli:  0.17.0 (installed)

Dependencies:
  @backstage/app-defaults               1.0.1
  @backstage/backend-common             0.13.2
  @backstage/backend-tasks              0.3.0
  @backstage/catalog-client             1.0.1
  @backstage/catalog-model              1.0.1
  @backstage/cli-common                 0.1.8
  @backstage/cli                        0.17.0
  @backstage/config-loader              1.1.0
  @backstage/config                     1.0.0
  @backstage/core-app-api               1.0.1
  @backstage/core-components            0.9.3
  @backstage/core-plugin-api            1.0.1
  @backstage/errors                     1.0.0
  @backstage/integration-react          1.0.1
  @backstage/integration                1.1.0
  @backstage/plugin-api-docs            0.8.4
  @backstage/plugin-app-backend         0.3.31
  @backstage/plugin-auth-backend        0.13.0
  @backstage/plugin-auth-node           0.2.0
  @backstage/plugin-catalog-backend     1.1.1
  @backstage/plugin-catalog-common      1.0.1
  @backstage/plugin-catalog-graph       0.2.16
  @backstage/plugin-catalog-import      0.8.7
  @backstage/plugin-catalog-react       1.0.1
  @backstage/plugin-catalog             1.1.0
  @backstage/plugin-github-actions      0.5.4
  @backstage/plugin-org                 0.5.4
  @backstage/plugin-permission-common   0.6.0
  @backstage/plugin-permission-node     0.6.0
  @backstage/plugin-permission-react    0.4.0
  @backstage/plugin-proxy-backend       0.2.25
  @backstage/plugin-scaffolder-backend  1.1.0
  @backstage/plugin-scaffolder-common   1.0.1
  @backstage/plugin-scaffolder          1.1.0
  @backstage/plugin-search-backend-node 0.6.0
  @backstage/plugin-search-backend      0.5.1
  @backstage/plugin-search-common       0.3.3
  @backstage/plugin-search-react        0.1.0
  @backstage/plugin-search              0.8.0
  @backstage/plugin-tech-radar          0.5.11
  @backstage/plugin-techdocs-backend    1.1.0
  @backstage/plugin-techdocs-node       1.1.0
  @backstage/plugin-techdocs-react      0.1.0
  @backstage/plugin-techdocs            1.1.0
  @backstage/plugin-user-settings       0.4.3
  @backstage/release-manifests          0.0.2
  @backstage/search-common              0.3.3
  @backstage/test-utils                 1.0.1
  @backstage/theme                      0.2.15
  @backstage/types                      1.0.0
  @backstage/version-bridge             1.0.1
✨  Done in 1.75s.
```

**Comment by Rugvip** [comment] 2022-05-14 15:00
Thank you for reporting! This is caused by #2405. It's fixed in master through #11506, which will be released on Tuesday. A workaround for now is to add `graphql-ws` as a dependency of the app.

**Comment by cmoulliard** [comment] 2022-05-14 18:26
> add `graphql-ws` as a dependency of the app

Where should we add this dep ?

**Comment by Rugvip** [comment] 2022-05-15 11:37
@cmoulliard putting it in `packages/app/package.json` should hopefully do the trick

**Comment by cmoulliard** [comment] 2022-05-15 13:01
Which version ?

**Comment by Rugvip** [comment] 2022-05-16 09:18
The latest one should be fine

**Comment by agardnerIT** [comment] 2022-05-17 09:30
Tried this but still erroring. I'll try again after the new release

**Comment by chrisjl154** [comment] 2022-05-17 10:19
Tried adding this dependency everywhere it seems to be needed, still gives an error. Will this definitely be released today?

**Comment by benjdlambert** [comment] 2022-05-18 14:40
This should be fixed now as we explicitly depend on the package now. Make sure you're on the latest versions of `@backstage/plugin-api-docs` and `@backstage/plugin-graphiql`

**Closed** 2022-05-19 13:03 UTC
Labels: bug

**Comment by younky-yang** [comment] 2022-05-20 01:19
actually it works well for Mac, but on Linux, we ned to explicitly add graphql-ws. So seemed some package has this issue on different platforms.

**Comment by josecosta-shell** [comment] 2023-05-03 15:27
I just got this very same error after trying to add soundcheck 
![image](https://user-images.githubusercontent.com/129780729/235963614-b03682e5-f24d-4d8c-ba7d-87b56d1b84a8.png)

**Comment by benjdlambert** [comment] 2023-05-03 16:30
@josecosta-shell I recommend you reach out to the Spotify folks that deal with the premium plugins. Doesn't look like an open source issue in this case I think 👍
