### ISSUE TITLE
OpenAPI definitions for the backend plugins

### ISSUE THREAD

**Issue by geototti21** [backstage/backstage#3234] opened 2020-11-04 10:57 UTC
## Feature Suggestion
👋 Hey, could we please provide the API specification for the `backend` components in an openapi(or similar) format like we do for the [auth-backend](https://github.com/backstage/backstage/blob/master/docs/openapi/definitions/auth.yaml) already?

## Context
Context behind this is that we are building the backend of the backstage in a different language (Go) and at the moment we have to reverse engineer the code to find the specs and adapt our API overrides at front-end accordingly. I think the main plugins that I'd love to be documented are the tech-docs and catalog plugin as they look the core ones.

Is there something else that I can use in the meantime to check the API specs?

Thanks in advance!

**Comment by Rugvip** [comment] 2020-11-04 11:58
Thank you for reporting, is it alright to close this as a duplicate of #2566?

**Comment by geototti21** [comment] 2020-11-04 12:02
> Thank you for reporting, is it alright to close this as a duplicate of #2566?

yeah defo, I should have search better the existing issues 😬 

thanks

**Closed** 2020-11-04 12:09 UTC
Labels: enhancement
