### ISSUE TITLE
🐛 Bug Report: Scaffolder encountered an error when upgrading from version 1.19.6 to 1.20.1.

### ISSUE THREAD

**Issue by chaulaode1257** [backstage/backstage#21306] opened 2023-11-15 08:06 UTC
### 📜 Description

I have upgraded the Backstage version from 1.19.6 to 1.20.1. Afterward, I checked my scaffolder component, and it appears to be not functioning correctly. The errors "The namespace ${{ parameters.orgName }} is not found or the user doesn't have permissions to access it"
more logs:

2023-11-15T06:33:30.921Z InputError: The namespace ${{ parameters.orgName }} is not found or the user doesn't have permissions to access it[73](https://xxxx.com/create/tasks/4d1b86f0-f6ca-4f7f-b199-aac3be155774#line-73)    at Object.handler (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-6b5fa0be.cjs.js:5927:17)[74](https://xxx.com/create/tasks/4d1b86f0-f6ca-4f7f-b199-aac3be155774#line-74)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[75](https://xxx.com/create/tasks/4d1b86f0-f6ca-4f7f-b199-aac3be155774#line-75)    at async NunjucksWorkflowRunner.executeStep (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-6b5fa0be.cjs.js:7230:9)[76](https://xxx.com/create/tasks/4d1b86f0-f6ca-4f7f-b199-aac3be155774#line-76)    at async NunjucksWorkflowRunner.execute (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-6b5fa0be.cjs.js:7303:9)[77](https://xxx.com/create/tasks/4d1b86f0-f6ca-4f7f-b199-aac3be155774#line-77)    at async TaskWorker.runOneTask (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/router-6b5fa0be.cjs.js:7525:26)[78](https://xxx.com/create/tasks/4d1b86f0-f6ca-4f7f-b199-aac3be155774#line-78)    at async run (/app/node_modules/p-queue/dist/index.js:163:29)

### 👍 Expected behavior

scaffolder works

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/1035031/6d19541b-490d-4a57-9aa5-3da7d310f1e2)

### 👟 Reproduction steps

1. go to scaffolder component
2. Fill some information
3. Next
4. An error shows: The namespace ${{ parameters.orgName }} is not found or the user doesn't have permissions to access it

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by HoangViet144** [comment] 2023-11-15 08:54
I strongly believe the root cause is backstage FE 1.20.1 not replace the `${{ paramaters.*}}` with `formData` from user's input. At backend side, I receive raw string `${{ paramaters.example_field }}` instead of `the actual value`

**Comment by benjdlambert** [comment] 2023-11-16 15:33
@HoangViet144 going to close this as fixed. Was released yesterday in 1.20.2. #21316

**Closed** 2023-11-16 15:33 UTC
Labels: bug, area:scaffolder
