### ISSUE TITLE
Bitbucket Server Integration requires appPassword and Token

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4208] opened 2021-01-21 23:45 UTC
After the last scaffolder update, Bitbucket Server requires both a token and an appPassword to work properly.

```
integrations: 
  bitbucket:
    - host: mybitbuckeserver.com
      apiBaseUrl: https://mybitbucketserver.com/rest/api/1.0
      username: username
      appPassword: token
      token: same-token
```

Only the token should be required and the appPassword should be removed.

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by OrkoHunter** [comment] 2021-03-04 16:34
@regicsolutions Wondering why did you close this issue - is this not a bug?

**Comment by regicsolutions** [comment] 2021-03-05 02:16
@OrkoHunter i thought this was fixed but confirmed it’s not

**Comment by freben** [comment] 2021-03-05 08:55
My understanding is that the correct behaviour is to require either `username + appPassword` or `token`. I.e. if you specify only `username` and `token` it should error out and say that the `username + appPassword` pair isn't complete. Is that correct?

Also, does this happen only in the scaffolder, when creating a new component?

**Comment by regicsolutions** [comment] 2021-03-05 12:27
User + token = 401 unauthorized (Issue with Scaffolder only works fine with catalog import)

User + password = 401 auth failed check credentials (issue with catalog import)

**Comment by benjdlambert** [comment] 2021-03-09 08:27
@regicsolutions thanks for the info on where you're seeing the issues, I'll dig into it.

**Comment by freben** [comment] 2021-03-16 08:08
just a gentle ping

**Comment by lorsatti** [comment] 2021-03-17 13:48
It works for me with username + token (personal access token) for Bitbucket Server. The token should have admin rights, in order to create a new repo.

**Comment by regicsolutions** [comment] 2021-03-17 14:00
> It works for me with username + token (personal access token) for Bitbucket Server. The token should have admin rights, in order to create a new repo.

Which version of Bitbucket Server are you running? I am on 7.4.1

**Comment by lorsatti** [comment] 2021-03-17 14:11
7.10.0

> > It works for me with username + token (personal access token) for Bitbucket Server. The token should have admin rights, in order to create a new repo.
> 
> Which version of Bitbucket Server are you running? I am on 7.4.1

**Comment by oleg-andreyev** [comment] 2021-03-25 11:28
Keep in mind Bitbucket Cloud != Bitbucket Server they have a different API.

https://docs.atlassian.com/bitbucket-server/rest/7.11.2/bitbucket-rest.html#idp209
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/refs/branches

**Comment by benjdlambert** [comment] 2021-03-25 13:49
Yep - sorry this is on me. Not had chance to look at this yet, will try to take a look at this sooner rather than later but it's kind of slipped off my top todo list

**Closed** 2021-04-09 08:09 UTC
Labels: bug, help wanted
