### ISSUE TITLE
🐛 Bug Report: oneOf operator inside template giving error "circular structure to JSON"

### ISSUE THREAD

**Issue by Nitinvonage** [backstage/backstage#21992] opened 2023-12-22 13:59 UTC
### 📜 Description

while filling one of the scaffolding template we are getting error "_Converting circular structure to JSON --> starting at object with constructor 'Object' | property 'oneOfSchema' -> object with constructor 'Object' | property 'oneOf' -> object with constructor 'Array' --- index 1 closes the circle_". This was not coming with backstage v1.19, it all started when we switched to v1.20.3

### 👍 Expected behavior

it should work in v1.20.3

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/110883891/396ce63a-4785-4d73-84f7-e0824b0bc6d3)
when you start filling a template which has oneOf operator it gives you error of circular dependency. looks like this has been fixed for other operators but not for onOf 

### 👟 Reproduction steps

1. Create a dummy template 
2. add oneOf operator inside it
```
title: Framework details
    required:
      - frameworkVersion
    properties:
      frameworkVersion:
        title: Framework Version
        type: string
        oneOf:
          - title: "7.0"
            const: net7.0
          - title: "6.0"
            const: net6.0
          - title: "5.0"
            const: net5.0
        default: net7.0
        description: Select .Net framework version
        
        ui:options:
          rows: 5

```
3. fill this template, after selecting the framework version from dropdown, once next is clicked you will get circular dependency error

### 📃 Provide the context for the Bug.

we are not able to release our new templates

### 🖥️ Your Environment

its not env specific, its coming in local as well
OS -Mac, 13
browser - chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by deepan10** [comment] 2023-12-27 10:52
Hello

When I reproduced this issue I could see it has a circular json structure during the JSON parse. https://github.com/backstage/backstage/blob/8b13af849a801129abd1d22406ff546fe9849fce/plugins/scaffolder-react/src/next/lib/schema.ts#L126 

![image](https://github.com/backstage/backstage/assets/5843888/9f8efd61-2d12-4fbd-bd0b-107e95bc412a)

Also figured out we can remove the circular json as mentioned here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value

I will implement it on the `extractSchemaFromStep` function to support all schema operators, will test and raise a pull request.

**Comment by Nitinvonage** [comment] 2023-12-27 11:09
thanks @deepan10 , till the time you are fixing it do you have any workaround for the same

**Comment by deepan10** [comment] 2023-12-27 11:25
@Nitinvonage ,
We can use the `anyOf` operator for this to fulfill the same purpose or `enum` as mentioned in backstage docs  [https://backstage.io/docs/features/software-templates/input-examples#array-with-custom-titles](https://backstage.io/docs/features/software-templates/input-examples#array-with-custom-titles)

**Comment by Rugvip** [comment] 2023-12-28 10:50
Closing as a duplicate of #20256

**Closed by Rugvip** 2023-12-28 10:50 UTC
Labels: bug
