### ISSUE TITLE
create-app fails in Node v14.17.0 and then fails to cleanup

### ISSUE THREAD

**Issue by joebowbeerxealth** [backstage/backstage#5781] opened 2021-05-23 03:37 UTC
Using Node v14.17.0, I tried several times to run `npx @backstage/create-app` but each time resulted in a failure to install cypress, and then even though the script announced that it was cleaning up, the app folder was not removed.

Using Node v12.22.1, I was successful.

## Expected Behavior

Either app created or folder removed.

## Current Behavior

Failed to create app and failed to cleanup.

## Possible Solution

Use Node v12.22.1

## Steps to Reproduce

1. `npx @backstage/create-app`

## Your Environment

- macOS BigSur 11.3.1
- node 14.17.0
- yarn 1.22.10

**Comment by Rugvip** [comment] 2021-05-24 19:18
Not able to reproduce this on Big Sur with node `14.17.0`. I suspect it's due to Apple silicon support though, are you running on an M1 by any chance? Node backported support in 14.17.0, but cypress may not have released binaries yet, so it may be best to run with rosetta for a bit longer.

If you're not on an M1 we'd need some more information to troubleshoot, including the log output of the yarn install run.

**Comment by h17liner** [comment] 2021-05-27 08:25
Just check `npx @backstage/create-app` on M1. Looks everything ok.


macOS BigSur 11.3.1
❯ node --version
v14.17.0
❯ yarn --version
1.22.10


```
❯ npx @backstage/create-app
npx: installed 70 in 6.583s
? Enter a name for the app [required] test1
? Select database for the backend [required] PostgreSQL

Creating the app...

 Checking if the directory is available:
  checking      test1 ✔

 Creating a temporary app directory:
  creating      temporary directory ✔

 Preparing files:
  copying       .dockerignore ✔
  copying       .eslintrc.js ✔
  templating    .gitignore.hbs ✔
  copying       README.md ✔
  copying       app-config.production.yaml ✔
  templating    app-config.yaml.hbs ✔
  templating    catalog-info.yaml.hbs ✔
  copying       lerna.json ✔
  templating    package.json.hbs ✔
  copying       tsconfig.json ✔
  copying       .eslintrc.js ✔
  copying       Dockerfile ✔
  copying       README.md ✔
  templating    package.json.hbs ✔
  copying       index.test.ts ✔
  copying       index.ts ✔
  copying       types.ts ✔
  copying       app.ts ✔
  copying       auth.ts ✔
  copying       catalog.ts ✔
  copying       proxy.ts ✔
  copying       scaffolder.ts ✔
  copying       techdocs.ts ✔
  copying       .eslintrc.js ✔
  copying       cypress.json ✔
  templating    package.json.hbs ✔
  copying       android-chrome-192x192.png ✔
  copying       apple-touch-icon.png ✔
  copying       favicon-16x16.png ✔
  copying       favicon-32x32.png ✔
  copying       favicon.ico ✔
  copying       index.html ✔
  copying       manifest.json ✔
  copying       robots.txt ✔
  copying       safari-pinned-tab.svg ✔
  copying       .eslintrc.json ✔
  copying       app.js ✔
  copying       App.test.tsx ✔
  copying       App.tsx ✔
  copying       apis.ts ✔
  copying       index.tsx ✔
  copying       setupTests.ts ✔
  copying       LogoFull.tsx ✔
  copying       LogoIcon.tsx ✔
  copying       Root.tsx ✔
  copying       index.ts ✔
  copying       EntityPage.tsx ✔

 Moving to final location:
  moving        test1 ✔

 Building the app:
  executing     yarn install ✔
  executing     yarn tsc ✔

🥇  Successfully created test1

See https://backstage.io/docs/tutorials/quickstart-app-auth to know more about enabling auth providers
```

But i met another problem - couldnt build app: 

```
❯ yarn run build
yarn run v1.22.10
$ lerna run build
lerna notice cli v4.0.0
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in 'app'
lerna ERR! yarn run build stdout:
$ backstage-cli app:build
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:

Error: Schema at ../../node_modules/@backstage/core/config.d.ts is invalid, Error: keyword value is invalid: data should be string, data should be equal to one of the allowed values

error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in 'app'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Rugvip** [comment] 2021-05-27 08:51
@h17liner thank you for checking it out, not quite sure what's up then : /

Regarding the error you saw it's triggered by the new TypeScript release, it's was fixed by https://github.com/backstage/backstage/pull/5822 which will be released in a few hours. For now it's possible to work around by pinning typescript to < 4.3

**Comment by Rugvip** [comment] 2021-05-27 08:52
Regarding the original issue, I'd guess it was just flakiness in the cypress release download then, or perhaps something that's now fixed on their end. Alright to close this?

**Comment by shoukoo** [comment] 2021-05-27 11:14
@Rugvip I'm new to this project, how can I downgrade the typescript? I cannot find typescript in package.json at the root level.

**Comment by Rugvip** [comment] 2021-05-27 11:30
@shoukoo best way for doing a short-term override is often to use [Yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/). You'd add it to the root `package.json` and point it to the version you want. Other options are to add a normal dependency and then twiddle a bit with `yarn.lock` to make sure it's locked to the version you want, or to just modify `yarn.lock` without adding a separate dependency.

In this case the release is just about to go out, it's building atm, so in a couple of minutes you'll be able to update `@backstage/config-loader` to a version that is compatible with TypeScript 4.3

**Comment by shoukoo** [comment] 2021-05-27 11:33
Thanks for the response, will give yarn resolutions a try.

**Comment by jhaals** [comment] 2021-05-27 14:31
Great, please re-open if you encounter the same issue again.

**Closed by jhaals** 2021-05-27 14:31 UTC
Labels: bug
