### ISSUE TITLE
🐛 Bug Report: Adding a parameters.properties in template editor causes a crash

### ISSUE THREAD

**Issue by antweiss** [backstage/backstage#18718] opened 2023-07-18 19:11 UTC
### 📜 Description

When trying to type in a new property in template editor once I add:
```yaml
      propname: 
```
frontend crashes with: 
```
TypeError
Cannot read properties of null (reading 'backstage:featureFlag')
Call Stack
 eval
  node_modules/@backstage/plugin-scaffolder/dist/esm/Router-8653bb84.esm.js:720:22
 filterOutProperties
  node_modules/@backstage/plugin-scaffolder/dist/esm/Router-8653bb84.esm.js:718:56
 MultistepJsonForm
  node_modules/@backstage/plugin-scaffolder/dist/esm/Router-8653bb84.esm.js:740:6
 renderWithHooks
  node_modules/react-dom/cjs/react-dom.development.js:14985:18
 updateFunctionComponent
  node_modules/react-dom/cjs/react-dom.development.js:17356:20
 beginWork
  node_modules/react-dom/cjs/react-dom.development.js:19063:16
 HTMLUnknownElement.callCallback
  node_modules/react-dom/cjs/react-dom.development.js:3945:14
 Object.invokeGuardedCallbackDev
  node_modules/react-dom/cjs/react-dom.development.js:3994:16
```

### 👍 Expected behavior

It should be possible to add yaml fields without the UI crashing

### 👎 Actual Behavior with Screenshots

This is still ok (entering a new line after the last property): 
<img width="1106" alt="Screen Shot 2023-07-18 at 22 05 50" src="https://github.com/backstage/backstage/assets/3274734/ff9baced-4b7e-4c6b-bcfb-4b79a0b6dd16">

Then while I enter the property name some warnings are shown at the bottom in red. Still ok:
<img width="984" alt="Screen Shot 2023-07-18 at 22 06 04" src="https://github.com/backstage/backstage/assets/3274734/ed240a29-65ff-4576-83e1-fadaa5804bae">

Then, once I type in a semicolon after the property name - the UI crashes:
<img width="1398" alt="Screen Shot 2023-07-18 at 22 06 19" src="https://github.com/backstage/backstage/assets/3274734/b71aac04-9e54-45f9-98b9-cbcd3fd63611">

and, once I click on `x Close` at the bottom:
<img width="1386" alt="Screen Shot 2023-07-18 at 22 06 29" src="https://github.com/backstage/backstage/assets/3274734/0f823d90-fb40-4c28-a7c5-d90da50f13ca">

### 👟 Reproduction steps

On a vanilla Backstage app:
- Go to template editor (http://your-bacsktage/create/edit)
- Click on "Edit Template Form"
- Try to type in a new entry in `parameters.properties` of the example template 

### 🖥️ Your Environment

Ubuntu 22.04
Node 18

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment] 2023-07-20 09:40
Hmm yeah, I think that we should try and catch these errors somewhere in an ErrorBoundary, and not display the form if possible or at least not crash the app. Is this something you want to raise a suggested fix for @antweiss :pray:

**Comment by antweiss** [comment] 2023-07-23 15:00
I'd love to. Need to understand the call stack a bit better. If I get this correctly - we shouldn't try to validate a field before a newline is entered.

**Comment by hpatoio** [comment] 2023-08-10 09:46
I'm creating a new action  and I'm having the very same problem. In my local env I've created a template that uses my new action. When I create a new component using the template everything works but when I reach the last page (the one that output all the info) Backstage crashes with a similar error


```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
MultistepJsonForm@webpack-internal:///../../node_modules/@backstage/plugin-scaffolder/dist/esm/Router-8653bb84.esm.js:704:7
div
CardContent@webpack-internal:///../../node_modules/@material-ui/core/esm/CardContent/CardContent.js:28:17
WithStyles@webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:25
ErrorBoundary2@webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:2448:5
div
Paper@webpack-internal:///../../node_modules/@material-ui/core/esm/Paper/Paper.js:47:17
WithStyles@webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:25
Card@webpack-internal:///../../node_modules/@material-ui/core/esm/Card/Card.js:27:17
WithStyles@webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:25
InfoCard@webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:2557:7
article
Content@webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:3710:69
main
ThemeProvider@webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:41:18
Page@webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:6268:33
AnalyticsContext@webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:72:36
TemplatePage@webpack-internal:///../../node_modules/@backstage/plugin-scaffolder/dist/esm/Router-8653bb84.esm.js:883:22
SecretsContextProvider@webpack-internal:///../../node_modules/@backstage/plugin-scaffolder-react/dist/esm/ref-6fdfc121.esm.js:21:80
```

**Comment by Rugvip** [comment] 2023-08-14 11:50
@hpatoio that seems like a different problem, could you create a new issue explaining it some more?

**Comment by hpatoio** [comment] 2023-09-01 13:49
@roman-shandurenko what exactly did you do ?  Did you had a new property in an existing template ?

**Comment by tudi2d** [comment] 2023-09-04 09:54
Hej @kuangp. Do you have any idea how we could improve the error boundaries here and in general to avoid future crashes? :)

**Comment by kuangp** [comment] 2023-09-05 15:51
hmm I'm only observing the "crash" when running in "dev" mode (eg. `yarn dev`). When running in "prod" mode, the error seems to be correctly caught by an ErrorBoundary and simply displays the error within the editor context (and the form does not render as @benjdlambert suggested) - The actual error in question (`Cannot read properties of null (reading 'backstage:featureFlag'`) seems to originate from here somewhere: https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx (haven't dug further into the root cause)

**Comment by benjdlambert** [comment] 2024-01-12 15:28
does this still happen? noting that the `MultistepJsonForm` component is now deprecated and soon to be removed shortly as it's part of the legacy exports in `/alpha` after the promotion of the `scaffolder/next` work.

**Comment by npiyush97** [comment] 2024-02-17 11:24
think fixed in #20221

**Comment by benjdlambert** [comment] 2024-04-05 17:48
Gonna close this as fixed for now, as I'm struggling to reproduce this now after new version is out. Please feel free to reach out if something is still awry.

**Closed by benjdlambert** 2024-04-05 17:48 UTC
Labels: bug, help wanted, area:scaffolder

**Comment by kunickiaj** [comment] 2024-10-11 02:06
FWIW experiencing this on 1.31.3
