### ISSUE TITLE
Backend fails to start. Similar to #2492 and #2500

### ISSUE THREAD

**Issue by ashishverma1108** [backstage/backstage#9187] opened 2022-01-26 19:02 UTC
I am trying to test backstage locally via https://backstage.io/docs/deployment/k8s and I can get my `docker run -it -p 7007:7007 backstage` to run the backend. Getting this error:
```
2022-01-26T18:46:37.226Z backstage info You are running an example backend, which is supposed to be mainly used for contributing back to Backstage. Do NOT deploy this to production. Read more here https://backstage.io/docs/getting-started/ 
2022-01-26T18:46:38.782Z backstage info Loaded config from app-config.yaml 
The configuration key 'catalog.processors.githubOrg' of app-config.yaml is deprecated and may be removed soon. Configure a GitHub integration instead.
2022-01-26T18:46:38.798Z backstage info 4 secrets found in the config which will be redacted 
Backend failed to start up Error: You must configure at least one key in backend.auth.keys for production.
    at Function.fromConfig (/app/packages/backend-common/dist/index.cjs.js:2771:13)
    at makeCreateEnv (/app/packages/backend/dist/index.cjs.js:426:57)
    at main (/app/packages/backend/dist/index.cjs.js:461:21)
```

## Expected Behavior
Backend should start and I should be able to access backstage at http://localhost:7007 as per the [documentation](https://backstage.io/docs/deployment/docker).

## Current Behavior
1. Kubernetes setup works as expected
2. Docker Image creation for [Backstage deployment](https://backstage.io/docs/deployment/k8s#:~:text=backstage%2Dsecrets%20created-,Creating%20a%20Backstage%20deployment,-To%20create%20the) is not going as expected. 
 > I am following [Host Build](https://backstage.io/docs/deployment/docker#:~:text=frontend%20topic%20below.-,Host%20Build,-This%20section%20describes) for building docker image
 > After cloning backstage repo, running required Yarn statements, & `docker image build . -f packages/backend/Dockerfile --tag backstage`
 > I get following error when trying to run `docker run -it -p 7007:7007 backstage`
```
    Backend failed to start up Error: You must configure at least one key in backend.auth.keys for production.
    at Function.fromConfig (/app/packages/backend-common/dist/index.cjs.js:2771:13)
    at makeCreateEnv (/app/packages/backend/dist/index.cjs.js:426:57)
    at main (/app/packages/backend/dist/index.cjs.js:461:21)
```

## Possible Solution
I feel setting NODE_ENV=development should solve the issue but I have tried to set this variable in multiple place but can't seem to make that error go away. Tried setting env variable in below listed places
1. In mac terminal before building docker image
2. In dockerfile via ENV, ARG, and running export command
3. setting the var when executing docker image build command

## Steps to Reproduce

Just follow the tutorial as described in #Current_Behavior section

## Context

Trying to test backstage for potential use

## Your Environment

OS:   Darwin 19.6.0 - darwin/x64
node: v16.13.2
yarn: 1.22.1
cli:  0.12.0 (local)

- NodeJS Version (v14): v16.13.2
- Operating System and Version (e.g. Ubuntu 14.04): Mac
- Browser Information: Chrome

**Comment by Rugvip** [comment] 2022-01-26 19:08
Is this happening in an app that's created with `@backstage/create-app`? that would need a fix

If you're encountering this when trying to package the main repo into a Docker image then there's more things that you'll need to set up, so it's working as intended. As the error message mentions you need to populate `backstage.auth.keys` in the configuration.

**Comment by ashishverma1108** [comment] 2022-01-26 20:40
Oh got it, thanks. Maybe I should try `npx @backstage/create-app` first. 

This error is coming up when trying to package the main repo into Docker image. Just for my curiosity, where can I find the documentation that walks through setting up `backstage.auth.keys` and other things that might need to be setup. I'm assuming [this](https://backstage.io/docs/deployment/k8s#creating-a-backstage-deployment) guide by itself is not complete.

**Comment by Rugvip** [comment] 2022-01-26 20:57
To see a reference for all the possible config values in any given Backstage project, you can run `yarn backstage-cli config:docs`.

The `backstage.auth.keys` is actually a new thing that doesn't have any documentation yet, which is why we're not including that in `@backstage/create-app` yet. It was actually covered in a demo from today's [community session](https://github.com/backstage/community/issues/37) though, so stay tuned for a recording of that if you want to know more :grin:

The getting started guide on backstage.io also goes on to cover some [configuration examples](https://backstage.io/docs/getting-started/configuration).

**Comment by ashishverma1108** [comment] 2022-01-26 21:02
Thanks for the prompt response @Rugvip . I will explore the docs and look forward to the recording. Is there a preferred app you release these recordings on... I couldn't find youtube channel. Also, feel free to close the issue. Thanks for your help.

**Comment by ashishverma1108** [comment] 2022-01-26 21:04
Found and subscribed to the channel :)

**Comment by Rugvip** [comment] 2022-01-26 21:26
np! Alright to close this issue?

**Closed** 2022-01-27 15:10 UTC
Labels: bug

**Comment by hari2192** [comment] 2022-02-20 13:31
@ashishverma1108 - What was final fix for this issue, if you please share ?

**Comment by elamaran11** [comment] 2024-03-23 15:48
@hari2192 @ashishverma1108 @jhaals @Rugvip Do we have a real resolution for this? Looks like the issue is closed without any documentation or proper resolution.

**Comment by Rugvip** [comment] 2024-03-23 16:46
@elamaran11 The solution is to configure `backstage.auth.key` in production, as explained by the error message. It's documented at https://backstage.io/docs/auth/service-to-service-auth, but we are also working towards removing this requirement soon.

**Comment by elamaran11** [comment] 2024-03-23 18:04
Hi @Rugvip Thankyou for responding but the recommendation doesnt work at all. When i tried to do `backstage.auth.key` with a crypto as recommended in the link you shared it does not work. Fundamentally where is this line of code 
```const tokenManager = ServerTokenManager.fromConfig(config, { logger: root });``` to add this, this no longer existing in `packages/backend/src/index.ts`. When i still tried this, im getting the below error:

```ForwardedError: Plugin 'auth' startup failed; caused by Error: Failed to connect to the database to make sure that 'backstage_plugin_auth' exists, error: no pg_hba.conf entry for host "10.0.146.116", user "postgres", database "postgres", no encryption```

As a followup, i tried the following:
1. updated the `NODE_ENV development` in DockerFile no luck
2.  Added the below to `database.connection` no luck:
```
      ssl: 
        rejectUnauthorized: false
```
3. Then tried below no luck:
```
      ssl: 
        require: false
        rejectUnauthorized: false
```
4. Then next and no luck:
```
      ssl: 
        require: true
        rejectUnauthorized: true
```
5. Then updated the below next and no luck:
```
      host: ${POSTGRES_SERVICE_HOST}
      port: ${POSTGRES_SERVICE_PORT}
```
Each of the above changes got me to same error. 

```ForwardedError: Plugin 'auth' startup failed; caused by Error: Failed to connect to the database to make sure that 'backstage_plugin_auth' exists, error: no pg_hba.conf entry for host "10.0.146.116", user "postgres", database "postgres", no encryption```

This is pretty frustrating that, we are going in to a rabbit hole and there is no path forward on docker or Kubernetes environment. Fundamentall the production functionality to impose `backstage.auth.key` is not working and there is no documentation to thoroughly demonstrate how this works for past one year. Appreciate if there is a workaround asap.

**Comment by freben** [comment] 2024-03-23 18:34
Configuring your postgres _server_ correctly (which is what's causing the HBA error) is out of scope for Backstage itself. Check the pg docs for how to properly set your HBAs.

And just to be extra clear. It's not `backstage.auth.key` - it should be `backend.auth.keys` according to https://backstage.io/docs/auth/service-to-service-auth#setup

In the new backend system you don't have to set the token manager; it's there by default already.

**Comment by elamaran11** [comment] 2024-03-24 05:42
Postgrest was configured correctly, i had issues with `ssl` configuration. Below worked.

```
  database:
    client: pg
    ensureExists: true
    pluginDivisionMode: 'schema'
    knexConfig:
      searchPath: ['knex', 'public']
    connection:
      ssl:
        require: false
        rejectUnauthorized: false
```

**Comment by JedGilbert** [comment] 2024-04-23 08:17
Hi @Rugvip, the documentation you shared last month suggests that "Backstage plugins that use the new backend system and handle credentials using the auth and httpAuth service APIs are secure by default, without requiring any configuration." 

However, the search plugins have a dependency on coreServices.tokenManager which seems to require a backend.auth.keys config in a production environment. Can you please confirm if it is still currently a requirement to configure the auth keys please? Not sure if the docs are out of sync or I'm missing something else. Thanks!

We're using the following plugins if it helps:

`backend.add(import('@backstage/plugin-search-backend/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-pg/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-catalog/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-techdocs/alpha'));`

**Comment by jrbe228** [comment] 2024-05-05 00:06
I'm encountering this issue when attempting to install Backstage with the default helm chart [values](https://github.com/backstage/charts/blob/main/charts/backstage/values.yaml).

**Comment by rahulkandru** [comment] 2024-05-07 09:47
You need to pass the secret in the app-config.yaml - 
```
backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
```
Generate a random secret - 
``` node -p 'require("crypto").randomBytes(24).toString("base64")' ```
