### ISSUE TITLE
🐛 Bug Report: Exit code 139 when running the docker after build

### ISSUE THREAD

**Issue by danielyaba** [backstage/backstage#25637] opened 2024-07-16 06:46 UTC
### 📜 Description

Hi,

I'm following the Docs about building a docker image (https://backstage.io/docs/deployment/docker)
After using the Host Build process the container fails to run with exit code 139 (Segmentation fault)
I didn't change anything in the application (neither `app-config.yaml` nor any other file)

### 👍 Expected behavior

The container should be running locally on my stations successfully 

### 👎 Actual Behavior with Screenshots

Output of "docker ps": 
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS                       PORTS                                          NAMES
f0e4f4bdb640   backstage                        "docker-entrypoint.s…"   11 seconds ago   Exited (139) 2 seconds ago                                                 

### 👟 Reproduction steps

Run the following commands:
```
npx @backstage/create-app@latest
cd backstage
yarn install --frozen-lockfile
yarn tsc
yarn build:backend --config ../../app-config.yaml
docker image build . -f packages/backend/Dockerfile --tag backstage
docker run -it -p 7007:7007 backstage
```

### 🖥️ Your Environment

Every thing is done locally on my macOS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment] 2024-07-18 09:23
I think we need some more info here and some more digging.

I wonder if you want to try the multi-stage build instead and see if you get similar results?

Could you also create an reproduction repository so we can try it out too, as we're unable to reproduce with your steps.

**Comment by danielyaba** [comment] 2024-07-18 14:39
Hi thanks for the response 

Those are the requirements packages version I used when building the backstage application on my local macOS ->
* `node -v`: v18.20.4
* `nvm -v`: 0.39.4
* `npx -v`: 10.8.2
* `yarn -v`: 1.22.22

You can check out [my public backstage repo](https://github.com/danielyaba/backstage)
This is Docker image after CI finished successfully: [danielyaba/backstage0.1.0](https://hub.docker.com/r/danielyaba/backstage)

Output of running the docker images:
```
backstage git:(main) docker run -it -p 7007:7007 --name backstage $BACKSTAGE /bin/bash
node@592c39623ba1:/app$ ls
app-config.production.yaml  app-config.yaml  node_modules  package.json  packages  yarn.lock
node@592c39623ba1:/app$ node packages/backend --config app-config.yaml
Segmentation fault
```
Please try to find if I did anything wrong

**Comment by benjdlambert** [comment] 2024-07-22 09:00
Hmm this is unfortunate as your example repo works on my machine.

You could try running the `node` process with a debugger to get a stack trace of the segfault so we can work out what's throwing. It's probably gonna be a `v8` thing, but it might give us some clues.

**Comment by danielyaba** [comment] 2024-07-23 08:51
Hi @benjdlambert,

It was probably an issue on my local macOS
I managed to deploy Backstage on my GKE successfully

Thanks a lot

**Comment by benjdlambert** [comment] 2024-07-23 10:23
OK nice! Gonna close this, but if you ever find out what the cause was I'd be interested to know! :pray:

**Closed by benjdlambert** 2024-07-23 10:23 UTC
Labels: bug
