### ISSUE TITLE
🐛 Bug Report: After unregistering entity from Catalog and deleting repo from GitHub, Backstage will try to find it again during restart of app (Unable to read url, NotFoundError: Request failed)

### ISSUE THREAD

**Issue by SmajlovicA** [backstage/backstage#27035] opened 2024-10-09 04:52 UTC
### 📜 Description

Whenever I test template creation, I then delete the GitHub repos and unregister/delete them from Backstage. However, I noticed that Backstage still tries to find them in the catalog after removal.

So when the container starts, it provides errors for repositories that no longer exist. 

```bash
{"entity":"location:default/generated-021d0e93cfa0308c93241c4a3f7699f16c35d95d","level":"warn","location":"url:https://github.com/GROUP/repo-test-idp-app-2/tree/main/catalog-info.yaml","message":"Unable to read url, NotFoundError: Request failed for https://api.github.com/repos/GROUP/repo-test-idp-app-2/contents/catalog-info.yaml?ref=main, 404 Not Found","plugin":"catalog","service":"backstage"}{"entity":"location:default/generated-d7c05b3738497a08ef6515b5e21a81d97cf17d8f","level":"warn","location":"url:https://github.com/GROUP/repo-test-idp-page-5/tree/main/catalog-info.yaml","message":"Unable to read url, NotFoundError: Request failed for https://api.github.com/repos/GROUP/repo-test-idp-page-5/contents/catalog-info.yaml?ref=main, 404 Not Found","plugin":"catalog","service":"backstage"}{"entity":"location:default/generated-dd36a29f1e19813211a9aee66f61c63cdb1229bd","level":"warn","location":"url:https://github.com/GROUP/repo-test-idp-page-1/tree/main/catalog-info.yaml","message":"Unable to read url, NotFoundError: Request failed for https://api.github.com/repos/GROUP/repo-test-idp-page-1/contents/catalog-info.yaml?ref=main, 404 Not Found","plugin":"catalog","service":"backstage"}{"entity":"location:default/generated-9fefa1829f35cd0294b7853c6b7d1a670cf813c2","level":"warn","location":"url:https://github.com/GROUP/repo-nest-idp-tst01/tree/main/catalog-info.yaml","message":"Unable to read url, NotFoundError: Request failed for https://api.github.com/repos/GROUP/repo-nest-idp-tst01/contents/catalog-info.yaml?ref=main, 404 Not Found","plugin":"catalog","service":"backstage"}{"entity":"location:default/generated-6d7d7e2ac24601d3086bfbe29645135da72a52fc","level":"warn","location":"url:https://github.com/GROUP/repo-nest-idp-tst03/tree/main/catalog-info.yaml","message":"Unable to read url, NotFoundError: Request failed for https://api.github.com/repos/GROUP/repo-nest-idp-tst03/contents/catalog-info.yaml?ref=main, 404 Not Found","plugin":"catalog","service":"backstage"}
```

Here is an example from an unprocessed entity:

```json
{
    "entity_id": "6f624e04-973a-4ed5-8d87-f0efee6993de",
    "entity_ref": "location:default/generated-f7e805c10e924a9dac83484932338213e2e65abd",
    "unprocessed_entity": {
        "apiVersion": "backstage.io/v1alpha1",
        "kind": "Location",
        "metadata": {
            "name": "generated-f7e805c10e924a9dac83484932338213e2e65abd",
            "annotations": {
                "backstage.io/managed-by-location": "url:https://github.com/GROUP/repo-test-idp-page-4/tree/main/catalog-info.yaml",
                "backstage.io/managed-by-origin-location": "url:https://github.com/GROUP/repo-test-idp-page-4/tree/main/catalog-info.yaml"
            }
        },
        "spec": {
            "type": "url",
            "target": "https://github.com/GROUP/repo-test-idp-page-4/tree/main/catalog-info.yaml"
        }
    },
    "processed_entity": null,
    "cache": {},
    "errors": [
        {
            "name": "NotFoundError",
            "message": "Unable to read url, NotFoundError: Request failed for https://api.github.com/repos/GROUP/repo-test-idp-page-4/contents/catalog-info.yaml?ref=main, 404 Not Found"
        }
    ],
    "next_update_at": "2024-10-09T05:19:00.384Z",
    "last_discovery_at": "2024-10-08T16:45:39.093Z",
    "location_key": "url:https://github.com/GROUP/repo-test-idp-page-4/tree/main/catalog-info.yaml",
    "result_hash": "257822efe323f2a3110cd7bdbe29108d867c5b6c",
    "unprocessed_hash": "7d98a08e5c8621c9f3fe28bca47bab4c63c6c640",
    "next_stitch_at": null,
    "next_stitch_ticket": null,
    "hash": "",
    "stitch_ticket": "6edf0c07-3ea8-47ec-b2a2-b82004468d7c",
    "final_entity": null,
    "last_updated_at": null,
    "tableData": {
        "id": 1,
        "uuid": "fce71456-fadd-4008-b09a-0165063b504f"
    }
}
```

Any idea how can I get rid of these? I tried to use:
```yaml
catalog:
  orphanStrategy: delete
```
But that also didn't help.

Thank you

### 👍 Expected behavior

Entities that have been removed from Backstage should not attempt to re-register.

### 👎 Actual Behavior with Screenshots

Behavior is in description.

### 👟 Reproduction steps

Restart container will restart Backstage app that will start searching those repos that not exists in catalog.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment] 2024-10-14 09:49
Could you provide the exact reproduction steps please? Especially the sequence and actions taken to register and then unregister the entity from the catalog before deleting the repo

**Comment by SmajlovicA** [comment] 2024-10-15 08:46
First thank you for response.

Here are steps to reproduce:

1. I will create GitHub repo using Backstage templates
2. Same Backstage template with last step register GitHub repo that is created in Catalog
3. I will then manually delete GitHub repo in GitHub UI
4. In Backstage catalog I will locate that Entity and go to Unregister which will offer to DELETE entity (I guess it does not offer unregister because it was deleted, maybe it is better step to unregister and then delete from GitHub repo but here is problem when I unregister because of Backstage & GitHub integration, entity will come back)
5. When I restart container that host Backstage app, I can find in logs that is trying to process Entity in Catalog that is deleted).

I have latest version 1.31.3 (backstage).

**Comment by Rugvip** [comment] 2024-10-17 08:59
@SmajlovicA alright, things are at least behaving as expected then. You do need to unregister the entity for it to go away permanently. Improving the user experience here is on our radar though, we're aware it's quite tricky to manage catalog items with certain setups at the moment. I'll close this since there's nothing actionable right now, but do keep an eye on #14574 for updates.

**Closed by Rugvip** 2024-10-17 08:59 UTC
Labels: bug, area:catalog
