### ISSUE TITLE
[Software Catalog] Catalog rules defined at catalog.locations configuration does not cover sub-locations

### ISSUE THREAD

**Issue by manusant** [backstage/backstage#7191] opened 2021-09-15 10:59 UTC
Catalog rules defined at catalog.locations configuration does not apply defined rules to sub-locations (Locations referenced by **_spec.targets_**) pointing to other resources.

## Current Behavior

Considering a location defined as:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: my-org-templates
  description: A collection of all my-org software templates
spec:
  targets:
    - ./location-1/template.yaml
    - ./location-2/template.yaml
    - ./location-3/template.yaml
```

sub/target locations defined as:
```yaml
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: docs-template
  title: Documentation Template
  description: Create a new standalone documentation project
spec:
  owner: ...
  type: ...
```
and Backstage configured for catalog ingestion in app-config.yaml as:
```yaml
catalog:
  rules:
    - allow: [ Component, API, Resource, Location ]
  locations:
    - type: url
      target: https://github.com/my-org/backstage/blob/develop/templates/all-templates.yaml
      rules:
        - allow: [ Template ]
```

From this configuration, the specified location should allow Component, API, Resource, Location and Template kinds but the sub-locations (e.g: ./location-1/template.yaml) are only allowing the globally allowed kinds (Component, API, Resource, Location) and completely ignoring the allow-rule _Template_ configured for upper/root location:
```yaml
- type: url
      target: https://github.com/my-org/backstage/blob/develop/templates/all-templates.yaml
      rules:
        - allow: [ Template ]
```
## Expected Behavior
Sub-location should also inherit rules from parent locations (not only the global ones).
Following the example configuration above all targets (sub-locations) of the specified location should have _Template_ kind allowed since the upper location allows it.

## Possible Solution
Not sure but probably a twick is needed in the current implementation to propagate rules applied on the upper location to the nested ones before catalog ingestion.

## Steps to Reproduce
Just use the scenario explained in the **Current Behavior** section and you will get a NotAllowed error when running the catalog ingestion.

## Context
This issue prevents us from configuring a proper access control when aggregating resources. This is especially important when different teams are contributing to the same backstage product.

## Your Environment

- NodeJS Version: 14
- Operating System and Version: MacOs an Linux

**Comment by freben** [comment] 2021-09-17 10:11
This is a duplicate of https://github.com/backstage/backstage/issues/5482. The problem still persists. I'll leave this one open for a bit longer to see if there's any additional feedback around the problem. See that other issue for some brief explanation of where we stand.

**Comment by freben** [comment] 2021-09-17 10:12
Oh, sorry - I mistakenly thought that the other issue was closed, but it (rightly) isn't. So let's close this one and focus the discussion over there. Apologies!

**Closed by freben** 2021-09-17 10:12 UTC
Labels: bug

**Comment by manusant** [comment] 2021-09-17 18:47
Yes agreed and sorry for the mess!
Thanks @freben
