### ISSUE TITLE
TechDocs: multiline YAML in `mkdocs.yml` leads to corrupted `techdocs_metadata.json`

### ISSUE THREAD

**Issue by martinohmann** [backstage/backstage#10277] opened 2022-03-17 15:11 UTC
## Expected Behavior

TechDocs are generated even if `mkdocs.yml` contains multiline YAML strings.

## Actual Behavior

The generator exits with an error due to a corrupted `techdocs_metadata.json`
(see log below).

## Steps to Reproduce

The following content of `mkdocs.yml` produces an error during TechDocs
generation:

```yaml
site_name: renovate-presets
site_description: |
  Reusable presets for the renovate dependency manager.

plugins:
  - techdocs-core
```

With the following `mkdocs.yml` snippet TechDocs are generated correctly:

```yaml
site_name: renovate-presets
site_description: 'Reusable presets for the renovate dependency manager.'

plugins:
  - techdocs-core
```

## Context

TechDocs build log:

```
info: Step 1 of 3: Preparing docs for entity component:default/renovate-presets {"timestamp":"2022-03-17T14:40:27.442Z"}
info: Prepare step completed for entity component:default/renovate-presets, stored at /tmp/backstage-HQhqaB {"timestamp":"2022-03-17T14:40:28.796Z"}
info: Step 2 of 3: Generating docs for entity component:default/renovate-presets {"timestamp":"2022-03-17T14:40:28.796Z"}
warn: docs/index.md not found. {"timestamp":"2022-03-17T14:40:28.798Z"}
warn: docs/README.md not found. {"timestamp":"2022-03-17T14:40:28.798Z"}
warn: docs/readme.md not found. {"timestamp":"2022-03-17T14:40:28.798Z"}
DEBUG    -  Loading configuration file: /tmp/backstage-HQhqaB/mkdocs.yml
DEBUG    -  Loaded theme configuration for 'mkdocs' from '/usr/local/lib/python3.7/dist-packages/mkdocs/themes/mkdocs/mkdocs_theme.yml': {'static_templates': ['404.html'], 'locale': 'en', 'include_search_page': False, 'search_index_only': False, 'highlightjs': True, 'hljs_languages': [], 'hljs_style': 'github', 'navigation_depth': 2, 'nav_style': 'primary', 'analytics': {'gtag': None}, 'shortcuts': {'help': 191, 'next': 78, 'previous': 80, 'search': 83}}
DEBUG    -  Config value: 'config_file_path' = '/tmp/backstage-HQhqaB/mkdocs.yml'
DEBUG    -  Config value: 'site_name' = 'renovate-presets'
DEBUG    -  Config value: 'nav' = None
DEBUG    -  Config value: 'pages' = None
DEBUG    -  Config value: 'site_url' = ''
DEBUG    -  Config value: 'site_description' = 'Reusable presets for the renovate dependency manager.\n'
DEBUG    -  Config value: 'site_author' = None
DEBUG    -  Config value: 'theme' = Theme(name='mkdocs', dirs=['/usr/local/lib/python3.7/dist-packages/mkdocs/themes/mkdocs', '/usr/local/lib/python3.7/dist-packages/mkdocs/templates'], static_templates=['404.html', 'sitemap.xml'], locale=Locale(language='en', territory=''), include_search_page=False, search_index_only=False, highlightjs=True, hljs_languages=[], hljs_style='github', navigation_depth=2, nav_style='primary', analytics={'gtag': None}, shortcuts={'help': 191, 'next': 78, 'previous': 80, 'search': 83})
DEBUG    -  Config value: 'docs_dir' = '/tmp/backstage-HQhqaB/docs'
DEBUG    -  Config value: 'site_dir' = '/tmp/techdocs-tmp-et7WX4'
DEBUG    -  Config value: 'copyright' = None
DEBUG    -  Config value: 'google_analytics' = None
DEBUG    -  Config value: 'dev_addr' = Address(host='127.0.0.1', port=8000)
DEBUG    -  Config value: 'use_directory_urls' = True
DEBUG    -  Config value: 'repo_url' = ''
DEBUG    -  Config value: 'repo_name' = ''
DEBUG    -  Config value: 'edit_uri' = ''
DEBUG    -  Config value: 'extra_css' = []
DEBUG    -  Config value: 'extra_javascript' = []
DEBUG    -  Config value: 'extra_templates' = []
DEBUG    -  Config value: 'markdown_extensions' = ['toc', 'tables', 'fenced_code']
DEBUG    -  Config value: 'mdx_configs' = {}
DEBUG    -  Config value: 'strict' = False
DEBUG    -  Config value: 'remote_branch' = 'gh-pages'
DEBUG    -  Config value: 'remote_name' = 'origin'
DEBUG    -  Config value: 'extra' = {}
DEBUG    -  Config value: 'plugins' = PluginCollection([('techdocs-core', <src.core.TechDocsCore object at 0x7fd50b5c0f60>)])
DEBUG    -  Loaded theme configuration for 'material' from '/usr/local/lib/python3.7/dist-packages/material/mkdocs_theme.yml': {'language': 'en', 'direction': None, 'features': [], 'palette': {'primary': None, 'accent': None}, 'font': {'text': 'Roboto', 'code': 'Roboto Mono'}, 'icon': None, 'favicon': 'assets/images/favicon.png', 'include_search_page': False, 'search_index_only': True, 'static_templates': ['404.html']}
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /tmp/techdocs-tmp-et7WX4
DEBUG    -  Reading markdown pages.
DEBUG    -  Reading: index.md
DEBUG    -  Copying static assets.
DEBUG    -  Copying media file: 'assets/images/favicon.png'
DEBUG    -  Copying media file: 'assets/javascripts/bundle.7f4f3c92.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/bundle.7f4f3c92.min.js.map'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.ar.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.da.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.de.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.du.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.es.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.fi.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.fr.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.hu.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.it.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.ja.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.jp.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.multi.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.nl.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.no.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.pt.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.ro.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.ru.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.stemmer.support.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.sv.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.tr.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/min/lunr.vi.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/lunr/tinyseg.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/vendor.d710d30a.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/vendor.d710d30a.min.js.map'
DEBUG    -  Copying media file: 'assets/javascripts/worker/search.9b3611bd.min.js'
DEBUG    -  Copying media file: 'assets/javascripts/worker/search.9b3611bd.min.js.map'
DEBUG    -  Copying media file: 'assets/stylesheets/main.fe0cca5b.min.css'
DEBUG    -  Copying media file: 'assets/stylesheets/main.fe0cca5b.min.css.map'
DEBUG    -  Copying media file: 'assets/stylesheets/palette.a46bcfb3.min.css'
DEBUG    -  Copying media file: 'assets/stylesheets/palette.a46bcfb3.min.css.map'
DEBUG    -  Building theme template: 404.html
DEBUG    -  Building theme template: sitemap.xml
DEBUG    -  Gzipping template: sitemap.xml
DEBUG    -  Building theme template: techdocs_metadata.json
DEBUG    -  Building markdown pages.
DEBUG    -  Building page index.md
INFO     -  Documentation built in 0.24 seconds
info: Successfully generated docs from /tmp/backstage-HQhqaB into /tmp/techdocs-tmp-et7WX4 using local mkdocs {"timestamp":"2022-03-17T14:40:29.354Z"}
error: Invalid JSON at /tmp/techdocs-tmp-et7WX4/techdocs_metadata.json with error /tmp/techdocs-tmp-et7WX4/techdocs_metadata.json: Unexpected token 
 in JSON at position 113 {"timestamp":"2022-03-17T14:40:29.355Z"}
error: Failed to build the docs page: Invalid JSON at /tmp/techdocs-tmp-et7WX4/techdocs_metadata.json with error /tmp/techdocs-tmp-et7WX4/techdocs_metadata.json: Unexpected token 
```

## Your Environment

- Output of `yarn backstage-cli info`:

```text
OS:   Darwin 20.6.0 - darwin/arm64
node: v16.9.0
yarn: 1.22.11
cli:  0.15.3 (installed)

Dependencies:
  @backstage/app-defaults                            0.2.1
  @backstage/backend-common                          0.13.0
  @backstage/backend-tasks                           0.2.0
  @backstage/catalog-client                          0.9.0
  @backstage/catalog-model                           0.13.0
  @backstage/cli-common                              0.1.8
  @backstage/cli                                     0.15.3
  @backstage/config-loader                           0.9.7
  @backstage/config                                  0.1.15
  @backstage/core-app-api                            0.6.0
  @backstage/core-components                         0.9.1
  @backstage/core-plugin-api                         0.8.0
  @backstage/errors                                  0.2.2
  @backstage/integration-react                       0.1.25
  @backstage/integration                             0.8.0
  @backstage/plugin-api-docs                         0.8.2
  @backstage/plugin-app-backend                      0.3.29
  @backstage/plugin-auth-backend                     0.12.1
  @backstage/plugin-auth-node                        0.1.5
  @backstage/plugin-catalog-backend-module-aws       0.1.2
  @backstage/plugin-catalog-backend-module-bitbucket 0.1.0
  @backstage/plugin-catalog-backend-module-github    0.1.0
  @backstage/plugin-catalog-backend-module-msgraph   0.2.19
  @backstage/plugin-catalog-backend                  0.24.0
  @backstage/plugin-catalog-common                   0.2.2
  @backstage/plugin-catalog-graph                    0.2.14
  @backstage/plugin-catalog-import                   0.8.5
  @backstage/plugin-catalog-react                    0.9.0
  @backstage/plugin-catalog                          0.10.0
  @backstage/plugin-explore-react                    0.0.14
  @backstage/plugin-explore                          0.3.33
  @backstage/plugin-github-actions                   0.5.2
  @backstage/plugin-org                              0.5.2
  @backstage/plugin-permission-common                0.5.2
  @backstage/plugin-permission-node                  0.5.4
  @backstage/plugin-permission-react                 0.3.3
  @backstage/plugin-proxy-backend                    0.2.23
  @backstage/plugin-scaffolder-backend               0.18.0
  @backstage/plugin-scaffolder-common                0.3.0
  @backstage/plugin-scaffolder                       0.15.0
  @backstage/plugin-search-backend-node              0.5.1
  @backstage/plugin-search-backend                   0.4.7
  @backstage/plugin-search-common                    0.3.1
  @backstage/plugin-search                           0.7.3
  @backstage/plugin-tech-radar                       0.5.9
  @backstage/plugin-techdocs-backend                 0.14.2
  @backstage/plugin-techdocs-node                    0.11.12
  @backstage/plugin-techdocs                         0.15.1
  @backstage/plugin-user-settings                    0.4.1
  @backstage/release-manifests                       0.0.2
  @backstage/search-common                           0.3.1
  @backstage/test-utils                              0.3.0
  @backstage/theme                                   0.2.15
  @backstage/types                                   0.1.3
  @backstage/version-bridge                          0.1.2
?  Done in 0.98s.
```

**Comment by pjungermann** [comment] 2022-03-29 13:21
the cause seems to be at https://github.com/backstage/mkdocs-techdocs-core/blob/main/src/core.py#L38

**Comment by soapraj** [comment] 2022-04-01 08:20
@martinohmann - does https://github.com/backstage/mkdocs-techdocs-core/pull/58 solve the issue? can this ticket be closed?

**Comment by pjungermann** [comment] 2022-04-01 10:41
@soapraj the change is not yet released there and afterwards, it might make sense to update at least some docs as well as the docker image version used for the "docker" build option of techdocs

**Comment by garyniemen** [comment] 2022-04-26 12:34
Just following up again @pjungermann and @martinohmann  - is the issue solved? Do you think you can update the relevant docs (as you mention above).

**Comment by martinohmann** [comment] 2022-05-10 07:18
@garyniemen https://github.com/backstage/mkdocs-techdocs-core/pull/58 solves the issue, but since it was merged there hasn't been a new release of the techdocs mkdocs plugin to pypi yet.

I would consider this issue solved when the fix is released to pypi so that users can switch to the latest `mkdocs-techdocs-core` version.

**Comment by martinohmann** [comment] 2022-05-11 08:33
A new version of the `mkdocs-techdocs-core` plugin was released yesterday: https://pypi.org/project/mkdocs-techdocs-core/1.0.2/. It includes the fix even though it's not explicitly mentioned in the changelog.

@pjungermann which docs update are you referring to? I don't think that this bug fix requires special documentation as it's a non-breaking change.

As far as I'm concerned this issue can be closed now.

**Comment by emmaindal** [comment] 2022-05-13 06:53
Thanks for confirming @martinohmann I'll close this issue!

**Closed by emmaindal** 2022-05-13 06:53 UTC
Labels: bug, docs-like-code
