### ISSUE TITLE
🐛 Bug Report: Search broken in v1.27.0 ?

### ISSUE THREAD

**Issue by c4rth** [backstage/backstage#24769] opened 2024-05-14 15:38 UTC
### 📜 Description

In my installation of Backstage v1.26.4 with PostgreSQL database, the search worked fine.
After update to v1.27.0 with `yarn backstage-cli versions:bump`, the search doesn't seem to work anymore.
As I have a catalogCollatorExtensionPoint, I remove it and try again, same issue.
I tried searching on techdocs content, user and group.

### 👍 Expected behavior

Search should return some results.

### 👎 Actual Behavior with Screenshots

Search from Techdocs page:
<img width="1265" alt="Screenshot 2024-05-14 at 17 32 45" src="https://github.com/backstage/backstage/assets/8505625/6e185824-c5e0-40c0-a843-9a1064e9e7d7">

Search from sidebar:
<img width="1654" alt="Screenshot 2024-05-14 at 17 34 00" src="https://github.com/backstage/backstage/assets/8505625/2d63ea0d-9bb9-4dd8-9faa-85bff469fad7">

### 👟 Reproduction steps

- update Backstage to v1.27.0
- start it 
- go to search

### 🖥️ Your Environment

```
OS:   Darwin 23.4.0 - darwin/arm64
node: v20.12.0
yarn: 1.22.22
cli:  0.26.5 (installed)
backstage:  1.27.0

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.3
  @backstage/backend-common                                        0.21.7, 0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/backend-test-utils                                    0.3.8
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.5
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.32
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.66
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-azure                   0.1.38
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.26
  @backstage/plugin-catalog-backend-module-openapi                 0.1.36
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.11.0
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-home-react                                     0.1.13
  @backstage/plugin-home                                           0.7.4
  @backstage/plugin-notifications-backend                          0.2.1
  @backstage/plugin-notifications-common                           0.0.3
  @backstage/plugin-notifications-node                             0.1.4
  @backstage/plugin-notifications                                  0.2.1
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.6
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.4.4
  @backstage/plugin-scaffolder-react                               1.8.5
  @backstage/plugin-scaffolder                                     1.20.0
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-pg                       0.5.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.22
  @backstage/plugin-search-backend                                 1.5.8
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-signals-backend                                0.1.4
  @backstage/plugin-signals-node                                   0.1.4
  @backstage/plugin-signals-react                                  0.0.3
  @backstage/plugin-signals                                        0.0.6
  @backstage/plugin-techdocs-addons-test-utils                     1.0.32
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.5.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
  ```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment] 2024-05-14 15:40
There's a chance that this is fixed by https://github.com/backstage/backstage/pull/24767, as it's in search that we discovered the issue

**Comment by brianphillips** [comment] 2024-05-14 23:42
I'm not sure if this is the same issue but the search backend endpoint is returning a 400 after the 1.27.0 upgrade ([discord thread](https://discord.com/channels/687207715902193673/770283289327566848/1240050352435494994))

```json
{
  "error": {
    "name": "InputError",
    "message": "Invalid query string: [\n  {\n    \"code\": \"custom\",\n    \"message\": \"Invalid input\",\n    \"path\": [\n      \"types\",\n      0\n    ]\n  }\n]"
  },
  "request": {
    "method": "GET",
    "url": "/query?term=backstage&types%5B0%5D=software-catalog"
  },
  "response": {
    "statusCode": 400
  }
}```

**Comment by Rugvip** [comment] 2024-05-15 09:13
Yep, that doesn't look like the same issue. `1.27.1` is out now with the above fix too

**Comment by Rugvip** [comment] 2024-05-16 10:41
Closing this as a duplicate of #24794 since a fix is being worked on there

**Closed by Rugvip** 2024-05-16 10:41 UTC
Labels: bug, area:discoverability
