### ISSUE TITLE
HttpError: Not Found when publishing GitHub repo with scaffolder

### ISSUE THREAD

**Issue by timja** [backstage/backstage#8263] opened 2021-11-26 15:58 UTC
## Expected Behavior

No error

## Current Behavior

GitHub API returns not found sometimes as it's eventually consistent

Code here is bombing out:
https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts#L169-L186

## Possible Solution

Thinking of either trying to retrieve from GitHub API or just adding in some retries

## Steps to Reproduce

1. scaffold with a template that adds github teams
2. attempt a few times, I've had it happen to me 2 out of ~15 tries
3. ...

## Context

Other blocks in the GitHub publisher have `try .. catch .. log` but that's a terrible pattern as the user will likely never see it.
This needs proper hardening.

Discussed with @benjdlambert at https://discord.com/channels/687207715902193673/913812564750766150/913819958193045536

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by jhaals** [comment] 2021-12-02 14:41
Awesome, thanks for taking a look!

**Comment by Crevil** [comment] 2022-01-21 09:11
@timja did you find the time to look into this? Otherwise I'd like to give it a go. 😄

**Comment by timja** [comment] 2022-01-21 09:53
I had a brief go at it, but didn't finish it off. Feel free

**Comment by Crevil** [comment] 2022-01-26 09:19
I'm starting work on this this week 🎉

**Comment by Crevil** [comment] 2022-01-26 09:19
@jhaals maybe you can reasign me on this issue to reflect above? 🙏

**Comment by benjdlambert** [comment] 2022-01-26 09:52
Done!

**Comment by Crevil** [comment] 2022-01-26 19:29
So looking a bit further into this I can see we use `@octokit/rest` in quite a lot of places. Should we go about this by updating usage from the deprecated package in only the scaffolder (to fix this specific issue) or should I go for migrating away from the package all together as a cleanup and then we can come back to this? 🤔 

WDYT @benjdlambert @jhaals ?

**Comment by Crevil** [comment] 2022-01-26 19:48
FWIW I started work with a commit only migrated the scaffolder backend to get an idea of the impact. So for it looks fine: https://github.com/lunarway/backstage/commit/8d49dc2eef3b2cd279c85a7d71b3c7d971950c3c

**Comment by benjdlambert** [comment] 2022-01-26 20:18
Hmm I think it's fine to have a go and migrate us off in the scaffolder at least for now. Looks like there could be some migration stuff with the GitHub App authentication that we might need to double check that it's gonna work but looks ok so far I think!

**Comment by Crevil** [comment] 2022-01-26 20:35
Got it. I'll send a PR for that as a first 👍

**Comment by Crevil** [comment] 2022-02-06 19:41
With the upgrade to `octokit` in #9189 I have been unable to recreate this issue locally.
It was released in `@backstage/plugin-scaffolder-backend@0.15.23`.

Should we close this issue and reopen if it turns up again?

By default octokit will retry requests 3 times with a 1 second base timeout (with some jitter and exponensial backoff).

**Comment by timja** [comment] 2022-02-06 19:45
Sure nice work

**Comment by peimanja** [comment] 2022-03-11 21:13
I hit this twice today after upgrading to Backstage 0.71.1. confirmed 
```

**Comment by peimanja** [comment] 2022-03-11 22:07
more specific error message would also help :)

**Comment by peimanja** [comment] 2022-03-14 01:13
Ignore me. This was due to wrong team passed to `access` 🤦‍♂️ 
However I still like to see better logging to understand better what is failing

**Comment by Crevil** [comment] 2022-03-14 05:33
I guess that is covered by #9208? 🙏

**Comment by timja** [comment] 2022-03-14 08:11
Not sure if it is covered by that that's a git error message rather than an API error message

**Closed** 2022-03-14 08:10 UTC
Labels: bug, good first issue, scaffolder

**Comment by timja** [comment] 2022-03-14 08:13
Created https://github.com/backstage/backstage/issues/10160 as a follow up
