### ISSUE TITLE
🐛 Bug Report: Entity Validator Plugin: file location not changeable

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#16490] opened 2023-02-21 11:14 UTC
### 📜 Description

The required file location field has a default location. The content of this text field cannot be modified.

Overall, it also raised the question if this is really required. At the PR I see that there is a fallback to use localhost which seems like never to be used or at least not really communicated as optional due to it being required.

Relates to issue #9245 and PR #16050.

### 👍 Expected behavior

I can change the URL.

### 👎 Actual Behavior with Screenshots

I cannot change the URL.

### 👟 Reproduction steps

1. Add the plugin according to its installation steps.
2. Go to `/entity-validation`
3. Try to change the "File Location" field content.

### 🖥️ Your Environment

Backstage 1.11.1 with `"@backstage/plugin-entity-validation": "^0.1.0"`. Chrome browser.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by pjungermann** [comment] 2023-02-21 11:16
Questions about whether `locationUrl` itself is required was answered here:
https://github.com/backstage/backstage/pull/16050#issuecomment-1434251554

Due to the fallback, the field itself could be optional, though.

**Comment by pjungermann** [comment] 2023-02-21 11:23
I also tried setting `<EntityValidationPage defaultLocation="" />` however the field just stays empty and stays unchangeable.

**Comment by elizabeth-a-hobbs** [comment] 2023-02-21 16:19
FYI this appears to be a duplicate of #16406 which already has some comments & a PR attached to it!

**Comment by pjungermann** [comment] 2023-02-21 16:22
duplicate of #16409

**Comment by freben** [comment] 2023-02-23 09:21
Seems to be fixed - closing! Ping @webark

**Closed by freben** 2023-02-23 09:21 UTC
Labels: bug

**Comment by webark** [comment] 2023-02-23 11:48
are you able to release a patch fix just for this one plugin? or is it tied to a whole backstage release.
