### ISSUE TITLE
Errors when building Host using Dockerfile provided with create-app

### ISSUE THREAD

**Issue by iress-mm** [backstage/backstage#4841] opened 2021-03-05 15:30 UTC
## Expected Behavior

Host image builds with no errors.

## Current Behavior

Errors being thrown for Python, pkg-config and libsecret as missing.

## Possible Solution

A workaround for the python issue is to use the node:14-buster base image rather than node:14-buster-slim.

## Steps to Reproduce

1. Create Backstage app by running the create-app (with Postgres)
2. From the root folder, run -> docker image build . -f packages/backend/Dockerfile -t backstage_host
3. Missing Python errors:
[5/5] Building fresh packages...
...
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
...
4. Add to the Dockerfile (before yarn install) -> RUN apt-get update || : && apt-get install python -y
5. Run docker build again, receive error:
[5/5] Building fresh packages...
...
/bin/sh: 1: pkg-config: not found
7. Add to the Dockerfile (before yarn install) -> RUN apt-get install pkg-config -y
8. Run docker build again, receive error:
[5/5] Building fresh packages...
...
No package 'libsecret-1' found
9. Add to the Dockerfile (before yarn install) -> RUN apt-get install libsecret-1-dev -y
10. Build completes with no errors

## Context

Building a backend host docker image locally.

## Your Environment

Node 14.16.0
Ubuntu 20.04
Docker Engine 20.10.5

VS Code 1.54.1

I'm new to Backstage, so this may be an entirely localised problem!!

**Comment by benjdlambert** [comment] 2021-03-09 09:55
@iress-mm did you add any other dependencies to your `node_modules` after using `create-app`? I'm unable to reproduce this with a fresh `npx @backstage/create-app` with `postgres`. I just get the normal warnings which can be ignored as stated.

**Comment by benjdlambert** [comment] 2021-03-09 12:46
Hmm - yeah I'm thinking that because there's this: 

```
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/app/node_modules/keytar: Command failed.
Exit code: 1
```

It's actually OK that it fails. It still continues right and completes successfully? And everything builds as expected?

**Comment by iress-mm** [comment] 2021-03-09 13:39
@benjdlambert  I've walked through from the beginning and you're absolutely right!

I think at the time I was experiencing other issues and that amount of red made me think it was part of the problem. If you don't mind a suggestion, it would be worth mentioning that in the docs.

Thanks for looking into it.

**Comment by benjdlambert** [comment] 2021-03-09 13:47
No worries, gonna close this ticket, but feel free to shout if there's anything else that pops up!

**Closed by benjdlambert** 2021-03-09 13:47 UTC
Labels: bug
