### ISSUE TITLE
🐛 Bug Report: Scaffolder - the behaviour of links in descriptions is not consistent

### ISSUE THREAD

**Issue by dejanbelusic** [backstage/backstage#27747] opened 2024-11-20 16:26 UTC
### 📜 Description

Looking at the `ScaffolderField` component, I can see that the links in the field descriptions will be opened in the new tab.
The code in question is the following: 
```
  <MarkdownContent
    content={rawDescription}
    linkTarget="_blank"
    className={classes.markdownDescription}
  />
```

When I look at the `Workflow` component I can see that the description field does not open links in the new tab.
```
  <MarkdownContent
    className={styles.markdown}
    content={
      description ?? sortedManifest.description ?? 'No description'
    }
  />
```

Same with the `DescriptionFieldTemplate`, which is used to render the description above the Form, the links are opening in the same tab.
```
  <MarkdownContent
    content={description}
    className={classes.markdownDescription}
  />
```

### 👍 Expected behavior

I would expect all the links from descriptions within the scaffolder to be opened in the new tab. 

That would ensure consistency, and when the user clicks on the link in the description, a new tab would open, and the user wouldn't lose the data he already filled in the form.

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-11-20 at 17 17 11](https://github.com/user-attachments/assets/63f986a0-4ff2-4e35-98dc-c89943f570e0)

The link in the template and step description will open in the same tabs, but the link in the field description will open in the new tab.

### 👟 Reproduction steps

Create a template and add links into descriptions for the template, step, and fields. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment] 2024-11-21 10:41
Sounds like a good improvement, do you want to raise a PR with the fix here? :pray:

**Comment by dejanbelusic** [comment] 2024-11-21 11:01
Yes, I can do that, will raise a PR shortly.

**Comment by GersonTrj** [comment] 2024-11-26 09:59
hi @dejanbelusic, how do you manage to have the links working in the scaffolder fields? 

I have this in my project, and none of the links are rendered as hyperlinks:
```     system:
          title: System
          type: string
          description: "You can add more systems [here](docslink)."
          ui:field: EntityPicker
          ui:help: "You can add more systems [here](docslink)."

**Comment by dejanbelusic** [comment] 2024-11-26 10:38
> hi @dejanbelusic, how do you manage to have the links working in the scaffolder fields?
> 
> I have this in my project, and none of the links are rendered as hyperlinks:
> 
> ```
>           title: System
>           type: string
>           description: "You can add more systems [here](docslink)."
>           ui:field: EntityPicker
>           ui:help: "You can add more systems [here](docslink)."
> ```

Hi @GersonTrj, looks like the `ScaffolderField` component is used in the default text fields but not in the custom fields. I also took a look at the `EntityPicker` field you are using and it looks to me like that would require some refactoring to get it working with the markdown, and that would be outside the scope of this issue. 

Feel free to request this update with the backstage maintainers/community.

**Comment by dejanbelusic** [comment] 2024-11-26 11:55
> Sounds like a good improvement, do you want to raise a PR with the fix here? 🙏

Hi @benjdlambert, the PR is open, feel free to review it: https://github.com/backstage/backstage/pull/27828.

**Comment by GersonTrj** [comment] 2024-11-26 11:59
hi @dejanbelusic but the description field I am using is not part of the entity picker right?

**Comment by dejanbelusic** [comment] 2024-11-26 12:37
> hi @dejanbelusic but the description field I am using is not part of the entity picker right?

Based on this line of code ui:field: `EntityPicker`, I would say you are using an Entity Picker custom field. Or I'm missing something here?

**Comment by GersonTrj** [comment] 2024-11-27 14:58
Sorry I thought that the description is not part of the entityPicker field since I can also use it for a string for example:

```
    properties:
      name:
        title: Component Name
        type: string
        description: "You can add more systems [here](docslink)."
        maxLength: 63
        pattern: ^[a-zA-Z0-9]+(?:[-_.][a-zA-Z0-9]+)*$
        ui:autofocus: true
```
But I was wrong, I just checked that this string type description renders as a link properly so the issue is indeed linked to the entityPicker as you mentioned.

**Comment by benjdlambert** [comment] 2024-11-29 15:51
Going to close this now as this relates to the https://github.com/backstage/backstage/pull/27828 PR. 

@GersonTrj do you want to open a seperate issue for the EntityPicker issue?

**Closed** 2024-11-29 15:51 UTC
Labels: bug, area:scaffolder
