### ISSUE TITLE
🐛 Bug Report: View full search results link in Search modal is missing href property in 1.15.0

### ISSUE THREAD

**Issue by ciprianna** [backstage/backstage#18381] opened 2023-06-21 20:13 UTC
### 📜 Description

`href` is missing from the `View Full Results ->` button in the Search modal on version 1.15.0.

### 👍 Expected behavior

The button is a link that takes users to the full search results page.

### 👎 Actual Behavior with Screenshots

The `href` property is missing from the link, and does not take the user anywhere.

<img width="1734" alt="Screenshot 2023-06-21 at 2 35 39 PM" src="https://github.com/backstage/backstage/assets/8051967/c85ea870-b877-4799-b1eb-89548ff51685">

### 👟 Reproduction steps

- Update to at least version 1.15.0.
- Search for something in the sidebar, opening the modal
- Attempt to click on the `View Full Results` button and notice it does not go anywhere

### 🖥️ Your Environment

```
OS:   Darwin 22.5.0 - darwin/x64
node: v18.16.0
yarn: 1.22.0
cli:  0.22.8 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                          1.4.0
  @backstage/backend-app-api                       0.4.4
  @backstage/backend-common                        0.18.5, 0.19.0
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.3
  @backstage/backend-tasks                         0.5.3
  @backstage/catalog-client                        1.4.2
  @backstage/catalog-model                         1.4.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.1
  @backstage/cli                                   0.22.8
  @backstage/config-loader                         1.3.1
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.8.1
  @backstage/core-components                       0.12.5, 0.13.2
  @backstage/core-plugin-api                       1.5.2
  @backstage/dev-utils                             1.0.16
  @backstage/errors                                1.2.0
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.4
  @backstage/integration-react                     1.1.14
  @backstage/integration                           1.5.0
  @backstage/plugin-adr-backend                    0.3.4
  @backstage/plugin-adr-common                     0.2.10
  @backstage/plugin-adr                            0.6.2
  @backstage/plugin-api-docs                       0.9.5
  @backstage/plugin-app-backend                    0.3.46
  @backstage/plugin-auth-backend                   0.18.4
  @backstage/plugin-auth-node                      0.2.15
  @backstage/plugin-catalog-backend-module-github  0.3.1
  @backstage/plugin-catalog-backend                1.10.0
  @backstage/plugin-catalog-common                 1.0.14
  @backstage/plugin-catalog-graph                  0.2.31
  @backstage/plugin-catalog-import                 0.9.9
  @backstage/plugin-catalog-node                   1.3.7
  @backstage/plugin-catalog-react                  1.7.0
  @backstage/plugin-catalog                        1.11.2
  @backstage/plugin-cloudbuild                     0.3.19
  @backstage/plugin-events-backend-module-github   0.1.8
  @backstage/plugin-events-backend                 0.2.7
  @backstage/plugin-events-node                    0.2.7
  @backstage/plugin-github-actions                 0.6.0
  @backstage/plugin-home-react                     0.1.0
  @backstage/plugin-home                           0.5.3
  @backstage/plugin-org                            0.6.9
  @backstage/plugin-permission-common              0.7.6
  @backstage/plugin-permission-node                0.7.9
  @backstage/plugin-permission-react               0.4.13
  @backstage/plugin-proxy-backend                  0.2.40
  @backstage/plugin-scaffolder-backend             1.15.0
  @backstage/plugin-scaffolder-common              1.3.1
  @backstage/plugin-scaffolder-node                0.1.4
  @backstage/plugin-scaffolder-react               1.5.0
  @backstage/plugin-scaffolder                     1.14.0
  @backstage/plugin-search-backend-module-catalog  0.1.2
  @backstage/plugin-search-backend-module-pg       0.5.7
  @backstage/plugin-search-backend-module-techdocs 0.1.2
  @backstage/plugin-search-backend-node            1.2.2
  @backstage/plugin-search-backend                 1.3.2
  @backstage/plugin-search-common                  1.2.4
  @backstage/plugin-search-react                   1.6.2
  @backstage/plugin-search                         1.3.2
  @backstage/plugin-tech-radar                     0.6.5
  @backstage/plugin-techdocs-backend               1.6.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.14
  @backstage/plugin-techdocs-node                  1.7.2
  @backstage/plugin-techdocs-react                 1.1.7
  @backstage/plugin-techdocs                       1.6.4
  @backstage/plugin-todo-backend                   0.1.43
  @backstage/plugin-todo                           0.2.21
  @backstage/plugin-user-settings                  0.7.4
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.0
  @backstage/theme                                 0.2.19, 0.4.0
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
✨  Done in 1.42s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ciprianna** [comment] 2023-06-22 03:15
Looks like the `plugin-search` version `1.3.2` includes this commit: https://github.com/backstage/backstage/pull/18236. Changelog [here](https://github.com/backstage/backstage/blob/master/docs/releases/v1.15.0-changelog.md#patch-changes-167.). The 1.15.0-next-3 version didn't have this issue, but also didn't have that commit according to the [changelog](https://github.com/backstage/backstage/blob/master/docs/releases/v1.15.0-next.3-changelog.md#backstageplugin-search132-next3). So I think it's isolated to that diff, but I haven't dug into the why yet to test it out.

**Comment by albibanushi** [comment] 2023-06-23 09:36
I want to add that all `software-catalog` search results are missing links on this release.

None of the below components are clickable, they are just text.

<img width="894" alt="backstage-search" src="https://github.com/backstage/backstage/assets/58179420/5cb80279-1512-460f-b62c-bed613bb9275">

**Comment by awanlin** [comment] 2023-06-23 16:52
That's odd, I don't have that issue @albibanushi. How about for you @ciprianna are the links on the results page missing for you as well?

**Comment by ciprianna** [comment] 2023-06-23 17:02
No, I'm not seeing that as an issue in our instance either.

**Comment by albibanushi** [comment] 2023-06-24 13:28
hi @awanlin @ciprianna 
It looks like the link is covered by a `span`. I am not sure if the bug is introduced by any MUI5 change but it happened after this commit.
We quick fixed it by setting:
```
  MuiChip: {
      labelSmall: {
        lineHeight: 2,
      },
    },
```
<img width="1161" alt="backstage-search2" src="https://github.com/backstage/backstage/assets/58179420/613b196d-1b65-443b-af6b-d3e07093e57d">

**Comment by pc-bob** [comment] 2023-07-10 23:38
I am able to reproduce this issue in the backstage demo instance: https://demo.backstage.io/catalog

When searching for something, click on the "view full results" button and observe that it doesn't do anything.

<img width="2042" alt="Screenshot 2023-07-10 at 4 37 29 PM" src="https://github.com/backstage/backstage/assets/94858151/50b1763c-966c-4815-99d9-eb0f6420e0a8">

**Comment by awanlin** [comment] 2023-07-10 23:48
Thanks @pc-bob, that issue has been fixed by @ciprianna PR here: https://github.com/backstage/backstage/pull/18407, but both @jrkt and @albibanushi are having a different issue which probably should be logged in a separate issue of its own

**Closed** 2023-07-11 13:55 UTC
Labels: bug, search, area:discoverability
