### ISSUE TITLE
🐛 Bug Report: EntityPicker crashes page with 1.28.2 and large catalog

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#25340] opened 2024-06-20 11:38 UTC
### 📜 Description

Earlier it was possible to use `EntityPicker` in scaffolder templates with a large amount of data in the catalog (For example 5k users and using `OwnerPicker`). After upgrading to 1.28.2, the page freezes due to the picker loading entity representation API for the titles + icons etc. for the entities. 

### 👍 Expected behavior

The page should not freeze

### 👎 Actual Behavior with Screenshots

Page freezes loading the entity presentation 

### 👟 Reproduction steps

1. Create a large catalog, for example with User entities, 5k is enough
2. Create a scaffolder template with OwnerPicker
3. Start the template and try to select a user from the picker

### 📃 Provide the context for the Bug.

Related issue: #25243
Related PR: #23283 (to make it work without entity presentation API and with only catalog)
Original PR: #24081
PR that might help: #25315

Location in code:
https://github.com/backstage/backstage/blob/e1cd125981e14a746810834ba21e83e22655a288/plugins/scaffolder/src/components/fields/EntityPicker/EntityPicker.tsx#L92

### 🖥️ Your Environment

OS:   Darwin 23.5.0 - darwin/arm64
node: v18.19.0
yarn: 1.22.22
cli:  0.26.9 (installed)
backstage:  1.28.2

Dependencies:
  @backstage/app-defaults                                            1.5.6
  @backstage/backend-app-api                                         0.7.8
  @backstage/backend-common                                          0.21.7, 0.22.0, 0.23.1
  @backstage/backend-defaults                                        0.2.18, 0.3.2
  @backstage/backend-dev-utils                                       0.1.4
  @backstage/backend-openapi-utils                                   0.1.13
  @backstage/backend-plugin-api                                      0.6.20
  @backstage/backend-tasks                                           0.5.25
  @backstage/backend-test-utils                                      0.4.2
  @backstage/catalog-client                                          1.6.5
  @backstage/catalog-model                                           1.5.0
  @backstage/cli-common                                              0.1.14
  @backstage/cli-node                                                0.2.6
  @backstage/cli                                                     0.26.9
  @backstage/config-loader                                           1.8.1
  @backstage/config                                                  1.2.0
  @backstage/core-app-api                                            1.12.6
  @backstage/core-compat-api                                         0.2.6
  @backstage/core-components                                         0.14.8
  @backstage/core-plugin-api                                         1.9.3
  @backstage/dev-utils                                               1.0.33
  @backstage/e2e-test-utils                                          0.1.1
  @backstage/errors                                                  1.2.4
  @backstage/eslint-plugin                                           0.1.8
  @backstage/frontend-plugin-api                                     0.6.6
  @backstage/integration-aws-node                                    0.1.12
  @backstage/integration-react                                       1.1.28
  @backstage/integration                                             1.12.0
  @backstage/plugin-api-docs                                         0.11.6
  @backstage/plugin-app-backend                                      0.3.69
  @backstage/plugin-app-node                                         0.1.20
  @backstage/plugin-auth-backend-module-atlassian-provider           0.2.1
  @backstage/plugin-auth-backend-module-aws-alb-provider             0.1.12
  @backstage/plugin-auth-backend-module-azure-easyauth-provider      0.1.3
  @backstage/plugin-auth-backend-module-bitbucket-provider           0.1.3
  @backstage/plugin-auth-backend-module-cloudflare-access-provider   0.1.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider             0.2.15
  @backstage/plugin-auth-backend-module-github-provider              0.1.17
  @backstage/plugin-auth-backend-module-gitlab-provider              0.1.17
  @backstage/plugin-auth-backend-module-google-provider              0.1.17
  @backstage/plugin-auth-backend-module-guest-provider               0.1.6
  @backstage/plugin-auth-backend-module-microsoft-provider           0.1.15
  @backstage/plugin-auth-backend-module-oauth2-provider              0.2.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider        0.1.13
  @backstage/plugin-auth-backend-module-oidc-provider                0.2.1
  @backstage/plugin-auth-backend-module-okta-provider                0.0.13
  @backstage/plugin-auth-backend-module-onelogin-provider            0.1.1
  @backstage/plugin-auth-backend                                     0.22.7
  @backstage/plugin-auth-node                                        0.4.15
  @backstage/plugin-auth-react                                       0.1.3
  @backstage/plugin-catalog-backend-module-aws                       0.3.15
  @backstage/plugin-catalog-backend-module-github-org                0.1.15
  @backstage/plugin-catalog-backend-module-github                    0.6.3
  @backstage/plugin-catalog-backend-module-msgraph                   0.5.28
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model   0.1.18
  @backstage/plugin-catalog-backend-module-unprocessed               0.4.7
  @backstage/plugin-catalog-backend                                  1.23.1
  @backstage/plugin-catalog-common                                   1.0.24
  @backstage/plugin-catalog-graph                                    0.4.6
  @backstage/plugin-catalog-node                                     1.12.2
  @backstage/plugin-catalog-react                                    1.12.1
  @backstage/plugin-catalog-unprocessed-entities-common              0.0.2
  @backstage/plugin-catalog-unprocessed-entities                     0.2.5
  @backstage/plugin-catalog                                          1.21.0
  @backstage/plugin-devtools-backend                                 0.3.6
  @backstage/plugin-devtools-common                                  0.1.10
  @backstage/plugin-devtools                                         0.1.15
  @backstage/plugin-events-backend-module-github                     0.2.6
  @backstage/plugin-events-backend                                   0.3.7
  @backstage/plugin-events-node                                      0.3.6
  @backstage/plugin-home-react                                       0.1.14
  @backstage/plugin-home                                             0.7.5
  @backstage/plugin-kubernetes-common                                0.8.0
  @backstage/plugin-notifications-backend                            0.3.1
  @backstage/plugin-notifications-common                             0.0.3, 0.0.4
  @backstage/plugin-notifications-node                               0.1.4, 0.2.1
  @backstage/plugin-notifications                                    0.2.2
  @backstage/plugin-org                                              0.6.26
  @backstage/plugin-permission-backend                               0.5.44
  @backstage/plugin-permission-common                                0.7.14
  @backstage/plugin-permission-node                                  0.7.31
  @backstage/plugin-permission-react                                 0.4.23
  @backstage/plugin-proxy-backend                                    0.5.1
  @backstage/plugin-scaffolder-backend-module-azure                  0.1.12
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud        0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-server       0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket              0.2.10
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.2.21
  @backstage/plugin-scaffolder-backend-module-cookiecutter           0.2.44
  @backstage/plugin-scaffolder-backend-module-gerrit                 0.1.12
  @backstage/plugin-scaffolder-backend-module-gitea                  0.1.10
  @backstage/plugin-scaffolder-backend-module-github                 0.3.1
  @backstage/plugin-scaffolder-backend-module-gitlab                 0.4.2
  @backstage/plugin-scaffolder-backend-module-notifications          0.0.3
  @backstage/plugin-scaffolder-backend                               1.22.10
  @backstage/plugin-scaffolder-common                                1.5.3
  @backstage/plugin-scaffolder-node-test-utils                       0.1.7
  @backstage/plugin-scaffolder-node                                  0.4.6
  @backstage/plugin-scaffolder-react                                 1.9.0
  @backstage/plugin-scaffolder                                       1.21.0
  @backstage/plugin-search-backend-module-catalog                    0.1.26
  @backstage/plugin-search-backend-module-elasticsearch              1.5.1
  @backstage/plugin-search-backend-module-techdocs                   0.1.25
  @backstage/plugin-search-backend-node                              1.2.25
  @backstage/plugin-search-backend                                   1.5.12
  @backstage/plugin-search-common                                    1.2.12
  @backstage/plugin-search-react                                     1.7.12
  @backstage/plugin-search                                           1.4.12
  @backstage/plugin-signals-backend                                  0.1.6
  @backstage/plugin-signals-node                                     0.1.6
  @backstage/plugin-signals-react                                    0.0.3, 0.0.4
  @backstage/plugin-signals                                          0.0.7
  @backstage/plugin-techdocs-backend                                 1.10.7
  @backstage/plugin-techdocs-node                                    1.12.6
  @backstage/plugin-techdocs-react                                   1.2.5
  @backstage/plugin-techdocs                                         1.10.6
  @backstage/plugin-user-settings-backend                            0.2.19
  @backstage/plugin-user-settings-common                             0.0.1
  @backstage/plugin-user-settings                                    0.8.7
  @backstage/release-manifests                                       0.0.11
  @backstage/test-utils                                              1.5.6
  @backstage/theme                                                   0.5.6
  @backstage/types                                                   1.1.1
  @backstage/version-bridge                                          1.0.8

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment] 2024-06-20 14:36
That's unfortunate. Do you know what's the actual blocker? Frequent repaints? A single thread of lots of work happening somewhere? Aggressive network traffic? Haven't had the time to reproduce, sorry for all of the questions :)

**Comment by freben** [comment] 2024-06-20 14:39
I'll also add that, any control that tries to handle huge numbers of entries all at once in ANY capacity in the DOM etc is doomed to fail since it'll hit scaling limits sooner or later. It should have detected the large number of items and acted accordingly. But that's a bigger refactor I assume.

**Comment by drodil** [comment] 2024-06-20 15:56
Don't know the details behind the entity presentation api, but basically the new entity picker calls the api individually for each option in the list. Didn't have time to dig deeper but if the representation api does actual rest API call, it means it will do 1/entity which is just way too much. Either using the representation api in the entity picker should be optional (disabled by default preferably) or the representation api should be able to handle an array of entity refs and do it with a single call. Or something else like getting the title from the catalog (like in the PR mentioned in the description).

I will be on PTO for the next 4 weeks so probably don't have time to debug this further but hopefully there are some people who will hit this issue as well and can take a look (looking at my own team 🤭).

**Comment by drodil** [comment] 2024-06-20 16:01
And of course, it's possible for us to create a custom field to scaffolder that handles this but I think it would be reasonable to have components that can handle large amounts of entities in the upstream. Don't think 1000 or 2000 or even 5000 entity catalogs are that uncommon among Backstage adopters 🤔

**Comment by benjdlambert** [comment] 2024-06-20 19:01
Just chiming in here that maybe something like https://github.com/backstage/backstage/pull/25315 could help.

It’s not the best solution for this particular issue, but it probably would solve a bit of it

**Comment by kmikko** [comment] 2024-06-24 09:32
More precisely it seems to be this line causing the problem: https://github.com/backstage/backstage/blob/0c5aa5a0071aa5e7bebb68887cd0ebd238613685/plugins/scaffolder/src/components/fields/EntityPicker/EntityPicker.tsx#L202

**Comment by kmikko** [comment] 2024-06-24 14:07
Did a little bit of digging on this and indeed `renderOption` seems to be the culprit.
Noticed that creation of the Material UI components and their styling especially `Box` in `EntityDisplayName` are surprisingly heavy. Managed to see some performance gains by refactoring the component structure but not enough to make it usable with 1k+ entities. Not sure if there's much to gain either because `renderOption` is called for each input option. Given the fact that MUI team probably [doesn't have the bandwidth](https://github.com/mui/material-ui/issues/34712#issuecomment-2150929663) to fix this any time soon I think using virtualization here too would be the way forward.

**Comment by benjdlambert** [comment] 2024-06-24 14:20
@kmikko the virtualization PR has been merged with a `-next` release due tomorrow maybe would be a good time to test this to see if it helps @drodil :pray:

**Comment by drodil** [comment] 2024-06-24 14:23
@benjdlambert thanks, but it seems that PR only affects the `MultiEntityPicker`, not plain `EntityPicker`. Also we don't have access to the `-next` releases so it's a bit of a pity.

**Comment by benjdlambert** [comment] 2024-06-24 14:25
Ah OK, but i'm guessing we can port the same virtualization logic to the `EntityPicker` also right? The change itself is pretty small, I wonder if you could apply it as a `yarn patch` to test it locally to see if it helps with your issue?

**Comment by kmikko** [comment] 2024-06-24 14:28
I'm working on the same team as @drodil and can confirm that adding similar kind of virtualization logic fixes the issue. I can craft a PR later today if someone else doesn't beat me to it. However as mentioned unfortunately we don't have access to `next` releases so we're not in that hurry per se.

**Comment by drodil** [comment] 2024-06-24 14:30
@kmikko great stuff! Maybe we need to check internally if we can get the `-next` releases in use if it's not possible to get a patch release for 1.28.

**Comment by benjdlambert** [comment] 2024-06-25 07:52
@drodil just to confirm also, you would only need to use the `-next` release of `@backstage/plugin-scaffolder` I believe.

**Closed** 2024-06-25 07:52 UTC
Labels: bug, area:catalog, area:scaffolder

**Comment by drodil** [comment] 2024-06-25 08:11
@benjdlambert yep, issue is just that our internal artifactory doesn't support those, only main releases 😄 Probably need to have a conversation internally about this

**Comment by benjdlambert** [comment] 2024-06-25 08:51
Ah OK, there's also `yarn patches` that you can create in the meantime. I was thinking of whipping this in a patch release anyways, but would be good to confirm that it works first before doing so.

**Comment by kmikko** [comment] 2024-06-25 11:38
We're rocking yarn v1 which doesn't have native patch support but made one with `patch-package` and can confirm that issues with both `EntityPicker` and `MultiEntityPicker` are fixed!

**Comment by benjdlambert** [comment] 2024-06-26 11:33
@kmikko @drodil we dropped 1.28.3 this morning with the patch in it.

**Comment by drodil** [comment] 2024-06-26 11:34
Awesome, thanks a lot @benjdlambert 🍻
