### ISSUE TITLE
current version of @techdocs/cli does not work

### ISSUE THREAD

**Issue by PavelPolyakov** [backstage/backstage#9436] opened 2022-02-09 15:24 UTC
## Expected Behavior

run `npx @techdocs/cli serve` and documentation is present in the browser

## Actual Behavior

<img width="707" alt="image" src="https://user-images.githubusercontent.com/839290/153232187-4b8daadb-5a7f-42dd-bce3-55cf9af02330.png">

## Steps to Reproduce

Run `npx @techdocs/cli serve` in the folder with documentation.

## Context

When I run `npx @techdocs/cli@0.8.11 serve` it works as it used to work before.

**Comment by Rugvip** [comment] 2022-02-09 15:27
Thank you for reporting! Will close this as a duplicate of #9424 though. This should be fixed by #9370 which is being released tomorrow

**Closed by Rugvip** 2022-02-09 15:27 UTC
Labels: bug
