### ISSUE TITLE
🐛 Bug Report: Todo plugin does not scan all the project files

### ISSUE THREAD

**Issue by antoniomuso** [backstage/backstage#14483] opened 2022-11-07 11:42 UTC
### 📜 Description

When registering an entity where the catalog file is not in the project's root, the Todo plugin doesn't show the `// Todo: ` entries.

### 👍 Expected behavior

The Todo entries should not be influenced by the location of the catalog file in the project.

### 👎 Actual Behavior with Screenshots

The right TODOs aren't shown by the plugin. 

### 👟 Reproduction steps

Steps:
1. Create a project
2. Put a catalog file in the project, not in the project's route. For example: `.backstage/catalog-info.yaml`
3. Register the catalog 
4. Now the TODO plugin shows only the TODOs inside the `.backstage` directory

### 📃 Provide the context for the Bug.

Gitlab

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment] 2022-11-07 12:41
If you want to store your catalog definitions at a different location that your source code then you'll want to set this annotation to point to the code: https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageiosource-location. That goes for all plugins and isn't specific to the Todo plugin.

Gonna close this as it's working as intended and the solution to the issue is to set the `backstage.io/source-location` annotation.

**Closed by Rugvip** 2022-11-07 12:41 UTC
Labels: bug

**Comment by antoniomuso** [comment] 2022-11-07 13:11
Thanks for the answer.
