### ISSUE TITLE
$yaml and $text placeholders behave differently for YAML OpenAPI spec

### ISSUE THREAD

**Issue by jpeach** [backstage/backstage#12251] opened 2022-06-24 05:52 UTC
## Expected Behavior

This API entity should work:
```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/source-location: url:https://github.com/prometheus/alertmanager
  name: external-api
  title: External API
  description: An API with an external OpenAPI spec
spec:
  type: openapi
  lifecycle: Active
  owner: group:cloudflare
  definition:
    $yaml: https://github.com/prometheus/alertmanager/blob/main/api/v2/openapi.yaml
```
## Actual Behavior

```
[1] 2022-06-24T05:51:04.744Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity api:default/external-api; caused by TypeError: /spec/definition must be string - type: string type=plugin entity=api:default/external-api
```

If I change the `$yaml` to $text`, then it works correctly. But the file type is YAML, so it ought to work identically in this case/

## Your Environment

```text
$ backstage-cli info
yarn run v1.22.19
$ /Users/jpeach/work/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 21.5.0 - darwin/arm64
node: v16.15.1
yarn: 1.22.19
cli:  0.17.2 (installed)

Dependencies:
  @backstage/app-defaults                            1.0.3
  @backstage/backend-common                          0.14.0
  @backstage/backend-tasks                           0.3.2
  @backstage/catalog-client                          1.0.3
  @backstage/catalog-model                           1.0.3
  @backstage/cli-common                              0.1.9
  @backstage/cli                                     0.17.2
  @backstage/config-loader                           1.1.2
  @backstage/config                                  1.0.1
  @backstage/core-app-api                            1.0.3
  @backstage/core-components                         0.9.5
  @backstage/core-plugin-api                         1.0.3
  @backstage/dev-utils                               1.0.3
  @backstage/errors                                  1.0.0
  @backstage/integration-react                       1.1.1
  @backstage/integration                             1.2.1
  @backstage/plugin-api-docs                         0.8.6
  @backstage/plugin-app-backend                      0.3.33
  @backstage/plugin-auth-backend                     0.14.1
  @backstage/plugin-auth-node                        0.2.2
  @backstage/plugin-bitbucket-cloud-common           0.1.0
  @backstage/plugin-catalog-backend-module-bitbucket 0.2.0
  @backstage/plugin-catalog-backend                  1.2.0
  @backstage/plugin-catalog-common                   1.0.3
  @backstage/plugin-catalog-graph                    0.2.18
  @backstage/plugin-catalog-import                   0.8.9
  @backstage/plugin-catalog-react                    1.1.1
  @backstage/plugin-catalog                          1.3.0
  @backstage/plugin-kubernetes-common                0.3.0
  @backstage/plugin-kubernetes                       0.6.6
  @backstage/plugin-org                              0.5.6
  @backstage/plugin-pagerduty                        0.4.0
  @backstage/plugin-permission-common                0.6.2
  @backstage/plugin-permission-node                  0.6.2
  @backstage/plugin-permission-react                 0.4.2
  @backstage/plugin-proxy-backend                    0.2.27
  @backstage/plugin-scaffolder-backend               1.3.0
  @backstage/plugin-scaffolder-common                1.1.1
  @backstage/plugin-scaffolder                       1.3.0
  @backstage/plugin-search-backend-node              0.6.2
  @backstage/plugin-search-backend                   0.5.3
  @backstage/plugin-search-common                    0.3.5
  @backstage/plugin-search-react                     0.2.1
  @backstage/plugin-search                           0.9.0
  @backstage/plugin-techdocs-backend                 1.1.2
  @backstage/plugin-techdocs-module-addons-contrib   1.0.1
  @backstage/plugin-techdocs-node                    1.1.2
  @backstage/plugin-techdocs-react                   1.0.1
  @backstage/plugin-techdocs                         1.2.0
  @backstage/plugin-user-settings                    0.4.5
  @backstage/release-manifests                       0.0.4
  @backstage/test-utils                              1.1.1
  @backstage/theme                                   0.2.15
  @backstage/types                                   1.0.0
  @backstage/version-bridge                          1.0.1
✨  Done in 0.44s.
```

**Comment by benjdlambert** [comment] 2022-06-27 11:43
Hmm, the `$yaml` placeholder is not supposed to be used here, should always be `$text` instead. Maybe we could update the docs to make this a little clearer, even though it's a little counterintuative? :pray:

**Comment by freben** [comment] 2022-06-30 12:44
Yep the naming of these isn't great. `$text` means "read whatever and output as a string here in the result", `$yaml` means "read whatever and parse it as yaml, and output as structured data here in the result". This gets doubly confusing when the file you're writing the placeholder in, happens to be yaml as well - but internally, it's all just json-like data structures, the concept of the entity originating from a yaml file is kinda gone at that point :)

See here https://backstage.io/docs/features/software-catalog/descriptor-format#substitutions-in-the-descriptor-format

![Screenshot 2022-06-30 at 14 43 05](https://user-images.githubusercontent.com/3097461/176679794-480bf615-5021-48ac-a059-af4183615917.png)

I was pondering some wording changes but came up short. I'll be closing this as it works as intended. If you have some suggestions on how to change the wording for the better there, we're happy to hear (or to review a contribution)!

**Closed by freben** 2022-06-30 12:44 UTC
Labels: bug

**Comment by jpeach** [comment] 2022-07-04 07:11
> Hmm, the `$yaml` placeholder is not supposed to be used here, should always be `$text` instead. Maybe we could update the docs to make this a little clearer, even though it's a little counterintuative? 🙏

Sorry for the late reply, I was out on vacation :)

I was expecting all the placeholders to be valid in all contexts, but since this context wants a string not an object `$text` makes sense. Thanks!
