### ISSUE TITLE
🐛 Bug Report: createUnifiedTheme does not allow overrides for Backstage components

### ISSUE THREAD

**Issue by Roshick** [backstage/backstage#18422] opened 2023-06-25 07:59 UTC
### 📜 Description

Neither the v4 nor the v5 Theme currently supports overrides for non Material-UI components when created via the new createUnifiedTheme (https://github.com/backstage/backstage/blob/3f304f6211620ed9386d905c53822d46e574a48f/packages/theme/src/unified/UnifiedTheme.tsx#L73C27-L73C27) method.

v4 fails here since transformV5ComponentThemesToV4 (https://github.com/backstage/backstage/blob/3f304f6211620ed9386d905c53822d46e574a48f/packages/theme/src/unified/overrides.ts#L120C1-L123) filters out all entries that are not part of "ThemeOptions['components']" which only contains the Material-UI components.

For this to work the Backstage components would need to be added via module augmentation as seen here https://stackoverflow.com/questions/76095729/how-can-i-add-my-custom-component-to-mui-theme-options-so-that-i-can-override-it

### 👍 Expected behavior

Adding Backstage component overrides via the "components" option and using styleOverrides should apply those overrides to the Backstage component.

### 👎 Actual Behavior with Screenshots

The overrides are not applied and TypeScript is unhappy because it doesn't know what to do with the Backstage component names in the "components" section of the options.

### 👟 Reproduction steps

1. Create a custom theme via createUnifiedTheme.
2. Add some Backstage component to the "components" option.
3. Check the result.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment] 2023-06-26 08:59
@tudi2d is this something you might know about?

**Comment by enyineer** [comment] 2023-07-06 07:55
Having the same problem here. Before `UnifiedTheme` it was possible to eg. set the Navigation Colors via the Palette. This is no longer possible with `createUnifiedTheme` as the Palette does no longer include backstage palette specifics. This breaks our design.

The [Documentation](https://backstage.io/docs/getting-started/app-custom-theme/) uses deprecated methods which we would like to avoid.

Is there any workaround for this? I couldn't figure it out yet.

**Comment by enyineer** [comment] 2023-07-06 09:38
I tried installing the current next release but this now leads to some problems with webpack and the Q&A Plugin:

```
[1] TypeError: Cannot read properties of undefined (reading 'redacter')
[1]     at Object.<anonymous> (/Users/nico/Projects/backstage/node_modules/@drodil/backstage-plugin-qeta-backend/node_modules/@backstage/backend-app-api/node_modules/@backstage/backend-common/dist/index.cjs.js:110:46)
[1]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[1]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[1]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1100:19)
[1]     at require (node:internal/modules/cjs/helpers:108:18)
[1]     at Object.<anonymous> (/Users/nico/Projects/backstage/node_modules/@drodil/backstage-plugin-qeta-backend/node_modules/@backstage/backend-app-api/dist/index.cjs.js:24:21)
[1]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[1]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[1]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1100:19)
[1]     at require (node:internal/modules/cjs/helpers:108:18)
[1]     at Object.<anonymous> (/Users/nico/Projects/backstage/node_modules/@drodil/backstage-plugin-qeta-backend/node_modules/@backstage/backend-common/dist/index.cjs.js:10:21)
[1]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
```

It seems to be incompatible with that release (if I'm not overlooking something else).

**Comment by benjdlambert** [comment] 2023-07-06 11:53
@enyineer did you use `yarn backstage-cli versions:bump --release=next`?

**Comment by enyineer** [comment] 2023-07-06 12:10
Thanks for the heads up @benjdlambert.

I did use the version bumper tool. However, when using `yarn backstage-cli versions:check` it does indeed show some duplicates:

```
yarn backstage-cli versions:check --fix
The following packages can be deduplicated by updating dependencies in package.json

  @backstage/backend-plugin-api @ ^0.5.3 should be changed to ^0.5.4-next.0
  @backstage/backend-tasks @ ^0.5.3 should be changed to ^0.5.4-next.0
  @backstage/catalog-client @ ^1.4.1 should be changed to ^1.4.3-next.0
  @backstage/catalog-client @ ^1.4.2 should be changed to ^1.4.3-next.0
  @backstage/catalog-model @ ^1.3.0 should be changed to ^1.4.1-next.0
  @backstage/catalog-model @ ^1.4.0 should be changed to ^1.4.1-next.0
  @backstage/core-components @ ^0.13.1 should be changed to ^0.13.3-next.1
  @backstage/core-components @ ^0.13.2 should be changed to ^0.13.3-next.1
  @backstage/core-plugin-api @ ^1.5.1 should be changed to ^1.5.3-next.0
  @backstage/core-plugin-api @ ^1.5.2 should be changed to ^1.5.3-next.0
  @backstage/errors @ ^1.1.5 should be changed to ^1.2.1-next.0
  @backstage/errors @ ^1.2.0 should be changed to ^1.2.1-next.0
  @backstage/integration @ ^1.5.0 should be changed to ^1.5.1-next.0
  @backstage/plugin-auth-node @ ^0.2.14 should be changed to ^0.2.16-next.0
  @backstage/plugin-auth-node @ ^0.2.15 should be changed to ^0.2.16-next.0
  @backstage/plugin-catalog-common @ ^1.0.14 should be changed to ^1.0.15-next.0
  @backstage/plugin-catalog-react @ ^1.6.0 should be changed to ^1.7.1-next.1
  @backstage/plugin-catalog-react @ ^1.7.0 should be changed to ^1.7.1-next.1
  @backstage/plugin-events-node @ ^0.2.6 should be changed to ^0.2.8-next.0
  @backstage/plugin-permission-common @ ^0.7.5 should be changed to ^0.7.7-next.0
  @backstage/plugin-permission-common @ ^0.7.6 should be changed to ^0.7.7-next.0
  @backstage/plugin-permission-node @ ^0.7.8 should be changed to ^0.7.10-next.0
  @backstage/plugin-permission-react @ ^0.4.12 should be changed to ^0.4.14-next.1
  @backstage/plugin-permission-react @ ^0.4.13 should be changed to ^0.4.14-next.1
  @backstage/plugin-search-common @ ^1.2.3 should be changed to ^1.2.5-next.0
  @backstage/plugin-search-common @ ^1.2.4 should be changed to ^1.2.5-next.0
  @backstage/theme @ ^0.4.0 should be changed to ^0.4.1-next.0
```

After searching the repository for any of those packages, they all seem to be updated to their respective *-next.x versions printed by the versions:check. I can't find any of the versions the tool seems to find in our repository.

I made sure to delete the lockfile and made a fresh install to make sure this wasn't the reason for this behaviour but it didn't help.

For example, `@backstage/plugin-catalog-react@npm:^1.7.0` has a dependency on `"@backstage/plugin-permission-react": ^0.4.13` instead of `^0.4.14-next.1` which in turn is a dependency of `"@backstage/plugin-home@npm:^0.5.2"` which in turn is a dependency of `"@drodil/backstage-plugin-qeta@npm:^1.13.3"` (The plugin throwing the error).

So using the version bumper utility doesn't help with third party plugins - at least if I do understand this issue correctly.

**Comment by benjdlambert** [comment] 2023-07-06 12:36
> So using the version bumper utility doesn't help with third party plugins

Yep this is what I was worried about, and there's not really a way we can fix that without using the resolutions block as you mentioned for packages which cannot contain duplicates.

**Comment by vllirette** [comment] 2023-07-18 21:37
I am using backstage version 1.16.0 that was released today and still can't override Backstage components. Is there a way to make it work?

**Comment by benjdlambert** [comment] 2023-07-20 09:16
@vllirette how are you trying to override backstage components? What's your steps to reproduce?

**Comment by shmaram** [comment] 2023-08-02 09:10
@benjdlambert , I'm having the same issue after updating to 1.16.0. 
I checked `yarn backstage-cli versions:check` and got no duplications 

This is the code I had before: 
```
export const lightThemeNew = createTheme({
  ...lightTheme,
  defaultPageTheme: 'home',
  pageTheme: newPageTheme,
});
```

here the above code, `createTheme` used to be able to use `SimpleThemeOptions` as prop and we were able to override Backstage theme, this function returned `BackstageTheme` which was the same as `lightTheme` so we were able to merge them

Now, we need to use `createUnifiedTheme`, and also `lightTheme` is deprecated and we need to use `themes.light` instead. the problem is that `themses.light` returns a mui theme, while `createUnifiedTheme` return `UnifiedTheme`.
I was able to do this:

```
export const unifiedLightTheme = createUnifiedTheme({
  palette: palettes.light,
  defaultPageTheme: 'home',
  pageTheme: newPageTheme,
});
```

Then in the `ThemeProvider` I needed to do this 
```
<ThemeProvider theme={unifiedLightTheme.getTheme('v4')}>
      <CssBaseline>{children}</CssBaseline>
</ThemeProvider>
```
Which alerts a type error but is still able to compile and load to overrided colors 

Can you assist on how is the best way to override the theme?
Nevertheless, I think that the docs must change and they still support the previous implementation

**Comment by freben** [comment] 2023-08-03 09:27
Ping @tudi2d FYI too.

**Comment by webark** [comment] 2023-08-03 19:56
@shmaram This is what we are currently doing.

```typescript

const BLUE = '#006de9';

const singlePageTheme: PageTheme = {
  colors: [BLUE, '#00ca9d'],
  shape: '',
  backgroundImage: `linear-gradient(24deg, ${BLUE}, #00ca9d)`,
  fontColor: '#fff',
};

function createCustomBaseTheme(palette: UnifiedThemeOptions['palette']): UnifiedTheme {
  return createUnifiedTheme({
    palette,
    defaultPageTheme: 'home',
    fontFamily: 'Rubik, Helvetica, Arial',
    pageTheme: {
      home: singlePageTheme,
      documentation: singlePageTheme,
      tool: singlePageTheme,
      service: singlePageTheme,
      website: singlePageTheme,
      library: singlePageTheme,
      other: singlePageTheme,
      app: singlePageTheme,
      apis: singlePageTheme,
    },
    components: {
      MuiGrid: {
        defaultProps: {
          spacing: 3,
        },
      },
      // https://github.com/backstage/backstage/issues/18422 there appears to be an issue with the
      // new unified theme where overrides for backstage components are not going through.
      // BackstageWarningPanel: {
      //   styleOverrides: {
      //     summaryText: {
      //       wordWrap: 'break-word',
      //     },
      //   },
      // },
    },
  });
}

const { dark: customDark, light: customLight } = palettes;

const customLightTheme = createCustomBaseTheme({
  ...customLight,
  navigation: {
    ...customLight.navigation,
    indicator: BLUE,
  },
  tabbar: {
    ...customLight.tabbar,
    indicator: BLUE,
  },
  primary: {
    ...customLight.primary,
    main: '#4291e9',
  },
});
const customDarkTheme = createCustomBaseTheme({
  ...customDark,
  navigation: {
    ...customDark.navigation,
    indicator: BLUE,
  },
  tabbar: {
    ...customDark.tabbar,
    indicator: BLUE,
  },
  primary: {
    ...customDark.primary,
    main: '#388be8',
  },
});

export const themes: AppTheme[] = [
  {
    id: 'light-theme',
    title: 'A Light Theme',
    variant: 'light',
    Provider: ({ children }) => <UnifiedThemeProvider theme={customLightTheme} children={children} />,
  },
  {
    id: 'dark-theme',
    title: 'A Dark Theme',
    variant: 'dark',
    Provider: ({ children }) => <UnifiedThemeProvider theme={customDarkTheme} children={children} />,
  },
];
```

**Comment by nodify-at** [comment] 2023-08-04 12:59
Since I'm watching this issue, I can override backstage components (as mentioned by @webark ) but you can also create a type to improve the Typescript checkins/autocompletion etc.

Extended Type for components:

```ts
export type ExtendedOverrides = {
  [K in keyof BackstageOverrides]: BackstageOverrides[K] & {
    styleOverrides?: BackstageOverrides[K];
  };
};
```

Usage:

```ts
const components: Theme['components'] & ExtendedOverrides = {
  MuiTabs: {
    styleOverrides: {
      root: {
        backgroundColor: 'red'
      }
    }
  },
  BackstageHeaderTabs: {
    styleOverrides: {
      selected: {
        backgroundColor: 'blue'
      }
    }
  },
}

createUnifiedTheme({
  components,
  // ... other options
});
```

**Comment by vllirette** [comment] 2023-08-14 19:43
@benjdlambert Sorry for the late response, I was on vacation.

> @vllirette how are you trying to override backstage components? What's your steps to reproduce?

Here's how I create my theme
```ts
export const darkTestTheme = createUnifiedTheme({
  palette: {
    ...palettes.dark,
    primary: {
      main: '#A7C1F9',
    },
    secondary: {
      main: '#9D97DA',
    },
    info: {
      main: '#608FF4',
    },
    warning: {
      main: '#FFAB00',
    },
    error: {
      main: '#e53935',
    },
    success: {
      main: '#2CBE7C',
    },
    navigation: {
      ...palettes.dark.navigation,
      indicator: '#2969F2',
      selectedColor: '#A7C1F9',
      color: '#D2D5D7',
      navItem: {
        hoverBackground: '#2256C6',
      },
    },
  },
  fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
  pageTheme: darkPageThemesFontColorOverride,
  defaultPageTheme: 'home',
  components: {
    BackstageHeader: {
      styleOverrides: theme => ({
        header: {
          backgroundImage: 'unset',
          boxShadow: '0 0.3rem 2.4rem #00000014',
          paddingBottom: theme.spacing(1),
        },
        title: {
          color: theme.page.fontColor,
          fontWeight: 900,
        },
        subtitle: {
          color: alpha(theme.page.fontColor, 0.8),
        },
        type: {
          color: alpha(theme.page.fontColor, 0.8),
        },
      }),
    },
    BackstageHeaderTabs: {
      styleOverrides: {
        defaultTab: {
          fontSize: 'inherit',
          textTransform: 'none',
        },
      },
    },
    BackstageItemCardHeader: {
      styleOverrides: theme => ({
        root: {
          color: theme.palette.text.primary,
          backgroundColor: alpha('#163984', 0.65),
        },
      }),
    },
    MuiPaper: {
      styleOverrides: {
        rounded: {
          borderRadius: 8,
        },
      },
    },
  },
});
```
And this is how I add it in the `App.tsx` file
```ts
const app = createApp({
  apis,
  icons: {
    alert: WebIcon,
  },
  themes: [
    {
      id: 'test-dark',
      title: 'Test Dark',
      variant: 'dark',
      Provider: ({ children }) => <UnifiedThemeProvider theme={darkTestTheme} children={children} />,
    },
  ],
```

If I remove any overrides that are "Backstage" components and leave the `MuiPaper` override, everything works correctly.

**Comment by benjdlambert** [comment] 2023-08-17 09:21
@vllirette are you saying that it's just a typescript error that you're getting and if you just put some `as any` in places everything does work as expected?

**Comment by eceeeren** [comment] 2023-11-14 11:22
Hello, I still have this issue as follows:

My company is using something like this to override Mui Components:

export const components: (UnifiedThemeOptions['components']) = {
  MuiTypography: {
    styleOverrides: {
.....
}}

Then these component variable is given into createUnifiedTheme({}) as components.

I would also like to override BackstageHeaderLabel here, however UnifiedThemeOptions['components'] does not accept BackstageHeaderLabel  as a component.

**Comment by Rugvip** [comment] 2023-11-14 20:05
Opened #21300 as a proposed fix for this. Went with an approach that end up provided accurate type hints for the `components` option of `createUnifiedTheme`.

**Closed** 2023-11-16 14:54 UTC
Labels: bug, help wanted

**Comment by awanlin** [comment] 2023-11-22 17:33
🎉 Excited to share that with the `1.21.0-next.1` release (full release will come on December 19th) you can now use overrides with the `UnifiedTheme`. We've updated the Aperture theme to work with this and you can see the code for that here: https://github.com/backstage/demo/blob/master/packages/app/src/theme/aperture.ts

A few thing to call out:

- You'll need to move your styles under the `styleOverrides` so there's a bit of manual work needed, it won't just be copy and paste. For example: 

Before:

```ts
BackstageHeaderTabs: {
      defaultTab: {
        fontSize: 'inherit',
        textTransform: 'none',
      },
    },
```

After:

```ts
BackstageHeaderTabs: {
      styleOverrides: {
        defaultTab: {
          fontSize: 'inherit',
          textTransform: 'none',
        },
      },
    },
```

- To get access to the `theme` you'll want to do this:

```ts
  MuiChip: {
      styleOverrides: {
        root: ({ theme }) => ({
          borderRadius: 3,
          backgroundColor: theme.palette.grey[50],
          color: theme.palette.primary.dark,
          margin: 4,
        }),
      },
```

**Comment by vj9486** [comment] 2023-12-14 18:24
Hello,
I am having issue with createUnifiedTheme, I followed the latest update of https://github.com/backstage/demo/blob/master/packages/app/src/theme/aperture.ts

  components: {
    BackstageHeaderTabs: {
      styleOverrides: {
        defaultTab: {
          fontSize: 'inherit',
          textTransform: 'none',
        },
      },
    },
}
    
 Issue:
 
 Type '{ BackstageHeaderTabs: { styleOverrides: { defaultTab: { fontSize: string; textTransform: string; }; }; }; BackstageOpenedDropdown: { styleOverrides: { icon: { '& path': { fill: string; }; }; }; }; BackstageTable: { ...; }; ... 9 more ...; MuiTypography: { ...; }; }' is not assignable to type 'Components<Omit<Theme, "components">>'.
  Object literal may only specify known properties, and 'BackstageHeaderTabs' does not exist in type 'Components<Omit<Theme, "components">>'.ts(2322)
index.d.ts(199, 5): The expected type comes from property 'components' which is declared here on type 'UnifiedThemeOptions'
(property) BackstageHeaderTabs: {
    styleOverrides: {
        defaultTab: {
            fontSize: string;
            textTransform: string;
        };
    };
}


I am using backstage version : "@backstage/cli": "^0.24.0"
Can anyone look into this issue

**Comment by awanlin** [comment] 2023-12-14 20:51
@vj9486, this hasn't been released as part of a monthly release yet, did you upgrade to at least the `1.21.0-next.1` weekly release? The `@backstage/cli` version isn't always helpful in telling what version you are on but I'm guessing you are still now on a version that supports this. Another way to help confirm would be to share the version in your `backstage.json` file which is in the root of your project.
