### ISSUE TITLE
Remove "Owned filter" when viewing Users in Catalog 

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#8198] opened 2021-11-22 16:09 UTC
## Feature Suggestion

When you open the catalog page and select Users from the filters, the view is almost always empty. It's because the default filter on the Catalog page is selected as "Owned" and ["ownedBy" relation](https://backstage.io/docs/features/software-catalog/well-known-relations#ownedby-and-ownerof) does not apply to Users and Groups.

There are two issues with this -
1. It takes one extra click on "All" before we see the list of users.
2. It feels really weird to have the words "Owned" and "Users" in the same context.

## Possible Implementation

Either we automatically switch to "All" when viewing Users in Catalog, or remove the "Owned" filter altogether when looking at Users.

## Context

Some screenshots
<img width="1625" alt="Screenshot 2021-11-22 at 9 33 53 PM" src="https://user-images.githubusercontent.com/8065913/142895429-1986f9e5-d215-4983-8a47-069f49fb64a1.png">

<img width="758" alt="Screenshot 2021-11-22 at 9 30 53 PM" src="https://user-images.githubusercontent.com/8065913/142895449-7523339c-09c6-4571-9c7a-44bd5eb12630.png">

And URLs

https://demo.backstage.io/catalog?filters%5Bkind%5D=user&filters%5Buser%5D=owned
https://demo.backstage.io/catalog?filters%5Bkind%5D=user&filters%5Buser%5D=all

**Comment by OrkoHunter** [comment] 2021-11-22 16:14
Maybe the same applies to Groups?

**Comment by djamaile** [comment] 2021-11-22 19:24
Makes sense

**Comment by freben** [comment] 2021-11-22 19:25
It would be nice if this filter was only visible (and applied) if the server has any ownership relations on any entity that matches the kind/type.

This essentially goes for any filter - show only of applicable, and deduce the applicability from the source data rather than hardcoded conditions.

If possible!

**Comment by djamaile** [comment] 2021-11-23 20:04
@freben shouldn't starred then also not show up if the logged in user hasn't starred anything?

**Comment by freben** [comment] 2021-11-23 20:48
Maybe, yeah. This is all up for discussion! Some things are good to show just to display to the user that an option exists at all, and to be able to have a nice empty-state display that maybe links to some "how to use this feature" docs etc. So there are arguments for both sides!

**Comment by adamdmharvey** [comment] 2021-11-23 21:57
Counter point to the above, is if I don't know the filter will show me my owned entities, then I may not see any value in assigning ownership to me. "Yeah I own it, but I'm ok if Freben is listed instead."

@OrkoHunter 's initial issue relates only to the Users and Groups entities, and just to the default, and I definitely agree with that in that viewing a list of Users, the "owned" filter should be hidden because it's not possible. But where it's not applicable, I think it may be better to stay?

The alternative may be, if I don't own any entities or I've not starred any don't HIDE the filter, just CHOOSE the alternative - "all"?

**Comment by devth** [comment] 2022-02-09 01:20
Was this fixed by https://github.com/backstage/backstage/pull/8220 ?

**Comment by adamdmharvey** [comment] 2022-02-09 03:19
Good call, @devth . Confirmed on a newly scaffold app that selecting the "Users" filter does swap straight to all and hide the Owner selector.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/33203301/153115476-3669f2a5-61d5-448b-aa05-1353414fb932.png">

**Closed by adamdmharvey** 2022-02-09 03:19 UTC
Labels: enhancement, good first issue, help wanted, catalog
