### ISSUE TITLE
🚀 Feature: Add step information to the Scaffolder context object

### ISSUE THREAD

**Issue by jvmdc** [backstage/backstage#26771] opened 2024-09-18 10:43 UTC
### 🔖 Feature description

Add information to the context object about the step that the custom action is being used as, e.g. the id and name of the step

### 🎤 Context

When writing custom actions, the context object is provided as the sole argument (https://backstage.io/docs/features/software-templates/writing-custom-actions/#the-context-object). This object currently provides the template name in `ctx.metadata.name`, but provides no information about the step that the action is used as.

We want to utilize the experimental checkpoints feature to ensure idempotency for steps. Since the key passed to the checkpoint is scoped to the scaffolder task and not the individual step, utilizing the same action multiple times at different points in the template will result in only the first action's checkpoint-enclosed code being run.

While it can be argued that this is the entire point of idempotency, we would like to be able to define an individual step as idempotent rather than the custom action itself. As an example, an action that commits and pushes the content of a directory to a repository is not idempotent on its own if the input specified is simply the directory path as the content may change in between runs of that action:

1. Create some directory with a file `helloworld`
2. Run `Commit and Push action` -> File is committed and added to repository
3. Add a new file `hi-there`
4. Run `Commit and Push action` -> Nothing will be done as checkpoint already passed

If we do not provide a checkpoint, the following instead happens:

1. Create some directory with a file `helloworld`
2. Run `Commit and Push action` -> File is committed and added to repository
3. Add a new file `hi-there`
4. Run `Commit and Push action` -> File is committed and added to repository

Now, imagine that at step 3 above, the system crashes or restarts for another reason. If we are using the `taskRecoveryStrategy` named `startOver`, the task will start from scratch. This means all 4 steps will be run again.
If there is no checkpoint, it means we try to commit both files again, despite `helloworld` already being present. 
If there is fixed checkpoint for the action, the second run will add no files (but we will still be missing `hi-there`)

Of course we can get around this for this example action by various hacky solutions, e.g. calculating a hash for the directory and using that as a key or providing an additional input parameter (E.g. `checkpointKey`), but these are either performance-hampering or user-confusing - Our users expect if they tell their template to commit and push at a given step, it commits and pushes at that step. By allowing us to access the ID of the step that the action is being used as, we can simply use that as the checkpoint key.

### ✌️ Possible Implementation

Add `ctx.metadata.stepId` and `ctx.metadata.stepName` containing the ID and name of the step respectively. The information is available in the TaskStep interface which is passed to `executeStep` here: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts#L233

(Consider renaming `ctx.metadata.name` to `ctx.metadata.templateName` as well to make it clearer what `name` is refering to. The context object is already a bit of a mixed bag, e.g. `baseUrl` refers to the template while `input` and `output` refers to the action itself)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by acierto** [comment] 2024-09-22 18:29
Hi @jvmdc 👋 

I agree, this is a solid use case to include both the step ID and step name (or simply the step ID) in the checkpoint key.
This will make your template configuration behave as intended.

Raised the PR for that: https://github.com/backstage/backstage/pull/26813

**Comment by benjdlambert** [comment] 2024-10-04 14:39
Can we close this now @acierto? :pray:

**Closed** 2024-10-18 13:00 UTC
Labels: enhancement, area:scaffolder
