### ISSUE TITLE
Error: Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#10824] opened 2022-04-14 04:08 UTC
## Expected Behavior

Hi, I just built the image and deployed it on our k8s, but I got the error said cannot find module 'fs-extra'.

## Actual Behavior
<img width="923" alt="image" src="https://user-images.githubusercontent.com/56138162/163311462-484d1de3-5d58-415c-affe-d86f7f27fcf1.png">

## Steps to Reproduce

1. yarn backstage-cli versions:bump

## Context

I tried to fix it through changing the `node:14-buster-slim` to  `node:14-buster` from Dockerfile, but i still got this error.

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
OS:   Linux 5.4.0-77-generic - linux/x64
node: v14.18.2
yarn: 1.22.17
cli:  0.16.0 (installed)

Dependencies:
  @backstage/app-defaults                         1.0.0
  @backstage/backend-common                       0.13.1
  @backstage/backend-tasks                        0.2.1
  @backstage/catalog-client                       1.0.0
  @backstage/catalog-model                        1.0.0
  @backstage/cli-common                           0.1.8
  @backstage/cli                                  0.16.0
  @backstage/config-loader                        1.0.0
  @backstage/config                               0.1.15, 1.0.0
  @backstage/core-api                             0.2.23
  @backstage/core-app-api                         1.0.0
  @backstage/core-components                      0.9.2
  @backstage/core-plugin-api                      0.1.13, 1.0.0
  @backstage/core                                 0.7.14
  @backstage/dev-utils                            1.0.0
  @backstage/errors                               0.1.5, 1.0.0
  @backstage/integration-react                    1.0.0
  @backstage/integration                          1.0.0
  @backstage/plugin-api-docs                      0.8.3
  @backstage/plugin-app-backend                   0.3.30
  @backstage/plugin-auth-backend                  0.12.3
  @backstage/plugin-auth-node                     0.1.6
  @backstage/plugin-catalog-backend-module-github 0.1.1
  @backstage/plugin-catalog-backend-module-ldap   0.4.1
  @backstage/plugin-catalog-backend               1.0.0
  @backstage/plugin-catalog-common                1.0.0
  @backstage/plugin-catalog-import                0.8.6
  @backstage/plugin-catalog-react                 1.0.0
  @backstage/plugin-catalog                       1.0.0
  @backstage/plugin-cost-insights                 0.11.25
  @backstage/plugin-github-actions                0.5.3
  @backstage/plugin-kubernetes-backend            0.4.13
  @backstage/plugin-kubernetes-common             0.2.8
  @backstage/plugin-kubernetes                    0.6.3
  @backstage/plugin-org                           0.5.3
  @backstage/plugin-pagerduty                     0.3.30
  @backstage/plugin-permission-common             0.5.3
  @backstage/plugin-permission-node               0.5.5
  @backstage/plugin-permission-react              0.3.4
  @backstage/plugin-proxy-backend                 0.2.24
  @backstage/plugin-scaffolder-backend            1.0.0
  @backstage/plugin-scaffolder-common             1.0.0
  @backstage/plugin-scaffolder                    1.0.1
  @backstage/plugin-search-common                 0.3.2
  @backstage/plugin-search                        0.7.4
  @backstage/plugin-tech-radar                    0.5.10
  @backstage/plugin-techdocs-backend              1.0.0
  @backstage/plugin-techdocs-node                 1.0.0
  @backstage/plugin-techdocs                      1.0.1
  @backstage/plugin-user-settings                 0.4.2
  @backstage/release-manifests                    0.0.2
  @backstage/search-common                        0.3.2
  @backstage/test-utils                           1.0.0
  @backstage/theme                                0.2.15
  @backstage/types                                0.1.3, 1.0.0
  @backstage/version-bridge                       0.1.2, 1.0.0
Done in 0.53s.
```

**Comment by freben** [comment] 2022-04-14 07:47
I think the v16 node base images do not have this problem. In the mean time, does it get resolved if you add fs-extra ^10 to your packages/backend dependencies?

**Comment by chuliang014** [comment] 2022-04-14 19:47
@freben yes, it's resolved after add fs-extra dependency

**Comment by Rugvip** [comment] 2022-04-19 15:08
Great! Will close this as it sounds like the issue is resolved

**Closed by Rugvip** 2022-04-19 15:08 UTC
Labels: bug

**Comment by sharadpattanshetti** [comment] 2022-05-03 04:22
> @freben yes, it's resolved after add fs-extra dependency

Which version did you use, because we see that latest version here is 9.0.13 - https://www.npmjs.com/package/@types/fs-extra?activeTab=versions ??

**Comment by chuliang014** [comment] 2022-05-03 21:07
@sharadpattanshetti `"fs-extra": "^10.0.1"`

**Comment by ShahadatAnik** [comment] 2026-02-09 19:05
bunx --bun shadcn@latest add https://shadcnexamples.com/r/product-list.json
error: Cannot find package 'fs-extra' from 'C:\Users\AppData\Local\Temp\bunx-179069033-shadcn@latest\node_modules\shadcn\dist\index.js'

Bun v1.3.8 (Windows x64)

i am having this problem. how to solve this?
