### ISSUE TITLE
🐛 Bug Report: Regex pattern not working in software template after 1.20 update

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#21476] opened 2023-11-22 13:29 UTC
### 📜 Description

Scaffolder field `pattern` used to work before updating to backstage 1.20.0, now the template gets stuck and it cannot be reviewed or run.

### 👍 Expected behavior

The template should be runnable

### 👎 Actual Behavior with Screenshots

The template gets stuck and you cannot continue to the next step. In the browser developer console there's the following error:

```
Form.js:483 Form validation failed
Array(1)
0: {stack: 'Invalid regular expression: /^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$/u: Invalid character class'}
length: 1
```

### 👟 Reproduction steps

Create a software template with the following input:
```
        email:
          title: Email
          type: string
          pattern: '^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$'
          description: Email address
```

Try to fill in the template and click 'Next'. Nothing happens.

### 🖥️ Your Environment

OS:   Darwin 23.1.0 - darwin/arm64
node: v18.15.0
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.20.2

Dependencies:
  @backstage/app-defaults                                            1.4.5
  @backstage/backend-app-api                                         0.5.8
  @backstage/backend-common                                          0.17.0, 0.19.9
  @backstage/backend-dev-utils                                       0.1.2
  @backstage/backend-openapi-utils                                   0.1.0
  @backstage/backend-plugin-api                                      0.6.7
  @backstage/backend-tasks                                           0.5.12
  @backstage/backend-test-utils                                      0.2.8
  @backstage/catalog-client                                          1.4.6
  @backstage/catalog-model                                           1.4.3
  @backstage/cli-common                                              0.1.13
  @backstage/cli-node                                                0.2.0
  @backstage/cli                                                     0.24.0
  @backstage/config-loader                                           1.5.3
  @backstage/config                                                  1.1.1
  @backstage/core-app-api                                            1.11.1
  @backstage/core-components                                         0.12.5, 0.13.8
  @backstage/core-plugin-api                                         1.8.0
  @backstage/dev-utils                                               1.0.23
  @backstage/errors                                                  1.2.3
  @backstage/eslint-plugin                                           0.1.3
  @backstage/frontend-plugin-api                                     0.3.0
  @backstage/integration-aws-node                                    0.1.8
  @backstage/integration-react                                       1.1.21
  @backstage/integration                                             1.7.2
  @backstage/plugin-api-docs                                         0.10.0
  @backstage/plugin-app-backend                                      0.3.55
  @backstage/plugin-app-node                                         0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider             0.2.1
  @backstage/plugin-auth-backend-module-github-provider              0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider              0.1.4
  @backstage/plugin-auth-backend-module-google-provider              0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider              0.1.4
  @backstage/plugin-auth-backend                                     0.20.0
  @backstage/plugin-auth-node                                        0.2.19, 0.4.1
  @backstage/plugin-catalog-backend-module-aws                       0.3.1
  @backstage/plugin-catalog-backend-module-msgraph                   0.5.14
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model   0.1.4
  @backstage/plugin-catalog-backend-module-unprocessed               0.3.4
  @backstage/plugin-catalog-backend                                  1.15.0
  @backstage/plugin-catalog-common                                   1.0.18
  @backstage/plugin-catalog-graph                                    0.3.0
  @backstage/plugin-catalog-node                                     1.5.0
  @backstage/plugin-catalog-react                                    1.9.0
  @backstage/plugin-catalog-unprocessed-entities                     0.1.5
  @backstage/plugin-catalog                                          1.15.0
  @backstage/plugin-devtools-backend                                 0.2.4
  @backstage/plugin-devtools-common                                  0.1.6
  @backstage/plugin-devtools                                         0.1.6
  @backstage/plugin-entity-feedback-backend                          0.2.4
  @backstage/plugin-entity-feedback-common                           0.1.3
  @backstage/plugin-entity-feedback                                  0.2.9
  @backstage/plugin-events-node                                      0.2.16
  @backstage/plugin-github-actions                                   0.6.7
  @backstage/plugin-home-react                                       0.1.5
  @backstage/plugin-home                                             0.5.10
  @backstage/plugin-jenkins-backend                                  0.3.1
  @backstage/plugin-jenkins-common                                   0.1.21
  @backstage/plugin-jenkins                                          0.9.1
  @backstage/plugin-kubernetes-common                                0.7.1
  @backstage/plugin-org                                              0.6.16
  @backstage/plugin-permission-backend                               0.5.30
  @backstage/plugin-permission-common                                0.7.10
  @backstage/plugin-permission-node                                  0.7.18
  @backstage/plugin-permission-react                                 0.4.17
  @backstage/plugin-proxy-backend                                    0.4.5
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.2.8
  @backstage/plugin-scaffolder-backend-module-cookiecutter           0.2.31
  @backstage/plugin-scaffolder-backend                               1.19.1
  @backstage/plugin-scaffolder-common                                1.4.3
  @backstage/plugin-scaffolder-node                                  0.2.8
  @backstage/plugin-scaffolder-react                                 1.6.0
  @backstage/plugin-scaffolder                                       1.16.0
  @backstage/plugin-search-backend-module-catalog                    0.1.11
  @backstage/plugin-search-backend-module-elasticsearch              1.3.10
  @backstage/plugin-search-backend-module-techdocs                   0.1.11
  @backstage/plugin-search-backend-node                              1.2.11
  @backstage/plugin-search-backend                                   1.4.7
  @backstage/plugin-search-common                                    1.2.8
  @backstage/plugin-search-react                                     1.7.3
  @backstage/plugin-search                                           1.4.2
  @backstage/plugin-sonarqube-backend                                0.2.9
  @backstage/plugin-sonarqube-react                                  0.1.10
  @backstage/plugin-sonarqube                                        0.7.8
  @backstage/plugin-techdocs-backend                                 1.9.0
  @backstage/plugin-techdocs-node                                    1.10.0
  @backstage/plugin-techdocs-react                                   1.1.13
  @backstage/plugin-techdocs                                         1.9.0
  @backstage/plugin-user-settings                                    0.7.12
  @backstage/release-manifests                                       0.0.11
  @backstage/test-utils                                              1.4.5
  @backstage/theme                                                   0.2.19, 0.4.4
  @backstage/types                                                   1.1.1
  @backstage/version-bridge                                          1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment] 2023-11-23 06:28
Apparently, the regex was incorrect and I think what we saw was because the regex was not validated before? Would it still be possible to see some error in the UI if the validation fails as this is very hard to spot when it happens?

**Comment by camilaibs** [comment] 2023-11-23 10:46
Hi @benjdlambert, could you take a look?

**Comment by benjdlambert** [comment] 2023-11-23 11:37
@drodil, hmm, we should get that error in some place to be able to render it somehow I think, not sure how though. Open for contributions if someone wants to pick this up though

**Comment by mprinold** [comment] 2023-11-23 13:17
@benjdlambert Id be happy to pick this up. I have a question though.

Where are we looking to show this error message? Is it on the the template editor, or the ui form when someone is actually trying to create from a template? or potentially both?

**Comment by NeuralEvolution** [comment] 2023-11-23 13:18
@benjdlambert  Id be happy to pick this up. I have a question though.
Where are we looking to show this error message? Is it on the the template editor, or the ui form when someone is actually trying to create from a template? or potentially both?

**Comment by benjdlambert** [comment] 2023-11-23 15:51
If we can render it in a nice place in the form, we should get it for free in both places  as they share the same component IIRC. If not we can look at implementing in one place first and seeing how we share it across the implementations.

**Comment by markstickley** [comment] 2023-11-28 17:21
Hi folks, I'm getting this same issue in rjsf's Form.js:

<img width="1043" alt="image" src="https://github.com/backstage/backstage/assets/83684/32e79d3b-a63e-4037-bbc4-e7b15a0657b0">

It says the regex is invalid, but it worked before the upgrade. Also it works if I [paste it into regex101.com](https://regex101.com/r/zlea4R/2) so I don't think it's actually invalid.

**Comment by benjdlambert** [comment] 2023-11-29 08:16
@markstickley can you paste the regex that you're actually using? We can test it in the upstream playground, but I think that it could be an issue for [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form) instead.

**Comment by markstickley** [comment] 2023-11-29 12:03
Of course:
```
  parameters:
    - title: Component
      properties:
        name:
          title: Name
          type: string
          description: Component name. Must be [a-z0-9A-Z], words optionally separated by one of [-_.] up to 63 chars
          maxLength: 63
          pattern: '^[A-Za-z0-9]([A-Za-z0-9\.]{0,61}|[A-Za-z0-9\-]{0,61}|[A-Za-z0-9\_]{0,61}|[A-Za-z0-9]{0,61})[A-Za-z0-9]$'
          ui:autofocus: true
          ui:options:
            rows: 1
```

Many thanks :)

**Comment by benjdlambert** [comment] 2023-11-29 19:12
@markstickley can confirm that @freben's suggestion fixes the error at least in the playground:

![image](https://github.com/backstage/backstage/assets/3645856/06615243-7b78-4886-a32f-ded88dc83bf0)

as opposed to:

![image](https://github.com/backstage/backstage/assets/3645856/8ecf4358-b7dc-4f1a-a674-4603c2580b16)

**Comment by markstickley** [comment] 2023-11-30 17:36
Many thanks @freben and @benjdlambert, not sure how those escaped characters got in there (and why it didn't complain before). That's fixed it for me.

**Comment by benjdlambert** [comment] 2023-11-30 18:19
I think with the latest bump to `react-jsonschema-form` they now validate the regex thats incoming with `ajv` which could be the cause of these error messages. Going to close this issue, but reach out if something is still not right!

**Closed by benjdlambert** 2023-11-30 18:19 UTC
Labels: bug, help wanted, area:scaffolder

**Comment by NeuralEvolution** [comment] 2023-12-05 09:28
@benjdlambert noticed that you closed this so not sure if you are still looking for a PR to surface these kind of error messages. If so i have manged to get them visiable so they look like this: 
<img width="1538" alt="Screenshot 2023-12-05 at 09 24 31" src="https://github.com/backstage/backstage/assets/57544905/44cac692-ced8-4a73-be20-19b84c49734b">

The only problem with this is that it will also show input errors like this:
<img width="1542" alt="Screenshot 2023-12-05 at 09 22 31" src="https://github.com/backstage/backstage/assets/57544905/d6341067-8484-4528-9377-8eb31bd40e0d">

If that is acceptable and this is still wanted ill go ahead and raise a PR.

**Comment by benjdlambert** [comment] 2023-12-05 15:40
@NeuralEvolution no please do raise a PR for this, It's not just useful for these regex errors right? It displays all validation errors including async ones too right?
