### ISSUE TITLE
🐛 Bug Report: createGitlabProjectVariableAction gets 401 Unauthorized

### ISSUE THREAD

**Issue by chkp-benzy** [backstage/backstage#25488] opened 2024-06-30 19:52 UTC
### 📜 Description

when using action gitlab:projectVariable:create out of the box i get 401 Unauthorized.

### 👍 Expected behavior

New Gitlab Variable should have beed created in my project

### 👎 Actual Behavior with Screenshots

i got 401 Unauthorized from gitlab

![image](https://github.com/backstage/backstage/assets/61980046/2bcfc764-6144-4fd2-9ff9-63d33f8135a5)

### 👟 Reproduction steps

```yaml
  steps:  
    - id: gitlab_var_create
      name: gitlab:projectVariable:create
      action: gitlab:projectVariable:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        projectId: ${{ parameters.peojectId }}
        key: ${{ parameters.key_name }}
        value: ${{ parameters.key_value }}
        variableType: "env_var"
        environmentScope: "*"
```

### 📃 Provide the context for the Bug.

when debugging the issue i saw that the header that was forwarded to gitlab is "PRIVATE-TOKEN" instead of "Authorization: Bearer"

was solved by changing the "token: token" to "oauthToken: token" in: https://github.com/backstage/backstage/blob/3dcc9d4e0b2d0def7db28845f11700ab6dc887da/plugins/scaffolder-backend-module-gitlab/src/actions/gitlabProjectVariableCreate.ts#L88 

### 🖥️ Your Environment

yarn run v1.22.19
OS:   Darwin 23.5.0 - darwin/arm64
node: v20.12.2
yarn: 1.22.19
cli:  0.26.10 (installed)
backstage:  1.28.3

Dependencies:
  @backstage/app-defaults                                          1.5.7
  @backstage/backend-app-api                                       0.7.9
  @backstage/backend-common                                        0.23.2
  @backstage/backend-defaults                                      0.3.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.14
  @backstage/backend-plugin-api                                    0.6.21
  @backstage/backend-tasks                                         0.5.26
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.6
  @backstage/cli                                                   0.26.10
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.13.0
  @backstage/core-compat-api                                       0.2.6
  @backstage/core-components                                       0.14.8
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.6
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.28
  @backstage/integration                                           1.12.0
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.70
  @backstage/plugin-app-node                                       0.1.21
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.2
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.13
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.4
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.4
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.16
  @backstage/plugin-auth-backend-module-github-provider            0.1.18
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.18
  @backstage/plugin-auth-backend-module-google-provider            0.1.18
  @backstage/plugin-auth-backend-module-guest-provider             0.1.7
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.16
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.2
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.14
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.2
  @backstage/plugin-auth-backend-module-okta-provider              0.0.14
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.2
  @backstage/plugin-auth-backend                                   0.22.8
  @backstage/plugin-auth-node                                      0.4.16
  @backstage/plugin-auth-react                                     0.1.3
  @backstage/plugin-catalog-backend-module-gitlab-org              0.0.4
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.20
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.19
  @backstage/plugin-catalog-backend                                1.23.2
  @backstage/plugin-catalog-common                                 1.0.24
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.12.0
  @backstage/plugin-catalog-node                                   1.12.3
  @backstage/plugin-catalog-react                                  1.12.1
  @backstage/plugin-catalog                                        1.21.0
  @backstage/plugin-devtools-backend                               0.3.7
  @backstage/plugin-devtools-common                                0.1.10
  @backstage/plugin-devtools                                       0.1.15
  @backstage/plugin-events-node                                    0.3.7
  @backstage/plugin-kubernetes-backend                             0.18.2
  @backstage/plugin-kubernetes-common                              0.8.0
  @backstage/plugin-kubernetes-node                                0.1.15
  @backstage/plugin-kubernetes-react                               0.4.0
  @backstage/plugin-kubernetes                                     0.11.11
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.18
  @backstage/plugin-permission-backend                             0.5.45
  @backstage/plugin-permission-common                              0.7.14
  @backstage/plugin-permission-node                                0.7.32
  @backstage/plugin-permission-react                               0.4.23
  @backstage/plugin-proxy-backend                                  0.5.2
  @backstage/plugin-scaffolder-backend-module-azure                0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.11
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.13
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.11
  @backstage/plugin-scaffolder-backend-module-github               0.3.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.3
  @backstage/plugin-scaffolder-backend                             1.22.11
  @backstage/plugin-scaffolder-common                              1.5.3
  @backstage/plugin-scaffolder-node                                0.4.7
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.22.0
  @backstage/plugin-search-backend-module-catalog                  0.1.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.26
  @backstage/plugin-search-backend-node                            1.2.26
  @backstage/plugin-search-backend                                 1.5.13
  @backstage/plugin-search-common                                  1.2.12
  @backstage/plugin-search-react                                   1.7.12
  @backstage/plugin-search                                         1.4.12
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.8
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.11
  @backstage/plugin-techdocs-node                                  1.12.7
  @backstage/plugin-techdocs-react                                 1.2.5
  @backstage/plugin-techdocs                                       1.10.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.8
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.7
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 2.92s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by camilaibs** [comment] 2024-07-01 12:20
Hi @chkp-benzy, thanks for opening an issue.
Just to confirm, was it working before or is this the first time you are trying to use this module?
I'm asking because it appears this action was created to only work with [personal tokens](https://github.com/jdalrymple/gitbeaker/blob/main/packages/rest/README.md#api-client) and a `private-token` header is expected to be set for this type of token:

https://github.com/jdalrymple/gitbeaker/blob/1d1e2e354cd55d4776bc73d70b16091cea1d679d/packages/requester-utils/src/BaseResource.ts#L122-L132

My recommendation would be to add a module configuration so that you can specify the AuthToken alternatively as well.  What do you think @backstage/scaffolder-maintainers ?

**Comment by elaine-mattos** [comment] 2024-07-01 12:33
Hi @camilaibs ,

I believe the problem is in the way the action instantiates the GitLab Client. [Here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend-module-gitlab/src/actions/gitlabProjectVariableCreate.ts#L86) the client is directly instantiated . If we use this [wrapper](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend-module-gitlab/src/util.ts#L90),  the type of token gets sorted out (id token or personal token) ...

**Comment by camilaibs** [comment] 2024-07-01 12:49
Thanks @elaine-mattos sounds like a great idea, thanks for the quick response 🙌🏻

**Comment by elaine-mattos** [comment] 2024-07-03 18:13
Hi @camilaibs ,

I have submitted a [PR](https://github.com/backstage/backstage/pull/25512), could you please take a look?  😊  
I have also realized there are other GitLab actions in the same situation and that some of them are using the @gitbeaker/node
 library that has already been deprecated. I would also take a look at these other actions if I can find some time 😅.

**Comment by chkp-benzy** [comment] 2024-07-03 21:46
Hi @camilaibs, thanks everyone for the quick response :)

Its the first time i'm trying to use this module,
and for my use-case the AuthToken is needed.

**Comment by benjdlambert** [comment] 2024-07-18 17:25
Closing this as fixed in @elaine-mattos' PR! :tada:

**Closed by benjdlambert** 2024-07-18 17:25 UTC
Labels: bug, area:scaffolder
