### ISSUE TITLE
Backstage-cli finds test, but does not include coverage

### ISSUE THREAD

**Issue by masonhuemmer** [backstage/backstage#13492] opened 2022-09-01 18:06 UTC
When I run the following script at the root directory: 

**command-line**
```yarn run backstage-cli test --coverage --coverageReporters cobertura```

I return all 10 tests which I have created. 

But when I look at the report, it doesn't include the test. 

However, when I run ```lerna run test -- --coverage```, the tool will individually run against the same test and include coverage in the report at the package level.

**Comment by Rugvip** [comment] 2022-09-01 18:40
Alright to close this as a duplicate of #13489? since the discussion is a bit further there and I think it's the same root cause.

**Closed** 2022-09-01 18:41 UTC
