### ISSUE TITLE
🔌 Plugin: Facing issues while doing SSO using AWS-Cognito user pool

### ISSUE THREAD

**Issue by leelakrishnayadav** [backstage/backstage#24269] opened 2024-04-15 05:02 UTC
### 🔖 Summary

I have been trying to implement SSO between backstage and using AWS-Cognito user pool. I followed the instructions as in the below thread https://github.com/backstage/backstage/issues/14612
But we couldn't succeed. Can you let us know if there is any change to the plugin/any help could be appreciated?
Thanks for your support in advance.

### ✌️ Context

I have been trying to implement SSO between backstage and using AWS-Cognito user pool. I followed the instructions as in the below thread https://github.com/backstage/backstage/issues/14612
But we couldn't succeed. Can you let us know if there is any change to the plugin/any help could be appreciated?
Thanks for your support in advance.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment] 2024-04-18 09:52
No progress as far as I'm aware. I'll close this as a duplicate of #14612, but re-opened that one.

**Closed by Rugvip** 2024-04-18 09:52 UTC
Labels: plugin, auth
