### ISSUE TITLE
🐛 Bug Report: Disable registration component for scaffolder via config does not work

### ISSUE THREAD

**Issue by ddeath** [backstage/backstage#27337] opened 2024-10-24 12:44 UTC
### 📜 Description

If you put this to your app-config.yaml:
```yaml
app:
  routes:
    bindings:
      scaffolder.registerComponent: false
```

It should according to the docs https://backstage.io/docs/features/software-templates/ disable registration button. This does not work anymore. (modifying code according to the docs still works)

### 👍 Expected behavior

Registration button should NOT be visible with config described above

### 👎 Actual Behavior with Screenshots

Registration button is still visible

### 👟 Reproduction steps

Start Backstage 1.31.2 and add following config:
```yaml
app:
  routes:
    bindings:
      scaffolder.registerComponent: false
```

Go to scaffolder http://localhost:3000/create and you will see the button being visible

### 📃 Provide the context for the Bug.

http://localhost:3000/create

### 🖥️ Your Environment

`packages/app/package.json`
```
{
  "name": "app",
  "version": "0.0.0",
  "private": true,
  "bundled": true,
  "backstage": {
    "role": "frontend"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "clean": "backstage-cli package clean",
    "test": "backstage-cli package test",
    "lint": "backstage-cli package lint"
  },
  "dependencies": {
    "@backstage-community/plugin-tech-radar": "^0.7.10",
    "@backstage/app-defaults": "^1.5.11",
    "@backstage/catalog-model": "^1.7.0",
    "@backstage/cli": "^0.27.1",
    "@backstage/core-app-api": "^1.15.0",
    "@backstage/core-components": "^0.15.0",
    "@backstage/core-plugin-api": "^1.9.4",
    "@backstage/integration-react": "^1.1.31",
    "@backstage/plugin-api-docs": "^0.11.9",
    "@backstage/plugin-catalog": "^1.23.0",
    "@backstage/plugin-catalog-common": "^1.1.0",
    "@backstage/plugin-catalog-graph": "^0.4.9",
    "@backstage/plugin-catalog-import": "^0.12.3",
    "@backstage/plugin-catalog-react": "^1.13.0",
    "@backstage/plugin-kubernetes": "^0.11.14",
    "@backstage/plugin-org": "^0.6.29",
    "@backstage/plugin-permission-react": "^0.4.26",
    "@backstage/plugin-scaffolder": "^1.25.0",
    "@backstage/plugin-search": "^1.4.16",
    "@backstage/plugin-search-react": "^1.8.0",
    "@backstage/plugin-techdocs": "^1.10.9",
    "@backstage/plugin-techdocs-module-addons-contrib": "^1.1.14",
    "@backstage/plugin-techdocs-react": "^1.2.8",
    "@backstage/plugin-user-settings": "^0.8.12",
    "@backstage/theme": "^0.5.7",
    "@internal/backstage-plugin-swagger-grpc": "^0.1.0",
    "@material-ui/core": "^4.12.2",
    "@material-ui/icons": "^4.9.1",
    "@roadiehq/backstage-plugin-argo-cd": "^2.8.3",
    "history": "^5.0.0",
    "react": "^18.0.2",
    "react-dom": "^18.0.2",
    "react-router": "^6.3.0",
    "react-router-dom": "^6.3.0",
    "react-use": "^17.2.4"
  },
  "devDependencies": {
    "@backstage/test-utils": "^1.6.0",
    "@playwright/test": "^1.32.3",
    "@testing-library/dom": "^9.0.0",
    "@testing-library/jest-dom": "^6.0.0",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.0.0",
    "@types/react-dom": "*",
    "cross-env": "^7.0.0"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "files": [
    "dist"
  ]
}
```

`backstage.json`
```
{
  "version": "1.31.2"
}
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ddeath** [comment] 2024-10-24 12:45
I was on `1.30.0` before and it was working then

**Comment by camilaibs** [comment] 2024-10-28 10:02
Hi @ddeath, I couldn't reproduce the behavior on the latest master branch. Would it be possible for you to try updating to the latest Backstage version and let us know if the error still persists?

**Comment by GersonTrj** [comment] 2024-11-04 09:01
I have the same issue in version  1.32.3

**Comment by ddeath** [comment] 2024-11-04 11:40
@camilaibs I tried this simplified steps:
1. run `npx @backstage/create-app@latest`
2. add to app-config.yaml:
```yaml
app:
  routes:
    bindings:
      scaffolder.registerComponent: false
```
3. `cd backstage`
4. `yarn dev` 
5. open backstage and see that register button is still there.

**Comment by freben** [comment] 2024-11-04 12:39
My guess is that this is because your app performs that registration in code.

Check [your app's `App.tsx`](https://github.com/backstage/backstage/blob/11cebe98991339300f95cdc2db7b8c1d2cd32cc7/packages/create-app/templates/default-app/packages/app/src/App.tsx#L51). Remove that code based mapping if you want to do it in config instead.

**Comment by ddeath** [comment] 2024-11-04 13:28
@freben it is fresh install of backstage and the docs are saying only that config addition is needed to disable it and as mentioned before. On old version it was working.

So at minimum Docs should be updated that config change is not enough anymore

**Comment by benjdlambert** [comment] 2024-11-08 15:16
After chats with @Rugvip and @freben we think that config should win over code, as right now that's not the case.

Happy for some contributions here to make this possible, or some doc updates where necessary :pray:

**Comment by GersonTrj** [comment] 2024-11-18 14:22
I think you should reopen this issue https://github.com/backstage/backstage/issues/26635

It is closed but the bug is still there @Rugvip

**Comment by GersonTrj** [comment] 2024-11-19 14:24
> @GersonTrj does something like this work?
> 
> ```ts
>  bind(apiDocsPlugin.externalRoutes, {
>      registerApi: process.env.NODE_ENV === 'production'  ? false : catalogImportPlugin.routes.importPage,
>  })
> ```

I guess it would work but we don't usually set that variable in the dockerfile, we tend to rely more on the app-config-environment files which is why the setting was perfect until it stopped working.

**Comment by benjdlambert** [comment] 2024-11-21 11:22
That setting is set for you automatically, you don't need to set it.

**Comment by benjdlambert** [comment] 2024-11-25 10:36
Gonna close this as a duplicate of https://github.com/backstage/backstage/issues/26446

**Closed by benjdlambert** 2024-11-25 10:36 UTC
Labels: bug, help wanted, area:scaffolder, area:core
