### ISSUE TITLE
using github urls with branch name containing / fails

### ISSUE THREAD

**Issue by sgandon** [backstage/backstage#5991] opened 2021-06-10 13:18 UTC
We have in our compagny some rules for naming branches and it is as follow  
`username/jira-ticket/some_description`  
But backstage does not support the / in the branch name.  
When I change the branch name to   
`username_jira-ticket_some_description`
using _ instead of / no errror occurs.

## Expected Behavior

it should work with any branch in git.

## Current Behavior

not working with branch that includes /

## Possible Solution
rename the branch

**Comment by Fox32** [comment] 2021-06-11 07:52
Duplicate of #4817 and you can find more details about this in the initial issue at #2815

**Comment by Rugvip** [comment] 2021-06-15 08:23
Thanks @Fox32, duplicate indeed. Gonna close this to keep the discussion focused.

**Closed by Rugvip** 2021-06-15 08:23 UTC
Labels: bug
