### ISSUE TITLE
Azure Devops Plugin Pipeline annotation 

### ISSUE THREAD

**Issue by patiln** [backstage/backstage#8528] opened 2021-12-17 03:11 UTC
Currently azure devops plugin supports only repos hosted in AzureDevops . we use azure devops for build and release and the Source Code is in bitbucket . can we have something like we can just pass the annotation with pipeline name and it displays the all relevant build for the pipeline

**Comment by awanlin** [comment] 2021-12-17 12:36
Hi @patiln, welcome, just wanted to let you know we have been working on this over is issue #7853. We have the back end changes in place and the plan was to work on the front end changes over the holidays. That starts on Monday for me so I'll keep you in the loop.

**Comment by awanlin** [comment] 2021-12-17 12:41
@freben can we close this as a duplicate of #7853, please?

**Closed** 2021-12-17 14:07 UTC
Labels: enhancement
