### ISSUE TITLE
🐛 Bug Report: New Backend System, github catalog plugin ...schedule.frequency "got string, wanted object"

### ISSUE THREAD

**Issue by nick-gray-bah** [backstage/backstage#25300] opened 2024-06-18 14:26 UTC
### 📜 Description

We're upgrading to the new backend system following the migration guide. As part of that effort, we are moving the github entity provider schedule from the catalog.ts file to app-config.yaml as instructed [here](https://backstage.io/docs/backend-system/building-backends/migrating#the-catalog-plugin:~:text=github%3A%0A%20%20%20%20%20%20yourProviderId%3A%0A%20%20%20%20%20%20%20%20%23%20...-,schedule%3A,timeout%3A%20PT3M,-To%20migrate%20GithubMultiOrgEntityProvider%20or%20GithubOrgEntityProvider). However when starting up the backend, we are seeing an error that the string provided in the migration guide (`PT30M`) is not accepted and it wants an object. Even when trying to pass an object, such as `frequency: { hours: 2 }` it still does not properly adjust the schedule when starting up the backend.

### 👍 Expected behavior

The app-config values for catalog.providers.github.providerId.schedule.frequency, ...initialDelay and ...timeout are interpreted correctly by the backend system at startup.

### 👎 Actual Behavior with Screenshots

app-config.yaml: 
![Screenshot 2024-06-18 at 10 20 24 AM](https://github.com/backstage/backstage/assets/124801880/7f3d3056-02c7-4a16-a3e4-73dbd38bb5cc)

error message: <img width="865" alt="Screenshot 2024-06-18 at 10 01 11 AM" src="https://github.com/backstage/backstage/assets/124801880/0523c85a-df5c-4fa0-ae4f-4b063b75b71f">

### 👟 Reproduction steps

Follow the migration guide [here](https://backstage.io/docs/backend-system/building-backends/migrating/#github) for migrating the GitHub entity provider to the new backend. Supply the values listed in app-config.yaml as shown in the migration guide. Build and start the backend system. 

### 📃 Provide the context for the Bug.

We are trying to migrate to the new backend system and this bug is preventing us from upgrading the catalog plugin.

### 🖥️ Your Environment

```
yarn backstage-cli info
yarn run v1.22.19
$ /Users/nickgray/Documents/example-backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.4.0 - darwin/arm64
node: v18.14.1
yarn: 1.22.19
cli:  0.26.6 (installed)
backstage:  1.26.1

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.7.5
  @backstage/backend-common                                        0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/backend-test-utils                                    0.3.7
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.3
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.13.10, 0.14.4
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.31
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7
  @backstage/frontend-plugin-api                                   0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26
  @backstage/integration                                           1.11.0
  @backstage/plugin-analytics-module-ga4                           0.2.4
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.2.19, 0.4.13
  @backstage/plugin-auth-react                                     0.1.0
  @backstage/plugin-catalog-backend-module-github-org              0.1.13
  @backstage/plugin-catalog-backend-module-github                  0.6.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.38
  @backstage/plugin-explore                                        0.4.20
  @backstage/plugin-github-actions                                 0.6.15
  @backstage/plugin-graphiql                                       0.3.7
  @backstage/plugin-home-react                                     0.1.12
  @backstage/plugin-home                                           0.7.3
  @backstage/plugin-kubernetes-backend                             0.17.0
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-kubernetes-node                                0.1.11
  @backstage/plugin-kubernetes-react                               0.3.4
  @backstage/plugin-kubernetes                                     0.11.9
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.4
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-pg                       0.5.26
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-tech-insights-backend-module-jsonfc            0.1.49
  @backstage/plugin-tech-insights-backend                          0.5.31
  @backstage/plugin-tech-insights-common                           0.2.12
  @backstage/plugin-tech-insights-node                             0.6.0
  @backstage/plugin-tech-insights                                  0.3.26
  @backstage/plugin-tech-radar                                     0.7.3
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.4.2
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.3.0, 0.4.4, 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment] 2024-06-18 14:56
Hi! Thanks for reporting, indeed that's unexpected, closing as a duplicate of #25115 so we can keep the discussion centered there

**Closed by freben** 2024-06-18 14:56 UTC
Labels: bug, area:catalog
