### ISSUE TITLE
🐛 Bug Report:  Failed to parse template string: ${{ parameters.customer_id }} with error Converting circular structure to JSON

### ISSUE THREAD

**Issue by arjunsbabu43** [backstage/backstage#21485] opened 2023-11-22 21:37 UTC
### 📜 Description

 action: fetch:template is not replacing the parameters from UI properly.
 Getting the following error 
 [1] 2023-11-22T21:09:59.315Z scaffolder error Failed to parse template string: ${{ parameters.customer_id }} with error Converting circular structure to JSON
[1]     --> starting at object with constructor 'Timeout'
[1]     |     property '_idlePrev' -> object with constructor 'TimersList'
[1]     --- property '_idleNext' closes the circle type=plugin

### 👍 Expected behavior

Parameters should replace correctly. The same template is working in a different environment 

### 👎 Actual Behavior with Screenshots

Template is as follows 
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-devops-debug
  title: Azure Devops pr
  description: Azure Devops pr
  labels:
    dna.template/is-public: yes
  tags:
    - azure
    - managed
spec:
  owner: group:platform-engineering-services/pes-engineering-team
  type: Landing Zone

  parameters:
    - title: Customer information
      required:
        - customer_id
      properties:
        customer_id:
          title: Customer ID
          type: string
          description: A unique 3 character alphanumeric code for the customer

  steps:

    - id: template_skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: skeleton
        values:
          customer_id: ${{ parameters.customer_id }}
      script:
        - echo "Debug: customer_id = ${{ parameters.customer_id }}"
    - id: rename_file
      name: Rename templated file
      action: fs:rename
      input:
        files:
          - from: ./skeleton/lz-sample.yaml
            to: ./skeleton/deployment.yaml
    - id: publish_pr
      name: Open Pull-Request
      action: publish:github:pull-request
      input:
        repoUrl: github.ibm.com?repo=prism-pes-tes-mdm&owner=Platform-Engineering-Services
        branchName: dddd
        title: Deploying Azure Workload aware Landing zone 
        description: |
          Create the ** pull request ** to start the pipeline
          test
        sourcePath: ./skeleton
        targetPath: ./azure/boilerplate/
  output:
    links:
      - title: Repository
        url: "https://dev.azure.com/AshutoshBhardwaj2/DealArchetype/_git/prismtest"

### 👟 Reproduction steps

Use the above template and the replace in the following file 
---
customer:
  description: "This is a  environment for customer ${{ values.customer_id }}"
  expiration: ddmmyyyy
  parentid: "${{ values.customer_id }}"

### 📃 Provide the context for the Bug.

seems some package update might have caused the issue 

arjunsbabu@Arjuns-MacBook-Air pes-prism-idp % npm version
{
  root: '1.0.0',
  npm: '10.2.3',
  node: '18.18.2',

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment] 2023-11-22 22:17
Hey :wave: thanks for reporting.

Going to close this as a duplicate of #21306. Please update to Backstage 1.20.2 using `yarn backstage-cli versions:bump`.

**Closed by benjdlambert** 2023-11-22 22:17 UTC
Labels: bug

**Comment by arjunsbabu43** [comment] 2023-11-26 03:55
thanks for the quick fix. it solved my problem and was really helpful
