### ISSUE TITLE
Could not fetch catalog entities on a all new deployment

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#10323] opened 2022-03-19 11:10 UTC
Hello,

I'd like to run backstage in my local environment. To do this, I'm following the steps in the [gettings-started guide](https://backstage.io/docs/getting-started/). 

Unfortunately, when the app is starting, I have an error : 

![image](https://user-images.githubusercontent.com/37327656/159118419-c094d2e3-b75a-4506-87ac-8857d071af5f.png)

While I see no errors in the logs of the backend : 

![image](https://user-images.githubusercontent.com/37327656/159118453-74ab07ac-adbc-466e-8c9e-b1d5a4846b92.png)

***N.B :*** I have the following error in my local environment but I get this error in multiple environments :

- Kubernetes through helm charts deployment
- Yarn deployment on a company VM behind a proxy
- In my local environment in a WSL withtout any proxy.

The reason why I was talking about my local environment is because this is the environment where I made any modifications just the commands below

## Steps to reproduce

```console
npx @backstage/create-app ## Create local-backstage app
cd local-backstage && yarn dev
```

## Environment

- Ubuntu 20.04 in WSL 2 on Windows 10 

Please let me know if you miss informations

***N.B:*** Backstage seems really great and IMHO could help A LOT of teams growing up 👍

**Comment by freben** [comment] 2022-03-19 13:29
I see the backend starting up, and I see techdocs successfully reading entities (but getting zero entities out).

What's in your browser's console and network inspector? Could a corporate policy or browser plugins block you?

**Comment by LvffY** [comment] 2022-03-19 14:03
Hello @freben 

I'm a bit confused ... I restarted my server and get the exact same error page as above.

![image](https://user-images.githubusercontent.com/37327656/159123878-58eaa1d0-42e6-4038-aa8a-3fed2c70ac38.png)

When I open my brower console to show you the console, just a refresh of the page made it work.

So I restart my server, again the error page. F5 --> Still the error page. Once again F5 --> Got the correct page ....

![image](https://user-images.githubusercontent.com/37327656/159124124-37973024-eba0-4ab4-ae84-c5ea88ed98e8.png)

Any idea what could lead to this state ?

**Comment by freben** [comment] 2022-03-19 14:06
So is it just a case of your backend starting up slower than your frontend? That would explain it, and we don't really have a check for that honestly.

**Comment by freben** [comment] 2022-03-19 14:07
We have hot reloading of most things - most of the time you don't have to restart as you develop. That may alleviate the problem somewhat.

**Comment by LvffY** [comment] 2022-03-19 14:20
@freben Ok it seems to be what you say.

The problem appears to multiple browsers (tested on Chrome and Firefox).

It appears that the when the logs lines prefixed by `[1]` appears my problem disappear. So the backend seems to be slower to start the backend and my impatience to test backstage seems to be the biggest problem here :)

Thanks !

**Comment by freben** [comment] 2022-03-21 18:39
Thanks for confirming.

I'm surprised that we haven't seen this happen in more instances. I have actually not seen reports about this before. I made a slimmer issue focused on a fix for this particular case, and I'll close this one for now to focus the discussion there going forward. We probably won't get around to working on this one in the very near term, but all suggestions and contributions in that ticket are welcome!

**Closed by freben** 2022-03-21 18:39 UTC

**Comment by mustafazeya** [comment] 2022-04-05 12:02
I am also facing the same issue. There is no issue while running the application on local machine. But the docker image build using the documentation https://backstage.io/docs/deployment/docker is giving same error.

![image](https://user-images.githubusercontent.com/31076711/161749496-cfcd36c9-396c-48ac-a7d9-69bbc35c0360.png)

**Comment by jaymal** [comment] 2022-04-14 12:37
@mustafazeya Hi were you able to resolve this?

**Comment by mustafazeya** [comment] 2022-04-14 12:41
> @mustafazeya Hi were you able to resolve this?I am facing exact same issue.Thanks

Yes, it was configuration issue in `app-config.yaml` file.

**Comment by mustafazeya** [comment] 2022-04-14 13:11
> @mustafazeya What issue was that?could you please clarify?Thanks 

We weren't getting issue locally ( if you used npx to create initial version,you shouldn't get into any issue).

When we were deploying docker image with a custom url,we were getting this issue.

We had some cache problem in browser and we changed frontend and backend url to same and then everything worked perfectly fine.

I hope this helps!

**Comment by Rafa3001** [comment] 2022-09-08 14:02
estou enfrentado o mesmo problema porém na Vm, quando vou registrar um componente ou algo relacionado aparece o seguinte problema.
<img width="896" alt="backstage1" src="https://user-images.githubusercontent.com/83523558/189142370-ca70250a-ac02-453f-85db-ecbe76b1641b.png">

**Comment by Rafa3001** [comment] 2022-09-08 14:14
Em minha maquina virtual está da seguinte forma em meu , estou usando a fedora (Linux).
Alguém poderia me ajudar a solucionar ?
estou enfrentando ele a semanas..
<img width="941" alt="VMMM" src="https://user-images.githubusercontent.com/83523558/189145308-55b07bab-cb57-488b-b697-ee2b39013a74.png">

**Comment by martinezhermes** [comment] 2022-10-10 15:18
Hello, maybe @LvffY had a cache problem, but I can't make it work either, I'm having the same error, with the same setup in a local machine, following the getting starter guide. None of the instructions in the getting started guide seem to work as intended, is that documentation up to date?

**Comment by drsounds** [comment] 2022-11-12 18:37
I got the same issue.

For me the error was that the CORS-url did not match the frontend URL

**Comment by hamzamaan** [comment] 2022-11-26 10:05
I am facing the same issue, how i can resolved this?
![image](https://user-images.githubusercontent.com/41535104/204083176-6c66791d-0dda-4ac1-8025-e442a1ac6f9c.png)

I installed on aws ec2 instance but when i installed on oracle box ubuntu vm and there is working properly.

**Comment by jethers** [comment] 2022-11-26 23:31
I'm stuck in this too :(

**Comment by soaand01** [comment] 2022-12-14 19:44
@jethers  Did you manage to solve your issue ? 
I am facing this issue as well and I am deploying via helm chart following the instructions here
https://github.com/backstage/charts

**Comment by jethers** [comment] 2022-12-14 20:47
Hi,

I solved it doing this: https://github.com/backstage/backstage/issues/14874

Thanks

Em qua., 14 de dez. de 2022 às 16:44, Anderson Soares <
***@***.***> escreveu:

**Comment by varma797** [comment] 2024-09-17 08:52
> > @mustafazeya What issue was that?could you please clarify?Thanks
> 
> We weren't getting issue locally ( if you used npx to create initial version,you shouldn't get into any issue).
> 
> When we were deploying docker image with a custom url,we were getting this issue.
> 
> We had some cache problem in browser and we changed frontend and backend url to same and then everything worked perfectly fine.
> 
> I hope this helps!

Subject: Issue with Custom Domain on Backstage via Traefik Ingress - Assistance Required

Hello @mustafazeya 

I am facing an issue with my app-config.yaml file after making custom domain changes. I have attached a screenshot of the error for your reference. Below is a summary of the problem:

Issue: I am using Traefik Ingress to route requests. When I use port forwarding on the pod, the application loads successfully on localhost:7007. However, I encounter issues when accessing the application via the custom host with a subpath using Traefik Ingress.

Could you please help me identify what I might be missing in my configuration?

Thank you for your assistance!
![Screenshot from 2024-09-17 14-21-26](https://github.com/user-attachments/assets/39b1f5c8-e340-41e9-bf79-ed19cf4af7d6)

```
Error: Could not fetch catalog entities
Failed to load entity kinds
TypeError: NetworkError when attempting to fetch resource.
```

  ```
app:
  title: Scaffolded Backstage App01
  #baseUrl: http://localhost:3000
  baseUrl: https://dummy-backstage.com:3000/backstage/

organization:
  name: My Company

backend:

  baseUrl: https://dummy-backstage.com:7007
  listen:
    port: 7007

  auth:
    dangerouslyDisableDefaultAuthPolicy: true
  csp:
    connect-src: ["'self'", 'http:', 'https:']

  cors:
    origin: 
      - http://localhost:3000
      - https://dummy-backstage.com:3000

    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
    Access-Control-Allow-Origin: '*'
```

**Comment by froyo-saif** [comment] 2024-10-21 06:36
Hello I am getting same error 
[1] node:internal/modules/cjs/loader:453
[1]       throw err;
[1]       ^
[1]
[1] Error: Cannot find module 'P:\Scania-dev-portal\scania-dev-portal\node_modules\@azure\identity\node_modules\@azure\abort-controller\dist\index.js'. Please verify that the package.json has a valid "main" entry
[1]     at tryPackage (node:internal/modules/cjs/loader:445:19)
[1]     at Module._findPath (node:internal/modules/cjs/loader:716:18)
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1131:27)
[1]     at Module._load (node:internal/modules/cjs/loader:986:27)
[1]     at Module.require (node:internal/modules/cjs/loader:1233:19)
[1]     at require (node:internal/modules/helpers:179:18)
[1]     at Object.<anonymous> (P:\Scania-dev-portal\scania-dev-portal\node_modules\@azure\identity\dist\index.js:13:23)   
[1]     at Module._compile (node:internal/modules/cjs/loader:1358:14)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
[1]     at Object.newLoader [as .js] (P:\Scania-dev-portal\scania-dev-portal\node_modules\pirates\lib\index.js:121:7) {   
[1]   code: 'MODULE_NOT_FOUND',
[1]   path: 'P:\\Scania-dev-portal\\scania-dev-portal\\node_modules\\@azure\\identity\\node_modules\\@azure\\abort-controller\\package.json',
[1]   requestPath: '@azure/abort-controller'
[1] }
[1]
[1] Node.js v20.14.0
[0] webpack compiled successfully

![image](https://github.com/user-attachments/assets/74e839fe-5b72-4ca3-aee0-5e9b34014195)
