### ISSUE TITLE
🐛 Bug Report: The backend image build takes too much long time about 3 hours

### ISSUE THREAD

**Issue by leezhihui** [backstage/backstage#25639] opened 2024-07-16 07:14 UTC
### 📜 Description

The backend image host build takes too much long time about 2 hours
The backend image multistage build takes about 3.5 hours.

### 👍 Expected behavior

want it can build in 0.5 hour or less time.

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-07-12 at 14 21 57](https://github.com/user-attachments/assets/88e2ba49-cc73-4f75-944e-96ba7ada11c1)

### 👟 Reproduction steps

Use docker build to build the backend image with dockerfile under backend/

docker buildx build --platform linux/arm64 -f ./Dockerfile --tag dev.artifactory.com/backstage:2.9.0.arm . --push

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment] 2024-07-16 12:22
Hi @leezhihui, we build and publish a demo container every release, those are taking about 30-40 minutes - https://github.com/backstage/backstage/actions/workflows/deploy_docker-image.yml. 

There's not a lot of detail here to further help you though. What version of Backstage are you on? Have you made any changes to the Dockerfile? Is this slow locally or on a CI/CD tool? Do you use a private registry?

**Comment by awanlin** [comment] 2024-07-16 16:10
When you say it's the master branch you don't mean of this repo? If so that is NOT at all the recommended path, you want to run `npx @backstage/create-app@latest` to create your Backstage instance and then any further changes are done to that. I'd read the getting started guide: https://backstage.io/docs/getting-started/

We use the Multi-stage build for the demo site and it is also pretty fast: https://github.com/backstage/demo/actions/workflows/master.yml

I only mention a private registry as possible being a reason for things being slow. I've seen that be the case some times.

**Comment by freben** [comment] 2024-07-17 07:03
Like @awanlin said: you probably don't want to do that. Don't clone/fork the backstage/backstage repo for your build and installation needs. The build takes a long time in part because it's a huge repo with all the plugins you don't need. You should follow https://backstage.io/docs/getting-started/ and make your own private repo that you build.

**Comment by leezhihui** [comment] 2024-07-17 07:33
Thank you @freben 
 So you mean the  https://backstage.io/docs/getting-started/  will guide how to build with not much plugins. will check it again.

Which folders should be reduced, if there has some guide doc. or the https://backstage.io/docs/getting-started is only one for minimized  build guide. 

Another point, so, the builds takes long time with huge repo is as expected?

**Comment by leezhihui** [comment] 2024-07-17 09:33
I tried the host build, it first takes 1.5h, when have the cache, it will finished in short time such as 15~20mins
here is the screenshot for host machine.
![Screenshot 2024-07-17 at 17 30 51](https://github.com/user-attachments/assets/d1026dd4-8fb5-40b8-abd9-9469949cd17d)

**Comment by benjdlambert** [comment] 2024-07-18 09:21
@leezhihui where is the most time spent, on which step in the docker image? This might help us pinpoint what is the cause of this slowness.

**Comment by leezhihui** [comment] 2024-07-18 10:17
Hi @benjdlambert
it take long time in execute yarn install --immunetable and finally failed at that line

I tried npm set registry with private one, seems not work

**Comment by leezhihui** [comment] 2024-07-19 04:41
![Uploading Screenshot 2024-07-19 at 12.41.19.png…]()

**Comment by benjdlambert** [comment] 2024-07-19 13:02
@leezhihui when you're building the docker container are you behind a corporate proxy or HTTP proxy?

**Comment by leezhihui** [comment] 2024-07-23 02:02
Yes @benjdlambert, internal network, should have a corporate proxy.

**Comment by benjdlambert** [comment] 2024-07-23 06:06
I wonder if you might need to pass through the `HTTP_PROXY` vars to the Docker builder and then pass them to yarn, or alternatively set the `yarn` proxy servers in the Dockerfile directly.

https://stackoverflow.com/questions/27749193/how-to-build-docker-images-with-dockerfile-behind-http-proxy-by-jenkins

or

```
      yarn config set proxy http://proxy.domain.tld:port
      yarn config set https-proxy http://proxy.domain.tld:port
 ```

**Comment by leezhihui** [comment] 2024-07-23 06:21
Hi @benjdlambert, If this docker file for multi-stage here https://backstage.io/docs/deployment/docker#multi-stage-build has include dealing with cache, looks every time when I run the docker buildx build will yarn install all the npm package again, not read from cache. but I notice it has this line, like doing cache
```
RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn install --frozen-lockfile --network-timeout 600000
```

**Comment by benjdlambert** [comment] 2024-07-23 06:24
The cache probably wont help, as the command doesn't succeed properly in the first place, because it shouldn't take 3 hours. It looks like you have `yarn install` issues, which aren't really Backstage related per-se, just something to do with your environment I think.

**Comment by leezhihui** [comment] 2024-07-23 06:29
How to set this one, how to know the proxy in myside. if set these proxy, it will execute yarn install finished in short time? y
```
      yarn config set proxy http://proxy.domain.tld:port
      yarn config set https-proxy http://proxy.domain.tld:port
```

**Comment by benjdlambert** [comment] 2024-07-23 07:06
It's just a guess at this point because `yarn` is taking so long. If you run `yarn` manually locally and not with the docker file does it finish fast? 

You might be able to check what your `$HTTP_PROXY` environment variable is in your terminal which might help you.
Not sure that this is a Backstage issue though like I said, so the amount of support I can give is pretty limited 😅

**Comment by leezhihui** [comment] 2024-07-23 07:44
thank you, 
Yes in local host yarn install can finished in about 3 minutes, and seems echo $HTTP_PROXY show nothing in terminal
![Screenshot 2024-07-23 at 15 42 23](https://github.com/user-attachments/assets/89f4d25b-1e38-4b8e-bcdf-34f5eb7b6e63)

**Comment by benjdlambert** [comment] 2024-07-23 07:53
Yeah that's more realistic, that's the time it should also take in the docker container as you can see from our container builds for the demo site, and when I run it locally it's similar.

Are all network requests slow when building the container? You could try `time curl http://google.com` or something to see how long this takes, it shouldn't take more that `0.05s`. 

I'm not sure what to suggest here to be honest, a little bit stumped as to why it's taking so long inside the container.

**Comment by leezhihui** [comment] 2024-07-23 08:08
looks it finished in 0.8s
```
#14 256.9 update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
#14 257.0 Setting up build-essential (12.9) ...
#14 257.0 Setting up python3-venv (3.11.2-1+b1) ...
#14 257.0 Processing triggers for libc-bin (2.36-9+deb12u7) ...
#14 257.2 Processing triggers for ca-certificates (20230311) ...
#14 257.4 Updating certificates in /etc/ssl/certs...
#14 279.4 0 added, 0 removed; done.
#14 279.4 Running hooks in /etc/ca-certificates/update.d...
#14 279.4 done.
#14 DONE 279.9s

#20 [build  3/11] RUN curl http://google.com
#20 0.360   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#20 0.367                                  Dload  Upload   Total   Spent    Left  Speed
100   219  100   219    0     0    655      0 --:--:-- --:--:-- --:--:--   673
#20 0.687 <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
#20 0.687 <TITLE>301 Moved</TITLE></HEAD><BODY>
#20 0.687 <H1>301 Moved</H1>
#20 0.687 The document has moved
#20 0.687 <A HREF="http://www.google.com/">here</A>.
#20 0.687 </BODY></HTML>
#20 DONE 0.8s

```

**Comment by leezhihui** [comment] 2024-07-23 08:51
Another, does it have the different platform like amd64 or arm64, because I need buildx to build multi platform image. the docker buildx command is like this:
`docker buildx build --progress=plain --platform linux/arm64, linux/amd64 -f ./Dockerfile --tag backstage:2.9.0.multi . --push 2>&1 | tee arm10_build.log`

**Comment by benjdlambert** [comment] 2024-07-23 10:36
I'm not sure, I just run `docker build -f ./Dockerfile` and it works quick for me.

**Comment by leezhihui** [comment] 2024-07-24 08:02
Hi, notice that the base image like 
`FROM node:18-bookworm-slim AS packages`
the base image has yarn version with 1.22.19 which mismatch with the value 3.8.1 in package.json 
![Screenshot 2024-07-24 at 15 59 08](https://github.com/user-attachments/assets/627b2e35-729c-4fa6-ae46-d4d920b5a838)

when run into yarn install it report these error
![Screenshot 2024-07-24 at 16 00 45](https://github.com/user-attachments/assets/e7163c45-8b5c-4156-a571-75dddc29acf5)

So, how to deal with this mismatch, it should be like this or it can be changed by over write with new install

**Comment by awanlin** [comment] 2024-07-24 11:48
You are back to what we mention at the start, the main Backstage repo isn't the starting point to using Backstage. In this case the main repo uses Yarn 3 but the default is Yarn 1. The Dockerfile in the main repo hasn't been updated to work with Yarn 3 as we never package it up into a container. 

I highly recommend you follow the getting started steps as you'll have a better long term experience: https://backstage.io/docs/getting-started/. This uses `npx @backstage/create-app@latest` which will create a Backstage instance for you which you would add to a git repo and then build a docker image of.

**Comment by leezhihui** [comment] 2024-07-25 01:39
Oh,
Thank you @awanlin,
my team have working with the main repo, if study I can start with the getting-started, but if I want to conquer the current situation, what should be better to get through this. does there has base image for yarn3 for the multistage build.

**Comment by Rugvip** [comment] 2024-07-25 10:40
Yep please use the getting-started flow and report any problems you encounter through that. I'm going to close this issue as unactionable, as the reported issue is due to general `yarn install` performance in your environment, and not related to Backstage.

**Closed by Rugvip** 2024-07-25 10:40 UTC
Labels: bug
