### ISSUE TITLE
[TechDocs] Infinite Loading if no index.md is available (since 1.1.0)

### ISSUE THREAD

**Issue by pjungermann** [backstage/backstage#10989] opened 2022-04-21 07:36 UTC
## Expected Behavior

Docs tab attempts to load and then fails visibly and maybe recommends actions (e.g., no index page found. This is where you can find more details on what you need to do)

## Actual Behavior

Attempts to load index.html and request fails with 404, but for the user it continues to "load" infinitely.

```text
GET /api/techdocs/static/docs/default/Component/component-name/index.html

Status 301
Location /api/techdocs/static/docs/default/component/component-name/index.html
```

```text
GET /api/techdocs/static/docs/default/component/bonial-helm-charts/index.html

Status 404
```

## Steps to Reproduce

1. Registered component with annotation `backstage.io/techdocs-ref: dir:..`
2. Simple mkdocs.yml like e.g.
```
site_name: name
site_description: description

plugins:
  - techdocs-core
```
3. open Docs tab

## Context

We were using the legacy behavior of using README.md files at the project root which then was transparently moved to docs/index.md.

In release 1.1.0 this behavior was removed (with the option to reenable it for some time).

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 20.6.0 - darwin/x64
node: v16.14.2
yarn: 1.22.18
cli:  0.17.0 (installed)

Dependencies:
  @backstage/app-defaults                               1.0.1
  @backstage/backend-common                             0.13.2
  @backstage/backend-tasks                              0.3.0
  @backstage/catalog-client                             1.0.1
  @backstage/catalog-model                              1.0.1
  @backstage/cli-common                                 0.1.8
  @backstage/cli                                        0.17.0
  @backstage/config-loader                              1.1.0
  @backstage/config                                     1.0.0
  @backstage/core-app-api                               1.0.1
  @backstage/core-components                            0.9.3
  @backstage/core-plugin-api                            1.0.1
  @backstage/errors                                     1.0.0
  @backstage/integration-react                          1.0.1
  @backstage/integration                                1.1.0
  @backstage/plugin-api-docs                            0.8.4
  @backstage/plugin-app-backend                         0.3.31
  @backstage/plugin-auth-backend                        0.13.0
  @backstage/plugin-auth-node                           0.2.0
  @backstage/plugin-badges-backend                      0.1.25
  @backstage/plugin-badges                              0.2.28
  @backstage/plugin-catalog-backend-module-aws          0.1.4
  @backstage/plugin-catalog-backend-module-bitbucket    0.1.2
  @backstage/plugin-catalog-backend-module-github       0.1.2
  @backstage/plugin-catalog-backend-module-msgraph      0.3.1
  @backstage/plugin-catalog-backend                     1.1.1
  @backstage/plugin-catalog-common                      1.0.1
  @backstage/plugin-catalog-graph                       0.2.16
  @backstage/plugin-catalog-import                      0.8.7
  @backstage/plugin-catalog-react                       1.0.1
  @backstage/plugin-catalog                             1.1.0
  @backstage/plugin-explore-react                       0.0.16
  @backstage/plugin-explore                             0.3.35
  @backstage/plugin-github-actions                      0.5.4
  @backstage/plugin-org                                 0.5.4
  @backstage/plugin-permission-common                   0.6.0
  @backstage/plugin-permission-node                     0.6.0
  @backstage/plugin-permission-react                    0.4.0
  @backstage/plugin-proxy-backend                       0.2.25
  @backstage/plugin-scaffolder-backend                  1.1.0
  @backstage/plugin-scaffolder-common                   1.0.1
  @backstage/plugin-scaffolder                          1.1.0
  @backstage/plugin-search-backend-node                 0.6.0
  @backstage/plugin-search-backend                      0.5.1
  @backstage/plugin-search-common                       0.3.3
  @backstage/plugin-search-react                        0.1.0
  @backstage/plugin-search                              0.8.0
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.15
  @backstage/plugin-tech-insights-backend               0.3.0
  @backstage/plugin-tech-insights-common                0.2.4
  @backstage/plugin-tech-insights-node                  0.2.9
  @backstage/plugin-tech-insights                       0.2.0
  @backstage/plugin-tech-radar                          0.5.11
  @backstage/plugin-techdocs-backend                    1.1.0
  @backstage/plugin-techdocs-node                       1.1.0
  @backstage/plugin-techdocs-react                      0.1.0
  @backstage/plugin-techdocs                            1.1.0
  @backstage/plugin-user-settings                       0.4.3
  @backstage/release-manifests                          0.0.2
  @backstage/search-common                              0.3.3
  @backstage/test-utils                                 1.0.1
  @backstage/theme                                      0.2.15
  @backstage/types                                      1.0.0
  @backstage/version-bridge                             1.0.1

```

**Comment by martinohmann** [comment] 2022-04-21 07:42
Hi there!

I was about to report the same issue but just found this one right before submitting so I'll add the information I gathered here instead of opening a separate issue.




Given the following repository layout:

```text
.
├── README.md
├── catalog-info.yaml
├── docs
│   └── development.md
└── mkdocs.yml

```

Note that there is no `index.md` or `README.md` in the docs directory. The repo was relying on the pre-1.1.0 behaviour where the `README.md` in the repository root would be automatically copied into the `docs_dir`.

We were aware of this breaking change and discovered the issue described below while evaluating our options for migrating our techdocs to work with the new requirement of having an `index.md`/`README.md` in the `docs_dir`.

## Expected Behavior

Individual pages (like `development` from the example above) can be navigated to via URL. Visiting the the docs index should result in a 404 or preferably a helpful message pointing out to the user that he/she may have forgotten to setup an `index.md`.

## Actual Behavior

The techdocs index page shows the loading animation indefinitely.

In the JavaScript console's network tab I can see a call to `index.html` resulting in 404.

Individual pages like `development` can be navigated to via URL. However, upon regeneration of the docs, these pages will show an error above the correctly regenerated docs:

```
Sorry! It took too long for the generated docs to show up in storage. Check back later.
```

Also see the techdocs build log attached below.

The generation of the techdocs itself seems to succeed without error. However, to me it looks like the success of techdocs generation is determined by the fact that there was an `index.html` generated which will never happen with the directory structure showed above since `index.md`/`README.md` are missing.

## Steps to Reproduce




1. Create a minimal `mkdocs.yml` with only `site_name` and `site_description`.
2. Create a `docs/` dir which contains at least one `.md` file that is neither named `index.md` nor `README.md`.
3. Enable techdocs in your `catalog-info.yaml` via the `backstage.io/techdocs-ref: dir:.` annotation.

## Context





Techdocs build log:

```text
event: log
data: "\u001b[32minfo\u001b[39m: Step 1 of 3: Preparing docs for entity component:default/opsdroid {\"timestamp\":\"2022-04-21T07:22:20.481Z\"}"

event: log
data: "\u001b[32minfo\u001b[39m: Prepare step completed for entity component:default/opsdroid, stored at /tmp/backstage-GPK4TH {\"timestamp\":\"2022-04-21T07:22:22.890Z\"}"

event: log
data: "\u001b[32minfo\u001b[39m: Step 2 of 3: Generating docs for entity component:default/opsdroid {\"timestamp\":\"2022-04-21T07:22:22.890Z\"}"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mLoading configuration file: /tmp/backstage-GPK4TH/mkdocs.yml"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mLoaded theme configuration for 'mkdocs' from '/usr/local/lib/python3.7/dist-packages/mkdocs/themes/mkdocs/mkdocs_theme.yml': {'static_templates': ['404.html'], 'locale': 'en', 'include_search_page': False, 'search_index_only': False, 'highlightjs': True, 'hljs_languages': [], 'hljs_style': 'github', 'navigation_depth': 2, 'nav_style': 'primary', 'analytics': {'gtag': None}, 'shortcuts': {'help': 191, 'next': 78, 'previous': 80, 'search': 83}}"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'config_file_path' = '/tmp/backstage-GPK4TH/mkdocs.yml'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'site_name' = 'Opsdroid'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'nav' = None\n\u001b[34mDEBUG    -  \u001b[0mConfig value: 'pages' = None"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'site_url' = ''"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'site_description' = 'A chat bot.'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'site_author' = None"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'theme' = Theme(name='mkdocs', dirs=['/usr/local/lib/python3.7/dist-packages/mkdocs/themes/mkdocs', '/usr/local/lib/python3.7/dist-packages/mkdocs/templates'], static_templates=['404.html', 'sitemap.xml'], locale=Locale(language='en', territory=''), include_search_page=False, search_index_only=False, highlightjs=True, hljs_languages=[], hljs_style='github', navigation_depth=2, nav_style='primary', analytics={'gtag': None}, shortcuts={'help': 191, 'next': 78, 'previous': 80, 'search': 83})"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'docs_dir' = '/tmp/backstage-GPK4TH/docs'\n\u001b[34mDEBUG    -  \u001b[0mConfig value: 'site_dir' = '/tmp/techdocs-tmp-Bd5szZ'\n\u001b[34mDEBUG    -  \u001b[0mConfig value: 'copyright' = None\n\u001b[34mDEBUG    -  \u001b[0mConfig value: 'google_analytics' = None\n\u001b[34mDEBUG    -  \u001b[0mConfig value: 'dev_addr' = Address(host='127.0.0.1', port=8000)\n\u001b[34mDEBUG    -  \u001b[0mConfig value: 'use_directory_urls' = True"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'repo_url' = ''\n\u001b[34mDEBUG    -  \u001b[0mConfig value: 'repo_name' = ''"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'edit_uri' = ''"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'extra_css' = []"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'extra_javascript' = []\n\u001b[34mDEBUG    -  \u001b[0mConfig value: 'extra_templates' = []"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'markdown_extensions' = ['toc', 'tables', 'fenced_code']\n\u001b[34mDEBUG    -  \u001b[0mConfig value: 'mdx_configs' = {}"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'strict' = False"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'remote_branch' = 'gh-pages'\n\u001b[34mDEBUG    -  \u001b[0mConfig value: 'remote_name' = 'origin'\n\u001b[34mDEBUG    -  \u001b[0mConfig value: 'extra' = {}"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'plugins' = PluginCollection([('techdocs-core', <src.core.TechDocsCore object at 0x7f599eabca20>)])"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mConfig value: 'watch' = None"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mLoaded theme configuration for 'material' from '/usr/local/lib/python3.7/dist-packages/material/mkdocs_theme.yml': {'language': 'en', 'direction': None, 'features': [], 'palette': {'primary': None, 'accent': None}, 'font': {'text': 'Roboto', 'code': 'Roboto Mono'}, 'icon': None, 'favicon': 'assets/images/favicon.png', 'include_search_page': False, 'search_index_only': True, 'static_templates': ['404.html']}"

event: log
data: "INFO     -  Cleaning site directory"

event: log
data: "INFO     -  Building documentation to directory: /tmp/techdocs-tmp-Bd5szZ"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mReading markdown pages."

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mReading: development.md"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying static assets."

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/images/favicon.png'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/bundle.5a9542cf.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/bundle.5a9542cf.min.js.map'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.ar.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.da.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.de.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.du.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.es.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.fi.min.js'\n\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.fr.min.js'\n\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.hi.min.js'\n\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.hu.min.js'\n\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.it.min.js'\n\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.ja.min.js'\n\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.jp.min.js'\n\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.multi.min.js'\n\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.nl.min.js'\n\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.no.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.pt.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.ro.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.ru.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.stemmer.support.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.sv.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.th.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.tr.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.vi.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/min/lunr.zh.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/tinyseg.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/lunr/wordcut.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/workers/search.092fa1f6.min.js'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/javascripts/workers/search.092fa1f6.min.js.map'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/stylesheets/main.50e68009.min.css'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/stylesheets/main.50e68009.min.css.map'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/stylesheets/palette.e6a45f82.min.css'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mCopying media file: 'assets/stylesheets/palette.e6a45f82.min.css.map'"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mBuilding theme template: techdocs_metadata.json"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mBuilding theme template: 404.html"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mBuilding theme template: sitemap.xml"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mGzipping template: sitemap.xml"

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mBuilding markdown pages."

event: log
data: "\u001b[34mDEBUG    -  \u001b[0mBuilding page development.md"

event: log
data: "INFO     -  Documentation built in 0.29 seconds"

event: log
data: "\u001b[32minfo\u001b[39m: Successfully generated docs from /tmp/backstage-GPK4TH into /tmp/techdocs-tmp-Bd5szZ using local mkdocs {\"timestamp\":\"2022-04-21T07:22:23.393Z\"}"

event: log
data: "\u001b[32minfo\u001b[39m: Step 3 of 3: Publishing docs for entity component:default/opsdroid {\"timestamp\":\"2022-04-21T07:22:23.396Z\"}"

event: error
data: "Sorry! It took too long for the generated docs to show up in storage. Check back later."
```

## Your Environment

- Output of `yarn backstage-cli info`:

```text
OS:   Darwin 20.6.0 - darwin/arm64
node: v16.9.0
yarn: 1.22.11
cli:  0.16.0 (installed)

Dependencies:
  @backstage/app-defaults                               1.0.1
  @backstage/backend-common                             0.13.2
  @backstage/backend-tasks                              0.3.0
  @backstage/catalog-client                             1.0.1
  @backstage/catalog-model                              1.0.1
  @backstage/cli-common                                 0.1.8
  @backstage/cli                                        0.17.0
  @backstage/config-loader                              1.1.0
  @backstage/config                                     1.0.0
  @backstage/core-app-api                               1.0.1
  @backstage/core-components                            0.9.3
  @backstage/core-plugin-api                            1.0.1
  @backstage/errors                                     1.0.0
  @backstage/integration-react                          1.0.1
  @backstage/integration                                1.1.0
  @backstage/plugin-api-docs                            0.8.4
  @backstage/plugin-app-backend                         0.3.31
  @backstage/plugin-auth-backend                        0.13.0
  @backstage/plugin-auth-node                           0.2.0
  @backstage/plugin-badges-backend                      0.1.25
  @backstage/plugin-badges                              0.2.28
  @backstage/plugin-catalog-backend-module-aws          0.1.4
  @backstage/plugin-catalog-backend-module-bitbucket    0.1.2
  @backstage/plugin-catalog-backend-module-github       0.1.2
  @backstage/plugin-catalog-backend-module-msgraph      0.3.1
  @backstage/plugin-catalog-backend                     1.1.1
  @backstage/plugin-catalog-common                      1.0.1
  @backstage/plugin-catalog-graph                       0.2.16
  @backstage/plugin-catalog-import                      0.8.7
  @backstage/plugin-catalog-react                       1.0.1
  @backstage/plugin-catalog                             1.1.0
  @backstage/plugin-explore-react                       0.0.16
  @backstage/plugin-explore                             0.3.35
  @backstage/plugin-github-actions                      0.5.4
  @backstage/plugin-org                                 0.5.4
  @backstage/plugin-permission-common                   0.6.0
  @backstage/plugin-permission-node                     0.6.0
  @backstage/plugin-permission-react                    0.4.0
  @backstage/plugin-proxy-backend                       0.2.25
  @backstage/plugin-scaffolder-backend                  1.1.0
  @backstage/plugin-scaffolder-common                   1.0.1
  @backstage/plugin-scaffolder                          1.1.0
  @backstage/plugin-search-backend-node                 0.6.0
  @backstage/plugin-search-backend                      0.5.1
  @backstage/plugin-search-common                       0.3.3
  @backstage/plugin-search-react                        0.1.0
  @backstage/plugin-search                              0.8.0
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.15
  @backstage/plugin-tech-insights-backend               0.3.0
  @backstage/plugin-tech-insights-common                0.2.4
  @backstage/plugin-tech-insights-node                  0.2.9
  @backstage/plugin-tech-insights                       0.2.0
  @backstage/plugin-tech-radar                          0.5.11
  @backstage/plugin-techdocs-backend                    1.1.0
  @backstage/plugin-techdocs-node                       1.1.0
  @backstage/plugin-techdocs-react                      0.1.0
  @backstage/plugin-techdocs                            1.1.0
  @backstage/plugin-user-settings                       0.4.3
  @backstage/release-manifests                          0.0.2
  @backstage/search-common                              0.3.3
  @backstage/test-utils                                 1.0.1
  @backstage/theme                                      0.2.15
  @backstage/types                                      1.0.0
  @backstage/version-bridge                             1.0.1
```

**Comment by garyniemen** [comment] 2022-04-25 14:38
Any comments @ottosichert before I add the label help wanted or good first issue?

**Comment by martinohmann** [comment] 2022-04-27 13:01
Seems like this issue is already fixed in v1.2.0-next.0: https://github.com/backstage/backstage/pull/10945

**Closed** 2022-04-27 13:01 UTC
Labels: bug, docs-like-code
