### ISSUE TITLE
Getting error after upgrading backstage version form 1.4 to 1.6

### ISSUE THREAD

**Issue by kumarnil** [backstage/backstage#13916] opened 2022-09-29 14:46 UTC
## Expected Behavior

Backstage upgrade should work form version 1.4 to 1.6

## Actual Behavior

Getting error after upgrading backstage version form 1.4 to 1.6

## Steps to Reproduce
17:16:20 Step 31/59 : RUN yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies
17:16:20 ---> Running in b389b0c4a58b
17:16:20 yarn run v1.22.19
17:16:20 $ /app/node_modules/.bin/backstage-cli backend:bundle --build-dependencies
17:16:20
17:16:20 Invalid command: backend:bundle --build-dependencies
17:16:20
17:16:20 Usage: backstage-cli [options] [command]
17:16:20
17:16:20 Options:
17:16:20 -V, --version output the version number
17:16:20 -h, --help display help for command
17:16:20
17:16:20 Commands:
17:16:20 new [options] Open up an interactive guide to creating new things in your app
17:16:20 test Run tests, forwarding args to Jest, defaulting to watch mode [DEPRECATED]
17:16:20 config:docs [options] Browse the configuration reference documentation
17:16:20 config:print [options] Print the app configuration for the current package
17:16:20 config:check [options] Validate that the given configuration loads and matches schema
17:16:20 config:schema [options] Print configuration schema
17:16:20 repo [command] Command that run across an entire Backstage project
17:16:20 package [command] Lifecycle scripts for individual packages
17:16:20 migrate [command] Migration utilities
17:16:20 versions:bump [options] Bump Backstage packages to the latest versions
17:16:20 versions:check [options] Check Backstage package versioning
17:16:20 clean Delete cache directories [DEPRECATED]
17:16:20 build-workspace [packages...] Builds a temporary dist workspace from the provided packages
17:16:20 create-github-app Create new GitHub App in your organization.
17:16:20 info Show helpful information for debugging and reporting bugs
17:16:20 help [command] display help for command
17:16:20 error Command failed with exit code 1.
17:16:20 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
17:16:20 The command '/bin/sh -c yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies' returned a non-zero code: 1

## Context

Not able to upgrade current backstage version

## Your Environment

Development 

- Browser Information: Chrome

- Output of `yarn backstage-cli info`: errror
17:16:20 Step 31/59 : RUN yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies
17:16:20 ---> Running in b389b0c4a58b
17:16:20 yarn run v1.22.19
17:16:20 $ /app/node_modules/.bin/backstage-cli backend:bundle --build-dependencies
17:16:20
17:16:20 Invalid command: backend:bundle --build-dependencies
17:16:20
17:16:20 Usage: backstage-cli [options] [command]
17:16:20
17:16:20 Options:
17:16:20 -V, --version output the version number
17:16:20 -h, --help display help for command
17:16:20
17:16:20 Commands:
17:16:20 new [options] Open up an interactive guide to creating new things in your app
17:16:20 test Run tests, forwarding args to Jest, defaulting to watch mode [DEPRECATED]
17:16:20 config:docs [options] Browse the configuration reference documentation
17:16:20 config:print [options] Print the app configuration for the current package
17:16:20 config:check [options] Validate that the given configuration loads and matches schema
17:16:20 config:schema [options] Print configuration schema
17:16:20 repo [command] Command that run across an entire Backstage project
17:16:20 package [command] Lifecycle scripts for individual packages
17:16:20 migrate [command] Migration utilities
17:16:20 versions:bump [options] Bump Backstage packages to the latest versions
17:16:20 versions:check [options] Check Backstage package versioning
17:16:20 clean Delete cache directories [DEPRECATED]
17:16:20 build-workspace [packages...] Builds a temporary dist workspace from the provided packages
17:16:20 create-github-app Create new GitHub App in your organization.
17:16:20 info Show helpful information for debugging and reporting bugs
17:16:20 help [command] display help for command
17:16:20 error Command failed with exit code 1.
17:16:20 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
17:16:20 The command '/bin/sh -c yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies' returned a non-zero code: 1

**Comment by afscrome** [comment] 2022-09-30 16:28
A number of changes to the CLI commands were made with 1.4

**Comment by afscrome** [comment] 2022-09-30 16:29
Backstage 1.4 made a number of changes, including hte removal of the `backend:bundle` command.  See the change log for recommended replacements: https://github.com/backstage/backstage/blob/master/docs/releases/v1.4.0-changelog.md#backstagecli0180

**Comment by Rugvip** [comment] 2022-09-30 22:49
@afscrome thanks!

Linking straight to the migration guide that replaces usage of the removed commands as well: https://backstage.io/docs/tutorials/package-role-migration

Gonna close this since it's working as intended (please migrate)

**Closed by Rugvip** 2022-09-30 22:49 UTC
Labels: bug

**Comment by kumarnil** [comment] 2022-10-01 14:54
Issue is fixed by changing the below line of code in the dockerfile.
#RUN yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies
RUN yarn --cwd packages/backend backstage-cli package build
