### ISSUE TITLE
Airbrake Plugin

### ISSUE THREAD

**Issue by moltenice** [backstage/backstage#6739] opened 2021-08-06 08:49 UTC
## Summary

Create a plugin for Airbrake to view incidents and perhaps even triage/resolve them all within Backstage.

## Project website (if applicable)

https://airbrake.io/

## Context

This will help ensure that production issues and incidents are visible to people right within Backstage when looking at their component.

**Comment by benjdlambert** [comment] 2021-11-29 09:41
Closing as duplicate of #8268

**Closed** 2021-11-29 09:41 UTC
Labels: plugin
