### ISSUE TITLE
Website does not have the correct trademark disclaimer

### ISSUE THREAD

**Issue by thisisobate** [backstage/backstage#22477] opened 2024-01-23 20:38 UTC
### 📜 Description

As part of our ongoing effort to https://github.com/cncf/techdocs/issues/198, we noticed that the website does not pass the trademark criteria on [CLOMonitor](https://clomonitor.io/search?foundation=cncf&not_passing_check=trademark_disclaimer&page=1).

To fix this:
Head to the source code of the website. In the `<footer>` section, add a **disclaimer** or **link** to the Linux foundation trademark disclaimer page:

**Disclaimer**
```
<footer>
   <p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>
</footer>
```

**Link**
```
 <footer>
      <ul>
          <li><a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademarks</a></li>
      </ul>
 </footer>
```

### 👍 Expected behavior

Footer should contain the correct trademark disclaimer.

### 👎 Actual Behavior with Screenshots

Footer does not contain a link to the Linux Foundation disclaimer's page.

### 👟 Reproduction steps

1. Go to backstage.io
2. Scroll down to the bottom of the page
3. Check to see if there is any trademark disclaimer linking to the Linux Foundation's disclaimer page.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tudi2d** [comment] 2024-01-24 08:56
Thanks @thisisobate for raising this! Created a draft PR to use the URL containing `/legal` & actual link. At the same time I'm not sure why the "Trademark disclaimer" check fails at the moment. Both of the following RegEx should be fullfiled:

```
"https://(?:w{3}\.)?linuxfoundation.org/(?:legal/)?trademark-usage"
"The Linux Foundation.* has registered trademarks and uses trademarks"
``` 
by our footer: 

<img width="932" alt="Screenshot 2024-01-24 at 09 54 22" src="https://github.com/backstage/backstage/assets/8904624/662c7622-3edb-4391-a3df-b0e91f875d45">

Can you maybe elaborate on what the current issue is? Is it that the link is only text & not an anchor element?

**Comment by thisisobate** [comment] 2024-01-30 18:02
I think the issue is from the artifact tool not able to detect trademarks in dynamic sites. You can follow through on how artifact folks themselves were able to [fix this issue](https://github.com/artifacthub/hub/issues/3620#issuecomment-1907619220).

**Comment by devharsh2k4** [comment] 2024-04-30 21:40
Hey can i get assigned

**Comment by devharsh2k4** [comment] 2024-07-05 14:22
@camilaibs yes sure

**Comment by camilaibs** [comment] 2024-07-05 14:24
> @camilaibs yes sure

Yay, thanks 🎉 
The issue is assigned to you 🙂

**Comment by avila-m-6** [comment] 2024-09-10 03:12
@camilaibs. I was checking on the artifacthub solution referenced earlier and they raised an exception, with [which Backstage is exempted already](https://clomonitor.io/projects/cncf/backstage) under the same description.

![image](https://github.com/user-attachments/assets/58116179-9a7f-45cc-9940-a77b2c662d50)

So this issue could be closed now

**Comment by Rugvip** [comment] 2024-09-12 08:56
@avila-m-6 alright, thank you! 👍

**Closed by Rugvip** 2024-09-12 08:56 UTC
Labels: bug, good first issue, help wanted
