### ISSUE TITLE
🐛 Bug Report: After upgrading node version to 20 and backstage v1.33.0-next.3 Type = v8::FunctionTemplate]: Assertion key <= detail::IsolateSpecificSize' failed

### ISSUE THREAD

**Issue by rmanik54** [backstage/backstage#27636] opened 2024-11-14 12:51 UTC
### 📜 Description

After I upgraded backstage version from 1.32.5 to v1.33.0-next.3, changed node version to 20 || 22 in engines in package.json file, then when I run yarn dev it's failing with this error 
`node: ../src/isolate/environment.h:360: v8::Local<T> ivm::IsolateSpecific<Type>::Deref(Functor) [with Functor = ivm::ClassHandle::GetFunctionTemplate() [with Type = ivm::LibraryHandle]::<lambda()>; Type = v8::FunctionTemplate]: Assertion `key <= detail::IsolateSpecificSize' failed.`

This is the line from where error is throwing
https://github.com/laverdet/isolated-vm/blob/main/src/isolate/environment.h#L360

### 👍 Expected behavior

It should run as usual without any error

### 👎 Actual Behavior with Screenshots

It's failing from isolated-vm package which is in node_modules

`node: ../src/isolate/environment.h:360: v8::Local<T> ivm::IsolateSpecific<Type>::Deref(Functor) [with Functor = ivm::ClassHandle::GetFunctionTemplate() [with Type = ivm::LibraryHandle]::<lambda()>; Type = v8::FunctionTemplate]: Assertion `key <= detail::IsolateSpecificSize' failed.`

### 👟 Reproduction steps

1. Change engine node version from package.json file to **20 || 22**.
2. Update backstage from **v1.32.5** to **v1.33.0-next.3**
3. Change your node version to **20**
4. Then start the backstage application with **yarn dev**

### 📃 Provide the context for the Bug.

0] <i> [webpack-dev-middleware] wait until bundle finished: /
[1] node: ../src/isolate/environment.h:360: v8::Local<T> ivm::IsolateSpecific<Type>::Deref(Functor) [with Functor = ivm::ClassHandle::GetFunctionTemplate() [with Type = ivm::LibraryHandle]::<lambda()>; Type = v8::FunctionTemplate]: Assertion `key <= detail::IsolateSpecificSize' failed.

### 🖥️ Your Environment

node: v20.18.0
yarn: 1.22.22
cli:  0.29.0-next.3 (installed)
backstage:  1.33.0-next.3

Dependencies:
  @backstage/app-defaults                                          1.5.13-next.2
  @backstage/backend-app-api                                       1.0.2-next.2, 1.0.1
  @backstage/backend-common                                        0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.5.3-next.3, 0.5.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.3.0-next.2
  @backstage/backend-plugin-api                                    1.0.2-next.2, 0.8.1, 1.0.1
  @backstage/backend-tasks                                         0.6.1
  @backstage/backend-test-utils                                    1.1.0-next.3
  @backstage/catalog-client                                        1.8.0-next.1, 1.7.1
  @backstage/catalog-model                                         1.7.0
  @backstage/cli-common                                            0.1.15-next.0, 0.1.14
  @backstage/cli-node                                              0.2.10-next.0, 0.2.9
  @backstage/cli                                                   0.29.0-next.3
  @backstage/config-loader                                         1.9.2-next.0, 1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.15.1
  @backstage/core-compat-api                                       0.3.2-next.2, 0.3.1
  @backstage/core-components                                       0.16.0-next.2, 0.15.1
  @backstage/core-plugin-api                                       1.10.0
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.1-next.2, 0.10.0
  @backstage/frontend-defaults                                     0.1.2-next.2, 0.1.1
  @backstage/frontend-plugin-api                                   0.9.1-next.2, 0.9.0
  @backstage/frontend-test-utils                                   0.2.2-next.2, 0.2.1
  @backstage/integration-aws-node                                  0.1.13-next.0, 0.1.12
  @backstage/integration-react                                     1.2.0
  @backstage/integration                                           1.15.1
  @backstage/plugin-api-docs                                       0.11.12-next.3
  @backstage/plugin-app-backend                                    0.3.77-next.2
  @backstage/plugin-app-node                                       0.1.27-next.2
  @backstage/plugin-app                                            0.1.2-next.2, 0.1.1
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.2-next.2
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.2-next.2
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.3.0-next.2
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.2-next.2
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.2-next.2
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.2-next.2
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.2-next.2
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.2-next.2
  @backstage/plugin-auth-backend-module-github-provider            0.2.2-next.2
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.2-next.2
  @backstage/plugin-auth-backend-module-google-provider            0.2.2-next.2
  @backstage/plugin-auth-backend-module-guest-provider             0.2.2-next.2
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.2-next.2
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.2-next.2
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.2-next.2
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.2-next.2
  @backstage/plugin-auth-backend-module-okta-provider              0.1.2-next.2
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.2-next.2
  @backstage/plugin-auth-backend                                   0.24.0-next.2
  @backstage/plugin-auth-node                                      0.5.4-next.2, 0.5.3
  @backstage/plugin-auth-react                                     0.1.8-next.2
  @backstage/plugin-bitbucket-cloud-common                         0.2.25-next.0, 0.2.24
  @backstage/plugin-catalog-backend-module-ldap                    0.10.0-next.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.2-next.3, 0.2.1
  @backstage/plugin-catalog-backend                                1.28.0-next.3
  @backstage/plugin-catalog-common                                 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.12-next.3
  @backstage/plugin-catalog-import                                 0.12.6-next.3
  @backstage/plugin-catalog-node                                   1.14.0-next.2, 1.13.1
  @backstage/plugin-catalog-react                                  1.14.1-next.3, 1.14.0
  @backstage/plugin-catalog                                        1.25.0-next.3, 1.24.0
  @backstage/plugin-events-node                                    0.4.5-next.3, 0.4.4
  @backstage/plugin-kubernetes-common                              0.8.3
  @backstage/plugin-kubernetes-react                               0.4.4
  @backstage/plugin-notifications-common                           0.0.6-next.0
  @backstage/plugin-notifications-node                             0.2.9-next.3
  @backstage/plugin-org                                            0.6.32-next.3
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.2-next.2
  @backstage/plugin-permission-backend                             0.5.50, 0.5.51-next.2
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.5-next.2, 0.8.4
  @backstage/plugin-permission-react                               0.4.27
  @backstage/plugin-proxy-backend                                  0.5.8-next.2
  @backstage/plugin-scaffolder-backend-module-azure                0.2.2-next.3, 0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.2-next.3, 0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.2-next.3, 0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.2-next.3, 0.3.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.2-next.3, 0.2.1
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.2-next.3, 0.2.1
  @backstage/plugin-scaffolder-backend-module-github               0.5.2-next.3, 0.5.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.6.1-next.3, 0.6.0
  @backstage/plugin-scaffolder-backend-module-notifications        0.1.3-next.3
  @backstage/plugin-scaffolder-backend                             1.26.2, 1.27.0-next.3
  @backstage/plugin-scaffolder-common                              1.5.7-next.0, 1.5.6
  @backstage/plugin-scaffolder-node                                0.5.1-next.3, 0.4.11, 0.5.0
  @backstage/plugin-scaffolder-react                               1.14.0-next.3
  @backstage/plugin-scaffolder                                     1.27.0-next.3
  @backstage/plugin-search-backend-module-catalog                  0.2.5-next.3
  @backstage/plugin-search-backend-module-techdocs                 0.3.2-next.3
  @backstage/plugin-search-backend-node                            1.3.5-next.3
  @backstage/plugin-search-backend                                 1.7.0-next.3
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.8.2-next.2, 1.8.1
  @backstage/plugin-search                                         1.4.19-next.3
  @backstage/plugin-signals-node                                   0.1.14-next.3
  @backstage/plugin-signals-react                                  0.0.6
  @backstage/plugin-techdocs-backend                               1.11.2-next.3
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.17-next.2
  @backstage/plugin-techdocs-node                                  1.12.13-next.3
  @backstage/plugin-techdocs-react                                 1.2.10-next.2
  @backstage/plugin-techdocs                                       1.11.1-next.3
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.15-next.3
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.7.1-next.0, 1.7.0
  @backstage/theme                                                 0.6.1-next.0, 0.6.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.10

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment] 2024-11-15 23:57
When does it throw this issue? Is it just when you run `yarn dev`?  

Closest thing I can find is https://github.com/laverdet/isolated-vm/issues/258 which is also connected to #22618 which got closed.

**Comment by rmanik54** [comment] 2024-11-16 15:39
@benjdlambert Yes, and also when I launch a container using a Docker image built on top of this, I use node:20 as the base image. 
The docker container exits with code 139 with this error. Then I ran yarn dev, it's also throwing same error.

This is where the dockerfile I built image from https://backstage.io/docs/deployment/docker/

**Comment by benjdlambert** [comment] 2024-11-16 20:15
Could you provide an example reproduction repo with a complete dockerfile so we can dive in a little bit as I'm unable to reproduce :pray:

**Comment by Vol1and** [comment] 2024-11-19 16:36
my Dockerfile

`# This dockerfile builds an image for the backend package.
# It should be executed with the root of the repo as docker context.
#
# Before building this image, be sure to have run the following commands in the repo root:
#
# yarn install
# yarn tsc
# yarn build:backend
#
# Once the commands have been run, you can build the image using `yarn build-image`

FROM node:18-bookworm-slim

# Install isolate-vm dependencies, these are needed by the @backstage/plugin-scaffolder-backend.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends python3 g++ build-essential && \
    yarn config set python /usr/bin/python3

# Install sqlite3 dependencies. You can skip this if you don't use sqlite3 in the image,
# in which case you should also move better-sqlite3 to "devDependencies" in package.json.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev

# From here on we use the least-privileged `node` user to run the backend.
USER node

# This should create the app dir as `node`.
# If it is instead created as `root` then the `tar` command below will fail: `can't create directory 'packages/': Permission denied`.
# If this occurs, then ensure BuildKit is enabled (`DOCKER_BUILDKIT=1`) so the app dir is correctly created as `node`.
WORKDIR /app

# This switches many Node.js dependencies to production mode.
ENV NODE_ENV production

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
COPY --chown=node:node yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn install --frozen-lockfile --production --network-timeout 300000

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY --chown=node:node packages/backend/dist/bundle.tar.gz app-config*.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.production.yaml"]
`

**Comment by Vol1and** [comment] 2024-11-19 16:39
Yeah, I also played a little with my modules, seems like it's the scaffolder related dependency error

**Comment by rmanik54** [comment] 2024-11-19 16:49
> The same issue here as well at roadie [RoadieHQ/roadie-backstage-plugins#1725](https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1725)

I am using this plugin though from roadie
@roadiehq/scaffolder-backend-module-utils

**Comment by Jenson3210** [comment] 2024-11-19 22:15
I think the issue is more in roadie plugin compared to here. 
The changelog clearly mentions isolated-vm to be bumped. 
We cannot expect that a plugin building on top of backstage has latest features available few hours after the release. 
For that reason I have screenshotted the issue there, hoping they will fix it fast + provided a workaround that's working on our side.

**Comment by addersuk** [comment] 2024-11-19 22:42
I also get the same failure and for me it is due to the Soundcheck plugin using "isolated-vm@4.7.2".  If i disable Soundcheck in the backend the app starts without issue.

Will have to wait for the new release of Soundcheck

**Comment by Jenson3210** [comment] 2024-11-19 22:46
@addersuk did you try the resolutions? At first glance, it looks to be working for me.

**Comment by benjdlambert** [comment] 2024-11-21 13:42
I think that this has been fixed in the roadie plugin now too.

Going to close this issue as fixed as it's not really a backstage issue. Need to make sure that there's only one version of `isolation-vm` and that it's at `5.x` :tada:

**Closed by benjdlambert** 2024-11-21 13:42 UTC
Labels: bug

**Comment by Jenson3210** [comment] 2024-11-21 14:00
What's the _why_ for _plugin-scaffolder-backend@npm:1.26.2_?

**Comment by benjdlambert** [comment] 2024-11-21 14:25
@veronluc-ansys are you running node 20 / 22?

Have you tried with the latest release?

**Comment by veronluc-ansys** [comment] 2024-11-21 14:54
Thanks for the support.
My bad, I had to update `@roadiehq/scaffolder-backend-module-utils` to 3.x.
I'm wondering, I thought `yarn backstage-cli versions:bump` would upgrade it, but didn't. Why?

**Comment by benjdlambert** [comment] 2024-11-21 14:59
`backstage-cli` only includes `@backstage/*` packages by default.

You can pass `--pattern @roadiehq/*` too if you wanted to bump all their packages too.

**Comment by ScottGuymer** [comment] 2024-11-22 09:19
For me running `yarn dedupe` was enough as I had different resolutions of the scaffolder backend (presumably from plugins) that were giving different versions of isolated-vm. Deduping fixed this and removed this error.
